pnpm/pnpm

- lib/fetch.js
- lib/install.js
This PR does the following:
1. Installation of scoped modules. All scoped modules will be installed into `node_modules/.store/@{scope}!{name}@{version}` 
2. Pass `pkgSpec` to more methods. 
3. More debugging: 
- add `tarball` to `finish` debug message to match shasums to tarball fetches.
- Debug `symlinkSelf`.
> Support installation of scoped modules

- lib/install.js
- test/index.js
This is an initial stab at refactoring install.js to support future versions.
Biggest functional change is that while a module is still building, it's available as `.store/lodash@4.0.0` _as a symlink_ to `.tmp/0a1b2c3d...` — this way, for modules that are circular dependencies, its sub-modules can already use it. This will come in handy later when we support lifecycle scripts which will require a modules dependencies to be fully-functional before running `preinstall` / `install` / `postinstall`.
> Refactor install.js

- lib/got.js
- lib/install.js
- lib/install/link_bins.js
- lib/install/link_bundled_deps.js
- lib/promise.js
- package.json
- test/index.js
- test/support/sepia.js
This adds support for binstubs of bundled dependencies.
This is crucial to make packages like fsevents work, which has `node-pre-gyp` as its `bundleDependencies`, which it expects to run as a postinstall script.
Now, if you do `pnpm install fsevents`, it will add the correct binstubs for its bundled dependencies (eg, `node_modules/fsevents/node_modules/.bin/mkdirp`).
It also makes pnpm use bluebird by default now. This gets us better debugging in development (just `export BLUEBIRD_DEBUG=1`), as well as more reliable Promise.all support.
> Bundle dependencies

- lib/fs/obliterate.js
- lib/install.js
In practice, this allows you to interrupt `pnpm install`, then run it again, and it'll work just fine after that... no matter where you stopped it.
- This makes `pnpm` installs into `.store` atomic. That is, if it's in `.store` and `.store/lodash@4.0.0/.pnpm_inprogress` is not present, you're sure that it's an incomplete installation of a module.
- With that, this adds `.pnpm_inprogress` to modules that are currently in progress in being built. It's cleaned up afterwards.
- `node_modules/.tmp` is cleaned up afterwards. There's no explicit handling to `rm -rf .tmp` or anything (that'd be awful!)—simply, if pnpm tries to rebuild a module that has `.pnpm_inprogress` (ie, from a broken install), it'll know to tear the old `.tmp` version of that down. Neat.
Note that since 0.5.0, pnpm symlinks …
> Improve atomicness

- lib/install.js
- lib/logger.js
- lib/resolve.js
- lib/resolve/npm.js
This better stops pnpm from doing anything when a sub-package is already bundled in a package, typically using `bundleDependencies`. This happens in `fsevents@1.0.6` where `node-pre-gyp` is already part of the `fsevents` package.
This also refactors `lib/resolve.js` a bit so that tarball/github resolution can be better implemented in the future.
> Improve bundleDependencies support

- HISTORY.md
- bin/pnpm-install
- lib/fs/require_json.js
- lib/install/post_install.js
This fixes running `pnpm install express` in a path where there's no package.json.
> Fix running pnpm in dirs without package.json

- HISTORY.md
- README.md
- lib/config.js
- lib/registry_for.js
- lib/resolve/npm.js
- package.json
> ## Custom registries
> 
> pnpm follows whatever is configured as npm registries. To use a custom registry (like the [strongloop npm registry](https://strongloop.com/strongblog/node-js-registry-mirror-rackspace/)), use:
> 
> ```sh
> # updates ~/.npmrc
> npm config set registry http://npmjs.eu
> ```
> 
> Or to use it for just one command:
> 
> ```
> env npm_registry=http://npmjs.eu
> ```
> 
> Private registries are supported, as well.
> 
> ```sh
> npm config set @mycompany:registry https://npm.mycompany.com
> pnpm install @mycompany/foo
> ```
> Custom registries (#10)

- HISTORY.md
- lib/resolve/npm.js
- test/index.js
This allows you to do:
```
pnpm i @rstacruz/tap-spec@4.1.1
```
We'll do a proper implementation soon (#12), but for now... this'll do. (#9)
> Work around scoped module limitations

- .travis.yml
- HISTORY.md
- README.md
- lib/fs/require_json.js
- lib/install.js
- lib/install/link_bins.js
- lib/install/link_bundled_deps.js
- lib/install/post_install.js
- package.json
- test/index.js
When you do `npm ls` in a pnpm-managed store, you get `extraneous` errors. This prevents you from shrinkwrapping.
This fixes that. Aww yiss.
> Increase compatibility with npm ls & shrinkwrap

- .travis.yml
To make the build faster.
Reference:
https://docs.travis-ci.com/user/workers/container-based-infrastructure/
> Enable container-based infrastructure on travis-ci

- bin/pnpm-install
- lib/install.js
- lib/resolve/npm.js
- lib/save.js
- test/index.js
Just doing an early pr so you can take a look and let me know if I'm on the correct path or if you have other ideas about how it should be implemented.
> [WIP] Support for the --save and --save-dev flags

- bin/pnpm
Without this detection,
if a user gives no parameter, the error message will be:
> shift: can't shift that many
Tell the users to pass at least 1 parameter and then print `pnpm-install --help` to improve the UX.
> Detect number of parameters, exit if less then 2.

- .npmignore
- HISTORY.md
- bin/pnpm-install
- lib/cmd/install.js
- lib/fs/unsymlink.js
- lib/install.js
- lib/install/link_peers.js
- package.json
- test/index.js
This emulates npm3's "flat" storage without actually being flat. This allows us to use peerDependencies. Work in progress; answers #42.
Given this dep tree:
- rimraf *
- glob ^6.0.1
- inflight ^1.0.4
- inherits 2 
It'll create these:
```
node_modules/.store/rimraf@2.5.1/_
node_modules/.store/glob@6.0.4/_
node_modules/.store/inflight@1.0.4/_
node_modules/.store/inherits@2.0.1/_
node_modules/rimraf (symlink)
```
but also create these symlinks:
```
node_modules/.store/node_modules/rimraf
node_modules/.store/node_modules/glob
node_modules/.store/node_modules/inflight
node_modules/.store/node_modules/inherits
```
that way, `inflight` can `require('inherits')` and it'll work. this also does so without any polution in `node_modules`, which means `npm ls` and `npm shrinkwrap` will work. \o/
> npm3-style flatness

- .travis.yml
- bin/pnpm-install
- lib/promise.js
- package.json
- test/index.js
This will transpile `lib/` down to Node 0.10 compatible syntax before publishing.
This supports all the way down to node 0.10, but that version comes with npm1.4. pnpm will work just fine with it, but to get support for `shrinkwrap` they'd need to upgrade to `npm@2`.
> Be compatible with Node.js 0.10

- bin/pnpm
I got hit by [this](http://superuser.com/questions/897148/shell-cant-shift-that-many-error).
```bash
❯ pnpm --help
/usr/local/bin/pnpm: 15: shift: can't shift that many
```
By always providing an argument for `shift` it should work for all shells :smile: :+1:
> Always provide an argument for shift

- lib/resolve/npm.js
Related to issue: https://github.com/rstacruz/pnpm/issues/44
Some registries do not support filtering metadata requests by adding a semver suffix to the uri. If this is the case we will get a 404, so we can fetch the metadata for all versions of the package and resolve the correct version on the client side - which is what npm does. If it still doesn't match then we error as per npm.
The specific use-case I'm interested in is when using GemFury to host private packages. GemFury will proxy any requests for non-private packages straight to the npm registry - which means that this approach will not result in two requests for every package when using it.
I'll add some unit tests if you think it's worth continuing with this PR
> Retry npm registry package resolving when 404s

- lib/resolve/npm.js
@misterbyrne, I've made your module resolution code the default method of finding packages. This is because the one we're using by default, `registry.npmjs.org/lodash/4.0.0`, is actually an undocumented endpoint (and hence not implemented by gemfury et al).
This instead uses `registry.npmjs.org/lodash`.
This has the following benefits:
- no more workarounds for scoped packages
- support for dist-tags for scoped packages
- faster gemfury downloads
- only need to fetch one json per package (eg, installing both lodash@2 and lodash@3 will perform 1 resolution, not one)
- faster dependency resolution for large packages because of the above (slightly?)
expect a possible slight performance dip for smaller packages, but not by much.
> Use npm's resolution algorithm

- lib/install.js
- test/index.js
#51. This allows you to do:
```
npm install lodash@3
npm install lodash@4
```
and it'll overwrite `lodash` with version 4.
> Allow installing new versions (#51)

- test/index.js
This is related to https://github.com/rstacruz/pnpm/pull/81 changes. I think you're taking advantage of `.only` for isolation of tests, but forgot to remove after working with the PR. :angel:
> Removes .only so other test cases won't be ignored

- bin/pnpm-install
Suppoer for --production was added in https://github.com/rstacruz/pnpm/pull/68 - but the check against production in bin/pnpm-install was still there prohibiting --production from working.
> remove production check in bin/pnpm-install

- lib/save.js
- package.json
- test/index.js
`npm` [installs things][demo] in [sorted manner][sorted], `pnpm` doesn't, so if you use `npm` after `pnpm`, you will get rewrited `package.json` and messy diff. This is a fix
[demo]: https://github.com/iamstarkov/npm-install-sorted-demo
[sorted]: https://github.com/npm/npm/blob/master/lib/utils/deep-sort-object.js#L2
> Feature: sorted deps

- lib/got.js
- package.json
- test/index.js
By simply using 'caw' module to create the HTTP agent with proxy settings
we are able to use 'pnpm' behind a basic corporate proxy (I could not test
it extensively on any kind of proxy).
I had to disable 'sepia' caching in case a proxy configuration is found
because it was not behaving fine with the new HTTP agent setup.
> Enable proxy tunneling

- lib/install.js
I _think_ I may have found the cause of #78 - and if I'm right then here's a quick fix. It's kinda hard to be sure since I couldn't recreate at will - although I could recreate it quite frequently on certain repos and haven't seen it on them since. I imagine that there are other non-sync ways of fixing the problem - but I haven't really looked that far.
Ideas:
- maybe only make the `unlink` call synchronous
- turn the `unlink` => `rename` chain into a promise that the `symlinkToModules` of dependents must wait for
- change `symlinkToModules` so it doesn't care if the rename is complete (would anything else downstream care either?)
> Fix issue #78 ?

- lib/fs/force_symlink.js
This should fix @rexxar's report here: https://github.com/rstacruz/pnpm/pull/138#issuecomment-205717593
In moving from `fs.symlink` to `fs.symlinkSync`, we missed one other call to fs.symlink(). This fixes that.
> Install: do symlinks synchronously

- lib/got.js
- package.json
**TL;DR:  This adds the auth token for requests to registries that npm already knows about. In other words, do an `npm adduser` first, then use pnpm as you normally would.**
Hi!
We're using a private Sinopia registry where I work, which requires authentication. Right now, pnpm can't be used in projects where we have a mixture of "external" and "internal" dependencies, because it doesn't send any auth info (which results in the registry sending a 403).
I've made a simple module that extracts the auth token set in `.npmrc` (if one exists) and added that as a dependency. I couldn't quite make out the official client signs requests and in which cases `always-auth` is used. For our internal registry, I have *not* set `always-auth`, yet it still authenticates GET-requests. So for now, I'm just …
> Send auth token if one exists for registry (#167, #105)

- lib/resolve.js
- lib/resolve/github.js
This PR adds support for resolving packages hosted on GitHub. It calls GH API first to resolve reference to a commmit SHA, then uses it to fetch `package.json` (to know which package name it is) and then to generate link to a tarball.
Let me know if I'm missing something and what should I do so functionality is merged into pnpm.
P.S. Thanks for pnpm, this is a huge improvement over official `npm install`
> Resolve hosted github packages

- lib/cmd/install.js
- package.json
close #50
cross-spawn used for executing the npm commands. There were problems on Windows when running `npm run` by `child_process.spawnSync`
> run postinstall and prepublish after installation

- lib/install.js
- lib/install/link_peers.js
- test/index.js
When a dependency is dependent on a scoped package, there is an error during installation. I was able to reproduce it via a test and then fix it.
close #219
> Fix issue with installing nested scoped packages

- HISTORY.md
- lib/fs/force_symlink.js
- lib/fs/rel_symlink.js
- lib/install.js
close #6
Checked on Windows 10. After these changes admin permissions are not needed for pnpm to work.
> Use junctions on Windows

- HISTORY.md
- lib/cmd/install.js
- lib/config.js
During implementation of #166 `camelcase-keys` was used to convert configs to camelcase function options and the underscored store_path option was not updated.
> Fix store-path property usage from the configs

- lib/got.js
- package.json
There is still an internal bug in rexxars/registry-auth-token#6,
but it just hits a very special use case and should also exist in 2.1.1.
So if 2.1.1 works for you, 3.0.0 should work as well.
resolves #270 #277
> add support for Basic Auth (registry-auth-token@3.0.0)

- lib/fs/require_json.js
- lib/save.js
- test/index.js
Using the cached version of package.json can cause overwriting of changes
close #280
> Read package.json before updating

- package.json
I suggest to use standardized commit messages. That will allow to generate the `HISTORY.md` file and maybe use `semantic-release` to automatically publish to npm.
This commit messages convention is used in many projects. @rstacruz, are you OK with it?
Some projects the use this commit format:
* https://github.com/ReactiveX/rxjs
* https://github.com/cyclejs/cyclejs
> Use commitizen for consistent commit messages

- .travis.yml
- appveyor.yml
This is crazy but pnpm can be used to install the dependencies for itself!
This is a nice additional check for the latest version of pnpm.
> Use pnpm for installing its own dependencies

- lib/install/link_bins.js
I've noticed this issue after we've started to use pnpm to install pnpm deps. The build was failing too frequently on appveyor.
link_bins was not returning a Promise. As a consequence the linking step was being completed too early and the next step was trying to use the bin files which were not yet created.
I think this bug is a pretty old one. Might fix some of the open issues.
> bin files are used once they were created

- lib/install/post_install.js
This is just a direct fix for my specific issue. I decided not to go down the rabbit hole of fixing the other potential incompatibilities with npm in lifecycle scripts.
> fix(post-install): prefer current node interpreter in child scripts (Fixes #296)

- bin/pnpm.js
- package.json
The current pnpm output on CI servers is not readable. It is better to not show the logs than to show a lot of mess.
> Run pnpm quietly on CI servers

- docs/store-json.md
- lib/api/init_cmd.js
- lib/api/install.js
- lib/api/uninstall.js
- lib/fs/store_json_controller.js
- lib/pkg_full_name.js
- lib/resolve/github.js
- lib/resolve/local.js
- package.json
- test/support/prepare.js
! can be part of a valid npm package name. Use + as a delimiter instead.
close #276
Stores created with the ! delimiter are not compatible with the new version that uses +.
Any store created by older versions of pnpm has to be removed and reinstalled.
> fix: don't use ! as a delimiter in the store

- lib/install/link_peers.js
- lib/resolve/github.js
- lib/resolve/local.js
- test/index.js
- test/packages/peer-deps-in-child-pkg/package.json
- test/packages/test-pnpm-peer-deps/package.json
Expose the version when possible, but the installation shouldn't
fail even when one of the peer dependencies have no version.
close #293
> fix: installation should not fail when peer has no version

- .scripts/hide_deps.js
- .scripts/release.sh
- .scripts/rename_key.js
- .scripts/unhide_deps.js
- .travis.yml
- appveyor.yml
If it will be decided that https://github.com/rstacruz/pnpm/pull/310 is too risky, this solution can be used. This solution doesn't make any changes in how pnpm is currently being installed and how it works, but it publishes every time pnpm is published and alternative version which has an improved installation speed.
> Publish an alternative version of pnpm with bundled dependencies

- .github/ISSUE_TEMPLATE.md
- bin/pnpm.js
- lib/api/init_cmd.js
- lib/debug.js
- lib/fetch.js
- lib/file_logger.js
- lib/fs/force_symlink.js
- lib/fs/mkdirp.js
- lib/install.js
- lib/install/post_install.js
- lib/logger/pretty.js
- lib/logger/simple.js
- lib/network/got.js
- lib/run_script.js
- package.json
- test/index.js
I created a custom logger for this feature (please review it as well [@zkochan/logger](https://github.com/zkochan/logger)). If it is fine, I'll transfer it to the pnpm organization.
The main idea is to use a logger which emits events with the logging info. The file logger records all the different logging levels. The progress logger listens only the `progress` type.
Also I substituted the debug usages with @zkochan/logger usages. But I did not remove debug, it listens now for debug logging events.
Example output: https://gist.github.com/zkochan/272e4c60eb3248373c63af9bc2db8924
> Create pnpm-debug.log file on fail

- lib/api/install.js
- lib/install.js
- lib/install/link_bins.js
- lib/install/post_install.js
- lib/install_multiple.js
- lib/logger/pretty.js
- package.json
pnpm currently runs the post install scripts of dependencies immediately once their resources were downloaded and does that asynchronously.
npm runs all the post install scripts once all the resources were downloaded and does that sequentially.
This changes makes pnpm run the scripts similarly to how npm runs them
Solves #337
> Run post install scripts after all dependencies were installed

- src/run_script.ts
Sometimes PATH env variable is called Path on Windows
The solution is a copy/paste [from npm](https://github.com/npm/npm/blob/8fa75cd0313e3cea8459f89b79208461e54b033b/lib/utils/lifecycle.js#L20-L28)
> fix(lifecycle): use the correct PATH env variable on Windows

- package.json
- src/api/initCmd.ts
- src/resolve/github.ts
- test/index.ts
GitHub API usage removed. The tarball is used from codeload.github.com
Close #361
The store path has changed for GitHub-hosted packages... Probably I'll add a notification to users that will force them to reinstall all the dependencies.
> fix(install): GitHub API rate limit issue

- docs/store-json.md
- package.json
- src/api/initCmd.ts
- src/api/uninstall.ts
- src/fs/storeJsonController.ts
- src/installMultiple.ts
- test/uninstall.ts
pnpm uninstall could not always link the dependency name to the dependency ID (used in the store). To solve this issue, a dependency name to ID map is added to the dependencies section of `store.json`.
The structure of the `store.json` has been changed.
Previously the dependencies property contained just a list of dependency IDs. E.g.:
```json
{
"math": [
"sum@1.0.0",
"@zkochan+max@2.1.0"
]
}
}
```
With this structure it was hard to link the dependencies to their IDs. The new structure uses a map which links the dependency to its ID:
```json
{
"map": {
"sum": "sum@1.0.0",
"@zkochan/max": "@zkochan+max@2.1.0"
}
}
}
```
Unfortunately the stores created by older version of pnpm are not usable after this breaking change. They have to be …
> fix(uninstall): dependencies from all sources can be deleted

- package.json
- src/api/install.ts
- src/api/uninstall.ts
- src/install/index.ts
- src/installMultiple.ts
- test/install.ts
- typings/local.d.ts
If a different version of a package is installed, the previous version should be removed from the store if no other package is dependent on it.
> fix(install): overwriting removes the previous version

- package.json
- src/api/extendOptions.ts
- src/api/install.ts
- src/api/link.ts
- src/env.ts
- src/install/installMultiple.ts
- src/install/linkBins.ts
- src/types.ts
- test/install.ts
This solves lots of issues that pnpm currently has on Node.js 4. Hopefully it also allows the usage of pnpm without the `--preserve-symlinks` option.
Ref #527
Most of the magic was done in cmd-shim [here](https://github.com/zkochan/cmd-shim/commit/68dc8ce2fc18228fd958940921ec121d70add6dc)
> When links are not preserved, set NODE_PATH for binstubs

- src/install/fetch.ts
- test/install.ts
We fetch into a temp directory now and then fs.rename() into the target dir.
With fs.rename() being an atomic operation we don't leave target dir in an
inconsistent state if failure happen in some parallel installation process.
Supersedes #549 
Fixes #547
> fix: make fetch atomic

- src/resolve/git.ts
- src/resolve/index.ts
Try the GitHub API first to resolve git deps. If fails due to
API limit, fall back to `git ls-remote`.
Always use codeload to download deps from GitHub.
Close #536
> perf(git-resolver): try the GitHub API first to resolve git deps

- src/api/getContext.ts
I'm publishing my fork of pnpm to try extensions API and stumbled with this.
> fix: handle the case when the package manager name is scoped

- README.md
- docs/README.md
- docs/global-install.md
- package.json
- src/api/cache.ts
- src/api/constantDefaults.ts
- src/api/extendOptions.ts
- src/api/getContext.ts
- src/api/install.ts
- src/api/link.ts
- src/cmd/cache.ts
- src/install/installMultiple.ts
- src/install/linkBins.ts
- src/types.ts
- test/cache.ts
- test/support/testDefaults.ts
- tsconfig.json
- typings/local.d.ts
To make global CLIs work without any additional configuration, link bins to a directory which is already in the system path.
> Global bin

- README.md
- package.json
- src/api/checkCompatibility.ts
- src/api/install.ts
- src/install/installMultiple.ts
- src/install/linkBins.ts
- src/install/linkPeers.ts
- test/install.ts
- typings/local.d.ts
This is a node_modules structure change. It combines changes from v0.50, where the package real location was moved under `node_modules` and changes from v0.51 for avoiding circular symlinks. This should solve #118.
Also made the realpath of modules shorter for nicer callstacks. Instead of 
`node_modules/.resolutions/registry.npmjs.org/<package name>/<version>`
it will be
`node_modules/.registry.npmjs.org/<package name>/<version>`
> Package realpath is always in a folder named as the package

- src/fs/getPkgDirs.ts
- src/install/installMultiple.ts
Fixing a regression caused by f39402e2ac0bd9494b8c1154a20dedd45e127da9
The issue was that bins were linking while dependencies were not yet installed
Hard to reproduce, unfortunately I was unable to write a unit test to cover the issue
Also a little refactoring
> Fix issue with bins linking

- src/bin/pnpm.ts
- src/fs/gracefulify.ts
- src/index.ts
- tsconfig.json
- typings/local.d.ts
`graceful-fs` solves the issue of EMFILE errors. However, the global fs module has to be patched.
This same solution is used by npm.
Close #609
> fix: too many open files

- src/api/extendOptions.ts
- src/api/install.ts
- src/fs/shrinkwrap.ts
- src/install/fetchResolution.ts
- src/resolve/git.ts
- src/resolve/index.ts
- src/resolve/local.ts
- src/resolve/npm/index.ts
- src/resolve/tarball.ts
- src/save.ts
- test/cache.ts
- test/cli.ts
- test/install.ts
- test/shrinkwrap.ts
- test/uninstall.ts
- test/utils/prepare.ts
The previous format had no specs in the entry point of the shrinkwrap file:
```yaml
dependencies:
react-datetime: localhost+4873/react-datetime/2.8.8
```
Hence if `react-datetime` was updated in package.json, it was reused from shrinkwrap.yaml anyway. The new version has the package name + the spec.
```yaml
dependencies:
react-datetime@^2.8.8: localhost+4873/react-datetime/2.8.8
```
This is needed only in the entry point. Other resolutions are package/version specific, so their spec will never change. E.g.
```yaml
packages:
localhost+4873/object-assign/3.0.0:
resolution:
shasum: 9bedd5ca0897949bca47e7ff408062d549f587f2
tarball: 'http://localhost:4873/object-assign/-/object-assign-3.0.0.tgz'
type: tarball
```
> Fix/shrinkwrap deps of deps should satisfy package.json semver

- docs/vs-npm.md
- package.json
- src/api/checkCompatibility.ts
- src/api/install.ts
- src/install/installMultiple.ts
- src/link/index.ts
- src/link/resolvePeers.ts
- test/install/peerDependencies.ts
BREAKING CHANGE: structure of node_modules changed
Close #678 
Example
```
.
└─ node_modules
├─ a             -> .registry.npmjs.org/b/1.0.0/node_modules/a
├─ b             -> .registry.npmjs.org/b/1.1.0/node_modules/b
├─ abc           -> .registry.npmjs.org/abc/1.0.0/a@1.0.0+b@1.1.0/node_modules/abc
├─ abc-carrier   -> .registry.npmjs.org/abc-carrier/1.0.0/node_modules/abc-carrier
└─ .registry.npmjs.org
├─ a ...
├─ b ...
├─ c ...
├─ abc-carrier/1.0.0/node_modules
|     ├─ abc-carrier   
|     ├─ b             -> .registry.npmjs.org/b/1.1.0/node_modules/b
|     └─ abc           -> .registry.npmjs.org/abc/1.0.0/a@1.0.0+b@1.0.0/node_modules/abc
└─ abc/1.0.0
├─ node_modules (the non-peer dependencies of abc)
|  └─ c   -> .registry.npmjs.org/c/1.0.0/node_modules/c
├─ …
```
> feat: proper resolving of peer dependencies

- package.json
- src/api/getContext.ts
- src/api/install.ts
- test/breakingChanges.ts
- typings/local.d.ts
* keeping external symlinks when recreating node_modules
* allow recreating node_modules only via general installation
Close #674
> Better DX on breaking node_modules changes

- src/api/getContext.ts
- src/api/install.ts
- src/api/removeOrphanPkgs.ts
- src/api/storeStatus.ts
- src/api/uninstall.ts
- src/fs/modulesController.ts
- test/storeStatus.ts
A new property called `skipped` added to
`node_modules/.modules.yaml`. The property is an array of
package IDs, of those packages that are optional an were
skipped during installation.
Close #681
> fix: store status doesn't fail on skipped optional deps

- package.json
- shrinkwrap.yaml
- src/api/install.ts
- src/api/uninstall.ts
- src/fs/safeReadPkg.ts
- src/link/index.ts
- src/link/resolvePeers.ts
- src/removeTopDependency.ts
- test/install/peerDependencies.ts
There is no need to always run a general installation for
creating a predictable `node_modules` structure. If peers are
resolved from top dependencies, the peers are not linked to
the dependent package. The dependent package can see such peers
w/o additional manipulations
Ref #724
> fix: peers are resolved similarly during named and general install

- README.md
- docs/how-peers-are-resolved.md
- package.json
- shrinkwrap.yaml
- src/link/index.ts
- src/link/resolvePeers.ts
- test/install/peerDependencies.ts
When a peer dependency is resolved not from the direct parent,
dependent packages should be duplicated with hard links in order
to preserve the correct set of resolved peer dependencies.
Semi-breaking change. The node_modules structure is changed but
doesn't need a complete removal of a node_modules created with
previous version of pnpm.
> 	fix(linking): packages should not loose their peer deps

- src/api/install.ts
- src/fs/pkgIdToFilename.ts
- src/fs/shrinkwrap.ts
- src/install/fetch.ts
- src/install/installMultiple.ts
- src/link/index.ts
- src/resolve/index.ts
- src/resolve/local.ts
- test/install/local.ts
- tsconfig.json
Relative path to the current working directory is saved
in the `shrinkwrap.yaml`.
Close #744
> fix(shrinkwrap): don't save absolute path shrinkwrap.yaml

- docs/vs-npm.md
- package.json
- shrinkwrap.yaml
- src/api/install.ts
- src/api/link.ts
- src/api/removeOrphanPkgs.ts
- src/install/fetch.ts
- src/install/fetchResolution.ts
- src/install/installMultiple.ts
- src/link/index.ts
- src/link/updateShrinkwrap.ts
- src/resolve/local.ts
- test/install/local.ts
- test/packages/pkg-with-local-dep/index.js
- test/packages/pkg-with-local-dep/package.json
This is roughly how `npm@5` handles it. However, pnpm does not try to install dependencies of the file dependency, just a symlink is created and the binstubs are linked into `node_modules/.bin` if there are any.
**BREAKING CHANGE:**
file dependencies are symlinked instead of copied (packed/unpacked)
Ref #772
> feat: symlink file dependencies instead of copying them

- .gitignore
- README.md
- package.json
- shrinkwrap.yaml
- src/bin/pnpm.ts
- src/cmd/help.ts
- src/cmd/install.ts
- src/cmd/recursive.ts
- src/cmd/update.ts
- src/requireHooks.ts
- test/install/hooks.ts
- test/recursive.ts
Add an `--ignore-hooks` flag. This is needed for the Glitch usecase, as `--ignore-scripts` don't cover the hooks too (I assume). If you want I can also merge the `--ignore-hooks` behavior into `--ignore-scripts`.
> feat: option to disable pnpm hooks

- src/cmd/recursive.ts
`await [Promise]` returns immediately; we want to wait for each
installation to complete before advancing to the next chunk.
enabling tslint's `await-promise` rule could have caught this, but
only if the typings for p-limit and graph-sequencer were improved.
> fix: wait for recursive package installation

- README.md
I think 2018 must be the year more people would use `pnpm` than `npm` & `yarn` as it saves an enormous amount of space. 
So this is the 1st question that comes up to the mind I guess (at least mine). Info from #1019.
> Added a FAQ

- package.json
- shrinkwrap.yaml
- src/cmd/recursive.ts
- test/recursive.ts
A ~`packages.yaml`~`pnpm-workspace.yaml` file can be used in the root of a multi-package
repository to specify an array of globs to use as package locations
Example of a ~`packages.yaml`~`pnpm-workspace.yaml` file:
```yaml
packages:
- 'packages/**'
- 'components/**'
```
close #1038
> feat(recursive): running commands on a subset of packages

- packages/default-reporter/src/reportError.ts
When execa throws error, the err object has code in number, not string.
When you try install a non-exist git dep (for instance typo)
```
⋊> ~/p/tp pnpm i fewofn/fdson
err.code.startsWith is not a function
```
> fix(reporting): fix exception on err.code.startsWith

- packages/supi/src/link/index.ts
- packages/supi/test/install/shamefullyFlatten.ts
I just moved `linkBins` below the flattening of the graph.
I've also added a check in the test.
> fix: call linkBins after we flattened the graph

- packages/pnpm/test/run.ts
pnpm does not properly pass arguments to command that is specified in the build script as npm does, with this change pnpm behaves exactly like npm.
Closes #1124
> fix: issue with passing properly args to the comannd

- packages/supi/src/api/getContext.ts
- packages/supi/test/install/independentLeaves.ts
- packages/supi/test/install/shamefullyFlatten.ts
I found the `--shamefully-flatten` error messages to be confusing because the grammar is odd.
This is a small fix to improve the wording, since we're experimenting with supporting this option.
> Clarify wording of error messages

- packages/default-reporter/src/reporterForClient.ts
- packages/pnpm/package.json
- packages/pnpm/shrinkwrap.yaml
- packages/pnpm/src/cmd/recursive/index.ts
- packages/utils/src/loggers.ts
Running scripts (lifecycle events) is performed only once all
install, unlink, update (or any other actions) are completed in
every project of the workspace.
close #1089
> feat(recursive): running scripts is a separate installation step

- packages/headless/src/index.ts
- packages/modules-yaml/src/index.ts
- packages/modules-yaml/test/index.ts
- packages/pnpm/test/recursive/misc.ts
- packages/supi/src/api/getContext.ts
- packages/supi/src/api/install.ts
- packages/supi/src/api/rebuild.ts
- packages/supi/src/api/uninstall.ts
- packages/supi/test/install/shamefullyFlatten.ts
- packages/supi/test/install/shrinkwrapDirectory.ts
- packages/supi/test/shrinkwrap.ts
This changes the way node_modules information of importers is
stored. The initial implementation in #1373 used a separate
`.modules.yaml` in every importer's node_modules directory.
Keeping only one `.modules.yaml` makes it easier to get all the
necessary info during recursive installation.
ref #1366
> feat: add importers field to .modules.yaml

- packages/pnpm/src/cmd/recursive/index.ts
- packages/pnpm/test/monorepo/index.ts
This is another issue with the graph-sequencer producing strange results when
sorting topologically, but everything should be fine. (
*I hope so*, because I really would like to use the `--filter=...package` feature!) 
Case that is fixed here:
- Package 'a' depends on 'b' and 'c'
- Package 'd' depends on 'a'
- Package 'e' depends on 'a', 'b' and 'c'
Command that has the wrong behavior:
pnpm recursive --filter=...a [command]
**Expected behavior**:
Packages are executed in order `['a', ['d', 'e']]` ('d' and 'e' can be
executed in parallel.)
**Actual behavior**:
Packages are executed in order `[['e', 'a', 'd']]`
**Fix to get expected behavior**:
Remove the unused dependencies 'b' and 'c' from the graph when sorting.
> fix: ignore filtered packages when sorting topologically

- packages/pnpm/test/monorepo/index.ts
- packages/resolve-dependencies/package.json
- packages/resolve-dependencies/shrinkwrap.yaml
- packages/resolve-dependencies/src/resolveDependencies.ts
- packages/resolve-dependencies/src/wantedDepIsLocallyAvailable.ts
- packages/supi/src/install/index.ts
When `link-workspace-packages` is `true`, local packages should be
preferred even if packages from the registry are already present
in `shrinkwrap.yaml`.
> fix(recursive): always prefer local packages when they are present

- packages/config/src/index.ts
Fixes #1425.
As far as I can tell, this is all that was actually going on in that issue. I've tested this out locally and `pnpx install -g` and `pnpx` both seem to be working on Linux even in the presence of an APPDATA variable.
> fix(config): only install to APPDATA on Windows

- packages/supi/package.json
- packages/supi/test/install/installationChecks.ts
- packages/supi/test/storeAdd.ts
- packages/supi/test/storePrune.ts
- packages/supi/test/storeUsages.ts
- packages/supi/test/uninstall.ts
- privatePackages/assert-project/package.json
- privatePackages/assert-project/src/index.ts
- privatePackages/assert-store/src/index.ts
- shrinkwrap.yaml
Closes #1536 
- Modifies `assert-project` to use `assert-store` for store-related assertions
- Modifies tests in `supi` to use `assert-store` directly when no project is configured (`pnpm install` is not run in tests)
If store structure changes in the future:
- **Currently**: We must change all tests that hard-code paths to the store
- **With the change**: We would just change the functions in `assert-store`. All tests use this as a facade, meaning they would not need to be changed.
- Added new unit tests
- `pnpm test` on `assert-store` and `assert-project`
- `pnpm test` on changed files in `supi`
> test(supi): abstract store assertions via assert-store

- packages/pnpm/test/install/misc.ts
- packages/pnpm/test/monorepo/index.ts
- packages/supi/package.json
- packages/supi/src/install/index.ts
- packages/supi/src/utils/getPref.ts
- packages/supi/test/install/aliases.ts
- packages/supi/test/install/misc.ts
- packages/supi/test/install/multipleImporters.ts
- packages/supi/test/install/peerDependencies.ts
- packages/supi/test/install/updatingPkgJson.ts
- packages/supi/test/uninstall.ts
- shrinkwrap.yaml
close #1633
the specified version spec is prefered. It doesn't matter what are
the values of the save-exact and save-prefix configs.
> feat: when a version spec is specified, add it to package.json

- packages/package-store/typings/index.d.ts
- packages/pnpm/src/cmd/store.ts
- packages/pnpm/src/types.ts
- packages/pnpm/test/storeAdd.ts
- packages/pnpm/typings/local.d.ts
- packages/resolve-dependencies/src/resolveDependencies.ts
- packages/supi/package.json
- packages/supi/src/storeAdd.ts
- packages/supi/test/storeUsages.ts
- packages/supi/typings/local.d.ts
- packages/utils/src/index.ts
- packages/utils/src/pickRegistryForPackage.ts
- pnpm-lock.yaml
> fix: "pnpm store add" should read the registries of scoped pkgs

- packages/default-resolver/src/index.ts
- packages/npm-resolver/src/index.ts
This exports the options of `@pnpm/npm‑resolver` as an interface so that they can be used by `@pnpm/default‑resolver`.
> refactor(default‑resolver): Use `ResolverFactoryOptions`

- packages/headless/src/index.ts
- packages/supi/src/install/index.ts
- packages/supi/src/install/link.ts
- packages/supi/src/save.ts
- packages/supi/test/install/lifecycleScripts.ts
When a non-optional package is not built successfully, the
package.json, pnpm-lock.yaml and node_modules/.pnpm-lock.yaml
should not be updated.
close #1397
> fix: a non-optional package's install script fails

- packages/fetch-from-npm-registry/src/index.ts
- packages/fetch-from-npm-registry/test/index.ts
> fix: correct HTTP agent should be selected after a redirect

- packages/pnpm/src/cmd/recursive/index.ts
- packages/pnpm/test/recursive/update.ts
> fix: recursive update --latest should use specs from local .npmrc

- packages/package-requester/package.json
- packages/package-requester/src/packageRequester.ts
- packages/supi/test/install/local.ts
- pnpm-lock.yaml
"pnpm install --frozen-lockfile" should fail if a local tarball's
integrity doesn't match the integrity in the lockfile.
close #1882
> fix: install should fail with out-of-date local tarball

- packages/headless/src/index.ts
- packages/modules-cleaner/package.json
- packages/modules-cleaner/src/prune.ts
- packages/supi/src/install/link.ts
- packages/supi/src/link/index.ts
- packages/supi/test/install/multipleImporters.ts
- pnpm-lock.yaml
When running install on a subset of workspace packages, only
those dependencies may be prunned which were only used by the
selected subset of workspace packages.
> fix: prunning by partial installation in a workspace

- packages/default-reporter/src/reportError.ts
- packages/default-reporter/test/reportingErrors.ts
- packages/package-is-installable/src/checkEngine.ts
- packages/package-is-installable/src/index.ts
- packages/pnpm/package.json
- packages/pnpm/src/cmd/install.ts
- packages/pnpm/src/cmd/link.ts
- packages/pnpm/src/cmd/prune.ts
- packages/pnpm/src/cmd/publish.ts
- packages/pnpm/src/cmd/rebuild.ts
- packages/pnpm/src/cmd/run.ts
- packages/pnpm/src/cmd/uninstall.ts
- packages/pnpm/src/cmd/unlink.ts
- packages/pnpm/src/findWorkspacePackages.ts
- packages/pnpm/src/readImporterManifest.ts
- packages/pnpm/test/install/misc.ts
- packages/types/src/package.ts
- pnpm-lock.yaml
pnpm should fail if the project has an engines.pnpm field in its
package.json and the running pnpm's version does not satisfy the
range.
pnpm should also fail it the project has an engines.node field
and process.version does not satisfy it.
close #1382
> feat: pnpm should fail if the project needs another version

- packages/package-is-installable/src/checkEngine.ts
- packages/package-is-installable/src/checkPlatform.ts
- packages/package-is-installable/src/index.ts
- packages/pnpm/src/cmd/install.ts
- packages/pnpm/src/cmd/link.ts
- packages/pnpm/src/cmd/outdated.ts
- packages/pnpm/src/cmd/prune.ts
- packages/pnpm/src/cmd/publish.ts
- packages/pnpm/src/cmd/rebuild.ts
- packages/pnpm/src/cmd/recursive/index.ts
- packages/pnpm/src/cmd/run.ts
- packages/pnpm/src/cmd/uninstall.ts
- packages/pnpm/src/cmd/unlink.ts
- packages/pnpm/src/findWorkspacePackages.ts
- packages/pnpm/src/packageIsInstallable.ts
- packages/pnpm/src/readImporterManifest.ts
- packages/pnpm/test/install/misc.ts
> fix: engines.node causes a fail only with engine-strict

- packages/default-reporter/src/reportError.ts
- packages/default-reporter/test/reportingErrors.ts
- packages/headless/src/index.ts
- packages/pnpm/src/cmd/recursive/index.ts
- packages/pnpm/test/install/shamefullyFlatten.ts
- packages/pnpm/test/monorepo/index.ts
- packages/shamefully-flatten/src/index.ts
- packages/supi/src/install/index.ts
- packages/supi/src/install/link.ts
- packages/supi/test/install/shamefullyFlatten.ts
> fix: flat node_modules is only possible in the workspace root

- packages/npm-resolver/src/index.ts
- packages/npm-resolver/test/index.ts
- packages/pnpm/src/cmd/publish.ts
- packages/pnpm/test/publish.ts
- ~save-exact should be considered when resolving `workspace:*`~ -no
- ~`pnpm add` inside a workspace should automatically use the `workspace:` protocol~ - do it in separate PR
> feat: support the workspace protocol

- packages/headless/package.json
- packages/headless/src/index.ts
- packages/headless/test/fixtures/simple-with-optional-dep/package.json
- packages/headless/test/fixtures/simple-with-optional-dep/pnpm-lock.yaml
- packages/headless/test/index.ts
"pnpm install --no-optional" should not fail on a project that
has an up-to-date lockfile.
close #1958
> fix(headless): should work with --no-optional

- packages/fetch-from-npm-registry/src/index.ts
- packages/fetch/package.json
- packages/fetch/src/index.d.ts
- packages/fetch/src/index.js
- packages/fetch/src/index.ts
- packages/fetch/tsconfig.json
- pnpm-lock.yaml
This adds type information to `@pnpm/fetch` and re‑exports important classes from `node‑fetch‑unix`.
This needs to be implemented in JavaScript with a hand‑written `.d.ts` file because only `node‑fetch` has a `@types` definition.
> feat(fetch): Add type information

- packages/pnpm/src/cmd/help.ts
- packages/pnpm/src/cmd/outdated.ts
- packages/pnpm/src/cmd/recursive/outdated.ts
- packages/pnpm/test/outdated.ts
- packages/pnpm/test/recursive/outdated.ts
Previously, by default the `outdated` commands displayed a “Details” column which usually contained the URL to the package repo. As the URL could be quite long, on narrow terminals it would cause the table to wrap in a way which ruined the table borders.
This commit hides the “Details” column by default, and displays the column if `--long` is passed to the command.
> feat(outdated): add long option, no details by default

- packages/pnpm/src/cmd/outdated.ts
- packages/pnpm/src/cmd/recursive/outdated.ts
This makes the following changes:
- Creates the `OutdatedOptions` interface
- Creates `sortOutdatedPackages(…)` helper functions
- Uses a `columnFns` array in both implementations
- `recursive outdated` used to directly pass an array to `R.sortWith()`
- Uses a `for`‑loop when applying the style to the table header to avoid the overhead of allocating a new array when calling `Array.map(…)`.
> refactor(pnpm): Unify more of `outdated` and `recursive outdated`

- packages/dependency-path/package.json
- packages/dependency-path/src/index.ts
- packages/dependency-path/test/index.ts
- packages/lockfile-utils/src/nameVerFromPkgSnapshot.ts
- packages/lockfile-utils/test/nameVerFromPkgSnapshot.ts
- pnpm-lock.yaml
This exposes the `peersSuffix` value from the `dependencyPath`.
- #1874
> feat(dependency‑path): Expose `peersSuffix`

- packages/pnpm/src/main.ts
- packages/pnpm/test/cli.ts
- packages/pnpm/test/install/misc.ts
- packages/pnpm/test/publish.ts
- packages/pnpm/test/uninstall.ts
- packages/pnpm/test/update.ts
close #1645
BREAKING CHANGES:
* the CLI fails when unknown options are used
* the CLI only accepts canonical forms of options:
* `pnpm install --no-package-lock` fails
* but `package-lock=false` in `.npmrc` is OK
> feat: cmds should fail on unsupported flags

- packages/config/src/index.ts
This change is making pnpm a little bit slower but the resulting node_modules will have fewer duplicates of packages. Our Twitter poll results show that deduplication is more important for our users the speed: https://twitter.com/pnpmjs/status/1109800824744656898
by default resolution-strategy=fewer-dependencies
> feat: use the fewer-dependencies resolution strategy by default

- packages/config/src/Config.ts
- packages/config/src/index.ts
- packages/package-store/package.json
- packages/package-store/src/fs/importIndexedDir.ts
- packages/package-store/src/fs/linkIndexedDir.ts
- packages/package-store/src/storeController/createImportPackage.ts
- packages/package-store/src/storeController/index.ts
- packages/package-store/test/createImportPackage.spec.ts
- packages/package-store/test/index.ts
- packages/pnpm/src/cmd/help.ts
- packages/supi/test/install/misc.ts
- packages/types/src/options.ts
- pnpm-lock.yaml
New config value for package-import-method: clone
close #1505
reflink is not supported by package-import-method
by default, try to clone packages instead of hard linking
> feat: use cross-platform solution to clone packages

- packages/lifecycle/src/runLifecycleHook.ts
> fix: show emptry string instead of undefined when package.json has no name

- packages/pnpm/src/main.ts
A lot of the pre‑4.0 commands support the `‑‑global` option, this adds it back where it makes sense.
I’ve also added all the documented options for [`pnpm why`](https://pnpm.js.org/en/cli/why).
> fix(pnpm): Add missing command options

- packages/pnpm/src/cmd/help.ts
Changes 'Manage you monorepo' to 'Manage your monorepo'. Simple fix I saw when I was trying to do some unrelated work.
> docs: fix typo in monorepo section

- typings/index.d.ts
- typings/typed.d.ts
Blocks #2019
This is done to preserve `git blame` and file history.
> refactor(typings): Rename `tape‑promise.d.ts` to `typed.d.ts`

- typings/local.d.ts
- typings/typed.d.ts
Blocks #2019
This ensures that any patches which switch from the `declare module {export = any}` type definition to a `@types/` or official type declaration don’t cause merge conflicts with #2019.
> refactor(typings): Sort third‑party type definitions

- packages/pnpm/src/cmd/recursive/index.ts
- packages/pnpm/src/cmd/recursive/run.ts
- packages/pnpm/test/recursive/run.ts
This changes the behavior of of `pnpm recursive run ...` so that it no
longer throws an error when run against a subset of packages and none of
the selected packages have the provided script.
Previously, running a command like `pnpm m run --filter foo build` would
throw an error if the `foo` package did not have a `build` script, even
if other workspace packages have a `build` script.
With this change, running `pnpm recursive run --filter foo build` will
not throw an error.
Note that if the provided package selectors match all packages (e.g.
`'*'`), then `pnpm recursive run` will fail if none of the packages have
the script. This is because the behavior depends on whether we're
running against a subset of packages or not, _not_ whether any package
selectors were provided.
Closes #1763
> feat(pnpm): don't fail 'recursive run' if no selected packages have script

- packages/config/src/index.ts
- packages/config/test/index.ts
This fixes 2 issues:
1. local registry settings should have bigger priority than global
2. package settings should have bigger priority than workspace set-
tings (this was only an issue with rawLocalConfig)
close #2096
> fix(config): settings are merged in correct order

- packages/package-is-installable/src/checkEngine.ts
- packages/package-is-installable/src/checkPlatform.ts
- packages/package-is-installable/src/index.ts
- packages/pnpm/src/packageIsInstallable.ts
This updates `@pnpm/package‑is‑installable` to use the `WantedEngine` and `WantedPlatform` types where appropriate.
> fix(package‑is‑installable): Use `WantedEngine` and `WantedPlatform`

- packages/lockfile-file/src/getLockfileImporterId.ts
This adds a return type to `getLockfileImporterId(…)`.
It would previously return `any` because of the untyped `normalize‑path` definition in `typings/local.d.ts`.
> feat(lockfile‑file): Add return type to `getLockfileImporterId(…)`

- packages/pnpm/src/cmd/publish.ts
- packages/pnpm/test/publish.ts
- packages/types/src/package.ts
Overriding some fields in the manifest, before the package is packed is a great
feature. [Package Bundlers](stereobooster/package.json#package-bundlers) support several additional fields.
This commit adds some of those well-known additional fields:
- [`browser`](stereobooster/package.json#browser)
- [`esnext`](stereobooster/package.json#esnext)
- [`es2015`](stereobooster/package.json#es2015)
- [`unpkg`](stereobooster/package.json#unpkg)
- `umd:main`: used by [microbundle](developit/microbundle)
- `exports`: Node.js [Package Exports](nodejs.org/api/esm.html#esm_package_exports)
Additionally the `bin` field may be overridden.
> feat(publishConfig): add additional well-known fields

- packages/npm-resolver/src/index.ts
- packages/npm-resolver/test/index.ts
I saw, that the `loose` options was already provided by using `true` as the last parameter https://github.com/npm/node-semver#functions.
Additionally adding `includePrerelease: true` also adds support for prerelease versions like `2.0.0-alpha.123`.
What is obviously missing in this PR is a test.
@zkochan would be great to get your advice on how to test this with the current setup :)
> Fixes #2171

- packages/pnpm/src/cmd/index.ts
- packages/pnpm/src/main.ts
This&nbsp;adds a&nbsp;proper&nbsp;type to&nbsp;what's&nbsp;exported from&nbsp;`cmd/index.ts`’s&nbsp;default&nbsp;export.
I’ve&nbsp;also&nbsp;improved the&nbsp;error&nbsp;message when&nbsp;`commandNames` hasn’t&nbsp;been&nbsp;properly&nbsp;specified.
> feat(pnpm): Add types to commands

- packages/plugin-commands-publishing/src/publish.ts
- packages/plugin-commands-publishing/test/publish.ts
Closes #2202
This PR makes sure, that the `workspace:` version protocol is not only cleaned up from the `dependencies` and `optionalDependencies`, but also from `devDependencies`.
> fix(publish): remove workspace from devDependencies

- packages/plugin-commands-installation/src/add.ts
However, to avoid confusion, "pnpm add --no-save <pkg>" fails.
ref #2110
> fix: don't fail on "pnpm add --save <pkg>"

- packages/config/src/Config.ts
- packages/config/src/index.ts
- packages/filter-workspace-packages/src/index.ts
- packages/find-workspace-packages/src/index.ts
- packages/pkgs-graph/src/index.ts
- packages/plugin-commands-installation/package.json
- packages/plugin-commands-installation/src/install.ts
- packages/plugin-commands-installation/src/link.ts
- packages/plugin-commands-recursive/src/exec.ts
- packages/plugin-commands-recursive/src/recursive.ts
- packages/plugin-commands-recursive/src/run.ts
- packages/plugin-commands-recursive/test/exec.ts
- packages/plugin-commands-recursive/test/link.ts
- packages/plugin-commands-recursive/test/list.ts
- packages/plugin-commands-recursive/test/misc.ts
- packages/plugin-commands-recursive/test/outdated.ts
- packages/plugin-commands-recursive/test/publish.ts
- packages/plugin-commands-recursive/test/rebuild.ts
- packages/plugin-commands-recursive/test/run.ts
- packages/plugin-commands-recursive/test/test.ts
- packages/plugin-commands-recursive/test/update.ts
- packages/plugin-commands-recursive/test/utils.ts
- packages/pnpm/package.json
- packages/pnpm/src/main.ts
- pnpm-lock.yaml
This changes will allow to move the recursive commands to the
plugins they belong to.
For instance, "pnpm install -r" should be handled by the same
plugin as "pnpm install"
> refactor: plugin-commands-recursive

- packages/supi/test/lockfile.ts
Hey @zkochan! We're decomissioning our private npm enterprise instance and moving to artifactory instead, so this service won't work anymore. I see you're skipping the tests anyway, so I think you may as well just delete it.
> Remove compass npm-registry test

- fixtures/has-outdated-deps/node_modules/.pnpm/lock.yaml
- fixtures/has-outdated-deps/package.json
- fixtures/has-outdated-deps/pnpm-lock.yaml
- packages/outdated/src/index.ts
- packages/plugin-commands-outdated/src/outdated.ts
- packages/plugin-commands-outdated/src/recursive.ts
- packages/plugin-commands-outdated/test/index.ts
- packages/plugin-commands-outdated/test/recursive.ts
This adds the ability to show only outdated dev or prod dependencies
```
pnpm [-r] outdated --dev
pnpm [-r] outdated --production [--no-optional]
pnpm [-r] outdated --no-optional
```
> feat: outdated --dev | --production | --no-optional

- packages/common-cli-options-help/src/index.ts
- packages/filter-workspace-packages/src/index.ts
- packages/filter-workspace-packages/src/parsePackageSelector.ts
- packages/filter-workspace-packages/test/index.ts
- packages/filter-workspace-packages/test/parsePackageSelector.ts
close #1651
Filtering by directory: `pnpm --filter {dir}`
Including dependents: `pnpm --filter ...{dir}`
Including dependencies: `pnpm --filter {dir}...`
Filtering changed projects inside a directory: `pnpm --filter {dir}[origin/master]`
> feat: filtering by location including deps/dependents

- fixtures/has-major-outdated-deps/.gitignore
- fixtures/has-major-outdated-deps/.npmrc
- fixtures/has-major-outdated-deps/node_modules/.pnpm/lock.yaml
- fixtures/has-major-outdated-deps/package.json
- fixtures/has-major-outdated-deps/pnpm-lock.yaml
- packages/outdated/package.json
- packages/outdated/src/index.ts
- packages/plugin-commands-outdated/src/createLatestManifestGetter.ts
- packages/plugin-commands-outdated/src/outdated.ts
- packages/plugin-commands-outdated/test/getLatestManifest.spec.ts
- packages/plugin-commands-outdated/test/index.ts
- pnpm-lock.yaml
> feat(outdated): --compatible

- packages/plugin-commands-outdated/src/recursive.ts
- packages/plugin-commands-outdated/src/utils.ts
- packages/plugin-commands-outdated/test/recursive.ts
`pnpm -r outdated` should show all the different current versions
close #2205
> fix(outdated): print different current versions separately

- packages/npm-resolver/src/index.ts
- packages/npm-resolver/test/index.ts
- packages/supi/src/install/index.ts
This fixes a regression introduced by #2172 (pnpm v4.3.3).
Local prerelease version of packages should be linked
only if the range is *
> fix: resolving packages in a monorepo

- packages/pnpm/src/main.ts
- packages/pnpm/test/monorepo/index.ts
Don't print an info message about projects not
being found when --parseable is used.
close #2265
close #1650
> fix: CLI output with --parseable

- packages/pnpmfile/src/requirePnpmfile.ts
- packages/pnpmfile/test/index.ts
- packages/pnpmfile/test/pnpmfiles/readPackageNoObject.js
- packages/pnpmfile/test/pnpmfiles/readPackageNoReturn.js
manifest's dependencies property must be an object, otherwise it will return an error message
Close #1296
> feat: add validation for readPackage hook's return manifest's dependencies property

- packages/plugin-commands-installation/src/install.ts
- packages/plugin-commands-installation/src/installDeps.ts
- packages/plugin-commands-installation/src/recursive.ts
- packages/plugin-commands-installation/src/update/index.ts
- packages/plugin-commands-installation/test/add.ts
- packages/plugin-commands-installation/test/update/recursive.ts
- packages/plugin-commands-installation/test/update/update.ts
- packages/supi/src/install/extendInstallOptions.ts
- packages/supi/src/install/getWantedDependencies.ts
- packages/supi/src/install/index.ts
- packages/utils/src/filterDependenciesByType.ts
- packages/utils/src/index.ts
Don't fail on recursive update when filtered by dependency types.
> fix: pnpm update -r --prod

- packages/cli-utils/src/getSaveType.ts
- packages/config/src/index.ts
- packages/plugin-commands-installation/package.json
- packages/plugin-commands-installation/src/recursive.ts
- packages/plugin-commands-installation/test/add.ts
- packages/plugin-commands-installation/test/addRecursive.ts
- packages/plugin-commands-installation/test/index.ts
- packages/pnpm/test/install/misc.ts
- packages/supi/src/utils/getPref.ts
- pnpm-lock.yaml
Recursively adding dependencies using --save-dev,
--save-optional, or --save-prod should work on
workspaces that don't use a central, shared
lockfile.
close #2294
> fix: add --save-dev -r

- packages/filter-lockfile/src/filterLockfileByImporters.ts
- packages/hoist/src/index.ts
- packages/lockfile-walker/src/index.ts
- packages/plugin-commands-rebuild/src/implementation/index.ts
- packages/supi/test/install/hoist.ts
Direct dependencies of workspace projects should
be hoisted.
close #2315
> fix: hoisting in a workspace

- packages/pnpm/src/main.ts
Suggested&nbsp;here: <https://github.com/pnpm/pnpm/issues/2169#issuecomment-581623835>
This&nbsp;makes&nbsp;`pnpm` exit&nbsp;with an&nbsp;error&nbsp;message when&nbsp;<code>pnpm&nbsp;r&nbsp;‑‑use‑beta‑cli</code>&nbsp;is&nbsp;run.
> feat(pnpm): Deprecate `pnpm r` alias of `pnpm remove`

- packages/parse-cli-args/src/index.ts
- packages/parse-cli-args/test/index.ts
- packages/pnpm/src/cmd/index.ts
- packages/pnpm/src/main.ts
- packages/pnpm/src/reporter/index.ts
- packages/pnpm/test/cli.ts
Fixes <https://github.com/pnpm/pnpm/issues/2325>
This&nbsp;isn’t&nbsp;technically a&nbsp;breaking&nbsp;change for&nbsp;`pnpm` (it&nbsp;might&nbsp;however&nbsp;be&nbsp;one for&nbsp;`@pnpm/parse‑cli‑args`), as&nbsp;unknown&nbsp;commands are&nbsp;already&nbsp;unsupported.
I’ve&nbsp;also slightly&nbsp;improved the&nbsp;error&nbsp;message that’s&nbsp;printed when&nbsp;<code>pnpm&nbsp;‑‑unknown‑option</code> is&nbsp;used, which&nbsp;currently&nbsp;writes:
```
For help, run: pnpm help undefined
```
instead&nbsp;of:
```
For help, run: pnpm help
```
> fix(pnpm): Fail on unknown command

- packages/pnpm/src/main.ts
- packages/pnpm/test/cli.ts
Running "pnpm" without any command should print help
and exit with a non-zero exit code.
ref #2325
> fix: pnpm should exit with non-zero code

- packages/filter-workspace-packages/src/index.ts
- packages/filter-workspace-packages/test/index.ts
- packages/plugin-commands-installation/src/installDeps.ts
- packages/plugin-commands-script-runners/test/runRecursive.ts
- packages/plugin-commands-script-runners/test/testRecursive.ts
- packages/pnpm/src/main.ts
> feat: print info if some of the filters don't match any projects

- packages/dependencies-hierarchy/src/index.ts
Introduces a cache for `getTree`.
Creates a helper function for `getTree` that returns dependencies along with whether there are any cycles in the tree in order to help calculate trees to the expected depth.
`pnpm why` takes two minutes in our repo without this change, but only three seconds with it.
close #2354
> perf(dependencies-hierarchy): cache previously found dependencies in getTree

- packages/default-reporter/src/reportError.ts
- packages/get-context/src/index.ts
- packages/supi/src/install/index.ts
- packages/supi/test/breakingChanges.ts
- packages/supi/test/install/only.ts
- packages/supi/test/lockfile.ts
When registries config settings change, don't create a broken
lockfile.
close #2379
TODO:
> fix: don't create a broken lockfile

- packages/plugin-commands-script-runners/src/run.ts
- packages/plugin-commands-script-runners/src/runRecursive.ts
- packages/plugin-commands-script-runners/test/runRecursive.ts
`pnpm run --filter <project>` should list available scripts of the project
`pnpm run --filter <project 1> --filter <project 2>` should fail
close #2357
> fix: pnpm run --filter <project>

- packages/dependencies-hierarchy/src/index.ts
Listing fails if package cannot be found in the wanted
lockfile.
close #2424
> fix: listing failure

- packages/hoist/src/index.ts
- packages/link-bins/src/index.ts
- packages/link-bins/test/index.ts
> fix: don't print useless warnings about conflicting binaries

- packages/npm-resolver/package.json
- packages/npm-resolver/src/index.ts
- packages/npm-resolver/tsconfig.json
- packages/pkgs-graph/package.json
- packages/pkgs-graph/src/index.ts
- packages/pkgs-graph/test/index.ts
- packages/plugin-commands-publishing/tsconfig.json
- packages/resolve-workspace-range/README.md
- packages/resolve-workspace-range/package.json
- packages/resolve-workspace-range/src/index.ts
- packages/resolve-workspace-range/tsconfig.json
- pnpm-lock.yaml
- utils/updater/src/index.ts
close #2279
We should use the same version matching algorithm when installing a new package inside the workspace and when sorting packages inside the workspace. This change is moving the version matcher to a new package and uses it in `@pnpm/npm-resolver` and `pkgs-graph`.
> fix(recursive): sorting prerelease packages

- .changeset/blue-wombats-help.md
- .changeset/mighty-buckets-study.md
- packages/plugin-commands-installation/src/remove.ts
- packages/plugin-commands-publishing/src/publish.ts
- packages/plugin-commands-publishing/test/gitChecks.ts
- packages/pnpm/src/main.ts
1. git checks before publish are on by default
2. `pnpm r` is not an alias of `pnpm remove`
> V5 breaking changes

- .changeset/swift-ties-cross.md
- packages/pnpm/bin/pnpm.js
> fix: print a meaningful error on unsupported Node.js versions

- .changeset/angry-mugs-argue.md
- packages/plugin-commands-script-runners/src/run.ts
- packages/plugin-commands-script-runners/src/runRecursive.ts
- packages/plugin-commands-script-runners/test/runRecursive.ts
I think these changes are correct.
I'm not sure whether the IF_PRESENT related functions / `const`s / help text should move along with the typing.
> feat: have if-present apply to recursive runs

- .changeset/fifty-horses-change.md
- packages/npm-resolver/src/index.ts
- packages/npm-resolver/src/pickPackage.ts
- packages/npm-resolver/test/index.ts
- packages/supi/test/install/lockfileOnly.ts
Reduce the number of directories in the store by keeping all the metadata json
files in the same directory.
Previously the metadata file of express would be stored at:
`<store>/registry.npmjs.org/express/index.json`
Now it will be stored at:
`<store>/metadata/registry.npmjs.org/express.json`
ref #2521
> perf: keep all the metadata files in the same dir

- .changeset/lovely-ducks-judge.md
- packages/cafs/src/getFilePathInCafs.ts
- packages/plugin-commands-store/test/storeAdd.ts
Instead of creating a separate subdir for executables in the content-addressable storage, use the directory where all the files are stored but suffix the executable files with `-exec`. Also suffix the package index files with `-index.json`.
ref #2521
> perf: use a suffix for exec files in CAFS, not a dir

- .changeset/three-moles-end.md
- packages/cafs/src/checkFilesIntegrity.ts
- packages/package-requester/src/packageRequester.ts
- packages/package-requester/test/index.ts
- packages/package-store/src/storeController/prune.ts
- packages/plugin-commands-store/src/storeStatus/index.ts
- packages/plugin-commands-store/test/storePrune.ts
- packages/pnpm/test/install/misc.ts
Move all the info in the package index file into a "files" property.
This will allow to store more information without breaking changes
in the future.
> feat!: make the package index file more extendable

- .changeset/wet-brooms-drive.md
- packages/headless/src/index.ts
- packages/headless/test/index.ts
- packages/hoist/src/index.ts
- packages/modules-cleaner/src/prune.ts
- packages/plugin-commands-rebuild/src/implementation/index.ts
- packages/plugin-commands-rebuild/test/index.ts
- packages/plugin-commands-store/src/storeStatus/index.ts
- packages/plugin-commands-store/test/storeStatus.ts
- packages/pnpm/test/install/misc.ts
- packages/resolve-dependencies/src/resolveDependencies.ts
- packages/supi/src/install/index.ts
- packages/supi/src/install/link.ts
- packages/supi/src/install/lockfile.ts
- packages/supi/src/install/resolvePeers.ts
- packages/supi/src/install/updateLockfile.ts
- packages/supi/test/install/fromRepo.ts
- packages/supi/test/install/hoist.ts
- packages/supi/test/install/independentLeaves.ts
- packages/supi/test/install/lifecycleScripts.ts
- packages/supi/test/install/misc.ts
- packages/supi/test/install/multipleImporters.ts
- packages/supi/test/install/optionalDependencies.ts
- packages/supi/test/install/peerDependencies.ts
- packages/supi/test/link.ts
- packages/supi/test/lockfile.ts
The structure of virtual store directory changed. No subdirectory created with the registry name. So instead of storing packages inside `node_modules/.pnpm/<registry>/<pkg>`, packages are stored inside `node_modules/.pnpm/<pkg>`.
> Reduce nesting in the virtual store

- .changeset/beige-ducks-rescue.md
- .changeset/heavy-eyes-ring.md
- .changeset/serious-geckos-taste.md
- packages/config/src/Config.ts
- packages/config/src/index.ts
- packages/plugin-commands-installation/src/installDeps.ts
- packages/plugin-commands-installation/src/recursive.ts
- packages/resolve-dependencies/src/index.ts
- packages/resolve-dependencies/src/resolveDependencies.ts
- packages/supi/src/install/extendInstallOptions.ts
- packages/supi/src/install/index.ts
- packages/supi/src/install/link.ts
- packages/supi/src/install/resolvePeers.ts
- packages/supi/src/install/updateLockfile.ts
- packages/supi/test/install/multipleImporters.ts
Setting the `link-workspace-packages` to `deep` makes pnpm resolve subdependencies from workspace packages.
> Linking packages to subdependencies

- packages/pnpm/README.md
pnpm v5 is significantly faster than npm and Yarn, so "as fast as" is not true anymore.
However, it is not as simple as that. I did not measure Yarn v2 with Plug'n'Play yet. And with the new Yarn, the workflow is a bit different. So we cannot compare Yarn v2 to pnpm v5.
So I think we need to explain pnpm's speed without mentioning Yarn and npm. At least not at the top of the page.
> docs(README): update speed description

- packages/pnpm/README.md
There are different ways to install pnpm but the easiest
and most reliable option is to use npm. So a new user should
use the method that we are most confident about.
> docs(README): suggest the most reliable installation

- .changeset/violet-steaks-burn.md
- packages/git-fetcher/src/index.ts
- packages/git-fetcher/test/index.ts
- packages/headless/test/utils/testDefaults.ts
- packages/store-connection-manager/src/createNewStoreController.ts
- packages/supi/test/utils/testDefaults.ts
Fixing a regression caused by breaking changes in the fetch function
API.
`@pnpm/git-fetcher` was not correctly updated.
As a result, git-hosted dependencies were not being installed.
> fix: installing git-hosted dependencies

- .changeset/nine-ants-add.md
- .changeset/three-cobras-wave.md
- packages/lifecycle/package.json
- packages/lifecycle/src/runLifecycleHook.ts
- packages/plugin-commands-script-runners/src/runRecursive.ts
- packages/plugin-commands-script-runners/test/runRecursive.ts
- pnpm-lock.yaml
A recursive run should not rerun the same package script which started the lifecycle event.
For instance, let's say one of the workspace projects has the following script:
```json
"scripts": {
"build": "pnpm run -r build"
}
```
Running `pnpm run build` in this project should not start an infinite recursion.
`pnpm run -r build` in this case should run `build` in all the workspace projects except the one that started the build.
Related issue: #2528
> fix(run): infinite recursion

- .changeset/happy-baboons-stare.md
- .changeset/late-pets-rescue.md
- .changeset/lovely-zebras-heal.md
- packages/common-cli-options-help/src/index.ts
- packages/config/src/Config.ts
- packages/config/src/index.ts
- packages/default-reporter/src/index.ts
- packages/default-reporter/src/reporterForClient/index.ts
- packages/default-reporter/src/reporterForClient/reportLifecycleScripts.ts
- packages/default-reporter/test/reportingLifecycleScripts.ts
- packages/plugin-commands-script-runners/src/run.ts
- packages/pnpm/src/cmd/index.ts
- packages/pnpm/src/reporter/index.ts
Add new global option called `--stream`.
When used, the output from child processes is streamed to the console immediately, prefixed with the originating package directory. This allows output from different packages to be interleaved.
close #2147
close #1609
> feat: --stream

- .changeset/rich-rabbits-drum.md
- .changeset/swift-hotels-approve.md
- packages/parse-cli-args/src/index.ts
- packages/plugin-commands-script-runners/src/exec.ts
- packages/plugin-commands-script-runners/src/run.ts
- packages/pnpm/src/cmd/complete.ts
- packages/pnpm/src/cmd/completion.ts
- packages/pnpm/src/cmd/index.ts
The `run` and `exec` commands may use the `--parallel` option.
`--parallel` completely disregards concurrency and topological sorting,
running a given script immediately in all matching packages
with prefixed streaming output. This is the preferred flag
for long-running processes such as watch run over many packages.
For example: `pnpm run --parallel watch`
close #2528
> feat: --parallel

- .changeset/green-olives-visit.md
- packages/default-reporter/src/reporterForClient/reportLifecycleScripts.ts
- packages/default-reporter/test/reportingLifecycleScripts.ts
This is how it looks (inspired by Lerna):
> feat(reporter): color the child output prefixes

- .changeset/polite-lions-sneeze.md
- packages/fetch-from-npm-registry/src/index.ts
- packages/fetch-from-npm-registry/test/index.ts
Don't remove authorization headers when redirecting requests
to the same host.
close #2602
> fix: don't always remove auth headers when redirecting

- .changeset/long-squids-wash.md
- packages/supi/src/install/allProjectsAreUpToDate.ts
- packages/supi/src/install/index.ts
- packages/supi/test/allProjectsAreUpToDate.test.ts
- packages/supi/test/install/multipleImporters.ts
When linked-workspaces = false and the lockfile is up to date, the projects up-to-date check is incorrectly re-running the resolution step.
This happens in workspaces where packages are using both the workspace version of a package, and a registry version of the package.
Fixes #2618
> fix(resolution): respect linked-workspaces = false in up-to-date check

- .changeset/modern-cheetahs-doubt.md
- .changeset/perfect-walls-run.md
- packages/filter-workspace-packages/src/index.ts
- packages/pkgs-graph/src/index.ts
- packages/pkgs-graph/test/index.ts
- packages/plugin-commands-listing/test/recursive.ts
- packages/pnpm/src/main.ts
Pass the linkedWorkspacePackages config to the pkg-graph,
only select packages that are explicitly referred to as workspace:...
when this setting is on.
Fixes #2625
> fix(filtering): Support linked-workspace- packages='false' in workspace filtering

- .changeset/calm-camels-bathe.md
- .changeset/nine-zoos-listen.md
- packages/cafs/package.json
- packages/cafs/src/parseJson.ts
- packages/supi/test/install/misc.ts
- pnpm-lock.yaml
This fixes a regression that appeared in v5.0.0.
close #2629
> fix: don't fail when a manifest starts with BOM

- packages/parse-cli-args/package.json
- packages/parse-cli-args/src/index.ts
- pnpm-lock.yaml
I am the author of didyoumean2, I have introduced function overloading to pick correct return type depends on options.returnType in v4.1.0
> chore: remove type assertions when using didyoumean2

- .changeset/tricky-ads-bake.md
- packages/tarball-fetcher/src/createDownloader.ts
When fetching tarballs, pass the proxy settings to the fetcher.
close #2650
> fix: pass the proxy settings to the fetcher

- .changeset/eight-penguins-hunt.md
- .changeset/orange-clocks-pretend.md
- packages/cli-utils/src/getConfig.ts
- packages/config/src/index.ts
- packages/global-bin-dir/src/index.ts
- packages/global-bin-dir/test/index.ts
- packages/pnpm/src/main.ts
`pnpm root -g` should not fail if the pnpm process has no access
to the global bin directory.
close #2700
> fix: root -g should not fail

- .changeset/cold-feet-arrive.md
- packages/pnpm/test/hooks.ts
- packages/supi/src/install/index.ts
This PR fixes a bug caused by #2693: when removing a dependency in a project with readPackage hook, lockfile is not updated as expected.
I fixed it by modifying both originalManifest and manifest when removing dependency. I just modified originalManifest before, which caused following dependency resolution wrong.
I have added another assertion to make sure this case is tested.
Additionally, the tests I added cause some other tests failling. I think I have found a workaround to get all tests pass. The problem seems becasuse pnpmfile.js added dep-of-pkg-with-1-dep to is-positive dependencies and saved it into pnpm store. So I should specify package in pnpmfile.js so that other packages not modified.
> fix lockfile not updated when remove dependency with readPackage hook

- .changeset/witty-chicken-eat.md
- packages/supi/src/utils/getPref.ts
- packages/supi/test/install/misc.ts
`pnpm add foo@` should install the latest `foo`
close #2737
> fix: installing a new dependency with a trailing @

- .changeset/tidy-dingos-happen.md
- packages/default-reporter/src/reporterForClient/reportMisc.ts
- packages/default-reporter/test/index.ts
Sometimes, when installing new dependencies that rely on many peer dependencies,
or when running installation on a huge monorepo, there will be hundreds or thousands of warnings.
Printing many messages to the terminal is expensive and reduces speed,
so pnpm will only print a few warnings and report the total number of the unprinted warnings.
> perf(reporter): print a warning summary

- .changeset/neat-planets-return.md
- packages/headless/src/index.ts
- packages/hoist/src/index.ts
- packages/plugin-commands-rebuild/src/implementation/index.ts
- packages/supi/src/install/index.ts
- packages/supi/src/link/index.ts
Yarn and npm are not printing any info in such cases,
when several dependencies try to create the same binary.
It is better if pnpm will print an info message, not a warning.
close #2823
> fix: report an info log instead of a warning on binary conflicts

- .changeset/famous-peas-punch.md
- packages/default-reporter/src/reporterForClient/reportScope.ts
- packages/default-reporter/test/reportingScope.ts
> feat(reporter): don't report scope when one project is selected

- .changeset/beige-masks-brush.md
- .changeset/clean-parents-perform.md
- .changeset/friendly-yaks-battle.md
- .changeset/ninety-jars-arrive.md
- .changeset/poor-fireants-complain.md
- .changeset/tidy-islands-look.md
- packages/common-cli-options-help/src/index.ts
- packages/config/src/Config.ts
- packages/config/src/index.ts
- packages/parse-cli-args/package.json
- packages/parse-cli-args/src/index.ts
- packages/parse-cli-args/test/index.ts
- packages/plugin-commands-installation/src/add.ts
- packages/plugin-commands-script-runners/src/run.ts
- packages/plugin-commands-script-runners/test/index.ts
- packages/pnpm/src/cmd/index.ts
- packages/pnpm/src/shorthands.ts
- packages/pnpm/test/recursive/misc.ts
- pnpm-lock.yaml
`--workspace-root`, `-w`: a new option that allows to focus on
the root workspace project.
E.g., the following command runs the `lint` script of the root
`package.json` from anywhere in the monorepo:
```
pnpm -w lint
```
ref #2853
> feat: --workspace-root

- packages/cafs/jest.config.js
- packages/cafs/package.json
- packages/cafs/test/index.ts
A new package for https://github.com/pnpm/pnpm/issues/2858
Here I'm not sure how to migrate it correctly, there is no expect. Any ?
> refactor: migrate carfs to jest

- .changeset/hip-lemons-rescue.md
- packages/common-cli-options-help/src/index.ts
- packages/filter-workspace-packages/src/index.ts
- packages/filter-workspace-packages/src/parsePackageSelector.ts
- packages/filter-workspace-packages/test/index.ts
- packages/filter-workspace-packages/test/parsePackageSelector.ts
Packages may be excluded from a command's scope, using "!" at the
beginning of the selector.
For instance, this will run tests in all projects except foo:
```
pnpm --filter=!foo test
```
And this one will run tests in all projects that are not under the
`lib` directory:
```
pnpm --filter=!./lib test
```
close #2804
> feat: excluding packages using --filter

- .changeset/cold-seals-help.md
- .changeset/lovely-bobcats-invent.md
- packages/lockfile-to-pnp/package.json
- packages/lockfile-to-pnp/src/index.ts
- packages/lockfile-to-pnp/test/index.ts
- pnpm-lock.yaml
I’ve also fixed the tests so that they also work on **Windows** and use the `mapfn` parameter of `Array.from`, to avoid creating an intermediate array.
---
This PR should be merged using **rebase‑only** (no squashing).
> feat(lockfile‑to‑pnp): correct `lockfileToPackageRegistry` return type

- .changeset/plenty-socks-boil.md
- packages/plugin-commands-publishing/src/publish.ts
Very minor - I hit this and initially thought I had to edit an `.npmrc` file or some other kind of global config, which would have been dangerous. The CLI flag is probably a better option most of the time because it has to be passed explicitly.
> Mention CLI flag in git checks hint

- packages/lifecycle/jest.config.js
- packages/lifecycle/package.json
- packages/lifecycle/test/index.ts
- packages/link-bins/jest.config.js
- packages/link-bins/package.json
- packages/link-bins/test/index.ts
- pnpm-lock.yaml
Migrated `lifecycle` and `link-bins` to use Jest for testing.
Please let me know any corrections needed. Thanks!
> Migrate more tests to Jest

- packages/manifest-utils/jest.config.js
- packages/manifest-utils/package.json
- packages/manifest-utils/test/getSpecFromPackageManifest.test.ts
- packages/matcher/jest.config.js
- packages/matcher/package.json
- packages/matcher/test/index.ts
- packages/modules-yaml/jest.config.js
- packages/modules-yaml/package.json
- packages/modules-yaml/test/index.ts
- packages/npm-registry-agent/jest.config.js
- packages/npm-registry-agent/package.json
- packages/npm-registry-agent/test/index.ts
- pnpm-lock.yaml
Migrated some additional packages to Jest for testing
* `manifest-utils`
* `matcher`
* `modules-yaml`
* `npm-registry-agent`
Replaced `proxyquire` in `npm-registry-agent` with Jest's mocking.
> Four packages to Jest

- .github/ISSUE_TEMPLATE.md
It was officially renamed a few years ago.
> fix: change "OS X" to "macOS"

- .changeset/moody-moose-fix.md
- packages/headless/src/index.ts
- packages/supi/test/install/hoist.ts
Fixed a performance regression that was caused by #3032
and shipped in pnpm v5.13.7
The performance of repeat `pnpm install` execution
was in some cases significantly slower.
> perf: fix a perf regression shipped in v5.13.7

- .changeset/blue-snakes-rhyme.md
- .changeset/polite-dragons-press.md
- .changeset/proud-pigs-judge.md
- .changeset/small-rockets-love.md
- packages/filter-lockfile/src/filterLockfile.ts
- packages/filter-lockfile/src/filterLockfileByImporters.ts
- packages/filter-lockfile/src/filterLockfileByImportersAndEngine.ts
- packages/lockfile-file/src/write.ts
- packages/supi/src/install/allProjectsAreUpToDate.ts
- packages/supi/src/install/index.ts
- packages/supi/test/install/overrides.ts
Never skip resolution if the overrides were changed,
even if frozenLockfile is true.
> fix: never skip resolution if the overrides were changed

- package.json
- packages/lockfile-utils/package.json
- packages/resolve-dependencies/package.json
- packages/supi/test/lockfile.ts
- pnpm-lock.yaml
close #2928
Actual fix in dependency: https://github.com/pnpm/get-npm-tarball-url/commit/d45342e799541aca06398dafa6df985b50f49216
> fix: lockfile flickering caused by build metadata

- .changeset/early-foxes-behave.md
- .changeset/fresh-eels-collect.md
- .changeset/heavy-balloons-change.md
- .changeset/polite-trees-invent.md
- .changeset/small-coins-beam.md
- .changeset/smooth-dolphins-think.md
- .changeset/wet-lobsters-kiss.md
- packages/config/src/Config.ts
- packages/config/src/index.ts
- packages/headless/src/index.ts
- packages/modules-cleaner/package.json
- packages/modules-cleaner/src/prune.ts
- packages/modules-yaml/src/index.ts
- packages/modules-yaml/test/index.ts
- packages/plugin-commands-rebuild/src/implementation/index.ts
- packages/plugin-commands-store/test/storePrune.ts
- packages/supi/src/install/extendInstallOptions.ts
- packages/supi/src/install/index.ts
- packages/supi/src/install/link.ts
- packages/supi/test/install/modulesCache.ts
- packages/supi/test/install/multipleImporters.ts
- packages/supi/test/install/peerDependencies.ts
- pnpm-lock.yaml
New option added: `modules-cache-max-age`. By default, the cache in node_modules is cleared once a week.
ref #3115
> perf: don't prune the modules directory on each install

- .changeset/eighty-geese-fly.md
- .changeset/strange-llamas-refuse.md
- packages/cli-utils/src/getConfig.ts
- packages/config/src/index.ts
- packages/config/test/index.ts
- packages/pnpm/src/main.ts
close https://github.com/pnpm/pnpm/issues/3111
> fix: only display unknown settings warning for install command

- .changeset/gentle-geese-camp.md
- packages/plugin-commands-audit/src/audit.ts
- packages/plugin-commands-audit/test/index.ts
Running `pnpm audit` and finding no vulnerabilities results in a `No known vulnerabilities found` message. It doesn't end with a line break character, so the prompt message is being printed on the same line.
> End with \n when `pnpm audit` finds nothing

- .changeset/big-bears-listen.md
- packages/link-bins/src/index.ts
- packages/link-bins/test/fixtures/pnpm-cli/node_modules/pnpm/index.js
- packages/link-bins/test/fixtures/pnpm-cli/node_modules/pnpm/package.json
- packages/link-bins/test/index.ts
close #3053
close #3155
close #2937
> fix: don't create a PowerShell cmd shims for pnpm CLI

- packages/pnpmfile/requireOrImport.js
- packages/pnpmfile/src/requirePnpmfile.ts
+ We ESM export `requireOrImportPnpmfile` instead of CJS module.export.
+ Import gets a URL as argument.
+ Works with both default and named export.
+ ESM File Loader is only invoked when error is ERR_REQUIRE_ESM.
> [fix] import of ESM pnpmFile

- .changeset/good-terms-grow.md
- packages/plugin-commands-publishing/package.json
- packages/plugin-commands-publishing/src/publish.ts
- packages/plugin-commands-publishing/src/recursivePublish.ts
- packages/plugin-commands-publishing/test/recursivePublish.ts
- pnpm-lock.yaml
`pnpm publish -r --force` publishes packages even if their current
version is already in the registry.
close #3154
> feat: pnpm publish -r --force

- .changeset/unlucky-sheep-play.md
- packages/tarball-resolver/src/index.ts
- packages/tarball-resolver/test/index.ts
> fix: escape a colon in tarball dependency ID

- .changeset/rich-insects-promise.md
- packages/plugin-commands-installation/src/update/index.ts
When packages are updated on all levels, there are fewer duplicates, so it makes sense to use a deep update as the default behavior.
> feat: the default depth of an update is Infinity

- .changeset/cool-insects-retire.md
- packages/npm-registry-agent/src/index.ts
- packages/npm-registry-agent/test/index.ts
When the registry uses the https protocol and the proxy uses socks,
its URL is changed from "socks://" to "https://socks://" in
getProxyUri(), which will not work. Fix it to work with a socks proxy.
close #3241
> fix: use of socks proxy

- .changeset/nasty-lizards-dance.md
- packages/headless/src/index.ts
This make value of PATH environment alwasy contains node_modules/.bin of
workspace root, despite whether lockfile is up to date or not.
Fixes #2086
> fix(headless): forward extraBinPaths to runLifecycleHookConcurrently

- .changeset/soft-dancers-happen.md
- packages/build-modules/src/index.ts
This PR fixes a bug I discovered recently that causes some dependencies to be skipped to build.
Minimal reproducible:
```json
{
"name":"example",
"@mikro-orm/core":"^4.5.2",
"@mikro-orm/knex":"^4.5.2"
},  
"devDependencies": {
"@mikro-orm/sqlite":"^4.5.2"
}   
}
```
Where `@mikro-orm/sqlite` depends on `sqlite3` which has an install script and `pnpm install` will build it normally as expected. However `sqlite3` will be skipped to build by the following steps:
```bash
pnpm install --prod
```
And then
```bash
pnpm install # sqlite3 will not be built in this step
```
> fix(build-modules): fix incorrect return in getSubgraphToBuild

- .changeset/giant-carrots-heal.md
- packages/exportable-manifest/src/index.ts
- packages/npm-resolver/src/index.ts
- packages/npm-resolver/test/index.ts
- packages/plugin-commands-publishing/test/publish.ts
- packages/resolve-workspace-range/src/index.ts
This is an attempt to support for workspace:^ and workspace:~ aliases.
> feat: workspace:^ and workspace:~ aliases (#3116)

- .changeset/cold-papayas-notice.md
- .changeset/cuddly-hats-remember.md
- packages/common-cli-options-help/src/index.ts
- packages/config/src/Config.ts
- packages/config/src/index.ts
- packages/config/test/index.ts
- packages/filter-workspace-packages/src/index.ts
- packages/filter-workspace-packages/src/parsePackageSelector.ts
- packages/lockfile-types/package.json
- packages/parse-cli-args/src/index.ts
- packages/parse-cli-args/test/index.ts
- packages/pkgs-graph/src/index.ts
- packages/pkgs-graph/test/index.ts
- packages/pnpm/src/cmd/index.ts
- packages/pnpm/src/main.ts
Add the new filter-prod option that executes the same as the filter option except
it does not include devDependencies when building the package graph.
> feat: add new filter-prod option

- .changeset/two-socks-bathe.md
- packages/pkgs-graph/src/index.ts
- packages/pkgs-graph/test/index.ts
Fixes the graph to include dependencies with `workspace:^` and `workspace:~` specifications.
> fix(pkgs-graph): include workspace version aliases (#3400)

- .changeset/fluffy-goats-double.md
- packages/supi/src/install/index.ts
> fix: setting child concurrency during headless install

- .changeset/little-dragons-wave.md
- packages/error/src/index.ts
- packages/npm-resolver/src/fetch.ts
- packages/npm-resolver/test/index.ts
When fetch command fails for any reason catch it and return FetchError to avoid Unhandled rejection
ref #3261
> fix(npm-resolver): unhandled rejection in fetch

- .changeset/smooth-bags-shave.md
- packages/supi/src/install/allProjectsAreUpToDate.ts
- packages/supi/test/allProjectsAreUpToDate.test.ts
Prefer headless install, when the lockfile is up-to-date
and some packages are linked using relative path via `workspace:<path>`.
> fix: prefer headless install when lockfile is up-to-date

- .changeset/strange-camels-kiss.md
- packages/list/src/renderJson.ts
- packages/list/test/index.ts
when running pnpm list  with --json flag for each workspace print the path in the json output
closes #3418
> feat(list): add workspace to list command when setting output to json

- .changeset/light-dolls-reply.md
- .changeset/rotten-balloons-double.md
- .changeset/violet-drinks-develop.md
- packages/config/src/Config.ts
- packages/config/src/index.ts
- packages/plugin-commands-nvm/README.md
- packages/plugin-commands-nvm/jest.config.js
- packages/plugin-commands-nvm/package.json
- packages/plugin-commands-nvm/src/index.ts
- packages/plugin-commands-nvm/src/node.ts
- packages/plugin-commands-nvm/test/node.test.ts
- packages/plugin-commands-nvm/tsconfig.json
- packages/plugin-commands-nvm/tsconfig.lint.json
- packages/pnpm/.gitignore
- packages/pnpm/package.json
- packages/pnpm/src/cmd/index.ts
- packages/pnpm/src/main.ts
- packages/pnpm/test/cli.ts
- packages/pnpm/tsconfig.json
- pnpm-lock.yaml
- utils/updater/src/index.ts
TODO:
***
`pnpm node [args...]` will autoinstall Node.js and run it.
If a project has `use-node-version` set in `.npmrc`, pnpm will auto-install the specified Node.js version and scripts will run using that version of Node.js
related discussion: https://github.com/pnpm/pnpm/discussions/3434
> feat: new plugin for managing Node.js versions

- .changeset/six-files-drive.md
- packages/find-workspace-dir/jest.config.js
- packages/find-workspace-dir/package.json
- packages/find-workspace-dir/src/index.ts
- packages/find-workspace-dir/test/index.ts
PNPM has support for passing in the lockfile dir override via `NPM_CONFIG_LOCKFILE_DIR`, however the workspace dir is only calculated by traversing up the folder structure from the working dir in search of a `pnpm-workspace.yaml` file. This change lets `NPM_CONFIG_WORKSPACE_DIR` work in a similar manner by overriding (and avoiding the traversal if possible).
> feat(find-workspace-dir): add env var support for setting the workspace dir

- .changeset/chatty-dolphins-destroy.md
- packages/plugin-commands-publishing/src/publish.ts
- packages/plugin-commands-publishing/src/recursivePublish.ts
- packages/plugin-commands-publishing/test/__snapshots__/recursivePublish.ts.snap
- packages/plugin-commands-publishing/test/recursivePublish.ts
`pnpm publish -r --report-summary` will save the summary of published packages to `pnpm-publish-summary.json`. Useful when some other tooling is used to report the list of published packages.
> feat(publish): --report-summary

- .changeset/pretty-moose-speak.md
- packages/plugin-commands-publishing/src/publish.ts
- packages/plugin-commands-publishing/test/publish.ts
- packages/run-npm/src/index.ts
- packages/types/src/package.ts
Adding support for "publishConfig.directory" field, feature present in changesets https://github.com/atlassian/changesets/pull/428, and lerna: https://github.com/lerna/lerna/tree/main/commands/publish#publishconfigdirectory
> feat(publish): support "publishConfig.directory" field

- .changeset/breezy-waves-camp.md
- packages/dependency-path/src/index.ts
- packages/dependency-path/test/index.ts
> fix: don't break the lockfile if it has peer deps with underscores

- .changeset/kind-beds-kneel.md
- .changeset/seven-donuts-yawn.md
- packages/plugin-commands-installation/src/installDeps.ts
- packages/plugin-commands-installation/test/warnCyclicDependencies.ts
- packages/sort-packages/src/index.ts
- typings/local.d.ts
In this PR I make pnpm print a warning if there are cyclic dependencies. But in future releases I think that we should consider throwing an error instead.
> fix: check safe graph sequencer result (#2162)

- .changeset/empty-pugs-kick.md
- packages/plugin-commands-store/src/store.ts
- packages/plugin-commands-store/test/storePath.ts
Add a `pnpm store path` command to print the location of the pnpm store
as the CLI would resolve it. This allows the user to inspect the current
store location, as well as allows external tooling (like shell scripts)
to locate the pnpm store without needing to make assumptions about its
location or needing to load the `@pnpm/store-path` module.
This command differs from running `pnpm get store`, as `pnpm get store`
prints "undefined" in the case that no custom store path has been set,
which requires external tooling to have knowledge about where pnpm
locates its store in the default case.
---
Please let me know if you would like anything changed or improved. The test I added simply tests that `pnpm store path` doesn't throw an error, but if you have any pointers on how to test the logger …
> feat(plugin-commands-store): add `store path` command

- .changeset/six-weeks-perform.md
- packages/supi/src/install/index.ts
- packages/supi/test/install/overrides.ts
> fix(supi): never do full resolution when package manifest is ignored

- .changeset/shy-days-whisper.md
- packages/pnpm/src/main.ts
- packages/pnpm/test/bin.ts
I found some missing newlines at the end of the output of `pnpm audit` and `pnpm list`.
When looking at `plugin-command-listing` I found that adding newlines there might be cumbersome, so I added it just before writing to stdout.
I also added some types, because the template literal I added complained about `any`.
> fix: ensure command output ends with newline

- .changeset/brown-cheetahs-protect.md
- packages/supi/src/install/getPreferredVersions.test.ts
- packages/supi/src/install/getPreferredVersions.ts
- packages/supi/src/install/index.ts
- packages/supi/src/parseWantedDependencies.ts
- packages/supi/test/install/multipleImporters.ts
When `pnpm add pkg` is executed in a workspace and `pkg` is already in the dependencies of one of the workspace projects, pnpm uses that already present version range to add the new dependency.
> feat: better deduping of direct dependencies in workspace projects

- .changeset/neat-needles-retire.md
- .changeset/sharp-buttons-sell.md
- packages/plugin-commands-publishing/fixtures/has-bin/package.json
- packages/plugin-commands-publishing/src/pack.ts
- packages/plugin-commands-publishing/test/pack.ts
- packages/pnpm/package.json
- packages/types/src/package.ts
By default, for portability reasons, no files except those listed in the bin field will be marked as executable in the resulting package archive. The executableFiles field lets you declare additional fields that must have the executable flag (+x) set even if they aren't directly accessible through the bin field.
```json
"publishConfig": {
"executableFiles": [
"./dist/shim.js",
]
}
```
> feat: publishConfig.executableFiles

- .changeset/chilly-ligers-thank.md
- .changeset/twenty-trains-pay.md
- packages/pnpm/src/main.ts
- packages/pnpm/test/monorepo/index.ts
> feat: exclude the root from recursive exec|run|add

- .changeset/heavy-rice-sneeze.md
- packages/plugin-commands-script-runners/src/run.ts
Fixes https://github.com/pnpm/pnpm/issues/3656
> fix: add "run" to NO_SCRIPT error example

- .github/workflows/release.yml
Fixes #3702
There is a warning on release workflow.
Installing ldid would fix the not working on M1 Mac problem by codesigning.
https://github.com/pnpm/pnpm/runs/3403887763
```
> Warning Unable to sign the macOS executable
Due to the mandatory code signing requirement, before the
executable is distributed to end users, it must be signed.
Otherwise, it will be immediately killed by kernel on launch.
An ad-hoc signature is sufficient.
To do that, run pkg on a Mac, or transfer the executable to a Mac
and run "codesign --sign - <executable>", or (if you use Linux)
install "ldid" utility to PATH and then run pkg again
```
> chore(release): update release.yml

- .changeset/seven-birds-flash.md
- packages/plugin-commands-script-runners/src/dlx.ts
- packages/plugin-commands-script-runners/test/dlx.ts
Allow use of mutiple ```--package``` parameters with ```pnpm dlx``` command. For use with CLI tools which may require some additional optional packages
> feat: allow installing mutiple packages using dlx command

- .github/workflows/ci.yml
Please add macOS runs to required status checks if you want.
> chore: add macos-latest to ci

- .changeset/poor-lobsters-turn.md
- packages/plugin-commands-setup/src/setup.ts
The executable installed by the package manager (e.g. Homebrew) should
not be removed after the setup command is run.
The installation script should remove that and install.sh do so.
> chore(setup): do not remove executable in setup

- .changeset/thirty-stringrays-type.md
- packages/config/src/index.ts
Currently I can't customize `cache-dir` / `state-dir` path from `.npmrc` file.
> fix: respect cache-dir/state-dir from config files

- .changeset/fifty-snakes-refuse.md
- packages/supi/src/install/index.ts
- packages/supi/test/install/fixLockfile.ts
Currently all fields in the lockfile entries will be regenerated when fixing the lockfile, including the dependencies field. This behavior  will lead to lose locked dependencies version of an existing lockfile entry, which is not work as intended.
Currently preferedVersion are used to lock the existing version and works well in most case, but in some edge cases, the lockfile structure may change due to the lose of locked dependency version info
> fix(supi): --fix-lockfile should preserve dependencies in the existing lockfile

- packages/supi/test/install/createVersionOverrider.test.ts
The #3682 was accidentally fixed by https://github.com/pnpm/pnpm/pull/3743
but the cases from #3682 are not covered with tests.
This PR adds missing coverage.
> test: add extra coverage for createVersionsOverrider

- .changeset/tiny-buttons-call.md
- .changeset/unlucky-eggs-whisper.md
- packages/headless/src/index.ts
- packages/hoist/src/index.ts
- packages/supi/src/install/link.ts
- packages/supi/test/install/hoist.ts
close #3808 
When partial install in monorepo, the hoist packages under .pnpm/node_modules may be wrong as we use the whole importIds in the lockfile to collect deps instead of the selected projects.
This causes problems, for example, project-A depends on is-positive@2.0.0 and project-B depends on is-positive@3.0.0, and is-positive@2.0.0 presents first in the lockfile, then is-positive@2.0.0 will be picked wrongly to hoist when we partial install project-B. we expect to hoist is-positive@3.0.0 but is-positive@2.0.0 is picked.
and  the packages which is not in the filtered lockfile graph will be ignored here: https://github.com/pnpm/pnpm/blob/b14c9a0f1e8082a72672f0892c631d51e6430675/packages/hoist/src/index.ts#L194-L202, the filter lockfile graph doesn't includes is-positive@2.0.0 …
> fix: only hoist packages in the dependencies tree when partial install

- .changeset/stale-mayflies-hear.md
- packages/cli-utils/src/packageIsInstallable.ts
- packages/cli-utils/src/readProjectManifest.ts
- packages/find-workspace-packages/src/index.ts
- packages/package-is-installable/package.json
- packages/package-is-installable/src/getSystemNodeVersion.ts
- packages/package-is-installable/src/index.ts
- packages/package-is-installable/test/getSystemNodeVersion.test.ts
- packages/pnpm/src/main.ts
- pnpm-lock.yaml
> fix: use the system default Node.js to check package compatibility

- .changeset/rich-horses-know.md
- packages/plugin-commands-script-runners/src/dlx.ts
- packages/plugin-commands-script-runners/test/dlx.ts
Closes #4023 
Now you can run commands like `pnpm dlx some-package@1.0.0` and `pnpm create svelte@next` without getting errors due to version specifiers present in the package.
> feat(dlx): handle version specifiers in command names

- .changeset/forty-yaks-cheat.md
- .changeset/silent-kangaroos-whisper.md
- packages/config/package.json
- packages/config/src/getScopeRegistries.ts
- packages/config/src/index.ts
- packages/config/test/index.ts
- packages/config/test/scoped-registries.ini
- packages/lockfile-utils/package.json
- packages/normalize-registries/package.json
- packages/resolve-dependencies/package.json
- pnpm-lock.yaml
> fix: don't add trailing slash to registry URLs

- .changeset/eleven-clouds-scream.md
- .changeset/nice-dolphins-kiss.md
- .changeset/spotty-bees-float.md
- packages/git-fetcher/src/index.ts
- packages/prepare-package/package.json
- packages/prepare-package/src/index.ts
- packages/prepare-package/tsconfig.json
- packages/tarball-fetcher/package.json
- packages/tarball-fetcher/src/createDownloader.ts
- pnpm-lock.yaml
> fix: print better error on git-hosted pkg install failure

- .changeset/quiet-bears-hang.md
- packages/lockfile-utils/src/pkgSnapshotToResolution.ts
- packages/lockfile-utils/test/pkgSnapshotToResolution.ts
- packages/resolve-dependencies/src/updateLockfile.ts
- packages/resolve-dependencies/test/relativeTarball.test.ts
> fix: calculating tarball location when registry has no trailing slash

- .changeset/sixty-houses-clap.md
- packages/npm-resolver/src/fetch.ts
- packages/npm-resolver/test/index.ts
> fix(npm-resolver): always add trailing slash to registry URL

- .github/workflows/ci.yml
As the `actions/setup-node@v2`'s new feature, it now support cache the pnpm install: https://github.com/actions/setup-node/blob/main/docs/advanced-usage.md#caching-packages-dependencies
> ci: add pnpm cache

- .changeset/red-lamps-camp.md
- packages/git-resolver/src/parsePref.ts
Recent retry feature exposed this bug. The hosted.git() only works with GitHub repos, bitbucket/gitlab has no gitTemplate defined in hosted-git-info.
-----
Before this fix, a `pnpm i` gave me:
```
⋊> ~/b/bcx-broker-au-frontend on new-ui ↑ pnpm i
 WARN  HEAD https://bitbucket.org/buttonwoodcx/bcx-ui error (undefined). Will retry in 10 milliseconds. 5 retries left.
 WARN  HEAD https://bitbucket.org/buttonwoodcx/bcx-ui error (undefined). Will retry in 60 milliseconds. 4 retries left.
 WARN  HEAD https://bitbucket.org/buttonwoodcx/bcx-ui error (undefined). Will retry in 360 milliseconds. 3 retries left.
 WARN  HEAD https://bitbucket.org/buttonwoodcx/bcx-ui error (undefined). Will retry in 2.1 seconds. 2 retries left.
 WARN  HEAD https://bitbucket.org/buttonwoodcx/bcx-ui error (undefined). …
```
> fix(git-resolver): avoid retries on bitbucket/gitlab private repos

- .changeset/hip-gorillas-happen.md
- packages/common-cli-options-help/src/index.ts
- packages/config/src/Config.ts
- packages/config/src/index.ts
- packages/default-reporter/src/index.ts
- packages/default-reporter/src/reporterForClient/index.ts
- packages/default-reporter/src/reporterForClient/reportLifecycleScripts.ts
- packages/default-reporter/test/reportingLifecycleScripts.ts
- packages/pnpm/src/cmd/index.ts
- packages/pnpm/src/reporter/index.ts
Implements proposal [#4070](https://github.com/pnpm/pnpm/discussions/4070)
Implementation details:
- enabled only for lifecycle logs and only when `--reporter=append-only`
- `--aggregate-output` is optional, and is disabled by default
- `.npmrc / cli` option supported
p.s. today is my first day of using Rxjs, I'm more than open to suggestions what to improve/change
> feat: aggregate-output

- package.json
- pnpm-lock.yaml
I've noticed this downgrade https://github.com/pnpm/pnpm/commit/0726f3b913185803250c1d36d4841422e292a3f6 with a good reason, I've patched the stable version, let's try this again.
The issue was some core dependencies had `core-js` babel/env config enabled that was injecting some `requires(..` into the transpiled code and since pnpm is strict, failed.
> chore: upgrade verdaccio 5.3.1

- .changeset/flat-dogs-admire.md
- packages/exportable-manifest/src/index.ts
- packages/exportable-manifest/test/index.test.ts
- packages/plugin-commands-publishing/src/pack.ts
- packages/types/src/package.ts
fix(plugin-commands-publishing): add readme file to published package.json
add readme file to published package.json to prevent missing in the verdaccio registry
https://github.com/pnpm/pnpm/issues/4091
> fix(plugin-commands-publishing): add readme file to published package.json

- .changeset/spotty-singers-behave.md
- packages/resolve-dependencies/src/mergePeers.ts
> fix: don't crash when peer ranges cannot be merged

- .changeset/khaki-cars-return.md
- packages/plugin-commands-env/src/node.ts
- packages/plugin-commands-env/test/env.test.ts
- packages/plugin-commands-env/test/fixtures/node-16.4.0-release-info.json
Fixes https://github.com/pnpm/pnpm/issues/4104. Opening as a draft until CI checks pass.
The suggested fix was to make `<pnpm-home-dir>/nodejs/X.X.X` dir creation more atomic by using [`path-temp`](https://www.npmjs.com/package/path-temp): https://github.com/pnpm/pnpm/issues/4104#issuecomment-990246287
It looks like this is already the case in all the code paths I looked at. Because of this, I believe we can just remove the premature `mkdir` that runs before the node archive gets downloaded. (Line 70.)
https://github.com/pnpm/pnpm/blob/89dcc1115abda5a3cb2f9b9f960e34007171c19d/packages/plugin-commands-env/src/node.ts#L69-L70
This premature `mkdir` was causing pnpm to think Node.js was already installed on reruns.
https://github.com/pnpm/pnpm/blob/89dcc1115abda5a3cb2f9b9f960e34007171c19d/pac …
> fix: use-node-version isn't respected if the first download fails

- .changeset/odd-garlics-crash.md
- packages/link-bins/src/index.ts
- packages/link-bins/test/fixtures/bin-not-exist/node_modules/foo/package.json
- packages/link-bins/test/index.ts
Attempt to fix #3763 
- Basically moves the codes that may throw `ENOENT` into `try-catch`.
- Added test too. Without this patch, the test will fail to run because an `ENOENT` error will be thrown from `getBinNodePaths`
Let me know if there's a better approach. Thanks
> fix(link-bins): don't throw error during install when bin points to path that doesn't exist

- .changeset/lemon-clocks-brake.md
- packages/config/src/Config.ts
- packages/config/src/index.ts
- packages/core/src/install/extendInstallOptions.ts
- packages/core/src/install/index.ts
- packages/core/test/hoistedNodeLinker/install.ts
- packages/core/test/install/nodeLinkerHoistedNodeModules.ts
- packages/headless/src/index.ts
- packages/headless/test/index.ts
ref #4073
In their [RFC](https://github.com/npm/rfcs/blob/main/accepted/0042-isolated-mode.md#naming), npm decided to use this terminology: 
> This mode is called isolated-mode because it makes the boundaries between packages and workspaces stronger, making them more isolated.
>
> To make the discussions more efficient, we could also name the current default installation mode of npm. We will call this mode hoisted-mode as packages are shared across workspaces by hoisting them to the root of the project. This term is already known by developers familiar with yarn or pnpm.
In Yarn, the node linker setting may have these values: pnp, node-modules, and pnpm.
Probably it is better to use isolated/hoisted instead of pnpm/node-modules because pnpm also creates a node-modules folder.
So I suggest …
> refactor: rename the values of the node-linker setting

- .changeset/itchy-mugs-occur.md
- packages/pnpm/src/main.ts
- packages/pnpm/test/install/lifecycleScripts.ts
Based on https://github.com/pnpm/pnpm/discussions/4153 I'd like to see if it's possible to provide option to not set npm_config_argv in process.env
~~This PR adds that option by setting in `.npmrc`:~~
```
set-npm-config-argv-as-environment-variable=false
```
~~(naming is hard, if there's better name, please do suggest 😆)~~
As suggested, used "`useBetaCli`". If flag is true, then don't set npm_config_argv in process.env
----
I also moved down this block
```
process.env['npm_config_argv'] = JSON.stringify(argv)
```
because at the original location, it haven't parsed configs from `.npmrc` yet
-----
Please let me know if there's any concern. Thanks
---
~~Edit: oh wow the test are failing, but I couldn't figure out how lifecycle events are run before config are read ? 😅😅😅😅~~
> feat: add option to not set npm_config_argv in process.env

- .changeset/famous-toys-provide.md
- .changeset/itchy-berries-wink.md
- .changeset/plenty-mayflies-hug.md
- packages/core/src/install/createPeerDependencyPatcher.ts
- packages/core/src/install/extendInstallOptions.ts
- packages/core/src/install/index.ts
- packages/core/test/install/createPeerDependencyPatcher.test.ts
- packages/plugin-commands-installation/src/getOptionsFromRootManifest.ts
- packages/types/src/package.ts
close #4183
example
```json
{
"pnpm": {
"peerDependencyRules": {
"ignoreMissing": ["babel-loader"],
"allowedVersions": {
"@angular/common": "13"
}
}
}
}
```
> feat: support peerDependencyRules for muting peer dep issues

- .changeset/eleven-sheep-wash.md
- packages/default-reporter/src/reporterForClient/reportDeprecations.ts
close #4227
This might cause a lot of additional warnings on big projects but both npm and Yarn print these warnings.
> fix: print warnings about deprecated subdependencies

- .changeset/forty-pens-stare.md
- packages/config/src/Config.ts
- packages/config/src/index.ts
- packages/pnpm/src/main.ts
The configuration option `update-notifier` allows users to disable the update verification. This is interesting when pnpm is installed from another package manager because the given instructions will not be accurate. The[ `update-notifier` option exists in NPM](https://docs.npmjs.com/cli/v8/using-npm/config#update-notifier) so it can also ease the migration to pnpm.
Closes #4158.
> feat: add support of the update-notifier configuration option

- .changeset/odd-kangaroos-care.md
- packages/parse-cli-args/src/index.ts
- packages/parse-cli-args/test/index.ts
- packages/plugin-commands-script-runners/src/run.ts
- packages/pnpm/test/run.ts
Fixes https://github.com/pnpm/pnpm/issues/3778.
There's a lot of scenarios mentioned in the original issue that make all solutions ambiguous/non-ideal. While still not perfect, I think the behavior below will cause the least amount of confusion:
- Anything after the `<command>` portion of `pnpm run <command>` is passed directly to `<command>` itself.
- Any command line flags before the `<command>` portion is treated as an option to `pnpm run`.
- For backwards compatibility, the first occurrence of `--` anywhere after `<command>` is swallowed.
For example:
- This allows `pnpm run --help` to still show the help text for `pnpm run`.
- While `pnpm run changeset --help` will show the help text of whatever command drives the `changeset` script.
- See https://github.com/pnpm/pnpm/pull/3492 for a …
> feat: run scripts without --

- .changeset/odd-kangaroos-care.md
- packages/plugin-commands-script-runners/src/run.ts
- packages/pnpm/test/run.ts
This is a followup to the discussion here: https://github.com/pnpm/pnpm/pull/4290#discussion_r795245493
Updating `pnpm run <script>` to not handle `--` in a backwards compatible manner since it's confusing.
Before this change:
```
❯ pnpm run --silent echo a -- b
a b
```
After this change:
```
❯ pnpm run --silent echo a -- b
a -- b
```
Opening as a draft PR until tests pass. I'll mark it "*Ready for review*" once this can be looked at.
> fix: revert backwards compatible handling of -- for run

- .changeset/odd-donuts-argue.md
- packages/exportable-manifest/src/index.ts
- packages/plugin-commands-publishing/test/pack.ts
- packages/plugin-commands-publishing/test/publish.ts
Close: https://github.com/pnpm/pnpm/issues/4311
> refactor(publish): remove meaningless key in publishConfig

- .changeset/slow-shrimps-laugh.md
- packages/plugin-commands-script-runners/src/exec.ts
- packages/plugin-commands-script-runners/test/exec.e2e.ts
Fixed: https://github.com/pnpm/pnpm/issues/4320
Once this PR has been merged, the following commands will be supported:
```shell
pnpm --recursive --shell-mode exec -- echo \"\$PNPM_PACKAGE_NAME\"
```
```json
{
"scripts": {
"check": " pnpm --recursive --shell-mode exec -- echo \"\\$PNPM_PACKAGE_NAME\""
}
}
```
> feat(exec): support shell interpreter

- .changeset/little-keys-fix.md
- packages/pnpm/src/main.ts
- packages/pnpm/test/run.ts
Fixes #4094. I think this is safe to do now that #4290 has merged, but could use help verifying.
Before:
```
❯ pnpm --unknown echo --test
> @ echo /Users/gluxon/Developer/pnpm
> echo "--test"
--test
```
After:
```
❯ pnpm --unknown echo --test
 ERROR   ERROR  Unknown option: 'unknown'
For help, run: pnpm help run
```
---
Note that explicitly typing `run` always showed an error before and after this change.
```
❯ pnpm run --unknown echo --test
 ERROR   ERROR  Unknown option: 'unknown'
For help, run: pnpm help run
```
```
❯ pnpm --unknown run echo --test
 ERROR   ERROR  Unknown option: 'unknown'
For help, run: pnpm help run
```
> fix: make unrecognized CLI flags show error when using fallback command

- .changeset/wicked-sheep-tell.md
- packages/core/src/install/index.ts
- packages/core/src/parseWantedDependencies.ts
- packages/core/test/install/overrides.ts
> feat: use the versions from overrides when adding deps without specs

- packages/pnpm/src/cmd/index.ts
Hi! I want to create the `init` command for `pnpm` and I figured I'd start here. Could you please check if I understand the interface of command packages correctly?
Also, I had to use `--no-verify` to push the branch as there were many linter errors, mostly regarding values of type `any` in template literals. Is it normal? Should I make a PR to fix those? Is it even viable to fix those?
> chore: document the interface of command packages

- packages/core/test/install/overrides.ts
Ref #4355
Added a missing test for:
> However, if a version is explicitly specifying, then the specified version will be used and the override will be ignored. So pnpm add foo@0 will install v0 and it doesn't matter what is in the overrides.
There is 1 failing tests but it doesn't seem to be related ("fail on non-compatible pnpm-lock.yaml")
> test: ignore override if a version is specified at install

- .changeset/brave-ties-begin.md
- packages/package-requester/src/packageRequester.ts
- packages/package-requester/test/index.ts
> fix: ignore case, when verifying package name in the store

- .changeset/silent-eagles-rest.md
- packages/core/test/install/lifecycleScripts.ts
- packages/lifecycle/package.json
- packages/pnpm/test/install/lifecycleScripts.ts
- pnpm-lock.yaml
> feat: run scripts without --unsafe-perm

- .changeset/itchy-pigs-deny.md
- packages/plugin-commands-installation/package.json
- packages/plugin-commands-installation/src/recursive.ts
- packages/plugin-commands-installation/test/miscRecursive.ts
- pnpm-lock.yaml
This is reproducible on Windows with virtual drives created by subst command
**Background:**
You are on windows, and you have drive C:.
You have created virtual drive X: using https://docs.microsoft.com/en-us/windows-server/administration/windows-commands/subst somewhere on C:
You cloned a pnpm-managed monorepo with a common lockfile to drive X: and did 'pnpm i'
**Expected:**
X:\pnpm>pnpm i
Scope: all 119 workspace projects
 WARN  There are cyclic workspace dependencies: X:\pnpm\packages\client, X:\pnpm\packages\git-fetcher, X:\pnpm\packages\package-store; X:\pnpm\packages\client, X:\pnpm\packages\git-fetcher, X:\pnpm\packages\package-store, X:\pnpm\packages\client, X:\pnpm\packages\tarball-fetcher, X:\pnpm\packages\package-store; X:\pnpm\packages\client, X:\pnpm\packages\git-fetcher, …
> fix: pnpm i should work on virtual drives

- .changeset/rude-rats-smell.md
- packages/config/src/index.ts
> fix: types should not be hoisted to the root of node_modules

- packages/lockfile-file/src/read.ts
part of #4494
* remove duplicate code
* clarify argument `prefix` of `function _read`
> lint: remove duplicate code

- .eslintrc.json
add `root: true` in project root eslint config file
reason: https://github.com/standard/eslint-config-standard-with-typescript/issues/787#issuecomment-1085558497
https://eslint.org/docs/user-guide/configuring/configuration-files#cascading-and-hierarchy
> fix: set root

- .changeset/chilled-humans-hide.md
- .changeset/funny-baboons-prove.md
- .changeset/giant-years-flow.md
- .changeset/tame-frogs-watch.md
- packages/build-modules/src/index.ts
- packages/config/src/index.ts
- packages/core/src/getPeerDependencyIssues.ts
- packages/core/src/install/extendInstallOptions.ts
- packages/core/src/install/index.ts
- packages/core/src/install/link.ts
- packages/core/src/link/index.ts
- packages/core/src/link/options.ts
- packages/get-context/src/index.ts
- packages/headless/src/index.ts
- packages/hoist/src/index.ts
- packages/link-bins/package.json
- packages/link-bins/src/index.ts
- packages/plugin-commands-env/package.json
- packages/plugin-commands-rebuild/src/implementation/extendRebuildOptions.ts
- packages/plugin-commands-rebuild/src/implementation/index.ts
- packages/plugin-commands-store/src/storeStatus/extendStoreStatusOptions.ts
- pnpm-lock.yaml
Deprecating `extend-node-path` in pnpm v7 has caused issues with "next dev".
This change is bringing back extending `NODE_PATH` in bin command shims. However, only when `node-linker` is set to `isolated` and packages are hoisted to `node_modules/.pnpm/node_modules`. Only `node_modules/.pnpm/node_modules` is added to `NODE_PATH`, so it should not cause too long input errors (as it was sometimes the case in pnpm v6)
> fix(cmd-shim): extend NODE_PATH with path to hidden hoisted dir

- .changeset/new-insects-invent.md
- packages/config/src/index.ts
> chore: public-hoist-pattern prettier config

- .changeset/eleven-kids-chew.md
- packages/core/test/utils/testDefaults.ts
- packages/headless/test/utils/testDefaults.ts
- packages/mount-modules/package.json
- packages/mount-modules/src/cli.ts
- packages/mount-modules/tsconfig.json
- packages/plugin-commands-env/src/node.ts
- packages/plugin-commands-installation/test/utils/index.ts
- packages/plugin-commands-listing/test/utils/index.ts
- packages/plugin-commands-outdated/test/utils/index.ts
- packages/plugin-commands-publishing/test/utils/index.ts
- packages/plugin-commands-rebuild/src/implementation/extendRebuildOptions.ts
- packages/plugin-commands-rebuild/test/utils/index.ts
- packages/plugin-commands-script-runners/test/utils/index.ts
- packages/plugin-commands-server/src/start.ts
- packages/plugin-commands-server/src/status.ts
- packages/plugin-commands-server/src/stop.ts
- packages/plugin-commands-store/src/store.ts
- packages/store-connection-manager/src/index.ts
- packages/store-path/src/index.ts
- packages/store-path/test/index.ts
- pnpm-lock.yaml
Related to: https://github.com/pnpm/pnpm/issues/2574
Changing the location of the global store from `~/.pnpm-store` to `<pnpm home directory>/store`
On Linux, by default it will be `~/.local/share/pnpm/store`
On Windows: `%LOCALAPPDATA%/pnpm/store`
On macOS: `~/Library/pnpm/store`
> feat: the global store location should be inside the pnpm home directory

- .changeset/beige-ravens-speak.md
- .changeset/large-items-work.md
- packages/core/test/install/multipleImporters.ts
- packages/core/test/install/peerDependencies.ts
- packages/dependency-path/package.json
- packages/dependency-path/src/index.ts
- packages/dependency-path/test/index.ts
- packages/pnpm/test/install/hooks.ts
- packages/resolve-dependencies/src/resolvePeers.ts
- pnpm-lock.yaml
This won't solve all the issues but maybe it will help in some cases with the ENAMETOOLONG errors (https://github.com/pnpm/pnpm/issues/4549)
The paths inside `node_modules/.pnpm` will be 6 symbols shorter.
> feat: use a shorter hash for dep path

- .changeset/curly-spiders-search.md
- .changeset/stale-apples-shop.md
- packages/client/src/index.ts
- packages/config/src/Config.ts
- packages/config/src/index.ts
- packages/git-fetcher/src/index.ts
- packages/git-fetcher/test/index.ts
- packages/store-connection-manager/src/createNewStoreController.ts
Implementing this idea: https://github.com/pnpm/pnpm/discussions/4526 
What do you think?
The danger here is that if the prepare scripts depend on git history, then it will fail
> feat(git-fetcher): shallow clone when fetching git resource

- packages/fetcher-base/README.md
- packages/modules-yaml/README.md
- packages/resolver-base/README.md
- packages/symlink-dependency/README.md
- privatePackages/assert-project/README.md
- privatePackages/assert-store/README.md
> docs(*): fix problems with sample code in documentation

- packages/fetch/src/fetch.ts
- packages/pnpm/.gitignore
- packages/pnpm/spnpm.js
- packages/resolve-dependencies/src/resolvePeers.ts
I've been doing a lot of local debugging with `spnpm` lately and it's challenging to work with. The ts-execution-engine has been oddly flaky and resulting in cases where TS files weren't getting resolved correctly. Also babel register adds some friction when I want to use `--inspect-brk` and set breakpoints before the execution begins; the sourcemaps aren't present until the files are resolved and read in.
This PR rewrites `spnpm` to use esbuild to bundle (with sourcemaps) a file which is then `require`ed in.
Esbuild is fast enough (~500ms on my machine) to just bundle on every invocation.
Let me know what you think. It's been much more stable for my local development and solves all the problems I've run into.
> Improve spnpm to use esbuild

- .changeset/mighty-papayas-itch.md
- packages/core/src/install/createPeerDependencyPatcher.ts
- packages/core/test/install/createPeerDependencyPatcher.test.ts
If a workspace has a global peerDependencyRule that is applied by more
than one package, the lockfile could contain duplicate copies
of the patched range. For example react-dom might have
`peerDependencies: 17.0.2 || 17 || 17 || 17 || 17` in the lockfile.
This causes merge conflicts as package updates seem to regularly change
the number of duplicates, causing lockfile conflicts.
The fix checks if the same widened range has already been appended,
and ignores subsequent duplicates if they exist.
Please refer to this repo for a reproduction workspace, which I tested on 6.x and 7.0-rc.4:
https://github.com/kamsar/pnpm-repro/blob/4b967e8433d9b33a0f519f8760ee928c9b0c2371/pnpm-lock.yaml#L119
(in my much larger private monorepo I've seen 7-10 duplications across lots of packages fwiw)
> fix(core): prevent duplication of peerDependencyRules in the lockfile

- .changeset/modern-maps-unite.md
- packages/package-requester/src/packageRequester.ts
- packages/package-requester/test/index.ts
- pnpm-lock.yaml
close https://github.com/pnpm/pnpm/issues/4566
close https://github.com/pnpm/pnpm/issues/4565
> fix: store integrity check when the lockfile is updated

- .changeset/strange-parents-drum.md
- packages/core/test/install/multipleImporters.ts
- packages/resolve-dependencies/src/resolveDependencies.ts
- utils/eslint-config/package.json
Fix for #4565. I couldn't find any relevant tests to work with.
I also tossed in a fix to `@pnpm/eslint-config` which was throwing this error for me locally:
```
(node:93074) [DEP0128] DeprecationWarning: Invalid 'main' field in '/Users/jdlm/stripe/contrib/pnpm/node_modules/@pnpm/eslint-config/package.json' of 'lib/index.js'. Please either fix that or report it to the module author
(Use `node --trace-deprecation ...` to show where the warning was created)
```
> Fix `add` bug with overlapping workspace packages

- .changeset/strange-llamas-tie.md
- packages/plugin-commands-script-runners/src/exec.ts
- packages/plugin-commands-script-runners/test/exec.e2e.ts
> fix(exec): commands of workspace project should be in PATH

- .changeset/funny-mirrors-act.md
- packages/filter-workspace-packages/src/getChangedPackages.ts
- packages/filter-workspace-packages/test/index.ts
fix #4594 🙇 
Package filtering is not working, if changed file include korean char.
Because `gif diff` result starts and end with `"`.
> fix(filter-workspace-packages): filter not working if the path contains Korean characters

- .github/workflows/codeql-analysis.yml
- .github/workflows/release.yml
Restrict the GitHub token permissions only to the required ones; this way, even if the attackers will succeed in compromising your workflow, they won’t be able to do much.
- Included permissions for the action. https://github.com/ossf/scorecard/blob/main/docs/checks.md#token-permissions
https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#permissions
https://docs.github.com/en/actions/using-jobs/assigning-permissions-to-jobs
[Keeping your GitHub Actions and workflows secure Part 1: Preventing pwn requests](https://securitylab.github.com/research/github-actions-preventing-pwn-requests/)
Signed-off-by: neilnaveen <42328488+neilnaveen@users.noreply.github.com>
> chore: Set permissions for GitHub actions

- .changeset/calm-lamps-occur.md
- packages/core/test/install/local.ts
- packages/resolve-dependencies/src/resolveDependencies.ts
- packages/resolve-dependencies/src/resolveDependencyTree.ts
> fix: a file dep has a file dep

- .changeset/yellow-wolves-swim.md
- packages/exportable-manifest/src/index.ts
- packages/exportable-manifest/src/overridePublishConfig.ts
- packages/exportable-manifest/test/index.test.ts
- packages/exportable-manifest/test/overridePublishConfig.test.ts
- packages/types/src/package.ts
fix #4636 🙇
Add typesVersions field to PUBLISH_CONFIG_WHITELIST
https://www.typescriptlang.org/docs/handbook/declaration-files/publishing.html#version-selection-with-typesversions
related pr: https://github.com/pnpm/pnpm.github.io/pull/255
> fix(exportable-manifest, types): add typesVersions field to PUBLISH_CONFIG_WHITELIST

- .changeset/green-cows-work.md
- packages/plugin-commands-init/src/init.ts
- packages/plugin-commands-init/test/init.test.ts
> fix(init): throw an error if arguments are passed to init command

- .changeset/khaki-carrots-smile.md
- .changeset/shiny-buses-breathe.md
- .changeset/silver-falcons-care.md
- .changeset/thirty-pumpkins-rule.md
- packages/core/src/install/index.ts
- packages/modules-cleaner/src/prune.ts
- packages/plugin-commands-installation/src/install.ts
- packages/plugin-commands-installation/src/prune.ts
- packages/plugin-commands-installation/src/recursive.ts
- packages/plugin-commands-installation/test/prune.ts
> fix(prune): should work in a workspace

- .changeset/neat-islands-think.md
- packages/plugin-commands-setup/src/setupOnWindows.ts
- packages/plugin-commands-setup/test/setupOnWindows/01.test.ts
- packages/plugin-commands-setup/test/setupOnWindows/02.test.ts
- packages/plugin-commands-setup/test/setupOnWindows/03.test.ts
- packages/plugin-commands-setup/test/setupOnWindows/04.test.ts
- packages/plugin-commands-setup/test/setupOnWindows/05.test.ts
- packages/plugin-commands-setup/test/setupOnWindows/06.test.ts
- packages/plugin-commands-setup/test/setupOnWindows/07.test.ts
Previous `pnpm setup` would break %PATH% containing non-ascii characters.
Now it works fine.
Closes https://github.com/pnpm/pnpm/issues/4698
> fix: `pnpm setup` breaks PATH with non-ascii characters

- .changeset/sour-peas-prove.md
- packages/plugin-commands-script-runners/src/runRecursive.ts
- packages/pnpm/test/monorepo/index.ts
> pnpm run --stream should prefix with dir name

- .changeset/red-feet-relax.md
- package.json
- packages/cli-utils/src/packageIsInstallable.ts
- packages/exportable-manifest/src/overridePublishConfig.ts
- packages/filter-lockfile/package.json
- packages/filter-lockfile/src/filterLockfileByImportersAndEngine.ts
- packages/filter-lockfile/test/filterByImportersAndEngine.ts
- packages/filter-lockfile/test/index.ts
- packages/headless/src/lockfileToDepGraph.ts
- packages/headless/src/lockfileToHoistedDepGraph.ts
- packages/lockfile-file/package.json
- packages/lockfile-file/src/sortLockfileKeys.ts
- packages/lockfile-file/test/__snapshots__/write.test.ts.snap
- packages/lockfile-file/test/write.test.ts
- packages/lockfile-types/src/index.ts
- packages/package-is-installable/package.json
- packages/package-is-installable/src/checkPlatform.ts
- packages/package-is-installable/src/index.ts
- packages/package-is-installable/test/checkPlatform.ts
- packages/resolve-dependencies/src/resolveDependencies.ts
- packages/resolve-dependencies/src/updateLockfile.ts
- packages/types/src/package.ts
- pnpm-lock.yaml
closes: https://github.com/pnpm/pnpm/issues/4454
This PR support for a filed named `libc` in `package.json`, it will taken into account when filter optional dependencies.
> feat: support libc field for package.json

- .changeset/dirty-dryers-lie.md
- packages/plugin-commands-setup/src/setupOnWindows.ts
- packages/plugin-commands-setup/test/setupOnWindows/01.test.ts
- packages/plugin-commands-setup/test/setupOnWindows/02.test.ts
- packages/plugin-commands-setup/test/setupOnWindows/03.test.ts
- packages/plugin-commands-setup/test/setupOnWindows/04.test.ts
- packages/plugin-commands-setup/test/setupOnWindows/05.test.ts
- packages/plugin-commands-setup/test/setupOnWindows/06.test.ts
- packages/plugin-commands-setup/test/setupOnWindows/07.test.ts
The output used to be garbled on non-English systems, but not anymore.
> fix: make `pnpm setup` free of garbled characters

- .changeset/curvy-plums-search.md
- package.json
- pnpm-lock.yaml
Fixes #4319
This was fixed upstream in [pkg-fetch 3.4](https://github.com/vercel/pkg-fetch/releases/tag/v3.4)
```
~/Developer/pnpm/packages/artifacts/macos-arm64
❯ NODE_OPTIONS="--max-old-space-size=4096" ./pnpm
❯ echo $?           
4
```
```
~/Developer/pnpm/packages/artifacts/macos-arm64
❯ NODE_OPTIONS="--max-old-space-size=4096" ./pnpm
Version 7.1.6 (compiled to binary; bundled Node.js v14.19.2)
Usage: pnpm [command] [flags]
pnpm [ -h | --help | -v | --version ]
```
> fix: pnpm pre-compiled binaries crash when NODE_MODULES is set

- .changeset/seven-shirts-vanish.md
- packages/build-modules/src/buildSequence.ts
- packages/build-modules/src/index.ts
- packages/cafs/package.json
- packages/cafs/src/addFilesFromDir.ts
- packages/cafs/src/addFilesFromTarball.ts
- packages/cafs/test/index.ts
- packages/cafs/tsconfig.json
- packages/core/test/install/fromRepo.ts
- packages/fetcher-base/src/index.ts
- packages/package-requester/src/packageRequester.ts
- packages/resolve-dependencies/src/index.ts
- packages/resolve-dependencies/src/resolveDependencies.ts
- packages/store-controller-types/src/index.ts
- pnpm-lock.yaml
> fix: resolve manifest promise when manifest is not found

- .changeset/fast-bears-care.md
- .changeset/sharp-pugs-join.md
- packages/core/src/getPeerDependencyIssues.ts
- packages/core/src/install/extendInstallOptions.ts
- packages/core/src/install/index.ts
- packages/core/test/install/reporting.ts
- packages/plugin-commands-installation/src/getOptionsFromRootManifest.ts
- packages/resolve-dependencies/src/resolveDependencies.ts
- packages/resolve-dependencies/src/resolveDependencyTree.ts
- packages/types/src/package.ts
close #4306
A new setting is supported for ignoring specific deprecation messages: `pnpm.allowedDeprecatedVersions`. The setting should be provided in the `pnpm` section of the root `package.json` file. The below example will mute any deprecation warnings about the `request` package and warnings about `express` v1:
```json
{
"pnpm": {
"allowedDeprecatedVersions": {
"request": "*",
"express": "1"
}
}
}
```
> feat: allowed deprecated versions

- .changeset/quiet-icons-wait.md
- packages/find-workspace-dir/src/index.ts
- packages/find-workspace-dir/test/index.ts
For case insensitive systems (Windows) `findWorkspaceDir` will return the path to the module as it was called (because of `cwd`) not the real path.
It leads to an issue when `getImporters` can't find the the manifest (#4904).
Can be reproduces if `pnpm` was called from "c:\code\project" but the real path is "C:\Code\Project".
`getImporters` will find all `manifestsByPath` as "C:\Code\Project\...", but `prefixes` will use workspace root "c:\code\project\...", and it can't match them.
It is possible to try [true-case-path](https://github.com/Profiscience/true-case-path/pulls) but has some vulnerable deps.
> fix: resolve real path for case insensitive systems

- .changeset/odd-masks-type.md
- packages/plugin-commands-deploy/src/deploy.ts
Currently the deploy command will throw when the deploy directory is nested.
Example running: 
```console
pnpm --filter=pkg deploy deploy/pkg
```
will throw with 
```console
 ENOENT  ENOENT: no such file or directory, mkdir '/home/project/deploy/pkg'
```
This happens when the parent folder (deploy in this case) has not been already created.
This PR adds { recursive: true } to allow creating the deploy directory recursivly.
> fix: use recursive for deploy command directory creation

- .changeset/tough-books-count.md
- packages/lockfile-file/src/write.ts
- packages/lockfile-file/test/normalizeLockfile.test.ts
> fix(lockfile): never add an empty `patchedDependencies` field to `pnpm-lock.yaml`

- .changeset/hip-sheep-smoke.md
- packages/git-resolver/src/index.ts
- packages/git-resolver/test/index.ts
Fix #2045
Previously, if you wanted to check out a git PR branch, you needed to specify the url as, e.g. `github:pnpm/pnpm#refs/pull/4953/merge`. Now this will resolve without the leading "refs", i.e. `github:pnpm/pnpm#pull/4953/merge`
> Add "refs/"+refname to resolution options

- .changeset/lucky-icons-give.md
- packages/core/src/install/index.ts
- packages/core/test/install/lockfileOnly.ts
- packages/plugin-commands-installation/src/install.ts
> fix: --lockfile-only in CI and with frozen-lockfile=true

- .changeset/perfect-cherries-worry.md
- packages/config/src/Config.ts
- packages/core/src/install/extendInstallOptions.ts
- packages/core/test/install/multipleImporters.ts
- packages/manifest-utils/src/getPref.ts
- packages/plugin-commands-installation/test/add.ts
- packages/plugin-commands-installation/test/miscRecursive.ts
- packages/pnpm/test/monorepo/index.ts
- packages/resolve-dependencies/src/index.ts
- packages/resolve-dependencies/src/updateProjectManifest.ts
- packages/which-version-is-pinned/src/index.ts
Makes workspace spec aliases (`workspace:^`, `workspace:~` and `workspace:*`) the default version specifiers when a workspace package is added.
Related to #4887
> feat: use workspace spec alias by default in pnpm add

- .changeset/early-bats-sell.md
- packages/core/src/install/link.ts
- packages/core/test/install/autoInstallPeers.ts
> fix: don't symlink the autoinstalled peers to the root of node_modules

- .changeset/fresh-singers-sparkle.md
- packages/plugin-commands-patching/src/patchCommit.ts
- packages/plugin-commands-patching/test/patch.test.ts
Avoid retaining a copy of the contents of files deleted during patching
fixes #5003
> feat: use irreversible-delete in pnpm patch-commit

- .changeset/lemon-numbers-hug.md
- packages/default-reporter/package.json
- packages/default-reporter/src/reporterForClient/pkgsDiff.ts
- packages/default-reporter/test/index.ts
before the fix, the summary was printing dependencies that did not change (but their dependencies changed):
after the fix:
> fix: summary reporting

- .changeset/kind-cups-rescue.md
- packages/pnpmfile/src/requireHooks.ts
- packages/pnpmfile/src/requirePnpmfile.ts
> fix: don't print info messages about .pnpmfile.cjs

- .changeset/rich-plums-mate.md
- packages/plugin-commands-rebuild/src/rebuild.ts
Make `pnpm rebuild` accepts `--store-dir`
```
pnpm install --store-dir <some_dir> --ignore-scripts
pnpm rebuild --store-dir <some_dir> --pending
```
pnpm complains
```
 ERROR   ERROR  Unknown option: 'store-dir'
Did you mean 'stream'? Use "--config.unknown=value" to force an unknown option.
```
```
pnpm rebuild --store-dir <some_dir> --pending works
```
```
pnpm rebuild --config.storeDir=<some_dir> --pending
```
> pnpm rebuild accepts --store-dir

- .changeset/cool-chefs-march.md
- packages/plugin-commands-deploy/src/deploy.ts
- packages/plugin-commands-deploy/test/deploy.test.ts
> fix(deploy): include all deps by default

- packages/core/package.json
- packages/headless/package.json
- packages/plugin-commands-installation/package.json
- packages/plugin-commands-rebuild/package.json
- pnpm-lock.yaml
v14 drops Node 12 support which doesn't impact us, other changes also don't require code updates, see: https://github.com/sinonjs/sinon/blob/v14.0.0/CHANGES.md
- upgrade `sinon` throughout packages to 14.0.0
> chore(deps): upgrade sinon to v14

- .changeset/bright-dingos-stare.md
- packages/audit/package.json
- packages/audit/src/index.ts
- packages/audit/test/index.ts
- packages/audit/tsconfig.json
- packages/plugin-commands-audit/package.json
- packages/plugin-commands-audit/src/audit.ts
- packages/plugin-commands-audit/test/fix.ts
- packages/plugin-commands-audit/test/index.ts
- pnpm-lock.yaml
Adds authentication to pnpm-audit for private registries
See #5038
> fix(audit): add authentication to pnpm-audit

- .changeset/dirty-mirrors-occur.md
- packages/build-modules/src/index.ts
- packages/config/src/Config.ts
- packages/config/src/index.ts
- packages/config/test/index.ts
- packages/core/src/install/extendInstallOptions.ts
- packages/core/src/install/index.ts
- packages/core/src/link/index.ts
- packages/core/src/link/options.ts
- packages/core/test/install/misc.ts
- packages/headless/src/index.ts
- packages/headless/src/linkHoistedModules.ts
- packages/hoist/src/index.ts
- packages/link-bins/package.json
- packages/link-bins/src/index.ts
- pnpm-lock.yaml
A new setting supported: `prefer-symlinked-executables`
When `true`, on Posix systems pnpm will create symlinks to executables in
`node_modules/.bin` instead of command shims.
This setting is `true` by default when `node-linker` is set to
`hoisted`.
close #4782
> feat: prefer-symlinked-executables

- .changeset/clever-guests-heal.md
- .changeset/clever-guests-heal2.md
- .changeset/wise-guests-turn.md
- packages/core/src/install/extendInstallOptions.ts
- packages/core/src/install/index.ts
- packages/plugin-commands-deploy/src/deploy.ts
- packages/plugin-commands-deploy/test/deploy.test.ts
- packages/plugin-commands-installation/src/install.ts
> fix(deploy): don't modify the lockfile and fail in CI

- .changeset/loud-weeks-move.md
- packages/plugin-commands-deploy/package.json
- packages/plugin-commands-deploy/src/deploy.ts
- packages/plugin-commands-deploy/src/deployHook.ts
- packages/plugin-commands-deploy/test/deployHook.test.ts
- packages/plugin-commands-deploy/tsconfig.json
- pnpm-lock.yaml
> fix(deploy): inject all types of deps

- .changeset/chilled-penguins-hang.md
- .changeset/fifty-otters-perform.md
- .changeset/tasty-elephants-battle.md
- packages/core/test/install/multipleImporters.ts
- packages/exportable-manifest/src/index.ts
- packages/npm-resolver/src/index.ts
- packages/plugin-commands-publishing/src/pack.ts
- packages/plugin-commands-publishing/test/pack.ts
- ~when the directory setting changes, `pnpm install` should update the symlink~ will be done in a separate PR
close #3901
> fix: symlink a workspace pkg correctly, when it has a custom publish dir

- .changeset/fair-foxes-know.md
- packages/plugin-commands-deploy/src/deploy.ts
This changes the behaviour of the deploy command as discussed in https://github.com/pnpm/pnpm/issues/4980 to use the working directory and to accept absolute paths.
close  #4980
> fix: plugin-commands-deploy use path resolve on deploy target dir

- .changeset/eighty-cheetahs-shout.md
- packages/lockfile-file/src/read.ts
- packages/lockfile-file/test/read.test.ts
when the package has a publishConfig.directory field
close #5124
> fix: don't incorrectly identify a lockfile out-of-date

- .changeset/lemon-impalas-wave.md
- packages/core/test/install/multipleImporters.ts
- packages/npm-resolver/src/index.ts
- packages/types/src/package.ts
> feat: publishConfig.linkDirectory

- .changeset/three-mugs-hide.md
- packages/config/package.json
- packages/config/src/index.ts
- packages/config/test/index.ts
- pnpm-lock.yaml
> fix: don't crash on a .npmrc with missing env var

- .changeset/tidy-seas-dance.md
- packages/config/src/Config.ts
- packages/config/src/index.ts
- packages/core/src/getPeerDependencyIssues.ts
- packages/core/src/install/extendInstallOptions.ts
- packages/core/src/install/index.ts
- packages/core/test/install/packageExtensions.ts
> feat: ignore-compatibility-db

- packages/core/src/install/index.ts
- packages/core/test/install/autoInstallPeers.ts
- packages/core/test/install/frozenLockfile.ts
- packages/core/test/install/misc.ts
- packages/core/test/install/multipleImporters.ts
- packages/core/test/lockfile.ts
- packages/default-reporter/src/reporterForClient/reportStats.ts
- packages/default-reporter/test/reportingProgress.ts
- packages/headless/src/index.ts
- packages/headless/test/index.ts
- packages/plugin-commands-installation/src/update/index.ts
- packages/plugin-commands-publishing/src/publish.ts
- packages/plugin-commands-publishing/test/gitChecks.ts
- packages/plugin-commands-setup/src/setup.ts
- packages/plugin-commands-setup/test/setup.test.ts
The correct usage is _[noun] is up to date_ and _an up-to-date [noun]_. That is, hyphens are only used when _up-to-date_ is used as an adjective preceding a noun. Two examples from the New Oxford American Dictionary for reference:
> a modern, up-to-date hospital
> the book will keep you up to date
> Change "up-to-date" to "up to date" where necessary

- .changeset/stupid-pants-turn.md
- packages/lockfile-file/src/sortLockfileKeys.ts
- packages/lockfile-file/test/sortLockfileKeys.test.ts
Make it more deterministic and prevent unnecessary churn in the lockfile. It is useful when looking for affected projects after changes to the lockfile. When the changes happen among various developers using various locale, the locale specific sorting causes changes in the lockfile for extraneous projects. Therefore, it could cause running unnecessary CI jobs, builds, releases and other work that would not be needed otherwise.
The `localeCompare` was used first time in [this commit](https://github.com/pnpm/pnpm/pull/3194/files#diff-b08cb8fd99387232e5a279315703d545880bc0d4fb8c7a7af2bd975009edd291R71) for this specific use case.
> fix(lockfile): change sorting of keys in lockfile

- .changeset/silent-turtles-suffer.md
- packages/cafs/src/index.ts
- packages/cafs/src/readManifestFromStore.ts
- packages/package-requester/src/packageRequester.ts
- packages/package-requester/test/index.ts
This PR fixes an issue where `verifyStoreIntegrity` is set to `false`. The problem was that `checkFilesIntegrity` is called with a deferred promise which is expected to be resolved, however, it was not. This PR makes sure that if integrity checks are disabled that it will still read the package manifest and resolve the promise properly.
> fix: read package manifest when verifyStoreIntegrity is false

- .github/workflows/ci.yml
- .github/workflows/codeql-analysis.yml
- .github/workflows/release.yml
- .github/workflows/update-latest.yml
I noticed that some GitHub actions are outdated, so upgraded them to latest which might lead to faster CI runs.
- update all `actions/*` to v3
- update all `github/codeql-action/*` to v2
> build: update used versions in github workflow actions

- .changeset/thin-games-kick.md
- packages/node.fetcher/package.json
- packages/node.fetcher/src/index.ts
- packages/node.fetcher/tsconfig.json
- packages/package-requester/package.json
- packages/package-requester/src/index.ts
- packages/package-requester/src/packageRequester.ts
- packages/package-requester/tsconfig.json
- packages/pick-fetcher/README.md
- packages/pick-fetcher/jest.config.js
- packages/pick-fetcher/package.json
- packages/pick-fetcher/src/index.ts
- packages/pick-fetcher/test/getFetcher.ts
- packages/pick-fetcher/test/pickFetcher.ts
- packages/pick-fetcher/tsconfig.json
- packages/pick-fetcher/tsconfig.lint.json
- packages/tarball-fetcher/src/gitHostedTarballFetcher.ts
- packages/tarball-fetcher/src/index.ts
- packages/tarball-fetcher/src/localTarballFetcher.ts
- packages/tarball-fetcher/src/remoteTarballFetcher.ts
- packages/tarball-fetcher/test/fetch.ts
- pnpm-lock.yaml
This PR splits the tarball fetcher into more specific types including
- `localTarball` for any locally hosted tarballs
- `remoteTarball` for packages hosted via remote tarballs, e.g. coming from the npm registry
- `gitHostedTarball` for git hosted packages
> feat: split package fetcher

- .changeset/shy-sloths-beam.md
- packages/client/package.json
- packages/client/src/index.ts
- packages/client/tsconfig.json
- packages/directory-fetcher/src/index.ts
- packages/fetcher-base/src/index.ts
- packages/git-fetcher/src/index.ts
- packages/package-requester/src/packageRequester.ts
- packages/package-store/src/storeController/index.ts
- packages/pick-fetcher/src/index.ts
- packages/pnpm/test/hooks.ts
- packages/pnpmfile/package.json
- packages/pnpmfile/src/requireHooks.ts
- packages/pnpmfile/tsconfig.json
- packages/resolver-base/src/index.ts
- packages/store-connection-manager/src/createNewStoreController.ts
- pnpm-lock.yaml
This PR adds a hook to configure custom fetchers. This allows to configure custom fetchers for all types of fetchers, e.g.
```ts
{
localTarball: CustomFetcherFactory,
remoteTarball: CustomFetcherFactory,
gitHostedTarball: CustomFetcherFactory,
git: CustomFetcherFactory,
directory: CustomFetcherFactory,
}
```
The `CustomFetcherFactory` is a function that receives options and returns a `FetchFunction` that resolves a `FetchResult`.
> feat: add hook for custom fetchers

- packages/core/src/install/link.ts
- packages/headless/src/index.ts
- packages/resolve-dependencies/src/index.ts
Small typo fixes (_much_ to _match_). The only place this is visible to the user is when `PATCH_NOT_APPLIED` error is thrown.
> docs: fix typos much -> match

- packages/pnpm/test/cli.ts
- packages/read-project-manifest/test/index.ts
In regular expressions, `[` and `]` have special meanings, and only one of the characters enclosed by them can be matched to the target string, and this test is actually to match `[command]` and `[flags]` itself, so these two special characters need to be escaped.
Also, Jest's `toMatch` method supports both strings and regular expressions, so I can pass in a string to avoid escaping:
```javascript
expect(result.stdout.toString()).not.toMatch('Usage: pnpm [command] [flags]')
```
But I observed other files of the project, most of them use regular expressions, and this file does. So I still choose to modify the regular expression (add escape characters) to achieve the purpose.
> fix(pnpm/test): add escape characters

- .changeset/wild-files-reply.md
- packages/core/test/install/defaultPeerDependencies.ts
- packages/core/test/install/peerDependencies.ts
- packages/resolve-dependencies/src/resolveDependencies.ts
When the same package is both in "peerDependencies" and in "dependencies", treat this dependency as a peer dependency if it may be resolved from the dependencies of parent packages.
> fix: packages with default peer dependencies

- .changeset/chilly-poets-care.md
- packages/pnpm/src/main.ts
This PR removes legacy signal handlers which are no longer necessary. This also means that when someone runs a script that gets interrupted, the process now properly terminates with the correct status code, e.g. 130 for `SIGINT` and not always `0`.
> fix: remove legacy signal handlers

- .changeset/polite-kings-travel.md
- packages/cafs-types/src/index.ts
- packages/cafs/src/index.ts
This PR exetnds the `cafs` object with `getFilePathByModeInCafs` which is useful for custom fetchers.
> feat(cafs): extend cafs with getFilePathByModeInCafs

- .changeset/five-ties-add.md
- packages/node.fetcher/src/getNodeTarball.ts
- packages/node.fetcher/src/normalizeArch.ts
- packages/node.fetcher/test/getNodeTarball.test.ts
- packages/node.fetcher/test/normalizeArch.test.ts
Add a check for macos apple silicon and required node version < 16.
In such case, download x64 binary.
Because arm build does not exist.
Macos automatically detects x64 instructions and converts them so downloaded node works as expected.
Previous behaviour:
Try to download non existing arm build and fail with 404.
NO breaking change
fixes #4489
> fix: node<16 download fail on arm chips on macos

- .changeset/purple-tools-leave.md
- packages/plugin-commands-env/package.json
- packages/plugin-commands-env/src/node.ts
- pnpm-lock.yaml
Add an immediate response when fetching Node.js on version switching, preventing pnpm looks like just hanging there.
I noticed that `@pnpm/logger` and `@pnpm/core-loggers` are being used in many packages. 
But it doesn't work when I try to use it like `logger.info({ message: "...", prefix: "dir" })`, I think I have missed something.
> feat(env): show state on fetching node

- .changeset/strong-panthers-agree.md
- packages/config/package.json
- packages/config/src/Config.ts
- packages/config/src/index.ts
- packages/core/src/install/extendInstallOptions.ts
- packages/core/src/install/index.ts
- packages/headless/src/index.ts
- packages/plugin-commands-deploy/test/utils/index.ts
- packages/plugin-commands-installation/src/install.ts
- packages/plugin-commands-installation/src/installDeps.ts
- packages/plugin-commands-installation/test/add.ts
- packages/plugin-commands-installation/test/global.ts
- packages/plugin-commands-installation/test/peerDependencies.ts
- packages/plugin-commands-installation/test/prune.ts
- packages/plugin-commands-installation/test/update/interactive.ts
- packages/plugin-commands-installation/test/utils/index.ts
- packages/plugin-commands-listing/test/utils/index.ts
- packages/plugin-commands-outdated/test/utils/index.ts
- packages/plugin-commands-patching/test/utils/index.ts
- packages/plugin-commands-publishing/src/publish.ts
- packages/plugin-commands-publishing/src/recursivePublish.ts
- packages/plugin-commands-rebuild/src/implementation/extendRebuildOptions.ts
- packages/plugin-commands-rebuild/src/implementation/index.ts
- packages/plugin-commands-script-runners/src/exec.ts
- packages/plugin-commands-script-runners/src/run.ts
- packages/plugin-commands-script-runners/src/runRecursive.ts
- packages/plugin-commands-script-runners/test/index.ts
- packages/plugin-commands-script-runners/test/utils/index.ts
- pnpm-lock.yaml
This PR fixes an issue with `preferSymlinkedExecutables` where the `NODE_PATH` was not set.
> fix: set NODE_PATH when  is turned on

- .changeset/orange-swans-relax.md
- packages/symlink-dependency/jest.config.js
- packages/symlink-dependency/package.json
- packages/symlink-dependency/src/symlinkDirectRootDependency.ts
- packages/symlink-dependency/test/symlinkDirectRootDependency.test.ts
- packages/symlink-dependency/tsconfig.json
- pnpm-lock.yaml
> fix: symlink local dep even when target dir does not exist

- .changeset/long-trainers-share.md
- packages/plugin-commands-env/package.json
- packages/plugin-commands-env/src/env.ts
- packages/plugin-commands-env/src/node.ts
- packages/plugin-commands-env/test/env.test.ts
- packages/plugin-commands-env/test/node.test.ts
- packages/plugin-commands-env/tsconfig.json
- pnpm-lock.yaml
This PR enhances the `pnpm env` functionality with the `uninstall` command, allowing to uninstall Node.JS globally, that was previously installed with `pnpm env use <version>`.
Partially closes #5155 
Listing installed Node.JS will be done in a separate PR, I'm trying to keep this one short.
I think there's room for refactoring, but for now, I just tried to follow what's already in place. If refactoring is an option, I could work on it furthermore.
> feat(env): add remove command to pnpm env

- CONTRIBUTING.md
Adds an initial compile step to provide pnpm.js needed by the `pd` script.
Resolves #5288.
> docs(CONTRIBUTING): correct setup instructions for first-time clone

- .changeset/fast-games-grow.md
- packages/npm-resolver/src/pickPackage.ts
- packages/npm-resolver/test/fixtures/bad-dates.json
- packages/npm-resolver/test/publishedBy.test.ts
- packages/plugin-commands-script-runners/test/testRecursive.ts
- packages/plugin-commands-store/test/storeStatus.ts
ref https://github.com/pnpm/pnpm/pull/5238
> fix: add fallback for time-based resolution

- .changeset/twenty-dragons-explode.md
- packages/core/test/install/autoInstallPeers.ts
- packages/resolve-dependencies/src/index.ts
> fix: auto installing peer dep in a workspace

- .changeset/fluffy-crews-join.md
- packages/plugin-commands-patching/src/patch.ts
- packages/plugin-commands-patching/src/patchCommit.ts
- packages/plugin-commands-patching/src/writePackage.ts
- packages/plugin-commands-patching/test/patch.test.ts
> fix(patch): allow to edit a package in any directory

- .changeset/calm-phones-jog.md
- packages/matcher/src/index.ts
- packages/matcher/test/index.ts
> feat(matcher): ignore patterns

- .changeset/angry-hounds-bow.md
- packages/core/src/getPeerDependencyIssues.ts
- packages/core/src/install/extendInstallOptions.ts
- packages/core/src/install/index.ts
- packages/core/test/install/patch.ts
- packages/plugin-commands-installation/src/getOptionsFromRootManifest.ts
- packages/resolve-dependencies/src/index.ts
- packages/resolve-dependencies/src/resolveDependencyTree.ts
- packages/types/src/package.ts
add flag to make non-applied patches a warning instead of a fatal error
close #5234
> feat(patch): allow non-applied patches

- .changeset/lemon-adults-grow.md
- .meta-updater/src/index.ts
- package.json
- pnpm-lock.yaml
resolves pnpm/meta-updater#5
Few changes need to be done to use new version of the `@pnpm/meta-updater`.
> chore: update @pnpm/meta-updater

- .changeset/two-cobras-melt.md
- packages/core/test/install/autoInstallPeers.ts
- packages/resolve-dependencies/src/resolveDependencies.ts
> fix: deduplicate peer deps

- .changeset/orange-apes-scream.md
- .changeset/stale-rice-nail.md
- packages/plugin-commands-installation/src/link.ts
- packages/plugin-commands-installation/test/link.ts
close https://github.com/pnpm/pnpm/issues/5368
pnpm link always use `cwd` and don't read the `--dir` option, I try to fix it but I am not sure if it's the best way
> fix: error in pnpm --dir <path> link --global

- .changeset/twenty-wolves-destroy.md
- packages/core/test/install/autoInstallPeers.ts
- packages/resolve-dependencies/src/resolveDependencies.ts
ref https://github.com/pnpm/pnpm/issues/5390
ref https://github.com/pnpm/pnpm/issues/5372
> fix: cli crash with auto-install-peers=true

- .github/workflows/ci.yml
- .github/workflows/update-latest.yml
This PR adds explicit [permissions section](https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#permissions) to workflows. This is a security best practice because by default workflows run with [extended set of permissions](https://docs.github.com/en/actions/security-guides/automatic-token-authentication#permissions-for-the-github_token) (except from `on: pull_request` [from external forks](https://securitylab.github.com/research/github-actions-preventing-pwn-requests/)). By specifying any permission explicitly all others are set to none. By using the principle of least privilege the damage a compromised workflow can do (because of an [injection](https://securitylab.github.com/research/github-actions-untrusted-input/) or compromised third party tool or …
> GitHub Workflows security hardening

- .changeset/bright-chefs-drop.md
- .changeset/eleven-cups-provide.md
- packages/matcher/src/index.ts
- packages/matcher/test/index.ts
- packages/plugin-commands-installation/src/recursive.ts
- packages/plugin-commands-installation/test/update/update.ts
> feat: excluding deps from update

- .changeset/rotten-moose-search.md
- packages/plugin-commands-installation/src/link.ts
- packages/plugin-commands-installation/test/link.ts
To fix repeated join in global link and use absolute path in test case
From discussion: https://github.com/pnpm/pnpm/discussions/5421
> fix: dir path repeated join in link global

- .changeset/large-suns-relax.md
- packages/pnpm/src/main.ts
- packages/pnpm/test/filterProd.test.ts
This is the followup PR for previous PR: #4957
> fix: filter-prod flag including all workspace pkgs

- .changeset/rude-vans-build.md
- fixtures/with-pnpm-update-ignore/package.json
- fixtures/with-pnpm-update-ignore/pnpm-lock.yaml
- packages/outdated/src/outdated.ts
- packages/outdated/src/outdatedDepsOfProjects.ts
- packages/plugin-commands-installation/jest.config.js
- packages/plugin-commands-installation/src/ignoreDependenciesWithSelectorPattern.ts
- packages/plugin-commands-installation/src/installDeps.ts
- packages/plugin-commands-installation/src/recursive.ts
- packages/plugin-commands-installation/test/update/update.ts
- packages/plugin-commands-outdated/src/outdated.ts
- packages/plugin-commands-outdated/src/recursive.ts
- packages/plugin-commands-outdated/test/index.ts
- packages/types/src/package.ts
Closes: #5358 
supports a function to ignore packages listed in `package.json > pnpm.update.ignore` on update/outdated commands like `npm-check-updates` to cover some usecase.
when we run `update/outdated` commands with the package.json with the fields like below:
```json
{
...
"pnpm": {
"updates": {
"ignore": [
...packages
]
}
}
}
```
pnpm will ignore packages listed in `package.json > pnpm.update.ignore` on update/outdated commands like `npm-check-updates`
> Feature: ignore packages listed in `package.json > pnpm.updateConfig.ignoreDependencies` on update/outdated commands

- .changeset/slow-panthers-refuse.md
- packages/core/test/install/autoInstallPeers.ts
- packages/resolve-dependencies/src/resolveDependencies.ts
> fix: don't override root deps when auto installing peers

- .changeset/loud-bugs-invite.md
- packages/plugin-commands-installation/test/update/update.ts
Fixes: #5410 
currently, `update` command's test cannot verify `update` command because `update` command works as `recursive` with `workspaceDir` and `dir` args but current test implementation passes both of `workspaceDir` and `dir` args into `update` command's handler. FYI: https://github.com/pnpm/pnpm/blob/main/packages/plugin-commands-installation/src/installDeps.ts#L128-L130
I fix this by removing `workspaceDir` args from `update` command's handler in `update` test
> Fix: test update command's handler correctly

- .changeset/wicked-zebras-deliver.md
- packages/plugin-commands-patching/src/patchCommit.ts
- packages/plugin-commands-patching/test/patch.test.ts
pnpm patch-commit did not apply patch if the absolute path to a directory passed to it contained a trailing slash on Windows, now the trailing slash is removed
closes https://github.com/pnpm/pnpm/issues/5449
> fix: pnpm patch-commit with a trailing slash on Windows does not work

- .changeset/thick-dancers-guess.md
- packages/plugin-commands-publishing/src/pack.ts
- packages/plugin-commands-publishing/test/pack.ts
> fix: return correct path in `pnpm pack`

- .changeset/few-ghosts-rule.md
- .changeset/heavy-tools-agree.md
- packages/core/src/install/index.ts
- packages/plugin-commands-installation/src/link.ts
- packages/plugin-commands-installation/test/link.ts
Fix: 
1. add dir option support in `pnpm link <pkg> --global`
2. remove WARN **undefined has no binaries**
> fix: add dir option support in link <pkg> --global

- .changeset/flat-kings-tell.md
- packages/config/package.json
- packages/config/test/index.ts
- pnpm-lock.yaml
Close https://github.com/pnpm/pnpm/issues/5518
The warning is a little annoying. It will be removed in the next patch version and be replaced in anthoer way in the future.
> fix: downgrade @pnpm/npm-conf to remove annoying builtin warning

- utils/get-release-text/src/main.ts
I noticed that the sponsor logos were fixed on `README.md` to work for light and dark mode in https://github.com/pnpm/pnpm/commit/a0b855fbce10a912460af6b14fd6ff0bbdf986ac, but not on `RELEASE.md`
Some `utm_medium` parameters were also wrongly pointing to `README.md`, updated that too.
- update `getChangelogEntry()` method to render sponsor logos for light and dark mode correctly
Sponsor logos like the one from Prisma are barely readable:
> docs: support light and dark versions of sponsor logos on release file

- .changeset/small-ads-warn.md
- packages/resolve-dependencies/src/index.ts
> fix: don't crash on lockfile with no packages field

- .changeset/wise-pugs-wave.md
- packages/config/src/index.ts
- packages/config/test/index.ts
When the environment variable `PNPM_HOME` is updated by user, the config `pnpmHomeDir` is still the default directory.
> fix: pnpmHomeDir should read PNPM_HOME defined in environment variables

- .changeset/wet-hornets-cheat.md
- packages/pnpm/src/err.ts
> fix: cannot set property name of which has only a getter

- .changeset/smart-coats-jam.md
- packages/find-packages/package.json
- packages/find-packages/src/index.ts
- packages/find-workspace-packages/package.json
- packages/find-workspace-packages/src/index.ts
- packages/hoist/package.json
- packages/hoist/src/index.ts
- packages/lockfile-file/package.json
- packages/lockfile-file/src/sortLockfileKeys.ts
- pnpm-lock.yaml
I feel kind of weird for creating a separate package for such a simple and straightforward function. But the only reason I have created it is to document why it is needed: https://github.com/pnpm/components/blob/main/util/lex-comparator/lex-comparator.docs.mdx
> fix: use lexigraphical sorting in places where it matters

- .changeset/lucky-eyes-double.md
- .changeset/moody-weeks-reply.md
- packages/default-reporter/src/reporterForClient/reportLifecycleScripts.ts
- packages/default-reporter/test/reportingLifecycleScripts.ts
- packages/lifecycle/src/runLifecycleHook.ts
> fix(log): line key does not necessarily exist

- .changeset/empty-boats-jog.md
- .changeset/unlucky-pigs-bow.md
- packages/plugin-commands-outdated/package.json
- packages/plugin-commands-outdated/src/outdated.ts
- packages/plugin-commands-outdated/src/recursive.ts
- packages/plugin-commands-outdated/test/index.ts
- packages/plugin-commands-outdated/test/recursive.ts
- packages/plugin-commands-outdated/tsconfig.json
- pnpm-lock.yaml
Support json format output with `outdated` command
Closes: #2705
support JSON format output with `outdated` command if `--format json` is specified. 
I tested this with my own project,
```
pnpm outdated --format json
```
```json
{
"@types/yargs": {
"current": "17.0.11",
"latest": "17,0.13",
"dependencyKind": "dev"
},
"dotenv": {
"current": "16.0.1",
"latest": "16,0.3",
"dependencyKind": "dev"
},
"jsdom": {
"current": "20.0.0",
"latest": "20,0.2",
"dependencyKind": "dev"
},
"tslib": {
"current": "2.4.0",
"latest": "2,4.1"
}
}
```
> Support json format output with `outdated` command

- .changeset/great-jeans-teach.md
- .changeset/young-toes-talk.md
- packages/directory-fetcher/package.json
- packages/directory-fetcher/src/index.ts
- packages/directory-fetcher/test/fixtures/pkg-with-broken-symlink/not-exists
- packages/directory-fetcher/test/fixtures/pkg-with-broken-symlink/package.json
- packages/directory-fetcher/test/index.ts
- pnpm-lock.yaml
> fix: don't break when injecting a dependency with broken symlinks

- .changeset/mighty-waves-tan.md
- .changeset/poor-berries-yell.md
- packages/core/test/install/local.ts
- packages/resolve-dependencies/package.json
- packages/resolve-dependencies/src/index.ts
- packages/resolve-dependencies/src/resolveDependencies.ts
- pnpm-lock.yaml
> fix: error that sometimes happen on projects with linked deps

- .changeset/curly-penguins-perform.md
- .changeset/weak-spies-thank.md
- packages/matcher/src/index.ts
- packages/matcher/test/index.ts
- packages/plugin-commands-installation/src/installDeps.ts
- packages/plugin-commands-installation/test/update/update.ts
> fix(matcher): should ignore successfully with multiple ignore patterns

- .changeset/olive-impalas-rush.md
- pkg-manifest/read-project-manifest/package.json
- pkg-manifest/read-project-manifest/src/index.ts
- pnpm-lock.yaml
Note this had to be done by switching to the fork
@gwhitney/detect-indent, because
sindresorhus/detect-indent no longer provides
CommonJS exports.
Resolves #5664.
> chore: bump detect-indent to 7.0.1

- env/plugin-commands-env/test/node.test.ts
When I tried to run the full test suite in Apple Sillicon, the test about installation of Node.js failed.
I fixed this by getting arch from `process.arch`.
This value is strictly not equal to the value Node.js uses, for example, `process.arch` returns `ppc64` but Node.js provides only `ppc64le`, but I think it is a trivial matter.
> test(plugin-commands-env): fix a test that falling in arm64

- .changeset/proud-schools-jump.md
- pkg-manager/core/src/install/index.ts
- pkg-manager/plugin-commands-installation/src/recursive.ts
- pnpm/test/hooks.ts
Resolves #5670
Recursive installation will now defer to `originalManifest` when checking if workspace `package.json` need to be updated, if available.
Note that this fix applies to the scenario where `pnpm-lock.yaml` exists, odds are that when generating from scratch, one of the following codepaths are used instead.
* https://github.com/pnpm/pnpm/blob/d5496cc3f8fb5696fb4236fb27a956ec93c50eda/pkg-manager/resolve-dependencies/src/index.ts#L187
* https://github.com/pnpm/pnpm/blob/d5496cc3f8fb5696fb4236fb27a956ec93c50eda/pkg-manager/core/src/install/index.ts#L750-L752
* https://github.com/pnpm/pnpm/blob/d5496cc3f8fb5696fb4236fb27a956ec93c50eda/pkg-manager/core/src/install/index.ts#L370
> fix: `--lockfile-only` and `readPackage` hook modifying workspace packages

- pnpm/test/hooks.ts
There are eslint errors in the following three places
[https://github.com/pnpm/pnpm/blob/main/pnpm/test/hooks.ts#L105~#L106](https://github.com/pnpm/pnpm/blob/main/pnpm/test/hooks.ts#L105~#L106)
[https://github.com/pnpm/pnpm/blob/main/pnpm/test/hooks.ts#L42](https://github.com/pnpm/pnpm/blob/main/pnpm/test/hooks.ts#L42)
[https://github.com/pnpm/pnpm/blob/main/pnpm/test/hooks.ts#L96](https://github.com/pnpm/pnpm/blob/main/pnpm/test/hooks.ts#L96)
> style: eslint error extra semicolon

- .changeset/flat-lobsters-whisper.md
- pkg-manager/plugin-commands-installation/src/getOptionsFromRootManifest.ts
- pkg-manager/plugin-commands-installation/test/getOptionsFromRootManifest.test.ts
> Support $ in overrides instead of specific version #5703

- .changeset/old-otters-sleep.md
- hooks/read-package-hook/src/createVersionsOverrider.ts
- hooks/read-package-hook/test/createVersionOverrider.test.ts
- resolving/local-resolver/test/index.ts
resolve #5493 
Fixed error reported when using the file protocol in overrides.
I'm not quite sure how to support the case of changing dependency to local files in `.pnpmfile.js`, when the files does not exist in the workspace directory, is it possible to retry to resolve the file in the root directory ?
> fix(read-package-hook): resolve file overrides should relative to root directory

- .github/workflows/ci.yml
This patch is intended to lower the maintenance burden of having to manually go through each matrix subjob name in the branch protection repository settings. It allows to only include the check job in the branch protection and it will robustly determine if the dependencies have succeeded or not.
It is currently mostly surves the Python ecosystem in projects like aiohttp, cryptography, open edX, pip etc. But I've also seen other communities picking it up lately, like the AWS Rust SDK and even the engine powering https://dev.to, to my surprise. Strictly speaking, it is agnostic.
Ref: https://github.com/marketplace/actions/alls-green#why
> Introduce a centralized GHA check/gate job

- .changeset/hot-dingos-act.md
- pkg-manifest/manifest-utils/src/getPref.ts
- pkg-manifest/manifest-utils/test/getPref.test.ts
> feat: update version when pinnedVersion is *

- .changeset/tricky-bulldogs-eat.md
- resolving/npm-resolver/src/index.ts
- resolving/npm-resolver/test/index.ts
> feat: try adding local pre-release package in workspaces

- .changeset/perfect-islands-trade.md
- hooks/read-package-hook/src/createVersionsOverrider.ts
- hooks/read-package-hook/test/createVersionOverrider.test.ts
> fix: it should possible to use abolute file paths in overrides

- .changeset/old-islands-perform.md
- pkg-manager/core/src/install/index.ts
- pkg-manager/core/src/parseWantedDependencies.ts
- pkg-manager/core/test/install/multipleImporters.ts
- pkg-manager/plugin-commands-installation/src/updateWorkspaceDependencies.ts
- pkg-manager/plugin-commands-installation/test/updateWorkspaceDependencies.test.ts
- pkg-manager/resolve-dependencies/src/getWantedDependencies.ts
- pkg-manager/resolve-dependencies/src/updateProjectManifest.ts
close #5317
close #5303
close #5312 
close #5726
> fix: should not replace workspace:* when update

- .changeset/four-ducks-try.md
- releasing/plugin-commands-publishing/src/publish.ts
show `--json` option for `pnpm publish --help`:
```
$ pd publish --help      
Version 7.18.1
Usage: pnpm publish [<tarball>|<dir>] [--tag <tag>] [--access <public|restricted>] [options]
Publishes a package to the npm registry.
Options:
--access <public|restricted>  Tells the registry whether this package should be published as public
or restricted
--dry-run                     Does everything a publish would do except actually publishing to the
registry
--force                       Packages are proceeded to be published even if their current version
is already in the registry. This is useful when a "prepublishOnly"
script bumps the version of the package before it is published
--ignore-scripts              Ignores any publish related lifecycle scripts (prepublishOnly,
postpublish, and …
```
> chore(plugin-commands-publishing): output --json option in help info

- .changeset/sharp-masks-leave.md
- pnpm/src/errorHandler.ts
- pnpm/src/main.ts
- pnpm/test/errorHandler.test.ts
> fix: print errors when --json option used

- .changeset/tricky-coats-join.md
- exec/lifecycle/package.json
- exec/lifecycle/src/runLifecycleHook.ts
- exec/lifecycle/test/fixtures/without-scriptstart-serverjs/package.json
- exec/lifecycle/test/index.ts
- exec/lifecycle/tsconfig.json
- pnpm-lock.yaml
Missing script start or server.js should print an error but got with: 
```
> node server.js
internal/modules/cjs/loader.js:905
throw err;
^
Error: Cannot find module '/xxx/server.js'
at Function.Module._resolveFilename (internal/modules/cjs/loader.js:902:15)
at Function.Module._load (internal/modules/cjs/loader.js:746:27)
at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:75:12)
at internal/main/run_main_module.js:17:47 {
code: 'MODULE_NOT_FOUND',
requireStack: []
}
```
> fix: throw an error while missing script start or server.js

- .changeset/sour-cougars-deliver.md
- exec/build-modules/package.json
- exec/build-modules/src/index.ts
- exec/build-modules/tsconfig.json
- pkg-manager/core/test/install/lifecycleScripts.ts
- pkg-manager/headless/src/index.ts
- pnpm-lock.yaml
> perf: do not build the same dependency multiple times when node-linker is hoisted

- .changeset/few-dancers-exist.md
- .changeset/nervous-avocados-end.md
- exec/plugin-commands-rebuild/package.json
- exec/plugin-commands-rebuild/src/implementation/index.ts
- exec/plugin-commands-rebuild/tsconfig.json
- pnpm-lock.yaml
> fix: rebuild should print a better error message

- reviewing/dependencies-hierarchy/src/index.ts
Some small cleanup. This argument is passed from `buildDependenciesHierarchy -> getTree -> getPkgInfo`, but `getPkgInfo` never uses it.
> refactor(dependencies-hierarchy): remove unused lockfileDir argument

- .changeset/perfect-squids-count.md
- .changeset/tiny-chicken-train.md
- __typings__/local.d.ts
- __typings__/typed.d.ts
- config/config/package.json
- config/config/src/index.ts
- config/config/src/readLocalConfig.ts
- config/plugin-commands-config/README.md
- config/plugin-commands-config/jest.config.js
- config/plugin-commands-config/package.json
- config/plugin-commands-config/src/ConfigCommandOptions.ts
- config/plugin-commands-config/src/config.ts
- config/plugin-commands-config/src/configGet.ts
- config/plugin-commands-config/src/configList.ts
- config/plugin-commands-config/src/configSet.ts
- config/plugin-commands-config/src/get.ts
- config/plugin-commands-config/src/index.ts
- config/plugin-commands-config/src/set.ts
- config/plugin-commands-config/test/configDelete.test.ts
- config/plugin-commands-config/test/configGet.test.ts
- config/plugin-commands-config/test/configList.test.ts
- config/plugin-commands-config/test/configSet.test.ts
- config/plugin-commands-config/tsconfig.json
- config/plugin-commands-config/tsconfig.lint.json
- pnpm-lock.yaml
- pnpm/package.json
- pnpm/src/cmd/index.ts
- pnpm/src/pnpm.ts
- pnpm/test/cli.ts
- pnpm/tsconfig.json
close #5621
This change may be considered breaking but if we don't do this change then the config commands break anyway when npm CLI gets updated. So I think it should be OK.
> feat: implement the config commands

- .changeset/fresh-taxis-own.md
- .changeset/lucky-pugs-sell.md
- env/node.fetcher/src/index.ts
- exec/plugin-commands-rebuild/test/index.ts
- exec/prepare-package/package.json
- exec/prepare-package/src/index.ts
- exec/prepare-package/test/__fixtures__/has-prepublish-script/package.json
- exec/prepare-package/test/index.ts
- exec/prepare-package/tsconfig.json
- fetching/git-fetcher/src/index.ts
- fetching/git-fetcher/test/index.ts
- fetching/tarball-fetcher/src/gitHostedTarballFetcher.ts
- fetching/tarball-fetcher/src/index.ts
- fetching/tarball-fetcher/test/fetch.ts
- pkg-manager/client/src/index.ts
- pkg-manager/client/test/index.ts
- pkg-manager/core/test/install/lifecycleScripts.ts
- pkg-manager/core/test/utils/testDefaults.ts
- pkg-manager/headless/test/utils/testDefaults.ts
- pkg-manager/package-requester/test/index.ts
- pnpm-lock.yaml
- store/package-store/test/index.ts
- store/server/test/index.ts
- store/store-connection-manager/src/createNewStoreController.ts
> fix: run prepublish scripts of packages installed from Git

- .changeset/chilly-flies-bow.md
- reviewing/license-scanner/src/licenses.ts
- reviewing/license-scanner/src/lockfileToLicenseNodeTree.ts
- reviewing/license-scanner/test/licenses.spec.ts
- reviewing/plugin-commands-licenses/src/outputRenderer.ts
- reviewing/plugin-commands-licenses/test/__snapshots__/index.ts.snap
- reviewing/plugin-commands-licenses/test/index.ts
Add the `description`-field to the output of the `licenses list`-command so that for each package the description in the package manifest gets listed too.
As this is a added field I don't think this should be a breaking change
> feat: add description field to output to licenses command output

- .changeset/red-planets-prove.md
- pnpm/src/pnpm.ts
Hi PNPM Team,
Thanks for the great tool!
I add the show alias to `pnpm view` according to [`npm view` docs](https://docs.npmjs.com/cli/v9/commands/npm-view) should support it like the below:
```sh
npm view [<package-spec>] [<field>[.subfield]...]
aliases: info, show, v
```
> feat(pnpm): add show alias to `pnpm view`

- .changeset/brave-coats-beam.md
- config/plugin-commands-config/src/ConfigCommandOptions.ts
- config/plugin-commands-config/src/config.ts
- config/plugin-commands-config/test/configSet.test.ts
> fix(config): the `--location=global` CLI option should work

- .changeset/spicy-panthers-agree.md
- config/config/src/index.ts
- pkg-manager/plugin-commands-installation/src/add.ts
- pkg-manager/plugin-commands-installation/test/add.ts
> fix: only the add command should fail if there is no bin directory in PATH

- .changeset/chilly-walls-melt.md
- reviewing/dependencies-hierarchy/src/DependenciesCache.ts
- reviewing/dependencies-hierarchy/src/getTree.ts
- reviewing/dependencies-hierarchy/test/getTree.test.ts
Fixes https://github.com/pnpm/pnpm/issues/4814.
I think this solution might be overly complex. If maintainers feel we should abandon caching, I can close this PR and put up an alternative that simply removes the (incorrect) cache.
Since the cache cannot be reused at different depth levels, there's an expected performance regression with this change.
For rudimentary benchmarking, I ran `pnpm list --depth=3` on the root of the pnpm repo. I'm using node `v19.3.0` on a Apple M1 device.
**This PR**:
```
❯ hyperfine --warmup 2 --runs 50 "node $pnpm list --depth=3"
Benchmark 1: node $HOME/pnpm/pnpm/lib/pnpm.js list --depth=3
Time (mean ± σ):     691.0 ms ±   8.0 ms    [User: 824.3 ms, System: 175.6 ms]
Range (min … max):   676.4 ms … 711.8 ms    50 runs
```
**Commit …
> fix(dependencies-hierarchy): account for depth in getTree cache

- reviewing/dependencies-hierarchy/src/buildDependenciesHierarchy.ts
- reviewing/dependencies-hierarchy/src/getTree.ts
- reviewing/dependencies-hierarchy/test/getTree.test.ts
Implementing the thought at https://github.com/pnpm/pnpm/pull/5817#discussion_r1054879549. No change log added since this shouldn't change program behavior.
> The separate `maxDepth` and `currentDepth` options may make the recursion here harder to reason about. Instead of passing `currentDepth + 1` on each recursive call, how do we feel about passing `maxDepth - 1`? That removes an extra option here and simplifies the math a bit.
Notes for reviewers:
- I personally think this is a bit simpler, but happy to close if maintainers disagree.
- Although the PR is small, reviewing commit by commit should still be easier.
> refactor(dependencies-hierarchy): simplify max depth recursion

- reviewing/dependencies-hierarchy/src/DependenciesCache.ts
- reviewing/dependencies-hierarchy/src/getTree.ts
- reviewing/dependencies-hierarchy/test/getTree.test.ts
I noticed when running `pnpm list --depth=3` on the `pnpm` package itself that the `node-gyp` optional dependency printed `wrappy` one level too deep.
```sh
❯ cd pnpm
❯ node $pnpm list --depth=3
optionalDependencies:
node-gyp 9.3.1
├── env-paths 2.2.1
├─┬ glob 7.2.3
│ ├── fs.realpath 1.0.0
│ ├─┬ inflight 1.0.6
│ │ ├── once 1.4.0
│ │ └── wrappy 1.0.2
│ ├── inherits 2.0.4
│ ├─┬ minimatch 3.1.2
│ │ └── brace-expansion 1.1.11
│ ├─┬ once 1.4.0
│ │ └── wrappy 1.0.2
│ └── path-is-absolute 1.0.1
├── graceful-fs 4.2.10
├─┬ make-fetch-happen 10.2.1
│ ├─┬ agentkeepalive 4.2.1
│ │ ├── debug 4.3.4
│ │ ├── depd 1.1.2
│ │ └── humanize-ms 1.2.1
│ ├─┬ cacache 16.1.3
│ │ ├── @npmcli/fs 2.1.2
│ │ ├── @npmcli/move-file 2.0.1
│ │ ├── chownr 2.0.0
│ │ ├── fs-minipass 2.1.0
│ │ ├── glob 8.0.3
│ │ ├── …
```
> fix(dependencies-hierarchy): fix a few cases where max depth could be exceeded

- .changeset/silly-ties-arrive.md
- exec/plugin-commands-script-runners/src/exec.ts
- exec/plugin-commands-script-runners/src/run.ts
- exec/plugin-commands-script-runners/src/runRecursive.ts
- exec/plugin-commands-script-runners/test/exec.e2e.ts
- exec/plugin-commands-script-runners/test/runRecursive.ts
close #4690
Implement `--resume-from` for `pnpm exec` command.
Not sure if `pnpm run` command also need this option, I personally think it is also quite useful, if it is okay, I can also update to support it :)
> feat(plugin-commands-script-runners): support --resume-from for pnpm exec command

- .changeset/hip-beers-smile.md
- exec/prepare-package/src/index.ts
- exec/prepare-package/test/__fixtures__/has-prepublish-script-and-main-file/package.json
- exec/prepare-package/test/index.ts
- jest.config.js
> fix: only build git-hosted dependency if it has no main file

- .changeset/giant-wasps-wink.md
- .changeset/good-monkeys-explode.md
- __fixtures__/workspace-with-nested-workspace-deps/package.json
- __fixtures__/workspace-with-nested-workspace-deps/packages/a/package.json
- __fixtures__/workspace-with-nested-workspace-deps/packages/b/package.json
- __fixtures__/workspace-with-nested-workspace-deps/packages/c/package.json
- __fixtures__/workspace-with-nested-workspace-deps/pnpm-lock.yaml
- __fixtures__/workspace-with-nested-workspace-deps/pnpm-workspace.yaml
- reviewing/dependencies-hierarchy/src/DependenciesCache.ts
- reviewing/dependencies-hierarchy/src/TreeNodeId.ts
- reviewing/dependencies-hierarchy/src/buildDependenciesHierarchy.ts
- reviewing/dependencies-hierarchy/src/getPkgInfo.ts
- reviewing/dependencies-hierarchy/src/getTree.ts
- reviewing/dependencies-hierarchy/src/getTreeNodeChildId.ts
- reviewing/dependencies-hierarchy/test/getTree.test.ts
- reviewing/dependencies-hierarchy/test/index.ts
- reviewing/list/src/index.ts
- reviewing/list/test/index.ts
- reviewing/plugin-commands-listing/src/list.ts
This pull request implements the feature request described at https://github.com/pnpm/pnpm/issues/4154. The `pnpm why` and `pnpm list` commands are now aware of dependencies from transitive workspace dependencies.
One cool aspect of this change is that `pnpm why` previously returned no output for packages depended on transitively from a `workspace:` linked package.
With the changes in this PR, `pnpm why` becomes much smarter.
1. Is this a breaking change? Users parsing `pnpm why --json <name>` or `pnpm list --json <name>` might be surprised by the additional output. We can gate this behavior behind a command line flag until the next major pnpm version if so.
1. Do we want a `--no-projects` filter regardless of whether this is a breaking change?
1. Do we want a `--only-projects` flag? That …
> feat: traverse through workspace packages in `why` and `list` commands

- .changeset/giant-cups-fold.md
- pnpm/src/cmd/recursive.ts
> fix: display --include-workspace-root option on recursive command's help info

- .changeset/clean-seals-boil.md
- config/config/src/Config.ts
- config/config/src/index.ts
- pkg-manager/core/src/install/extendInstallOptions.ts
- pkg-manager/core/src/install/index.ts
- pkg-manager/core/test/install/peerDependencies.ts
- pkg-manager/plugin-commands-installation/src/installDeps.ts
- pkg-manager/plugin-commands-installation/src/recursive.ts
- pkg-manager/resolve-dependencies/src/index.ts
- pkg-manager/resolve-dependencies/src/resolveDependencyTree.ts
- pkg-manager/resolve-dependencies/src/resolvePeers.ts
- pnpm/test/monorepo/index.ts
partially reverts https://github.com/pnpm/pnpm/pull/4469
> feat: resolve peer dependencies from workspace root

- .changeset/chatty-jars-speak.md
- .changeset/plenty-ravens-sell.md
- exec/plugin-commands-script-runners/src/exec.ts
- exec/plugin-commands-script-runners/src/makeEnv.ts
- exec/plugin-commands-script-runners/test/exec.e2e.ts
- exec/plugin-commands-script-runners/test/makeEnv.test.ts
close #5846 
For the following project:
```
// test/test_pnpm:colon/package.json
{
"name": "test-pnpm-example",
"version": "1.0.0",
"scripts": {
"test": "cowsay 'hi'"
},
"cowsay": "^1.5.0"
}
}
```
After run `pd install` ,  `pd exec cowsay hi  ` or  `pd cowsay hi` will executed successfully.
However, currently, running the test script in package.json(`pd test`) still reports an command not found error. It seems to be consistent with the behavior of yarn classic.
If we want to support `pd test` in this case , we may need to change `@pnpm/npm-lifecycle`?
> fix(plugin-commands-script-runners): support directory with path delimiter when running local bin

- .changeset/hip-schools-yawn.md
- .changeset/kind-squids-sleep.md
- pkg-manager/core/test/install/lifecycleScripts.ts
- pkg-manager/headless/src/lockfileToHoistedDepGraph.ts
- pkg-manager/package-requester/src/packageRequester.ts
- store/package-store/src/storeController/index.ts
- store/server/src/connectStoreController.ts
- store/store-controller-types/src/index.ts
This fixes a bug introduced by #5814
сlose #5823
> fix: side effects upload when node-linker is set to hoisted

- .changeset/rare-spoons-play.md
- pkg-manager/core/test/hoistedNodeLinker/install.ts
- pkg-manager/headless/src/lockfileToHoistedDepGraph.ts
> fix: re-add manually removed packages to node_modules when `node-linker` is set to `hoisted`

- .changeset/rotten-squids-cry.md
- pkg-manager/link-bins/src/index.ts
- pkg-manager/link-bins/test/index.ts
fix #5945 
The reason for this problem is that `supabase` creates a binfile during postinstall, and before that `linkBin` will encounter the problem that the file cannot be found.
> fix: catch error when binfile is not exisit

- .github/workflows/release.yml
This action automatically generates manifests for the Winget Community Repository ([microsoft/winget-pkgs](https://github.com/microsoft/winget-pkgs)).
pnpm is in Winget (https://github.com/pnpm/pnpm/issues/3112#issuecomment-1285403232) but is outdated because updates are being manually pushed to winget-pkgs for each new version. Winget Releaser should solve this problem.
**Before merging this:**
1. Add a PAT with `public_repo` scope as a repository secret named `WINGET_TOKEN`.
2. Fork https://github.com/microsoft/winget-pkgs under @pnpm. The action will use that fork for making a branch and creating a PR with the upstream [winget-pkgs](https://github.com/microsoft/winget-pkgs) repository on every release.
3. Install [Pull](https://github.com/apps/pull) on the winget-pkgs fork to ensure …
> ci: add Winget Releaser workflow

- .changeset/tasty-coins-join.md
- pkg-manager/core/src/install/index.ts
- pkg-manager/plugin-commands-installation/test/update/update.ts
- pkg-manager/resolve-dependencies/src/index.ts
- pkg-manager/resolve-dependencies/src/updateProjectManifest.ts
As discussed in https://github.com/pnpm/pnpm/pull/5720#issuecomment-1366816792
given a example project like following:
```
//package.json
"ava": "latest"
}
```
After run `pnpm up` , currently we will get `ava: "^5.1.1"`. We should behave the same as before, keeping `latest` here.
> fix: update without specify --latest should not update tag version

- .github/workflows/update-latest.yml
You will have to put the inputs to Winget Releaser manually if you are going to do a workflow dispatch. Please try triggering the workflow again after merging.
> ci: set workflow dispatch inputs to Winget Releaser

- .changeset/hip-lamps-attend.md
- __utils__/prepare/src/index.ts
- pkg-manager/core/test/install/local.ts
- pkg-manifest/exportable-manifest/package.json
- pkg-manifest/exportable-manifest/src/index.ts
- pkg-manifest/exportable-manifest/test/index.test.ts
- pkg-manifest/exportable-manifest/tsconfig.json
- pnpm-lock.yaml
- pnpm/test/monorepo/index.ts
- pnpm/test/recursive/misc.ts
Without this patch `workspace:@foo/bar@*` is replaced by `npm:@foo/bar@*` on publish, i.e. the `*` is not replaced by the actual version number from `@foo/bar`'s `package.json`.
> fix: replace version number for namespaced workspace packages

- .changeset/happy-dolphins-wave.md
- pnpm/src/cmd/help.ts
Add the `store path` command to the help of the CLI (`pnpm --help`).
```
...
Manage your store:
store add            Adds new packages to the pnpm store directly. Does not modify any projects or files outside the store
store prune          Removes unreferenced (extraneous, orphan) packages from the store
store status         Checks for modified packages in the store
...
```
```
...
Manage your store:
store add            Adds new packages to the pnpm store directly. Does not modify any projects or files outside the store
store path           Prints the path to the active store directory
store prune          Removes unreferenced (extraneous, orphan) packages from the store
store status         Checks for modified packages in the store
...
```
> docs: add `store path` description to cli help

- pkg-manager/core/src/install/index.ts
Putting up a minor PR to address something that confused me as I was reading through pnpm source code.
I think there's a typo in the name of the internal `lockfileIsUpToDate` function in the `core` package. It checks if the lockfile is _not_ up to date.
https://github.com/pnpm/pnpm/blob/977caa7d7c9fb5809aa8b57270d03ead8f1e0175/pkg-manager/core/src/install/index.ts#L588-L607
The usage of this function seems to match the idea that it currently checks if the lock file is not up to date. The `needsFullResolution` variable should be `true` when `!maybeOpts.ignorePackageManifest && lockfileNotIsUpToDate(...)`
https://github.com/pnpm/pnpm/blob/977caa7d7c9fb5809aa8b57270d03ead8f1e0175/pkg-manager/core/src/install/index.ts#L288-L297
> refactor(core): rename lockfileIsUpToDate to lockfileIsNotUpToDate

- .changeset/lazy-brooms-search.md
- pkg-manager/resolve-dependencies/src/resolveDependencies.ts
Fixes https://github.com/pnpm/pnpm/issues/5106
A repro was provided where the `/cacache/12.0.4` dependency in a lockfile kept changing its `promise-inflight` resolution between `1.0.1` and `1.0.1_bluebird@3.7.2`.
```diff
/cacache/12.0.4:
resolution: {integrity: sha512-a0tMB40oefvuInr4Cwb3GerbL9xTj1D5yg0T5xrjGCGyfvbxseIXX7BAO/u/hIXdafzOI5JC3wDwHyf24buOAQ==}
dependencies:
bluebird: 3.7.2
chownr: 1.1.4
figgy-pudding: 3.5.2
glob: 7.2.3
graceful-fs: 4.2.9
infer-owner: 1.0.4
lru-cache: 5.1.1
mississippi: 3.0.0
mkdirp: 0.5.5
move-concurrently: 1.0.1
-      promise-inflight: 1.0.1_bluebird@3.7.2
+      promise-inflight: 1.0.1
rimraf: 2.7.1
ssri: 6.0.2
unique-filename: 1.1.1
y18n: 4.0.3
dev: true
```
Here's the definition of `promise-inflight` elsewhere in the lockfile.
```yaml …
```
> fix: check for peerDependenciesMeta in pkgIsLeaf to fix installation non-determinism

- .changeset/gentle-spies-develop.md
- patching/plugin-commands-patching/package.json
- patching/plugin-commands-patching/src/patchCommit.ts
- patching/plugin-commands-patching/test/patch.test.ts
- patching/plugin-commands-patching/tsconfig.json
- pnpm-lock.yaml
- pnpm/src/main.ts
close #6048 
Many thanks to @shawnmcknight‘s research work.
Steps to reproduce: 
1. create a project as following:
```
// pnpm-workspace.yaml
packages:
- packages/*
// package.json
{
"name": "pnpm-patch",
"version": "1.0.0",
}
// packages/a/package.json
{
"name": "@pkg/a",
"version": "1.0.0",
"express": "4.18.2"
}
}
```
2. run `pnpm install` in project root directory.
3. run `pnpm patch express@4.18.2` and then edit `index.js` in temp dir:
4. run `pnpm patch-commit <temp-dir>`
We can see `patches/express@4.18.2` is generated successfully and `pnpm.patchedDependencies` also added in root package.json:
```
diff --git a/index.js b/index.js
index d219b0c878dc6136eb2096cffa140bf6bf2b8e9c..479633ae78ed075057d974ea56f7ab2f43d3a90e 100644
--- a/index.js
+++ b/index.js
@@ -7,5 …
```
> fix: patch-commit should auto apply patches in workspaces

- .changeset/large-turkeys-hope.md
- config/parse-overrides/src/index.ts
- config/parse-overrides/test/index.ts
- hooks/read-package-hook/package.json
- hooks/read-package-hook/src/createPeerDependencyPatcher.ts
- hooks/read-package-hook/src/createVersionsOverrider.ts
- hooks/read-package-hook/src/index.ts
- hooks/read-package-hook/src/isSubRange.ts
- hooks/read-package-hook/test/createPeerDependencyPatcher.test.ts
- hooks/read-package-hook/test/createVersionOverrider.test.ts
- hooks/read-package-hook/tsconfig.json
- pnpm-lock.yaml
This feature gives people the ability to override peerDependencies at an individual package level.
> feat: add `parent>child` selector syntax to allowedVersions for peer dependency override capability

- .changeset/cuddly-ducks-lay.md
- cli/cli-utils/src/recursiveSummary.ts
- exec/plugin-commands-script-runners/src/runRecursive.ts
- exec/plugin-commands-script-runners/test/runRecursive.ts
As discussed in https://github.com/pnpm/pnpm/pull/6098#issuecomment-1445258329, add a `skipped` status when script is missing.
> fix: add report summary skipped status when script is missing

- .changeset/unlucky-avocados-unite.md
- hooks/read-package-hook/src/createPeerDependencyPatcher.ts
- hooks/read-package-hook/test/createPeerDependencyPatcher.test.ts
This fixes a corner case that was missed in the original implementation, which is when the `allowedVersions` option only contains `parent>child` selectors.
If anyone needs a temporary work around while waiting for this to make it into a release, they can circumvent the issue by defining a "bogus" `child` selector in conjunction with the `parent>child` selector(s).
```js
"allowedVersions": {
"react": "0", // any version number lower than or equal to the defined peerDependencies
"pkg-a>react": "18"
}
```
> fix: allowedVersions corner case when only parent>child selectors exist

- .changeset/flat-bees-fail.md
- reviewing/license-scanner/src/getPkgInfo.ts
- reviewing/plugin-commands-licenses/test/__snapshots__/index.ts.snap
- reviewing/plugin-commands-licenses/test/fixtures/with-file-protocol/package.json
- reviewing/plugin-commands-licenses/test/fixtures/with-file-protocol/pnpm-lock.yaml
- reviewing/plugin-commands-licenses/test/fixtures/with-file-protocol/sub-dep/package.json
- reviewing/plugin-commands-licenses/test/index.ts
fix #6115 
For single project, given a package.json like following:
```
{
"safe-execa": "^0.1.3",
"test-dep": "file:./test-dep"
}
}
```
After run `pnpm licenses ls`, it will throw an error:
```
 ERR_PNPM_UNSUPPORTED_PACKAGE_TYPE  Unsupported package resolution type for file:test-dep
```
For package `foo` in workspaces, this error is also reported if `dependencyMeta.foo.inject` is set to `true`
> fix: should not throw an error when local dependency use file protocol

- .changeset/violet-insects-attack.md
- pkg-manager/resolve-dependencies/src/index.ts
> fix: incorrect error block when subproject has been patched (#6183)

- .changeset/itchy-onions-battle.md
- __fixtures__/multiple-scripts-error-exit/dev-bar.js
- __fixtures__/multiple-scripts-error-exit/dev-foo.js
- __fixtures__/multiple-scripts-error-exit/package.json
- __fixtures__/multiple-scripts-error-exit/process-foo.js
- pnpm-lock.yaml
- pnpm/package.json
- pnpm/src/errorHandler.ts
- pnpm/src/pnpm.ts
- pnpm/test/errorHandler.test.ts
- pnpm/test/utils/execPnpm.ts
- pnpm/test/utils/isPortInUse.ts
close #6162 
When run multiple scripts at the same time, if one of them throw an error, the pnpm process exited, but the other script child processes may still be running.
Steps to reproduce:
1. `git clone git@github.com:await-ovo/pnpm-run-multiple-scripts-processes-exit-issues.git`
2. `cd pnpm-run-multiple-scripts-processes-exit-issues`
3. `pnpm run "/^dev:.*/"`
You can see that the node and web servers start on port `9999` and `9990` separately, and after waiting for 1 second, the node server throws an exception, then pnpm run process is exited.
But if you run `lsof -i:9990`, you can see that web server process doesn't exited:
```
$ lsof -i:9990    
COMMAND   PID         USER   FD   TYPE             DEVICE SIZE/OFF NODE NAME
node    98962 username  22u  IPv6 0x9fd9ab4f570298fd      0t0 …
```
> fix:  clean up child processes when process exited

- .changeset/loud-geese-obey.md
- lockfile/lockfile-file/src/sortLockfileKeys.ts
- lockfile/lockfile-file/test/sortLockfileKeys.test.ts
We've been seeing seemingly-random reordering of `patchedDependencies` in the lockfile as different people regenerate it at different times. Sorting in a consistent order should prevent that from happening.
> fix: sort patchedDependencies consistently in lockfiles

- .changeset/khaki-icons-rest.md
- .gitignore
- lockfile/audit/src/index.ts
- patching/plugin-commands-patching/package.json
- patching/plugin-commands-patching/src/getPatchedDependency.ts
- patching/plugin-commands-patching/src/patch.ts
- patching/plugin-commands-patching/src/patchCommit.ts
- patching/plugin-commands-patching/src/writePackage.ts
- patching/plugin-commands-patching/test/patch.test.ts
- patching/plugin-commands-patching/tsconfig.json
- pnpm-lock.yaml
- pnpm/src/main.ts
- reviewing/list/src/index.ts
close #6192 
The following changes were added:
1. Throws a meaningful error when `pnpm patch` does not specify a package:
```
$ pd patch        
 ERR_PNPM_MISSING_PACKAGE_NAME  `pnpm patch` requires the package name
```
2. If the locally installed version is `foo@1.0.0`, running `pnpm patch foo@2` will display a warning message:
```
$ pd patch foo@2  
 WARN  Can not find foo@2 in project /project-dir
```
3.  If no version is specified(`pnpm patch foo`) and there is only one version of `foo` installed locally, then the locally installed version is used directly.
4. If no version is specified(`pnpm patch foo`) and there are multiple versions of foo installed locally, the user will need to manually select which version of foo to patch:
```
$ pd why chalk
Legend: production dependency, …
```
> feat: when patch package does not specify a version, use locally installed version by default.

- .changeset/seven-humans-cover.md
- config/config/src/index.ts
> fix: don't extend NODE_PATH in command shims

- .changeset/rotten-students-agree.md
- config/config/src/dirs.ts
- config/config/src/index.ts
- config/config/test/dirs.test.ts
Code was added on Oct 29, 2022 that prioritizes the environment variable `PNPM_HOME` for use setting the home / store-dir / data-dir: https://github.com/pnpm/pnpm/pull/5566
This refactor does not change any logic. It simply moves the PNPM_HOME option onto the top of list of other options in the function where the data-dir is defined: `getDataDir`. This is the only place in the code where `getDataDir` is used aside from tests.
This should make the code more readable and maintainable.
> refactor: move usage of PNPM_HOME into getDataDir

- .changeset/thick-zebras-promise.md
- lockfile/plugin-commands-audit/src/audit.ts
- lockfile/plugin-commands-audit/test/__snapshots__/index.ts.snap
> fix(plugin-commands-audit): only three paths are displayed in the audit output

- .changeset/khaki-spoons-decide.md
- resolving/git-resolver/src/parsePref.ts
- resolving/git-resolver/test/index.ts
5 years later I'm still pestering you with git+ssh+semver @zkochan :)
Currently pnpm fails to install `git+ssh://git@example.com:org/repo.git#semver:~1.2.3` (where example.com is an internal git server, not github.com) because it will end up looking for refspec `/~1.2.3` which doesn't match any git tag. We end up there both because of escaping the colon in `semver`, but also because we assume git+ssh URL cannot accept semver range spec.
Trying to install `https://example.com/org/repo.git#semver:~1.2.3` works as expected.
Looking through the code, we had quite a few patches to handle SCP-like urls, because we wanted to use `new URL`, and not the deprecated `url.parse`.
Yarn has this patch https://github.com/yarnpkg/yarn/blob/master/src/util/git.js#L103
but npm …
> handle git+ssh with semver

- .changeset/wild-dolphins-work.md
- __utils__/assert-project/package.json
- __utils__/assert-store/package.json
- exec/plugin-commands-rebuild/package.json
- exec/plugin-commands-script-runners/package.json
- package.json
- patching/plugin-commands-patching/package.json
- pkg-manager/core/package.json
- pkg-manager/core/test/install/peerDependencies.ts
- pkg-manager/headless/package.json
- pkg-manager/package-requester/package.json
- pkg-manager/plugin-commands-installation/package.json
- pkg-manager/resolve-dependencies/src/index.ts
- pkg-manager/resolve-dependencies/src/resolvePeers.ts
- pkg-manager/resolve-dependencies/test/resolvePeers.ts
- pnpm-lock.yaml
- pnpm/package.json
- releasing/plugin-commands-deploy/package.json
- releasing/plugin-commands-publishing/package.json
- reviewing/plugin-commands-licenses/package.json
- reviewing/plugin-commands-listing/package.json
- reviewing/plugin-commands-outdated/package.json
- store/plugin-commands-store/package.json
Background: #4301
My solution is:
- Use the manifest (package.json) to generate a map of NPM aliases.
- When resolving peers, we should check `ctx.parentPkgs[peerName]` and the packages in `npmAliases[peerName]`. Assume we combine the two sources to an array named `pkgsToCheck`.
- Check each item in `pkgsToCheck`, not only the original `ctx.parentPkgs[peerName]`.
- During checking, we use a temp var `badPeerIssues` to record the bad peer issues instead of the original `ctx.peerDependencyIssues.bad[peerName]`.
- If we found a version that satisfies the semver, we found the peer, no need to check more items.
- The result should be one of the following:
- When we found the peer, nothing bad happens.
- Else, if there are items in `badPeerIssues`, we add them to …
> feat: support resolving peers with npm aliases

- .changeset/beige-eggs-study.md
- pkg-manager/core/test/lockfile.ts
- pkg-manager/resolve-dependencies/src/updateLockfile.ts
- pkg-manager/resolve-dependencies/test/relativeTarball.test.ts
pnpm doesn't store the URLs to package tarballs, when the package tarball URL may be calculated automatically using the registry, package name and version.
For instance, if we know that the package is hosted in the `https://registry.npmjs.org` registry and the name of the package is `is-odd` and the version of the package is `1.0.0`, then we know that we can download the tarball from:
```
https://registry.npmjs.org/is-odd/-/is-odd-1.0.0.tgz
```
However, if the registry uses a different URL format for storing the tarballs, then we can't calculate it automatically and in this case we need to store that tarball URL in the lockfile. Currently, we don't store the whole URL in the lockfile, just the URL path. So, for instance, if the tarball was hosted at …
> fix!: save the whole tarball URL, when it doesn't use the standard format

- .changeset/few-wasps-enjoy.md
- hooks/read-package-hook/src/createVersionsOverrider.ts
- hooks/read-package-hook/test/createVersionOverrider.test.ts
> fix: should use the one with parent syntax when both override rules match the same target

- .changeset/green-scissors-battle.md
- workspace/pkgs-graph/src/index.ts
For #6277
One easy way to optimize this code is to avoid calling `Object.values` on `pkgMap` over and over again; this code does not modify `pkgMap` in any way, so we can just get it once at the top and then reuse it. This saves the bulk of the time on DefinitelyTyped, a monorepo with >9000 packages.
This function is still quadradic, as it scans all of `pkgMap` for every entry of `pkgMap`, but improving that will require a more complicated change, whereas this PR is very safe.
> perf(pkgs-graph): optimize createPkgGraph by calling Object.values only once

- .changeset/fifty-boats-drum.md
- pkg-manager/headless/src/index.ts
For #6277 (ish)
Like #6281, this calculation was happening quadradically, but we can just calculate this one time and reuse it.
> perf(headless): hoist importerManifestsByImporterId calculation

- .changeset/eighty-brooms-cover.md
- __utils__/assert-project/package.json
- __utils__/assert-store/package.json
- exec/plugin-commands-rebuild/package.json
- exec/plugin-commands-script-runners/package.json
- package.json
- patching/plugin-commands-patching/package.json
- pkg-manager/core/package.json
- pkg-manager/headless/package.json
- pkg-manager/package-requester/package.json
- pkg-manager/plugin-commands-installation/package.json
- pkg-manager/plugin-commands-installation/src/recursive.ts
- pnpm-lock.yaml
- pnpm/package.json
- pnpm/test/monorepo/dedupePeers.test.ts
- releasing/plugin-commands-deploy/package.json
- releasing/plugin-commands-publishing/package.json
- reviewing/plugin-commands-licenses/package.json
- reviewing/plugin-commands-listing/package.json
- reviewing/plugin-commands-outdated/package.json
- store/plugin-commands-store/package.json
> fix: `dedupe-peer-dependents` should not remove peer deps from workspace root

- __utils__/eslint-config/package.json
- pnpm-lock.yaml
Update `@typescript-eslint/eslint-plugin` and `@typescript-eslint/parser` to latest(v5.56.0) to avoid typescript version warnings when run compile:
```
WARNING: You are currently running a version of TypeScript which is not officially supported by @typescript-eslint/typescript-estree.
You may find that it works just fine, or you may not.
SUPPORTED TYPESCRIPT VERSIONS: >=3.3.1 <5.0.0
YOUR TYPESCRIPT VERSION: 5.0.2
```
> fix(deps): update @typescript-eslint/eslint-plugin and @typescript-eslint/parser

- .changeset/silver-cameras-count.md
- resolving/npm-resolver/src/pickPackage.ts
I was doing some memory profiling to understand why pnpm was OOMing on my laptop.
A heap snapshot showed that about 500 MB of the memory usage of pnpm is instances of Limiter (and the objects they reference) that can't be garbage collected because they're referenced by `metafileOperationLimits`.
To fix this, we can instead keep track of how many times each limiter is currently being used. Whenever the refcount hits zero, we can safely drop the object.
I measured the peak memory usage using `time` before and after. Before, we get:
```
Done in 2m 12.1s
$@   152.69s  user 41.42s system 146% cpu 2:12.51 total
max memory:                2237 MB
```
After, we have:
```
Done in 2m 9.9s
$@   139.49s  user 39.27s system 137% cpu 2:10.20 total
max memory:                1525 MB
```
Representing a …
> perf(npm-resolver): reduce max memory usage

- .changeset/twelve-gifts-rescue.md
- workspace/pkgs-graph/src/index.ts
This speeds up the install of "with paths" test case (https://github.com/jakebailey/DefinitelyTyped/tree/blog-pnpm-workspaces-with-paths) from 49.7s to 14s.
Time spent in `createPkgMap` has been reduced from ~35s to ~200ms, matching the performance in #6287.
Fixes #6281 (for real this time)
> perf(pkgs-graph): speed up createPkgGraph when directory specifiers are present

- .changeset/tender-ties-punch.md
- pkg-manager/core/src/install/index.ts
- pkg-manager/core/test/install/overrides.ts
- pkg-manager/core/test/install/packageExtensions.ts
The current error and hint messages for `FROZEN_LOCKFILE_WITH_OUTDATED_LOCKFILE` is not very straightforward in explaining what the issue is.
This PR attempt to fix this by being a bit more explicit as to what the required upgrade is (lockfile version incompatibility).
The original message was too confusing as per this post last year: https://github.com/orgs/pnpm/discussions/4847
> Make the `FROZEN_LOCKFILE_WITH_OUTDATED_LOCKFILE` error and hint messages more clear

- .changeset/forty-bears-smoke.md
- pkg-manager/core/src/install/hooks.ts
- pkg-manager/core/src/install/index.ts
- pnpm/test/install/hooks.ts
This PR makes sure that `registries` are passed to the `preResolution` hook as part of the `ctx`.
> feat(hooks): pass registries to preResolution hook

- .changeset/pretty-toys-agree.md
- resolving/npm-resolver/src/pickPackageFromMeta.ts
As noted in a recent twitter thread, a large fraction of the clean install of DT is just `semver.satisfies`:
We can work around this in two ways:
- Cache the Range objects.
- Make sure we pass in `SemVer` to `Range.test`, as that avoids re-parsing the same semver string over and over again.
After doing this, we get:
For a `git clean -fdx && pnpm install --offline`, this nets a significant time savings.
Before:
```
Done in 2m 38.7s
total time:  158.99s
user time:   188.91s
system time: 31.17s
CPU percent: 138%
max memory:  1686 MB
```
After:
```
Done in 2m 9s
total time:  129.24s
user time:   156.34s
system time: 32.13s
CPU percent: 145%
max memory:  1667 MB
```
It turns out that I independently figured out the same level of caching that yarn berry uses: …
> perf(npm-resolver): improve performance of semver.satisfies

- package.json
- pnpm-lock.yaml
While working in this repo, I noticed changes in `pnpm-lock.yaml` that weren't expected after adding a new dependency. To reproduce:
1. Check out `main` commit d86fce63e4b66b8f2ca9c53b2b63aadd1b847f47
2. Delete the `neverBuiltDependencies` dependencies block
3. Rerun `pnpm install`
4. Observe many transitive dependencies shifting `@types/jest` from `7.21.2` to `7.21.3`.
Both `7.21.2` and `7.21.3` are appearing in the lockfile because:
- The older `7.21.2` version is a direct dep of the workspace:
https://github.com/pnpm/pnpm/blob/d86fce63e4b66b8f2ca9c53b2b63aadd1b847f47/pnpm-lock.yaml#L44-L46
- The newer `7.21.3` version is required by `@babel/generator@7.21.3`.
https://github.com/pnpm/pnpm/blob/d86fce63e4b66b8f2ca9c53b2b63aadd1b847f47/pnpm-lock.yaml#L5969-L5973
It's a bit strange that …
> chore(deps): dedupe @types/jest@7.21.2 with 7.21.3

- .changeset/red-knives-decide.md
- cli/default-reporter/src/reportError.ts
- cli/default-reporter/test/index.ts
- pnpm/test/errorHandler.test.ts
As discussed in  https://github.com/pnpm/pnpm/pull/6190#issuecomment-1490570242, When executing `pnpm -r --no-bail run build`, if some packages report an error on build, we don't see the error summary at the moment, only the following message:
```
$ pnpm -r --no-bail run build
Cannot read properties of undefined (reading 'length')
```
> fix(default-reporter): should print error summary as expected

- .changeset/healthy-goats-tell.md
- .changeset/short-mirrors-exercise.md
- .changeset/wise-actors-fix.md
- lockfile/lockfile-file/src/experiments/inlineSpecifiersLockfileConverters.ts
- packages/dependency-path/src/index.ts
- packages/dependency-path/test/index.ts
> fix: installing local dep from directory that starts with @

- .changeset/little-badgers-sort.md
- config/plugin-commands-config/src/configGet.ts
- config/plugin-commands-config/test/configGet.test.ts
Due to [main](https://github.com/pnpm/pnpm/blob/main/pnpm/src/main.ts#L291~#L294), the boolean format cannot be printed by `pnpm config get <key>` now. Need to transform it into string format.
> fix: `pnpm config get <key>` returns empty when the value is a boolean

- .changeset/tender-birds-wave.md
- pkg-manager/core/test/lockfile.ts
- pkg-manager/get-context/src/index.ts
> fix: add -g to mismatch registries error info when original command has -g option

- .changeset/brave-radios-cough.md
- .changeset/tiny-camels-divide.md
- lockfile/lockfile-utils/src/satisfiesPackageManifest.ts
- lockfile/lockfile-utils/test/satisfiesPackageManifest.ts
- pkg-manager/core/src/install/allProjectsAreUpToDate.ts
- pkg-manager/core/src/install/extendInstallOptions.ts
- pkg-manager/core/src/install/index.ts
- pkg-manager/core/test/allProjectsAreUpToDate.test.ts
- pkg-manager/core/test/install/excludeLinksFromLockfile.ts
- pkg-manager/headless/src/index.ts
- pkg-manager/resolve-dependencies/src/index.ts
This is needed for when pnpm is used in Bit CLI via its API (related PR: https://github.com/teambit/bit/pull/7176). Bit adds some local dependencies to the project dynamically. And the locations of these local dependencies may differ on different machines. Hence, it doesn't make sense to add these dependencies to the lockfile.
Would this setting be useful to other users too? Would it make sense to make it `true` by default in a future version? Right now I did not make it configurable for the pnpm CLI. It seems like duplicating the local dependency specifiers to the lockfile is not required. The local dependency specifier is always resolved to the same location, so it is enough if it is only in `package.json`.
> feat: don't add linked in deps to the lockfile when `excludeLinksFromLockfile` is set to `true`

- .changeset/lovely-balloons-drive.md
- cli/default-reporter/src/index.ts
- cli/default-reporter/src/reporterForClient/index.ts
- cli/default-reporter/src/reporterForClient/reportSummary.ts
- cli/default-reporter/test/index.ts
In order to filter out packages from the installation summary, a filter function may be passed to the reporter: filterPkgsDiff.
This feature is only useful for Bit CLI currently. Related PR: https://github.com/teambit/bit/pull/7176
> feat(default-reporter): a new option added

- .changeset/swift-schools-poke.md
- cli/default-reporter/package.json
- config/package-is-installable/package.json
- env/node.resolver/package.json
- env/plugin-commands-env/package.json
- exec/plugin-commands-rebuild/package.json
- hooks/read-package-hook/package.json
- lockfile/lockfile-file/package.json
- lockfile/merge-lockfile-changes/package.json
- packages/dependency-path/package.json
- patching/plugin-commands-patching/package.json
- pkg-manager/core/package.json
- pkg-manager/package-requester/package.json
- pkg-manager/resolve-dependencies/package.json
- pnpm-lock.yaml
- pnpm/package.json
- resolving/git-resolver/package.json
- resolving/npm-resolver/package.json
- reviewing/list/package.json
- reviewing/outdated/package.json
- workspace/resolve-workspace-range/package.json
This picks up the performance improvements by @H4ad.
On DT using `git clean -fdx; pnpm install --offline`, before:
```
Done in 2m 15.1s
total time:  135.31s
user time:   162.02s
system time: 31.29s
CPU percent: 142%
max memory:  1797 MB
```
After:
```
Done in 1m 43.6s
total time:  103.89s
user time:   115.92s
system time: 30.47s
CPU percent: 140%
max memory:  1858 MB
```
~30% faster.
> perf: bump semver to 7.4.0

- .changeset/fuzzy-parents-juggle.md
- fs/hard-link-dir/package.json
- fs/hard-link-dir/src/index.ts
- fs/hard-link-dir/test/index.ts
- pnpm-lock.yaml
I was running into an issue where I have a workspace package (`@my-org/my-app`) that has a dependency on `@my-org/my-lib`. In turn, `my-lib` has a `dist` directory that is in the root of the monorepo (this is how nx sets things up). It uses `publishConfig.directory` and `publishConfig.linkDirectory`.
`package.json (my-app)`
```JSON
{
"@my-org/my-lib": "workspace:^"
},
"dependenciesMeta": {
"@my-org/my-lib": { "injected": true }
}
}
```
`package.json (my-lib)`
```JSON
{
"publishConfig": {
"directory": "../../dist/lib/my-lib",
"linkDirectory": true
}
}
```
There is an issue with pnpm where, given the above conditions, if you run `pnpm install` but `dist/lib/my-lib` does not exist, the process will fail with a ENOENT error.
This change request makes it so that the install …
> fix(hard-link-dir): prevent fatal error on ENOENT

- .changeset/fast-icons-retire.md
- .changeset/sixty-scissors-enjoy.md
- pkg-manager/plugin-commands-installation/src/dedupe.ts
- pkg-manager/plugin-commands-installation/src/install.ts
This PR supports `pnpm dedupe --check`. Splitting the change into multiple PRs to make it easier to review.
This allows the `dedupe` command handler to pass options to the `installDeps` function that aren't available on the pnpm install command line or config interface. (The next pull request adds a `lockfileCheck` option to the `installDeps` function.)
The new setup better matches the setup in the `add` and `update` command handlers, which also call `installDeps` directly.
https://github.com/pnpm/pnpm/blob/ee61ca4cb7ce6b3cb177f892940edb55b19b9e17/pkg-manager/plugin-commands-installation/src/add.ts#L207
The previous setup mimicked the `prune` command. Keeping the dedupe and install commands as similar as possible was the original goal of having the dedupe command reuse the install command …
> refactor: call installDeps directly in dedupe command handler 

- .changeset/fuzzy-spiders-begin.md
- pkg-manager/core/src/install/extendInstallOptions.ts
- pkg-manager/core/src/install/index.ts
- pkg-manager/plugin-commands-installation/src/installDeps.ts
This PR supports `pnpm dedupe --check`. Splitting the change into multiple PRs to make it easier to review.
- https://github.com/pnpm/pnpm/pull/6403
- https://github.com/pnpm/pnpm/pull/6404
- https://github.com/pnpm/pnpm/pull/6408
Adding a `lockfileCheck` option to `installDeps`. See the new JSDoc for details.
- This will be useful for `pnpm dedupe --check`.
- The `pnpm check-lockfile` command discussed in https://github.com/pnpm/pnpm/issues/6105#issuecomment-1437739132 would benefit from this too.
> feat: add internal lockfileCheck option for lockfile only diff installs

- .changeset/khaki-bats-learn.md
- config/config/src/Config.ts
- config/config/src/index.ts
- releasing/plugin-commands-publishing/src/pack.ts
- releasing/plugin-commands-publishing/src/publish.ts
- releasing/plugin-commands-publishing/test/pack.ts
This options allows specifying custom compression level.
Underlying node implementation enforces correct number ranges,
but silently ignores `NaN`, so we explicitly check that provided value is valid.
More information about this `level` option can be found in [node docs](https://nodejs.org/api/zlib.html#class-options) and [zlib specs](https://zlib.net/manual.html#Advanced).
Supported values are (`6` is default in node):
```c
// Compression levels.
#define Z_NO_COMPRESSION         0
#define Z_BEST_SPEED             1
#define Z_BEST_COMPRESSION       9
#define Z_DEFAULT_COMPRESSION  (-1)
```
I didn't add any test but I tested manually
that compressing with `-1`, `0` and `1` create an installable package.
Also tested manually that using `pnpm config set pack-gzip-level 0` and …
> feat(pack): add pack-gzip-level

- .changeset/modern-planes-cough.md
- packages/mount-modules/test/__fixtures__/simple/pnpm-lock.yaml
- releasing/plugin-commands-publishing/src/publish.ts
- releasing/plugin-commands-publishing/test/publish.ts
Fixes: https://github.com/pnpm/pnpm/issues/6435
I'm new to `pnpm`. Not sure I'm correct
> feat: support `publish --provenance`

- .changeset/little-waves-tease.md
- pnpm/dev/pd.js
"spnpmImportsPlugin" didn't work as expected because of the wrong path in line:27
[pnpm/dev/pd.js#L26-L30](https://github.com/pnpm/pnpm/blob/8db1b48095e06de55725be99a17e5424e6e75b02/pnpm/dev/pd.js#L26-L30)
localPackages are ["@pnpm/constants", "@pnpm/xxx", ...] but the pathPart is `constants` `xxx` etc
> fix: spnpmImportsPlugin not work as expectation in pd

- .changeset/hot-buttons-train.md
- pkg-manager/core/test/hoistedNodeLinker/install.ts
- pkg-manager/headless/src/index.ts
> fix: linking bins of local deps, when node-linker is hoisted

- .changeset/sixty-walls-sparkle.md
- __fixtures__/pnpm-workspace.yaml
- patching/plugin-commands-patching/test/patch.test.ts
- pkg-manager/core/test/breakingChanges.ts
- pkg-manager/core/test/install/only.ts
- pkg-manager/core/test/lockfile.ts
- pkg-manager/get-context/package.json
- pkg-manager/get-context/src/index.ts
- pnpm-lock.yaml
- reviewing/plugin-commands-licenses/package.json
- reviewing/plugin-commands-licenses/test/index.ts
- reviewing/plugin-commands-licenses/tsconfig.json
I frequently run `pnpm install` on a Bit workspace and it removes my node_modules. Then I need to wait for minutes to reinstall everything from scratch with `bit install`. This change will ask for permission before pnpm removes `node_modules`. `pnpm install --force` will do it without the prompt.
> fix: only remove node_modules if the user confirms to do so

- pkg-manager/plugin-commands-installation/src/fetch.ts
Since `pnpm i` have short alias for `--production` and `--develop`, `pnpm fetch` should also have them too
> feat(pnpm fetch): add shortAlias -D and -P

- .changeset/dirty-comics-press.md
- .changeset/selfish-dingos-confess.md
- .changeset/wild-radios-drum.md
- pkg-manager/core/src/install/index.ts
- pkg-manager/core/src/install/link.ts
- pkg-manager/core/test/hoistedNodeLinker/install.ts
- pkg-manager/core/test/install/injectLocalPackages.ts
- pkg-manager/core/test/install/multipleImporters.ts
- pkg-manager/core/test/install/optionalDependencies.ts
- pkg-manager/core/test/install/stats.ts
- pkg-manager/direct-dep-linker/src/linkDirectDeps.ts
- pkg-manager/headless/src/index.ts
- pkg-manager/plugin-commands-installation/src/recursive.ts
The `stats` object is useful for detecting if there were changes done to the `node_modules` during installation.
> feat: the installation API should return installation stats

- .changeset/smooth-hounds-smell.md
- config/config/package.json
- pnpm-lock.yaml
- releasing/plugin-commands-publishing/src/publish.ts
Fix #6384 
Also add override `"yaml@<2.2.2": ">=2.2.2"` to `package.json` to fix audit vulnerabilities.
> fix: publish unknown otp option

- config/package-is-installable/.changeset/smooth-hotels-clean.md
- config/package-is-installable/src/checkEngine.ts
- config/package-is-installable/src/getSystemNodeVersion.ts
- config/package-is-installable/test/checkEngine.ts
- config/package-is-installable/test/getSystemNodeVersion.test.ts
refer to https://github.com/npm/cli/blob/bdab631b9847013dc4e8d4083669acf6c7bfb457/lib/cli.js#L16
> fix: special version node check

- .changeset/angry-bobcats-develop.md
- pkg-manager/plugin-commands-installation/src/link.ts
- pkg-manager/plugin-commands-installation/test/link.ts
> fix(link): don't update version specs in package.json

- patching/plugin-commands-patching/src/index.ts
- patching/plugin-commands-patching/src/patchRemove.ts
- patching/plugin-commands-patching/test/patch.test.ts
- pnpm/src/cmd/index.ts
- pnpm/src/main.ts
close #6119 
add `pnpm patch-remove` command to remove  patches.
> feat(plugin-commands-patching): add patch-remove command

- .changeset/tasty-kiwis-change.md
- config/config/package.json
- config/config/src/index.ts
- pnpm-lock.yaml
> fix: normalize cwd on Windows

- package.json
I've moved my local default to Node 20 and am now hitting the case where the pnpm version set by corepack is really really old (which then hits the `this` errors); this bumps it to the latest.
Not sure if I should also bump the `engines` too, though. Probably yes?
> chore: update root corepack packageManager field for Node 20 support

- .changeset/ninety-eels-begin.md
- .changeset/rotten-rivers-ring.md
- lockfile/lockfile-utils/src/satisfiesPackageManifest.ts
- lockfile/lockfile-utils/test/satisfiesPackageManifest.ts
- pkg-manager/core/src/install/allProjectsAreUpToDate.ts
- pkg-manager/headless/src/index.ts
> fix: print more info when lockfile is outdated

- .changeset/pink-tips-rule.md
- __typings__/local.d.ts
- cli/cli-utils/src/readProjectManifest.ts
- exec/plugin-commands-script-runners/package.json
- exec/plugin-commands-script-runners/src/buildCommandNotFoundHint.ts
- exec/plugin-commands-script-runners/src/exec.ts
- exec/plugin-commands-script-runners/src/run.ts
- exec/plugin-commands-script-runners/test/exec.e2e.ts
- exec/plugin-commands-script-runners/test/index.ts
- pkg-manager/plugin-commands-installation/package.json
- pkg-manager/plugin-commands-installation/src/nodeExecPath.ts
- pnpm-lock.yaml
Fixes #6492
For both the `exec` and `run` commands, adds a `hint` property based on a new `buildCommandNotFoundHint` utility.
Reuses the [`didyoumean2`](https://npmjs.com/package/didyoumean2) package already used elsewhere in pnpm (and, fun fact, npm & yarn!).
Co-authored-by: Zoltan Kochan <z@kochan.io>
> feat: expanded missing command error, including 'did you mean'

- .changeset/kind-windows-reflect.md
- exec/plugin-commands-rebuild/src/implementation/index.ts
When using node-linker=hoisted the MISSING_HOISTED_LOCATIONS error (added by https://github.com/pnpm/pnpm/pull/5819) is thrown if an optional dependency is missing in the hoisted locations in `node_modules/.modules.yaml`.
This makes it impossible to have a successful install.
See https://github.com/pnpm/pnpm/issues/6092 which was similar but for skipped dependencies.
> do not throw MISSING_HOISTED_LOCATIONS for optional packages

- .changeset/twelve-ears-thank.md
- exec/lifecycle/src/runLifecycleHooksConcurrently.ts
when I use pnpm with workspace, I found that the execution order of lifecycle script is wrong. When the maximum value of buildIndex is greater than `10`, this problem will be caused. The reason is that when sorting buildIndex, because the type of buildIndex is number, no compare function is added, resulting in disordered order after sorting.
In the figure below, the following one is expected
> fix: lifecycle buildindex sort

- .changeset/gentle-lies-play.md
- pkg-manager/resolve-dependencies/src/resolvePeers.ts
- pkg-manager/resolve-dependencies/test/dedupeDepPaths.test.ts
resolves: #6605
When dedupe-peer-dependents is enabled (default), use the path (not id) to
determine compatibility.
When multiple dependency groups can be deduplicated, the
latter ones are sorted according to number of peers to allow them to
benefit from deduplication.
> fix(resolvePeers): fix deduplication when version missmatch

- .github/workflows/update-latest.yml
Winget Releaser now supports all runners. I think the workflow would be slightly faster if it's not using the Windows runner; I would like to test that here 😅.
> ci: change winget job runner to `ubuntu-latest`

- .changeset/blue-numbers-rest.md
- patching/plugin-commands-patching/package.json
- patching/plugin-commands-patching/src/patchCommit.ts
- patching/plugin-commands-patching/test/patch.test.ts
- pnpm-lock.yaml
This PR adds a feature to ignore files/folders specified in `rootProjectManifest.pnpm.ignorePatchedCommitDependencies`. If this configuration property exists, the corresponding files/folders in the `rootProjectManifest.pnpm.ignorePatchedCommitDependencies[pkgNameAndVersion]` array will be ignored during the patching commit process. 
close #6565
> fix: `pnpm patch` should ignore files that are not included in the patched package

- .changeset/grumpy-falcons-flow.md
- lockfile/lockfile-utils/src/index.ts
- lockfile/lockfile-utils/src/refIsLocalTarball.ts
- pkg-manager/core/package.json
- pkg-manager/core/src/install/allProjectsAreUpToDate.ts
- pkg-manager/core/src/install/index.ts
- pkg-manager/core/src/install/link.ts
- pkg-manager/core/test/allProjectsAreUpToDate.test.ts
- pkg-manager/core/test/install/local.ts
- pkg-manager/headless/src/lockfileToDepGraph.ts
fix #5381, #6502 
Let's say we have a project like the following:
```
// pkg-foo/package.json
{
"name": "pkg-foo",
"local-file": "file:../local-file"
}
}
// local-file/package.json
{
"name": "local-file",
"version": "1.0.0",
"is-positive": "2.0.0" 
}
}
```
The comparison between this PR and the current pnpm install or update is as follows:
* Before
|  | add new file  to  local-file directory | change is-positive to 3.0.0 |
| --- | --- | --- |
| pnpm update | Not synced | synced |
| pnpm update —latest | Not synced | Synced |
| pnpm update local-file | Not synced | synced |
| pnpm install | Not synced | Not synced |
* After this PR
|  | add new file  to  local-file directory | change is-positive to 3.0.0 |
| --- | --- | --- |
| pnpm update | Synced | …
> fix:  should always treat local file dependency as new dependency 

- .changeset/breezy-bats-double.md
- cli/default-reporter/package.json
- cli/default-reporter/src/reporterForClient/reportLifecycleScripts.ts
- pnpm-lock.yaml
Reflecting [my comment](https://github.com/pnpm/pnpm/issues/2148#issuecomment-1096687280) in #2148, I've replaced the use of `strip-ansi` before truncating a line (which removed all colour codes in script output) with `cli-truncate` which is aware of ANSI escape codes.
> fix(2148): don't remove ANSI colour codes from script output

- .github/workflows/ci.yml
Somehow, certain workflows can take over 6 hours to complete, probably due to an infinite execution. I think that 1 hour is a reasonable limit for CI jobs, and it will allow to quickly react to rogue CI runs
Source: https://github.com/pnpm/pnpm/actions/runs/5267002956/jobs/9521690045?pr=6674
> chore: introduce 1-hour timeout for CI

- .github/workflows/ci.yml
This uses the native [`concurrency` property](https://docs.github.com/en/actions/using-jobs/using-concurrency) of GitHub Actions jobs to cancel runs on previous commits when there exists a newer commit. It will help with not getting redundant fail alerts as well as to save CI minutes
> chore: cancel previous CI runs

- .changeset/quiet-moons-sparkle.md
- pkg-manager/core/test/hoistedNodeLinker/install.ts
- pkg-manager/headless/src/lockfileToDepGraph.ts
- pkg-manager/headless/src/lockfileToHoistedDepGraph.ts
- pkg-manager/real-hoist/src/index.ts
PeerDependencies should be installed when `autoInstallPeers` is set to true and `nodeLinker` is set to `hoisted`.
> node-linker=hoisted support autoinstallpeers

- .changeset/wet-laws-retire.md
- reviewing/license-scanner/src/getPkgInfo.ts
- reviewing/plugin-commands-licenses/test/fixtures/with-git-protocol-patched-deps/package.json
- reviewing/plugin-commands-licenses/test/fixtures/with-git-protocol-patched-deps/patches/is-positive@3.1.0.patch
- reviewing/plugin-commands-licenses/test/fixtures/with-git-protocol-peer-deps/package.json
- reviewing/plugin-commands-licenses/test/index.ts
> fix: license ls should work even when there is a patched git protocol dependency

- .changeset/stupid-pets-melt.md
- pkg-manager/core/test/install/injectLocalPackages.ts
- pkg-manager/core/test/install/local.ts
- pkg-manager/resolve-dependencies/src/updateLockfile.ts
There is no need to include the version of a dependency in the lockfile,
if that dependency is installed from a local directory
> fix: don't include the version for local directory dependencies

- .changeset/plenty-bags-fix.md
- exec/lifecycle/package.json
- exec/lifecycle/src/runLifecycleHooksConcurrently.ts
- exec/lifecycle/tsconfig.json
- exec/plugin-commands-rebuild/src/implementation/extendRebuildOptions.ts
- exec/plugin-commands-rebuild/src/implementation/index.ts
- pkg-manager/core/src/install/index.ts
- pkg-manager/core/test/install/multipleImporters.ts
- pkg-manager/headless/src/index.ts
- pnpm-lock.yaml
> fix: link local bins created by postinstall scripts

- .changeset/brave-clouds-sing.md
- pkg-manager/resolve-dependencies/src/resolveDependencies.ts
Replacing object spread with a prototype chain, avoiding extra memory allocations in `resolveDependencies`
This becomes noticeable on relatively large monorepo(~2k packages) reducing memory usage and making it faster
Also in my case:
1. allowing to complete `pnpm install` without `--max_old_space_size=8192` (it is slower, but at least works without OOM crash)
2. prevents OOM issue with `auto-install-peers=true` (for me this is crashing otherwise no matter `max_old_space_size`)
--- 
flame graph using pprof-it, running `NODE_OPTIONS="--max_old_space_size=8192" pprof-it ../pnpm/pnpm/bin/pnpm.cjs install --offline --resolution-only`
before: 
after:
> perf(resolve-dependencies): avoid copying preferredVersions object

- .changeset/brown-mayflies-sparkle.md
- pkg-manager/resolve-dependencies/src/resolvePeers.ts
Replacing object spread with a prototype chain, avoiding extra memory allocations in `resolvePeersOfNode`(similar to #6735)
This becomes noticeable on relatively large monorepo(~2k packages) reducing memory usage and making it almost twice faster in my case
--- 
flame graph using pprof-it, running `NODE_OPTIONS="--max_old_space_size=8192" pprof-it ../pnpm/pnpm/bin/pnpm.cjs install --offline --resolution-only`
before: 
after:
> perf(resolve-dependencies): avoid object copy in resolvePeersOfNode

- .changeset/dull-moles-notice.md
- pkg-manager/core/test/install/fromRepo.ts
- store/cafs/src/checkPkgFilesIntegrity.ts
fix #6721 
When we have never installed `pnpm/for-testing.no-package-json` before, the first installation will succeed:
```
$ pnpm add pnpm/for-testing.no-package-json
Packages: +1
+
Packages are hard linked from the content-addressable store to the virtual store.
Content-addressable store is at: /Users/Library/pnpm/store/v3
Virtual store is at:             node_modules/.pnpm
dependencies:
+ for-testing.no-package-json 0.0.0
Progress: resolved 1, reused 0, downloaded 1, added 1, done
Done in 2.8s
```
When reinstalling this dependency again, node will exit silently:
```
$ rm -rf node_modules pnpm-lock.yaml
$ pnpm add pnpm/for-testing.no-package-json
Progress: resolved 0, reused 1, downloaded 0, added 0
```
> fix: always resolve manifest promise even if the dependency does not have package.json

- .changeset/rare-items-search.md
- pkg-manager/resolve-dependencies/src/resolveDependencies.ts
> fix(resolve-dependencies): prefer versions found in parent packages only

- .changeset/fluffy-eggs-matter.md
- pkg-manager/resolve-dependencies/src/resolveDependencies.ts
Replacing object spread with a prototype chain, avoiding extra memory allocations in `resolveDependenciesOfImporters`
similar to #6735
also, fixing for the edge case when `importer.preferredVersions` can be overridden unintentionally
before:
after:
> perf(resolve-dependencies): preferredVersions in resolveDependenciesOfImporters

- .changeset/bright-ants-stare.md
- pkg-manager/resolve-dependencies/src/resolveDependencies.ts
- pkg-manager/resolve-dependencies/src/resolvePeers.ts
- pkg-manager/resolve-dependencies/src/updateLockfile.ts
Replacing usages of Ramda `isEmpty` with alternatives.
To my surprise - I have discovered that it is really slow.
(it looks like because of allowing too many possible input types, it does a lot of unnecessary work).
before:
after:
that is around 15%, faster by just not using it
> refactor(resolve-dependencies): remove ramda isEmpty usages

- .changeset/fair-apples-mix.md
- pkg-manager/resolve-dependencies/src/resolveDependencies.ts
- pkg-manager/resolve-dependencies/src/resolveDependencyTree.ts
- pkg-manager/resolve-dependencies/src/resolvePeers.ts
- pkg-manager/resolve-dependencies/test/dedupeDepPaths.test.ts
- pkg-manager/resolve-dependencies/test/resolvePeers.ts
- use `Map` of Sets for `depPathsByPkgId`
- use `Map` for `pathsByNodeId`
- make `DependenciesTree` a `Map` instead of a dictionary object
- use `Set` for `resolvedPeerNames`
- use `Map` for `resolvedPeers`, avoiding conversions
- avoid unnecessary conversion from `Set` to `Array`
before:
after:
> refactor(resolve-dependencies): use Maps and Sets instead of objects

- .changeset/nice-geese-fly.md
- pkg-manager/resolve-dependencies/src/nodeIdUtils.ts
- pkg-manager/resolve-dependencies/src/resolveDependencies.ts
Fix to avoid creating invalid nodeId, small optimization
> fix(resolve-dependencies): optimize splitNodeId, fix invalid nodeId

- .changeset/ninety-rats-breathe.md
- reviewing/dependencies-hierarchy/src/buildDependenciesHierarchy.ts
Moving loading wantedLockfile outside dependenciesHierarchyForPackage, reducing memory usage and preventing OOM crash on larger cases when loading the same lock file too many times
Flame graph running `pnpm why`
before: 
after:
> fix(dependencies-hierarchy): fix loading multiple copies of lockfile

- .changeset/young-scissors-grow.md
- pkg-manager/modules-cleaner/src/prune.ts
Ramda's `difference` happens to be slow, for the case how it is used in `prune` function.
before:
after:
> perf(modules-cleaner): replace ramda difference with better alternative

- .changeset/hot-cobras-fix.md
- pkg-manifest/read-project-manifest/package.json
- pkg-manifest/read-project-manifest/src/index.ts
- pnpm-lock.yaml
- use lodash deepClone instead of `JSON.parse(JSON.stringify)`, which is few times faster
- clone dependencies objects only once(when sorting)
- replace `sortKeys` usage with a simpler alternative(given we do not have nested structure to be sorted recursively, but a plain object - it can be done faster)
before
after
> perf(read-project-manifest): optimize normalize function

- .changeset/small-windows-brush.md
- exec/prepare-package/src/index.ts
- exec/prepare-package/test/__fixtures__/has-prepublish-script/package.json
> fix: don't run postpublish of git-hosted dependency

- .changeset/six-spies-fly.md
- pkg-manager/package-requester/package.json
- pkg-manager/package-requester/src/packageRequester.ts
- pnpm-lock.yaml
- store/cafs/src/index.ts
- store/cafs/src/writeBufferToCafs.ts
- store/cafs/test/optimisticRenameOverwrite.test.ts
This is a regression caused by: https://github.com/pnpm/pnpm/pull/6817
> fix: don't fail when multiple containers use the same store

- .changeset/four-penguins-buy.md
- pkg-manager/package-requester/package.json
- pkg-manager/package-requester/src/packageRequester.ts
- pnpm-lock.yaml
> fix: use shorter temp file name for the index files

- .changeset/yellow-nails-divide.md
- network/auth-header/src/index.ts
- network/auth-header/test/getAuthHeaderByURI.ts
~~* add compatibility back for `always-auth=true` so the authorization is still passed to components not matching the registry urls~~ Removed due to security issue.
* add https (:443 ) port filter in the URL parsing section so that authorization headers are added if the registry request matches.
* This fixes problems with large organizations that use and share multiple scopes across registries
~~1. `pnpm` was deleting the authorization header, making registries that act as pass-through registries fail to fetch their tarball file download when attempting to access another registry with shared scope.~~ Removed due to security issue.
2. `pnpm` was skipping https ports IE `:443` that artifactory was transforming. This caused a registry mismatch and it skipped authorization. This is related to …
> feat(always-auth): add https port parsing on registry matching for artifactory compatibility

- .changeset/lemon-meals-lick.md
- cli/parse-cli-args/src/index.ts
- cli/parse-cli-args/test/index.ts
fix #6594 
Also, currently `pnpm install ""` will report an error
```
$ pnpm install ""         
 ERR_PNPM_MISSING_PACKAGE_NAME  `pnpm add` requires the package name
```
that was fixed in this pr as well.
> fix: should not swallows empty string in params

- .changeset/chilled-terms-matter.md
- pkg-manager/core/src/install/index.ts
- pkg-manager/core/test/install/frozenLockfile.ts
Change the error message to indicate the wanted lockfile is absent, not present. This now reflects the actual error.
All the other locations use the correct error description.
(Draft PR because I still need to set up my environment for contributing.)
> fix: negate error on install without lockfile

- .changeset/cyan-oranges-wait.md
- patching/plugin-commands-patching/src/patchCommit.ts
- patching/plugin-commands-patching/test/patch.test.ts
- pkg-manager/plugin-commands-installation/src/import/index.ts
- pkg-manager/plugin-commands-installation/src/link.ts
- pkg-manager/plugin-commands-installation/src/remove.ts
- pnpm/src/main.ts
- workspace/filter-workspace-packages/src/index.ts
- workspace/find-packages/src/index.ts
- workspace/find-packages/test/index.ts
ref #6885 
1. only check non-root project manifest when `shared-workspace-file` is true.
2. `pnpm patch` and `pnpm patch-commit` should works correctly when shared-workspace-file is false
> fix(plugin-commands-patching): patch should works correctly when shared-workspace-file is false

- .changeset/chatty-houses-build.md
- exec/plugin-commands-script-runners/src/buildCommandNotFoundHint.ts
- exec/plugin-commands-script-runners/src/exec.ts
- exec/plugin-commands-script-runners/src/run.ts
- exec/plugin-commands-script-runners/test/exec.e2e.ts
Related comment: https://github.com/scaffold-eth/scaffold-eth-2/pull/444#discussion_r1273164114
Initially, I have hoped that I can create a hint for `pnpm $script` in general, but since I don't know how to distinguish between `pnpm $script` and `pnpm exec $script`, I have to settle for `pnpm exec $script` only.
> feat: friendlier error message when command not found

- .changeset/new-windows-drum.md
- cli/default-reporter/src/reporterForClient/reportBigTarballsProgress.ts
- cli/default-reporter/test/reportingProgress.ts
When running the CLI, downloads will show their progress, e.g. `1.12 MB/ 3 MB`, showing only significant digits.
As the output is constantly updated, the length of the line in the output might constantly change (2.99 -> 3 -> 3.3 -> 3.33), leading to a visually very noisy display.
https://github.com/pnpm/pnpm/assets/219373/7e98d064-9702-4d61-9cc5-01884dc6b74b
Tbh, I don't know much typescript and no pnpm - so i did not even build and test these changes ... *duckaway*.
Changes boil down to use [pretty-bytes according to their documentation](https://www.npmjs.com/package/pretty-bytes).
Fixes #6901
> feat(cli-output): harmonize download progress out

- .changeset/stale-coats-happen.md
- fetching/tarball-fetcher/src/remoteTarballFetcher.ts
- fetching/tarball-fetcher/test/fetch.ts
Related comment: https://github.com/orgs/pnpm/discussions/6376#discussioncomment-6420573
> perf: improve tarball fetching speed

- .changeset/two-waves-stare.md
- exec/plugin-commands-script-runners/src/exec.ts
it was caused by `which` not working correctly
> fix: misleading "command not found" error message

- .changeset/hungry-geckos-roll.md
- __fixtures__/has-package-lock-v3-json/.gitignore
- __fixtures__/has-package-lock-v3-json/package-lock.json
- __fixtures__/has-package-lock-v3-json/package.json
- __fixtures__/pnpm-workspace.yaml
- pkg-manager/plugin-commands-installation/src/import/index.ts
- pkg-manager/plugin-commands-installation/test/import.ts
> fix: add support for npm lockfile v3 in `import`

- .changeset/young-dryers-smash.md
- pkg-manager/plugin-commands-installation/src/update/getUpdateChoices.ts
- pkg-manager/plugin-commands-installation/src/update/index.ts
- pkg-manager/plugin-commands-installation/test/update/getUpdateChoices.test.ts
- pkg-manager/plugin-commands-installation/test/update/interactive.ts
- reviewing/outdated/src/outdated.ts
- reviewing/outdated/test/outdated.spec.ts
Partially resolves https://github.com/pnpm/pnpm/issues/6314
Notes:
- I really hate how the table rows are generated as it makes it nearly impossible to segment by dependency type while preserving column widths.
> feat(interactive-update): group dependancies by type, add package url column

- __fixtures__/circular/pnpm-lock.yaml
- __fixtures__/fixture-with-external-shrinkwrap/pnpm-lock.yaml
- __fixtures__/fixture-with-no-pkg-name-and-no-version/pnpm-lock.yaml
- __fixtures__/fixture-with-no-pkg-version/pnpm-lock.yaml
- __fixtures__/fixture/pnpm-lock.yaml
- __fixtures__/fixtureWithLinks/general/pnpm-lock.yaml
- __fixtures__/general/pnpm-lock.yaml
- __fixtures__/has-2-outdated-deps/node_modules/.pnpm/lock.yaml
- __fixtures__/has-2-outdated-deps/pnpm-lock.yaml
- __fixtures__/has-major-outdated-deps/pnpm-lock.yaml
- __fixtures__/has-not-outdated-deps/pnpm-lock.yaml
- __fixtures__/has-outdated-deps-and-external-shrinkwrap/pnpm-lock.yaml
- __fixtures__/has-outdated-deps/pnpm-lock.yaml
- __fixtures__/monorepo/pnpm-lock.yaml
- __fixtures__/pkg-with-external-lockfile/pnpm-lock.yaml
- __fixtures__/with-file-dep/pnpm-lock.yaml
- __fixtures__/with-peer/pnpm-lock.yaml
- __fixtures__/with-unsaved-deps/pnpm-lock.yaml
- __fixtures__/workspace-with-2-pkgs/pnpm-lock.yaml
- __fixtures__/workspace-with-different-deps/pnpm-lock.yaml
- __fixtures__/workspace-with-lockfile-dupes/pnpm-lock.yaml
- __fixtures__/workspace-with-private-pkgs/pnpm-lock.yaml
- pkg-manager/plugin-commands-installation/test/__snapshots__/dedupe.ts.snap
This PR fixes a CI break. The next person to change `pnpm-lock.yaml` would have hit this error.
The CI break in question can be found here: https://github.com/pnpm/pnpm/actions/runs/6032629535/job/16368092501. This is a simple commit that just adds a dummy `pnpm.overrides` entry. https://github.com/pnpm/pnpm/commit/ea6f55266a356b6fa174a3f95d4c059d5c15bde6
Copying the error out for easier viewing:
```
Packages are hard linked from the content-addressable store to the virtual store.
Content-addressable store is at: /home/runner/setup-pnpm/node_modules/.bin/store/v3
Virtual store is at: circular/node_modules/.pnpm
with-peer | Progress: resolved 7, reused 1, downloaded 6, added 7, done
with-non-package-dep | Progress: resolved 1, reused 0, downloaded 1, added 1, done
with-unsaved-deps | …
```
> test: fix ENOENT break on ci checks by using sha512 integrity in fixtures

- .changeset/odd-bears-think.md
- exec/plugin-commands-script-runners/src/runRecursive.ts
close #7005 
[logger.info(err)](https://github.com/pnpm/pnpm/blob/main/exec/plugin-commands-script-runners/src/runRecursive.ts#L134) here looks like doesn't actually do anything, Because we will output error information in `errorHandler`. 
But when the reporter type is `append-only`,  since the [message attribute](https://github.com/pnpm/pnpm/blob/main/cli/default-reporter/src/reporterForClient/reportMisc.ts#L53) is `undefined`, it will also output a unused `undefined`.
> When the reporter type is the default, it looks like `undefined` are [filtered here](https://github.com/pnpm/pnpm/blob/main/cli/default-reporter/src/mergeOutputs.ts#L50), so it doesn't do anything under normal use.
> chore: remove unused logger.info

- pkg-manifest/read-project-manifest/src/index.ts
Noticing a warning for `@typescript-eslint/no-explicit-any` when running `pnpm lint:ts`.
```
❯ pnpm lint:ts
> monorepo-root@ lint:ts /Users/gluxon/Developer/pnpm2
> eslint "**/src/**/*.ts" "**/test/**/*.ts"
/Users/gluxon/pnpm2/pkg-manifest/read-project-manifest/src/index.ts
217:46  warning  Unused eslint-disable directive (no problems were reported from '@typescript-eslint/no-explicit-any')
✖ 1 problem (0 errors, 1 warning)
0 errors and 1 warning potentially fixable with the `--fix` option.
```
It looks like this ESLint disable is no longer needed. The `any` type here was changed to `unknown` recently https://github.com/pnpm/pnpm/commit/b4892acc5fe6bbb993c01dc497c3721db653d33c#diff-9772b105160de4e18e6f731a919c7c84a353d9f1f48ede962d923b4fc6b86fbc.
> chore: remove unused eslint-disable directive

- jest.setup.js
Some tests don't clean up their resources completely and cause the retried run fail. Let's set `logErrorsBeforeRetry` to make it more clear that the retried run was a retry and not the first attempt. Otherwise Jest hides the first attempt. This makes it easier to distinguish between a test that's truly broken and one that's not retry-able.
The main motivation is to debug a test failure that I believe is keeping resources alive and hanging. https://github.com/pnpm/pnpm/pull/7029
It's possible this adds more noise than it helps. Happy to close if we think that's the case.
Here's an example of a test failure Jest will now print. This is otherwise hidden.
```
LOGGING RETRY ERRORS  should skip store integrity check and resolve manifest if fetchRawManifest is true
RETRY 1 
thrown: "Exceeded …
```
> test: set logErrorsBeforeRetry to debug failing retries

- pnpm/test/server.ts
- pnpm/test/utils/execPnpm.ts
Sometimes the server tests hang and hit the 4 minute timeout. This PR doesn't fix that, but makes it more clear what line the hanging is happening on.
Before this change, Jest wasn't able to tell us which specific part of a test was hanging.
```
● installation using pnpm server
thrown: "Exceeded timeout of 240000 ms for a test.
Add a timeout value to this test to increase the timeout, if this is a long-running test. See https://jestjs.io/docs/api#testname-fn-timeout."
62 | }
63 |
> 64 | skipOnWindows('installation using pnpm server', async () => {
|               ^
65 |   await using setup = prepareServerTest()
66 |   const { project, serverJsonPath } = setup
67 |
at Object.<anonymous> (test/server.ts:64:4)
```
With a few changes, Jest now shows the specific line that timed out.
1. The …
> test: make it easier to tell which line in server tests hang

- .changeset/wet-lies-smoke.md
- cli/default-reporter/src/reportError.ts
1. Start the pnpm store server.
```
❯ pnpm server start
```
2. Run a command that is expected to error.
```
❯ pnpm install is-positive@1.0.1
Cannot read properties of undefined (reading 'code')
```
In this example, we're attempting to install a version that doesn't exist.
The actual error is now printed with the fix in this PR.
```
❯ pnpm install is-positive@1.0.1
A store server is running. All store manipulations are delegated to it.
 ERROR  No matching version found for is-positive@1.0.1
This error happened while installing a direct dependency of /Users/gluxon/Developer/test
```
Errors from the pnpm server go through a different reporting code path. It looks like in this case the `err` object is empty for the `log` argument.
https://github.com/pnpm/pnpm/blob/ee61ca4cb7ce6b3cb177f892940ed …
> fix: report correct errors when using the pnpm server

- .changeset/chilled-ghosts-flow.md
- store/plugin-commands-server/src/start.ts
- store/server/src/createServer.ts
Fixes #7038. When running `pnpm server start`, the tarball fetcher worker pool (introduced in https://github.com/pnpm/pnpm/pull/6850) is immediately marked as "_finishing_" by this statement.
https://github.com/pnpm/pnpm/blob/131c723030ec4016274ca1cef33aadd66eb0e3b9/pnpm/src/main.ts#L300
The server continues running and handles requests after this point, which causes a few problems:
1. It results in a degraded state where the worker pool will think it's exiting and therefore never reuses workers. When the server is asked to do work it'll create a new worker, but immediately discard it.
2. In addition to the degraded state, there's an edge case in the worker pool finishing state's implementation that can cause hanging.
The exact conditions of the hanging were observed in …
> fix(server): prevent intermittent hanging when requesting a tarball worker

- .changeset/selfish-pianos-burn.md
- pnpm/src/main.ts
- workspace/filter-workspace-packages/src/index.ts
fixes https://github.com/pnpm/pnpm/issues/6981
> fix: [use-]node-version isn't passed on workspace

- .changeset/metal-starfishes-decide.md
- exec/prepare-package/src/index.ts
- pkg-manager/core/test/install/lifecycleScripts.ts
> fix: don't run prepublishOnly of git-hosted dependencies

- .changeset/four-carpets-itch.md
- config/plugin-commands-config/src/config.ts
- config/plugin-commands-config/test/configGet.test.ts
- config/plugin-commands-config/test/configSet.test.ts
fix #7106 
* Throw `ERR_PNPM_CONFIG_NO_PARAMS` for `pnpm config set` and `pnpm config delete` that missing  config key.
* output all settings when `pnpm config get` doesn't have config key.
> feat(plugin-commands-config): throw meaningful error for config sub commands

- .changeset/calm-walls-peel.md
- package.json
- pkg-manager/plugin-commands-installation/src/dedupe.ts
- pkg-manager/plugin-commands-installation/test/dedupe.ts
https://github.com/renovatebot/renovate/discussions/24417#discussioncomment-7003258
Fixes https://github.com/pnpm/pnpm/issues/7102.
Because I am not very familiar with the code of pnpm, I am not sure if the changes I made have other side effects.
> feat: add pnpm dedupe --ignore-scripts

- cli/default-reporter/src/reportError.ts
- config/config/src/index.ts
- exec/plugin-commands-rebuild/src/implementation/index.ts
- exec/plugin-commands-script-runners/src/create.ts
- exec/plugin-commands-script-runners/src/dlx.ts
- packages/dependency-path/src/index.ts
- patching/plugin-commands-patching/src/patchCommit.ts
- pkg-manager/package-bins/src/index.ts
- pkg-manager/plugin-commands-installation/src/getOptionsFromRootManifest.ts
- workspace/filter-workspace-packages/src/index.ts
`===` should be faster according to [startsWith source](https://github.com/zloirock/core-js/blob/446aa802ebc37831c14c5f18be17d01189374bd5/packages/core-js/modules/es.string.starts-with.js#L26-L36) in theory
[perf test](https://perf.link/#eyJpZCI6InFmNmVhMmwzMTNnIiwidGl0bGUiOiJGaW5kaW5nIG51bWJlcnMgaW4gYW4gYXJyYXkgb2YgMTAwMCIsImJlZm9yZSI6ImNvbnN0IGRhdGEgPSAnYWFhJyIsInRlc3RzIjpbeyJuYW1lIjoiVGVzdCBDYXNlIiwiY29kZSI6ImRhdGEuc3RhcnRzV2l0aCgnYicpIiwicnVucyI6WzM5MzAwMCwxNDI2MDAwLDkwMDAsMjQ1NjAwMCwzNjUyMDAwLDQ1MDQwMDAsNDgzNjAwMCwxODA4MDAwLDMwNDEwMDAsMjE5MjAwMCw0NTU4MDAwLDIyMjgwMDAsMjY0NzAwMCw0MzEwMDAwLDI1MzcwMDAsMTg5NTAwMCw1Mzc5MDAwLDQ5NTMwMDAsMzMyNjAwMCw1MjE5MDAwLDQ4NzIwMDAsMzEwMzAwMCwxNjQ2MDAwLDQwMzcwMDAsNDYwMDAwMCwzNjUxMDAwLDI1MTkwMDAsMTM2OTAwMCw1MjM1MDAwLDIzNTAwMDAsNDc1NDAwMCw1NDI4MDAwLDI3MDAwMD …
> perf: replace startsWith with ===

- .changeset/modern-crabs-smile.md
- exec/plugin-commands-rebuild/package.json
- exec/plugin-commands-rebuild/src/implementation/extendRebuildOptions.ts
- exec/plugin-commands-rebuild/src/implementation/index.ts
- exec/plugin-commands-rebuild/src/rebuild.ts
- exec/plugin-commands-rebuild/test/index.ts
- exec/plugin-commands-rebuild/test/recursive.ts
- pkg-manager/core/package.json
- pkg-manager/core/src/install/index.ts
- pkg-manager/plugin-commands-installation/src/import/index.ts
- pkg-manager/plugin-commands-installation/src/installDeps.ts
- pkg-manager/plugin-commands-installation/src/recursive.ts
- pnpm-lock.yaml
Fix #7135 #5407
In the current implementation there are 2 bugs that prevent `pnpm.neverBuiltDependencies` and `pnpm.onlyBuiltDependencies` to work under a workspace that doesn't share a single lockfile
1. The argument passed to some `getOptionsFromRootManifest` calls are wrong. They were incorrectly passed the project manifest instead of the intended root project manifest.
2. Both `neverBuiltDependencies` and `onlyBuiltDependencies` settings are not implemented in the recursive logic.
This PR provides a fix to the bugs above.
> fix: honor never/only-built-dependencies in workspace setup

- pnpm/dev/pd.js
Trying to develop from a fresh clone of `pnpm`, I noticed that the worker was missing from `./pnpm/pnpm/dev/dist`. This makes it so that esbuild compiles it in addition to the main `pnpm` script.
Without this, `pd install` was failing with:
```
MODULE_NOT_FOUND  Cannot find module '/Users/steven/src/pnpm/pnpm/dev/dist/worker.js'
```
> fix(pd): ensure `pd` builds the pnpm worker

- .changeset/twenty-walls-sit.md
- config/config/src/getOptionsFromRootManifest.ts
As someone currently migrating from Yarn, I would find it extremely helpful to be able to give Yarn and pnpm different override instructions.
By merging these two, migration from Yarn is even easier, because you can fix pnpm-specific overrides inside `pnpm.overrides` without affecting the existing Yarn setup.
> feat: merge manifest `resolutions` and `pnpm.overrides`

- .changeset/twelve-apricots-scream.md
- fs/indexed-pkg-importer/package.json
- pnpm-lock.yaml
Close: #7186 
In Windows, use `FSCTL_SET_SPARSE` ([FSCTL_SET_SPARSE IOCTL](https://learn.microsoft.com/en-us/windows/win32/api/winioctl/ni-winioctl-fsctl_set_sparse)), to set the destination file as sparse before cloning to it.
Sparse files do not allocate space for null bytes, preventing the cloned file from being filled with them. In short, this ensures that the cloned files are not empty.
> fix: avoid empty cloned files

- .changeset/proud-oranges-talk.md
- __typings__/local.d.ts
- deps/graph-sequencer/README.md
- deps/graph-sequencer/jest.config.js
- deps/graph-sequencer/package.json
- deps/graph-sequencer/src/index.ts
- deps/graph-sequencer/test/index.ts
- deps/graph-sequencer/tsconfig.json
- deps/graph-sequencer/tsconfig.lint.json
- exec/build-modules/CHANGELOG.md
- exec/build-modules/package.json
- exec/build-modules/src/buildSequence.ts
- exec/build-modules/tsconfig.json
- exec/plugin-commands-rebuild/CHANGELOG.md
- exec/plugin-commands-rebuild/package.json
- exec/plugin-commands-rebuild/src/implementation/index.ts
- exec/plugin-commands-rebuild/tsconfig.json
- pkg-manager/core/CHANGELOG.md
- pkg-manager/core/package.json
- pkg-manager/core/tsconfig.json
- pnpm-lock.yaml
- workspace/sort-packages/CHANGELOG.md
- workspace/sort-packages/src/index.ts
Faster than https://github.com/jamiebuilds/graph-sequencer
In scenarios where we have a large graph but only need to execute commands on a few specific nodes, the `graphSequencer` function now offers enhanced support. The `includeNodes` parameter allows us to limit the result to only the nodes we're interested in.
```javascript
graphSequencer(new Map([
[0, [1]],
[1, [2]],
[2, [3]],
[3, [0]],
]), [0, 1, 2])
```
For instance, if our graph is a big cycle but our subgraph is a simple linked list, we can now safely execute commands on the selected nodes.
```javascript
{
safe: true,
chunks: [[2], [1], [0]],
cycles: [],
}
```
In the previous behavior of the `graphSequencer` function, there were some peculiarities when handling single-node cycles.
```javascript
graphSequencer({
graph: new Map([ …
```
> feat(graph-sequencer): add package @pnpm/graph-sequencer

- .changeset/swift-ducks-talk.md
- exec/lifecycle/src/index.ts
- exec/lifecycle/test/fixtures/gyp-with-preinstall/binding.gyp
- exec/lifecycle/test/fixtures/gyp-with-preinstall/package.json
- exec/lifecycle/test/index.ts
According to [npm documentation](https://docs.npmjs.com/cli/v10/using-npm/scripts):
> If there is a binding.gyp file in the root of your package and you haven't defined your own install or preinstall scripts, npm will default the install command to compile using node-gyp via node-gyp rebuild
However, in the case of `pnpm`, this check was only performed if an install script was defined, resulting in a discrepancy between the behavior of npm and pnpm. You can refer to this GitHub issue for more information: https://github.com/aws/aws-lambda-nodejs-runtime-interface-client/issues/78.
This pull request modifies `pnpm` to execute `node-gyp rebuild` only when neither the preinstall nor the install scripts are defined.
> fix: do not run node-gyp rebuild if preinstall lifecycle script is present

- .changeset/proud-trees-develop.md
- patching/plugin-commands-patching/package.json
- patching/plugin-commands-patching/src/getPatchedDependency.ts
- patching/plugin-commands-patching/src/patchCommit.ts
- patching/plugin-commands-patching/test/patch.test.ts
- patching/plugin-commands-patching/tsconfig.json
- pnpm-lock.yaml
fix #7196
1. When patching dependency that installed from git, download the dependency directly from the tarball url in the lockfile, not from the npm registry (theversion in git may not have been released yet).
2. When prompted to select a version to patch, display a hint as to whether it is from git or not:
```
pnpm patch hi
? Choose which version to patch …
❯ 0.0.0
1.0.0 Git Hosted
```
>  fix(plugin-commands-patching): should fetch dependency from tarball url when patching dependency installed from git

- .changeset/fifty-kiwis-end.md
- lockfile/lockfile-utils/src/pkgSnapshotToResolution.ts
- lockfile/lockfile-utils/test/pkgSnapshotToResolution.ts
- pkg-manager/core/test/lockfile.ts
- pkg-manager/package-requester/test/index.ts
- pnpm/test/hooks.ts
- resolving/npm-resolver/src/index.ts
- resolving/npm-resolver/test/index.ts
- resolving/resolver-base/src/index.ts
- store/package-store/test/index.ts
- store/server/test/index.ts
In some cases, pnpm would add a `registry` field to tarball resolutions in pnpm-lock.yaml. This field is no longer used, so it was removed, which should make lockfiles smaller and their generation more deterministic.
💬 [Discord discussion](https://canary.discord.com/channels/731599538665553971/747905674578624633/1168693156854890506)
> fix(lockfile): remove `registry` from tarball resolutions

- .changeset/spotty-tools-compete.md
- fs/packlist/package.json
- pnpm-lock.yaml
Related issues:
- https://github.com/npm/cli/issues/5007
Fixed via: https://github.com/pnpm/npm-cli/commit/0af133ecb85d246b754c4eafb29d8d5720da2292
To reproduce in the pnpm repo, run `pnpm pack` in `store/store-path`.
> fix: regression caused by upgrading npm-packlist

- .github/workflows/ci.yml
- jest-with-registry.config.js
- jest.config.js
This allows concurrency for running the non registry-mock dependent tests
> test: change jest config worker count

- README.md
I am writing to propose an enhancement to the README file of the pnpm project. 
As pnpm serves as an alternative to both npm and yarn, I believe it would be beneficial to include a usage trend link for JavaScript package managers in the project's documentation. It's easy to compare the popularity rates of different package managers.  
Thank you for your time.
> Add usage trend

- .changeset/real-dolls-share.md
- fetching/tarball-fetcher/src/remoteTarballFetcher.ts
- fetching/tarball-fetcher/test/fetch.ts
If you run pnpm on [this repo](https://github.com/gcuddy/margins), you'll get errors like the following:
```
 WARN  GET https://registry.npmjs.org/@tiptap-pro/extension-mathematics/-/extension-mathematics-2.3.3.tgz error (ERR_PNPM_FETCH_404). Will retry in 10 seconds. 2 retries left.
 WARN  GET https://registry.npmjs.org/@tiptap-pro/extension-mathematics/-/extension-mathematics-2.3.3.tgz error (ERR_PNPM_FETCH_404). Will retry in 1 minute. 1 retries left.
 ERR_PNPM_FETCH_404  GET https://registry.npmjs.org/@tiptap-pro/extension-mathematics/-/extension-mathematics-2.3.3.tgz: Not Found - 404
This error happened while installing a direct dependency of /Users/deivid/code/dependabot/dependabot-core/npm_and_yarn/spec/fixtures/projects/pnpm/nonexistent_locked_dependency
No authorization header …
```
> fix: don't retry fetching missing packages

- .changeset/rich-radios-share.md
- store/package-store/src/storeController/prune.ts
- store/plugin-commands-store/src/store.ts
- store/plugin-commands-store/src/storePrune.ts
- store/plugin-commands-store/test/storePrune.ts
- store/store-controller-types/src/index.ts
add the ability to use --force to remove alien directory from the store
> feat: prune --force removes alien directories

- .changeset/small-eels-cry.md
- cspell.json
- pkg-manager/package-requester/src/packageRequester.ts
It was discovered last week that pnpm is fastest when `network-concurrency` is set to the exact number of available CPU cores.
What do you think, @zkochan?
**NOTE:** I haven't tested this on machine with fewer than 16 cores.
> perf: default network-concurrency to cpu count

- .changeset/three-apricots-wonder.md
- deps/graph-builder/src/lockfileToDepGraph.ts
- pkg-manager/core/src/install/link.ts
- pkg-manager/core/test/install/misc.ts
- pkg-manager/headless/test/index.ts
> fix: don't try to readd packages on repeat install

- .changeset/fifty-rabbits-sleep.md
- workspace/read-manifest/src/index.ts
- workspace/read-manifest/test/index.ts
> fix(workspace.read-manifest): allow null or empty manifest

- .changeset/unlucky-bees-film.md
- pkg-manager/core/test/lockfile.ts
- resolving/npm-resolver/src/index.ts
- resolving/npm-resolver/test/index.ts
(IMPORTANT) When the package tarballs aren't hosted on the same domain on which the registry (the server with the package metadata) is, the dependency keys in the lockfile should only contain `/<pkg_name>@<pkg_version`, not `<domain>/<pkg_name>@<pkg_version>`.
This change is a fix to avoid the same package from being added to `node_modules/.pnpm` multiple times. The change to the lockfile is backward compatible, so previous versions of pnpm will work with the fixed lockfile.
We recommend that all team members update pnpm in order to avoid repeated changes in the lockfile.
> fix: use the registry domain in the package ID, not the tarball domain

- .changeset/three-penguins-trade.md
- network/auth-header/src/index.ts
- network/auth-header/test/getAuthHeaderByURI.ts
> fix: missing auth token in registries with paths included

- .changeset/six-fireants-count.md
- workspace/read-manifest/src/index.ts
Follow up to https://github.com/pnpm/pnpm/pull/7278. I happened to be in this code path while working on #7072 and noticed a few ways the validation logic could be more type safe.
There should be no behavior changes in this PR. Just moving some functions and type annotations around.
> refactor(read-manifest): improve type safety of manifest validation logic

- patching/plugin-commands-patching/src/patch.ts
When running `pnpm patch-commit C://....` in Windows machine it can't find the file without quotes
> $ pnpm patch-commit C:\Users\A7med\AppData\Local\Temp\d26090b9171e469a1772e17685fc5823
> ENOENT  ENOENT: no such file or directory, open 'C:\UsersA7medAppDataLocalTempd26090b9171e469a1772e17685fc5823\package.json'
After some debugging I found that it must be wrapped with quotes:
> $ pnpm patch-commit 'C:\Users\A7med\AppData\Local\Temp\d26090b9171e469a1772e17685fc5823'
> Packages: -1
> -
> Progress: resolved 1045, reused 1016, downloaded 0, added 1, done
> fix(patch-commit): Wrap out patch dir in quotes in the log statement

- pnpm/test/filterProd.test.ts
- pnpm/test/monorepo/index.ts
Similar to https://github.com/pnpm/pnpm/pull/7346, I'm seeing this test in `test/filterProd.test.ts` flake on Windows.
```
2023-12-19T18:45:03.5114961Z FAIL test/filterProd.test.ts (6.17 s)
2023-12-19T18:45:03.5117704Z   ● --filter should include devDependencies
2023-12-19T18:45:03.5118205Z 
2023-12-19T18:45:03.5120054Z     expect(received).toStrictEqual(expected) // deep equality
2023-12-19T18:45:03.5120621Z 
2023-12-19T18:45:03.5120898Z     - Expected  - 1
2023-12-19T18:45:03.5121295Z     + Received  + 0
2023-12-19T18:45:03.5121553Z 
2023-12-19T18:45:03.5121686Z       Array [
2023-12-19T18:45:03.5123124Z         "project-1",
2023-12-19T18:45:03.5123926Z         "project-3",
2023-12-19T18:45:03.5124769Z     -   "project-4",
2023-12-19T18:45:03.5125159Z       ] …
```
> test: fix flaking filterProd and monorepo test due to json-append on windows

- .changeset/great-comics-clap.md
- pkg-manager/plugin-commands-installation/src/update/index.ts
Fixes https://github.com/pnpm/pnpm/issues/7439
According to `enquirer` [sources](https://github.com/enquirer/enquirer/blob/70bdb0fedc3ed355d9d8fe4f00ac9b3874f94f61/lib/prompt.js#L327) it uses `styles.success` or `styles.dark`.
According to my tests with chalk, `chalk.white()` is invisible in light terminal theme. So I suggest using `gray` (any other ideas are welcome).
> Fix `--update-interactive` for light theme

- .changeset/brave-zoos-tan.md
- reviewing/list/src/renderParseable.ts
- reviewing/list/test/index.ts
> fix(reviewing): filter the same print message

- .changeset/friendly-owls-smell.md
- env/plugin-commands-env/src/envAdd.ts
- env/plugin-commands-env/src/envRemove.ts
- env/plugin-commands-env/test/env.test.ts
Fix incorrect error messages.
```shell
pnpm env rm 21.5.0
# ERR_PNPM_NOT_IMPLEMENTED_YET  "pnpm env use <version>" can only be used with the "--global" option currently
pnpm env rm 21.5.0 --global
```
```diff
- pnpm env use
+ pnpm env remove
```
> fix: --global related error messages

- .changeset/gorgeous-seas-listen.md
- cli/default-reporter/src/reporterForClient/index.ts
- cli/default-reporter/src/reporterForClient/reportSummary.ts
Close https://github.com/pnpm/pnpm/issues/926
Fix  [#7319 ](https://github.com/pnpm/pnpm/pull/7319)
Here the result : 
@brc-dd
Tested on [ vuejs/vitepress](https://github.com/vuejs/vitepress) :
```bash
~/vitepress main*
❯ pd i
Scope: all 4 workspace projects
Packages: +622
++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
Progress: resolved 654, reused 622, downloaded 0, added 622, done
dependencies:
+ @docsearch/css 3.5.2
+ @docsearch/js 3.5.2
+ @types/markdown-it 13.0.7
+ @vitejs/plugin-vue 4.5.0
+ @vue/devtools-api 6.5.1
+ @vueuse/core 10.6.1
+ @vueuse/integrations 10.6.1
+ focus-trap …
```
> feat: pnpm i a-module-already-in-dev-deps should show message

- .changeset/late-seals-brake.md
- cspell.json
- env/node.fetcher/src/index.ts
- pnpm/src/main.ts
The automatic install feature causes PNPM to throw and fail in WebContainer as downloading different versions is not supported on that target.
This skips the download/install in WebContainer and allows PNPM to continue functioning with a warning.
> fix: skip automatic download/install of Node.js versions in WebContainer

- .changeset/real-knives-bathe.md
- config/config/src/index.ts
- pkg-manager/plugin-commands-installation/src/recursive.ts
Resolves #6524 
I was not able to verify the fix with [the mentioned `pd` command](https://github.com/pnpm/pnpm/blob/main/CONTRIBUTING.md?plain=1#L22). I applied the same changes to this repository as I did on my local installation of `pnpm` for the issue to be fixed.
**I might not have fixed the original issue** so I'll describe here the issue I faced and how I fixed it.
* This issue only concerns systems that are NOT case sensitive in their file path (basically Windows).
* Place yourself in a folder where to create a test project, make sure the `parent` folder is either not existent or not important
* Run the following commands (I'm using gitbash but equivalents in powershell or cmd behave the same) :
```bash
[ ! -e parent ] || rm -rf parent
mkdir -p parent/workspaces
(
cd Parent # Bad …
```
> fix: use real path for module root dir (#6524)

- .changeset/silent-berries-cry.md
- pnpm-lock.yaml
- reviewing/license-scanner/package.json
- reviewing/license-scanner/src/licenses.ts
- reviewing/license-scanner/test/licenses.spec.ts
- reviewing/plugin-commands-licenses/test/__snapshots__/index.ts.snap
This fixes a bug in the license-scanner where nondeterministic versions are used when multiple versions of a single package are depended on. This doesn't usually matter, but can cause problems if the license information changed between versions.
The ideal solution here would be to output license information for all versions that are depended on, but this is a breaking change so I opted instead to just make the versioning deterministic.
> fix(license-scanner): use deterministic version for each dependency

- pkg-manager/plugin-commands-installation/src/install.ts
Adding `--ignore-workspace` to the `pnpm install --help` section. 
This is an undocumented feature that is quite useful in monorepos where we have a directory that contains a `package.json` file and it is not part of the workspace.
> fix(install-help): add ignore-workspace

- .changeset/funny-snails-turn.md
- pkg-manager/get-context/src/index.ts
> fix: registry configuration from previous install should not override the current one

- .changeset/curvy-flies-run.md
- pnpm-lock.yaml
- reviewing/license-scanner/src/licenses.ts
- reviewing/license-scanner/test/licenses.spec.ts
- reviewing/plugin-commands-licenses/package.json
- reviewing/plugin-commands-licenses/src/outputRenderer.ts
- reviewing/plugin-commands-licenses/test/__snapshots__/index.ts.snap
- reviewing/plugin-commands-licenses/test/index.ts
Resolves https://github.com/pnpm/pnpm/issues/7224
> feat(license-scanner): show all licenses for JSON

- .changeset/nasty-apricots-taste.md
- exec/plugin-commands-script-runners/src/dlx.ts
- pnpm/test/run.ts
> fix(dlx): set saveProd to true for getting pkgName from dependencies

- .changeset/smooth-buckets-drop.md
- __typings__/typed.d.ts
- fs/packlist/src/index.ts
- releasing/plugin-commands-publishing/src/pack.ts
- releasing/plugin-commands-publishing/test/pack.ts
fix #4195 
Following @popeindustries's  suggestion,  we can create publishManifest before pack tarball, and then use the [`packageJsonCache` option in npm-packlist](https://github.com/npm/npm-packlist/blob/v5.1.3/lib/index.js#L211) to avoid loading pacakge.json from the local filesystem, which should ensure that the final list of files in packed tarball is the one that needs to be published.
> fix(plugin-commands-publishing): should pack main file or bin files defined in publishConfig

- pnpm/bin/pnpm.cjs
The node version hasn't been changed with #7459. So i correct it.
> chore: correct log node version

- __utils__/eslint-config/package.json
- packages/calc-dep-state/src/index.ts
- pnpm-lock.yaml
Updating `@typescript-eslint/*` dependencies and fixing a new `@typescript-eslint/no-floating-promises` error.
> chore(deps): update typescript-eslint (6.11.0 -> 6.18.1)

- .changeset/afraid-news-cheat.md
- releasing/plugin-commands-publishing/src/pack.ts
- releasing/plugin-commands-publishing/test/pack.ts
As discussed in https://github.com/pnpm/pnpm/pull/7538#issuecomment-1905025493.
`prepack` script may modifes `package.json`, so we should reread the manifest after executing the `prepack`script.
> fix(pack): "pnpm pack" should work as expected when prepack modifies the manifest

- .changeset/pretty-apples-dance.md
- fs/indexed-pkg-importer/src/index.ts
Set default `package-import-method` to hardlinks in Windows to avoid performance errors in systems without Dev Drives.
Close #7524 
Close #7547 
Close #7492
> feat: set default import method in Win to hardlink

- .changeset/nice-hairs-flow.md
- cli/default-reporter/src/reporterForClient/reportLifecycleScripts.ts
- cli/default-reporter/test/reportingLifecycleScripts.ts
Fixes https://github.com/pnpm/pnpm/issues/7556
> fix: print correctly aggregate output when mixing stages

- .changeset/breezy-poems-act.md
- .changeset/strange-ghosts-visit.md
- crypto/object-hasher/package.json
- crypto/object-hasher/src/index.ts
- crypto/object-hasher/test/index.ts
- pnpm-lock.yaml
Fixes https://github.com/pnpm/pnpm/pull/7563#issuecomment-1915260716
Marked this as a major bump given the hash values are changing.
Adds some more tests too; `object-hash` _cannot_ hash `undefined`, so I just made it return `0`. Feel free to suggest something better.
> fix(object-hasher): switch to object-hash to fix hashing of large objects

- pnpm/dev/pd.js
For some reason, esbuild uses the upstream version of `js-yaml` rather than the @zkochan fork. This throws a little plugin into esbuild's resolution to resolve `js-yaml` using Node's resolvers instead, which seems to find the correct version.
There may be a better way to do this, especially considering esbuild does fine in the normal build of pnpm as far as I can tell... though that may be because `tsc` does the first pass.
> chore(pd): make esbuild find `js-yaml` correctly

- pnpm/dev/pd.js
This change makes it so that `pd` starts a Node process and passes `--enable-source-maps` to it, which allows for better debugging when `pd` commands fail.
I'm not sure if this will work on Windows since it changes a simple `require` to a `childProcess.execSync`.
> chore(pd): ensure pd always runs with sourcemaps

- .changeset/thin-pumpkins-mate.md
- pkg-manager/resolve-dependencies/src/resolveDependencies.ts
- pnpm/test/link.ts
close #4761
close #4793
close #7511
close #7560
> fix: linking globally a package with no name in package.json

- .changeset/lemon-windows-tickle.md
- pkg-manager/get-context/src/index.ts
pnpm sometimes needs to purge modules folders (node_modules) when certain configuration changes (in other words, when it needs to start from scratch).
This prompt, problematically, was getting triggered asynchronously for each importer in the workspace that needed a purge, which would sometimes lead to gargantuan prompts instead of one consolidated prompt.
The fix is to queue up which importers need a purge, then fire the prompter all at once.
Closes #7320
> fix(get-context): avoid excess purge prompts

- pkg-manager/core/test/install/peerDependencies.ts
- pkg-manager/resolve-dependencies/src/resolvePeers.ts
This issue is only on v9
related: https://github.com/pnpm/pnpm/pull/7606
> fix: do not fail when the same package with peer dependency is installed via different aliases

- .changeset/forty-turtles-rhyme.md
- .gitattributes
- cspell.json
- store/cafs/src/parseTarball.ts
- store/cafs/test/index.ts
> fix: unpacking tarballs that appear to be not USTAR or GNU TAR

- .changeset/quick-students-hope.md
- reviewing/plugin-commands-licenses/src/licensesList.ts
- reviewing/plugin-commands-licenses/test/index.ts
- reviewing/plugin-commands-licenses/test/utils/index.ts
Fixes #7725
This PR fixes a bug where calling `pnpm licenses list --json` in a workspace member package returns incorrect `"paths"`. I also added a test case to make sure `paths` was correct.
> fix(licenses): use correct lockfileDir

- cli/cli-utils/src/packageIsInstallable.ts
- config/package-is-installable/test/checkEngine.ts
- pnpm/test/install/misc.ts
Fixes #7733
`"packageManager"` field in `package.json` may contain semver with pre-release (e.g. `8.0.0-dev`) or build identifiers (e.g. `8.0.0+sha256.hash...`), or URL.
`"packageManager"` is determined if it's a URL by checking for the existance of character ':' in the value. This works because ':' must appear on all URLs, while the character may not appear on semvers. `URL.canParse()` is not used because the function is not implemented in all node versions pnpm currently supports (>= 18.12).
If it is a semver, build values are stripped, and it is compared with pnpm version including the pre-release identifiers.
URLs are ignored as there is no way to check that running pnpm version is the same as the build at URL.
> fix: packageManager field can contain various values

- .changeset/hungry-mirrors-thank.md
- hooks/read-package-hook/src/createVersionsOverrider.ts
- hooks/read-package-hook/test/createVersionOverrider.test.ts
pnpm will install a wrong dependency when link override is an absolute path
```
"pnpm": {
"overrides": {
"test": "link:/absolute-path//test"
}
}
```
> fix: link overrides should be able to use absolute path

- fs/find-packages/README.md
The package used to be named "find-packages" but it's moved to "@pnpm/fs.find-packages", but the badge image src wasn't updated
> Update README.md: Update badge image of @pnpm/fs.find-packages

- .changeset/loud-teachers-kiss.md
- pnpm-lock.yaml
- workspace/pkgs-graph/package.json
- workspace/pkgs-graph/src/index.ts
- workspace/pkgs-graph/test/index.ts
- workspace/pkgs-graph/tsconfig.json
> fix: ordering workspace projects that are in peer dependencies

- .changeset/plenty-tomatoes-battle.md
- pkg-manager/plugin-commands-installation/src/prune.ts
- pkg-manager/plugin-commands-installation/test/prune.ts
> fix(prune): add `--ignore-scripts` arg to `prune` command

- .changeset/fresh-boats-press.md
- .changeset/plenty-humans-exist.md
- .changeset/silly-moles-rhyme.md
- config/config/src/dirs.ts
- config/config/test/dirs.test.ts
- pnpm/CHANGELOG.md
This reverts commit b970d965517ac1e78d2bb9d572a6a2b5e310378a.
As mentioned by @arcc1845 in https://github.com/pnpm/pnpm/issues/7732, the original premise of this change doesn't seem correct. The `$HOME/Library` directory is not protected by macOS System Integrity Protection (SIP).
I think we should go back to `$HOME/Library` on macOS. I personally don't have a preference on `$HOME/Library` versus `~/.config`, but would prefer to have less changes on the unreleased v9 branch. I think we'll see more users confused by the current behavior on the alpha branch when v9 releases if we don't revert.
> revert: use the same directories on macOS as on Linux

- cli/cli-utils/src/packageIsInstallable.ts
> fix: don't check the package manager field, when executed by corepack

- .changeset/hungry-eyes-reply.md
- releasing/plugin-commands-publishing/src/publish.ts
Closes #7845 
Prior to this PR, pnpm publishes a package when we run `pnpm publish package-1.0.1.tgz --access public --no-git-checks --tag exp --ignore-scripts`, but ignores `--tag`, `--access` and all options.
Because pnpm only passes the tarball name to params in releasing/plugin-commands-publishing/src/publish.ts.
After this PR we can use pnpm with any options.
I've just started learning about pnpm, so apologies if I'm wrong. The original code ignored processing for args, such as the `--publish-branch` option, because the processing for the tarball was done first, but I am not confident that this is correct.
> fix: wrong tag stated in `pnpm publish`

- packages/dependency-path/src/index.ts
I want to improve type checker performance as recommended by https://github.com/microsoft/TypeScript/wiki/Performance#using-type-annotations.
In order to prevent merge conflict, I will do it one module at a time.
> refactor: return type for dependency-path

- __utils__/prepare/package.json
- __utils__/prepare/src/index.ts
- config/config/src/index.ts
- exec/plugin-commands-script-runners/package.json
- exec/plugin-commands-script-runners/src/dlx.ts
- exec/plugin-commands-script-runners/test/create.ts
- exec/plugin-commands-script-runners/test/dlx.e2e.ts
- exec/plugin-commands-script-runners/test/dlx.ts
- exec/plugin-commands-script-runners/test/utils/index.ts
- pnpm-lock.yaml
- pnpm/test/run.ts
- store/plugin-commands-store/package.json
- store/plugin-commands-store/src/cleanExpiredCache.test.ts
- store/plugin-commands-store/src/cleanExpiredCache.ts
- store/plugin-commands-store/src/cleanExpiredDlxCache.test.ts
- store/plugin-commands-store/src/cleanExpiredDlxCache.ts
- store/plugin-commands-store/src/storePrune.ts
- store/plugin-commands-store/test/storeAdd.ts
- store/plugin-commands-store/test/storePath.ts
- store/plugin-commands-store/test/storePrune.ts
- store/plugin-commands-store/test/storeStatus.ts
- store/plugin-commands-store/tsconfig.json
Fixes https://github.com/pnpm/pnpm/issues/5277
---
**TODO:**
> feat(dlx): cache

- pnpm/test/run.ts
The parallel dlx calls are not guaranteed to be concurrent to each other in the CI.
> test: fix unreliable assertions

- pkg-manager/resolve-dependencies/src/resolveDependencies.ts
I think this is slightly more readable, but happy to just close this PR if others disagree.
> refactor: split out resolvedDependenciesOfImporter for readability

- pkg-manager/resolve-dependencies/src/resolveDependencies.ts
I was looking over the `resolveDependencies` function and noticed `extendedWantedDepsByImporters` isn't a map. It looks like that's just an array we use to `zipWith` the `importers` array later.
Instead of creating two separate arrays and zipping them together, the initial transform can create the zipped pairs array directly. I think this is slightly more readable and happens to be a bit more performant, but the performance difference is probably negligible.
> refactor: remove zipWith when resolving dependencies of importers

- .changeset/shiny-zoos-love.md
- exec/lifecycle/package.json
- exec/lifecycle/src/runLifecycleHook.ts
- exec/plugin-commands-script-runners/test/index.ts
- pnpm-lock.yaml
Configuring [`script-shell` in `.npmrc`](https://pnpm.io/cli/run#script-shell) on Windows to a `.bat` or `.cmd` file,
```ini
script-shell = node_modules/.bin/shell-mock.cmd
```
will result in:
```
spawn EINVAL
at spawn (../../node_modules/.pnpm/@pnpm+npm-lifecycle@3.0.2_typanion@3.14.0/node_modules/@pnpm/npm-lifecycle/lib/spawn.js:36:15)
```
This previously worked, but changed after the [Node.js security release on April 10th, 2024](https://nodejs.org/en/blog/vulnerability/april-2024-security-releases-2).
Yesterday, I attempted to update `@pnpm/npm-lifecycle` to support `.bat`/`.cmd` files, but this change was reverted after discovering behavior differences with arguments passed to these `.bat`/`.cmd` files.
https://github.com/pnpm/npm-lifecycle/pull/42
As of version 10.5.0, npm doesn't …
> fix: error when `script-shell` is configured to a `.bat` or `.cmd` file

- .changeset/quick-walls-report.md
- pkg-manager/core/src/install/index.ts
> fix: don't upgrade the lockfile format during frozen lockfile install

- .changeset/unlucky-chefs-learn.md
- workspace/read-manifest/src/catalogs.ts
- workspace/read-manifest/src/errors/InvalidWorkspaceManifestError.ts
- workspace/read-manifest/src/index.ts
- workspace/read-manifest/test/__fixtures__/catalog-invalid-array/pnpm-workspace.yaml
- workspace/read-manifest/test/__fixtures__/catalog-invalid-object/pnpm-workspace.yaml
- workspace/read-manifest/test/__fixtures__/catalog-invalid-specifier/pnpm-workspace.yaml
- workspace/read-manifest/test/__fixtures__/catalog-ok/pnpm-workspace.yaml
- workspace/read-manifest/test/__fixtures__/catalogs-conflicting-defaults/pnpm-workspace.yaml
- workspace/read-manifest/test/__fixtures__/catalogs-invalid-array/pnpm-workspace.yaml
- workspace/read-manifest/test/__fixtures__/catalogs-invalid-named-catalog-array/pnpm-workspace.yaml
- workspace/read-manifest/test/__fixtures__/catalogs-invalid-named-catalog-object/pnpm-workspace.yaml
- workspace/read-manifest/test/__fixtures__/catalogs-invalid-named-catalog-specifier/pnpm-workspace.yaml
- workspace/read-manifest/test/__fixtures__/catalogs-invalid-object/pnpm-workspace.yaml
- workspace/read-manifest/test/__fixtures__/catalogs-ok/pnpm-workspace.yaml
- workspace/read-manifest/test/index.ts
Part of https://github.com/pnpm/pnpm/issues/7072.
This PR reads pnpm catalogs in `WorkspaceManifest` and adds type definitions for them. Future pull requests will read from this config.
The changes are feature flagged for now to prevent the catalogs feature from being accidentally used before it's fully implemented.
The next PR is https://github.com/pnpm/pnpm/pull/8020, but I'll leave that in draft mode until this PR merges.
> feat: read catalog configs from workspace manifest (feature flagged)

- pkg-manager/resolve-dependencies/src/dedupeInjectedDeps.ts
Very small change to improve type checking.
The `linkedDep` constant is pushed to `opts.resolvedImporters[id].directDependencies`, which requires its entries to satisfy the `ResolvedDirectDependency` interface. Making the type annotation on `linkedDep` more accurate so errors are clearer if someone changes `ResolvedDirectDependency` in the future.
> refactor(resolve-dependencies): annotate linkedDep as ResolvedDirectDependency

- .changeset/curly-actors-repeat.md
- cspell.json
- pkg-manager/resolve-dependencies/src/hoistPeers.ts
- pkg-manager/resolve-dependencies/src/resolveDependencies.ts
- pkg-manager/resolve-dependencies/test/hoistPeers.test.ts
> fix: only automatically resolve optional peers with versions that satisfy the ranges

- catalogs/types/CHANGELOG.md
- catalogs/types/README.md
- catalogs/types/package.json
- catalogs/types/src/index.ts
- catalogs/types/tsconfig.json
- catalogs/types/tsconfig.lint.json
- pnpm-lock.yaml
- pnpm-workspace.yaml
Cherry picking the commit that creates a new `@pnpm/catalogs.types` package from a different draft PR https://github.com/pnpm/pnpm/pull/8020 so we can merge the catalogs feature into `main` more incrementally. This also makes the more complicated draft PR smaller and easier to review.
Sounds like a new `@pnpm/catalogs.types` package is okay: https://github.com/pnpm/pnpm/pull/8020#discussion_r1581501808
> feat: create new `@pnpm/catalogs.types` package

- .changeset/flat-poets-worry.md
- package.json
- pnpm-lock.yaml
- renovate.json
- reviewing/plugin-commands-licenses/package.json
- reviewing/plugin-commands-outdated/package.json
- reviewing/plugin-commands-outdated/src/outdated.ts
- reviewing/plugin-commands-outdated/test/index.ts
When I run `pnpm outdated --long` under the pnpm repository, the printed information is as follows.
After modification, it is as follows:
> fix: `outdated` output table information is misplaced

- .changeset/kind-carrots-fry.md
- deps/graph-sequencer/src/index.ts
- deps/graph-sequencer/test/index.ts
Earlier implementations would return after finding the first circle, which in some scenarios found the smallest circle, see the test file for specific scenarios.
> feat(graph-sequencer): Topological ordering will look for the longest circle

- .changeset/real-glasses-pull.md
- reviewing/plugin-commands-licenses/src/outputRenderer.ts
- reviewing/plugin-commands-licenses/test/__snapshots__/index.ts.snap
When I run `pnpm licenses ls --long` under the repository, the printed information as follows.
After modification, it is as follows:
> fix: `licenses` output table misplaced

- pnpm-lock.yaml
Running `pnpm install` on one of my PRs, I'm noticing `pnpm-lock.yaml` changes where `semver` dependencies on `^7.6.0` are switching between `7.6.0` and `7.6.2`.
This PR deduplicates the `semver` dependency and removes `7.6.0`.
> chore(deps): deduplicate semver 7.6.0 onto 7.6.2

- .changeset/ninety-kids-push.md
- pkg-manager/resolve-dependencies/src/resolvePeers.ts
ref #8072
My tests show that with these changes pnpm v9 uses not more memory than v8.
> fix: reduce memory usage during peers resolution

- README.md
This PR updates the download trend image to be dynamic, replacing the static image used previously (https://github.com/pnpm/pnpm/pull/7274).
Thanks for reviewing!
> Update download trend image to be dynamic

- .changeset/perfect-needles-collect.md
- pkg-manager/core/test/install/autoInstallPeers.ts
- pkg-manager/core/test/install/peerDependencies.ts
- pkg-manager/resolve-dependencies/src/resolveDependencies.ts
- pkg-manager/resolve-dependencies/src/resolveDependencyTree.ts
Reverts https://github.com/pnpm/pnpm/commit/4b65113b9c696ffb2ffe06b38191d43e2120310a
ref https://github.com/pnpm/pnpm/issues/8072
This change makes install faster at least 3 times in some Bit workspaces.
> perf: fix hoisting peers

- cli/default-reporter/src/reporterForClient/reportUpdateCheck.ts
- cli/default-reporter/test/__snapshots__/reportingUpdateCheck.ts.snap
The Corepack CLI was refactored to add much more intuitive commands in PR https://github.com/nodejs/corepack/pull/291
This landed in `corepack@0.20.0` https://github.com/nodejs/corepack/releases/tag/v0.20.0
Which landed in `node@18.19.0` https://github.com/nodejs/node/pull/49464
This has been available since last year https://nodejs.org/en/blog/release/v18.19.0
> fix: update corepack install command for outdated version

- catalogs/protocol-parser/CHANGELOG.md
- catalogs/protocol-parser/README.md
- catalogs/protocol-parser/jest.config.js
- catalogs/protocol-parser/package.json
- catalogs/protocol-parser/src/index.ts
- catalogs/protocol-parser/src/parseCatalogProtocol.ts
- catalogs/protocol-parser/test/parseCatalogProtocol.test.ts
- catalogs/protocol-parser/tsconfig.json
- catalogs/protocol-parser/tsconfig.lint.json
- pnpm-lock.yaml
Cherry picking the commit that creates a new `@pnpm/catalogs.protocol-parser` package from a different draft PR https://github.com/pnpm/pnpm/pull/8020 so we can merge the catalogs feature into `main` more incrementally. This also makes the more complicated draft PR smaller and easier to review.
This package will be unused until a future PR merges.
> feat: create new `@pnpm/catalogs.protocol-parser` package

- pkg-manager/core/src/install/index.ts
Copying a commit out from https://github.com/pnpm/pnpm/pull/8020 to merge into the `main` branch. This small refactor should be a no-op and not change pnpm's behavior.
> refactor: factor out isWantedDepPrefSame to extend in a future commit

- .changeset/unlucky-avocados-talk.md
- .changeset/young-carpets-stare.md
- cli/cli-utils/src/packageIsInstallable.ts
- cli/cli-utils/src/readProjectManifest.ts
- config/config/src/Config.ts
- config/config/src/index.ts
- pnpm/test/install/misc.ts
- workspace/find-packages/src/index.ts
close #8087
I considered printing a warning or info message instead. However, this would get printed on all commands and probably break some tools that parse the output of pnpm. So, safer just to not print anything (and faster to implement).
> fix: don't fail if the pnpm version doesn't match the one in the packageManager field

- .changeset/hungry-pears-allow.md
- patching/plugin-commands-patching/src/patchCommit.ts
The generated diff file will be wrong format if users install an expanded diff tool like [difftastic](https://github.com/Wilfred/difftastic).
> feat: disallow external diff drivers

- .changeset/brown-apes-compare.md
- config/config/src/index.ts
fixes #8188 
Basically, in a Turkish locale computer; config variables has issues on parsing if they have a "i" character because of camelcase function gets current computer's locale by default. and i become "İ" on Turkish locale. It could probably happen in other languages too.
As a result of this, config variables (even default ones) could have problems like following after config parse operation,
Expected:
Actual:
So as the final result even a simple pnpm install command acts with a default filter. Probably this can create other causes too.
I know this update is in the core of the pnpm, please let me know if you need further information or testing effort.
Thank you for great project and your efforts!
> fix(config): use locale while parsing variables as camelcase

- .changeset/metal-panthers-grow.md
- workspace/read-manifest/src/index.ts
The `packages` field of `WorkspaceManifest` is currently defined as nullable, but I believe this won't ever be the case since we're verifying that it's always present in `readWorkspaceManifest`.
https://github.com/pnpm/pnpm/blob/6ccdfff08cf1a7d481cb5c547757f72b72c8bbc5/workspace/read-manifest/test/index.ts#L24-L28
Let's remove the nullable type annotation to make it easier for code using `WorkspaceManifest` to read `packages`.
This will be useful for https://github.com/pnpm/pnpm/pull/8120#issuecomment-2146312263.
It'd be good to use the compiler to rely on `patterns` never being `undefined`, which would be the case if `packages` from `WorkspaceManifest` also can't be `undefined`.
> fix: update WorkspaceManifest packages field type to be non-null

- .changeset/thirty-seals-study.md
- config/config/package.json
- config/config/src/Config.ts
- config/config/src/index.ts
- config/config/test/fixtures/pkg-with-valid-workspace-yaml/pnpm-workspace.yaml
- config/config/test/index.ts
- config/config/tsconfig.json
- pkg-manager/plugin-commands-installation/src/import/index.ts
- pkg-manager/plugin-commands-installation/src/installDeps.ts
- pkg-manager/plugin-commands-installation/src/link.ts
- pkg-manager/plugin-commands-installation/src/remove.ts
- pnpm-lock.yaml
- pnpm/src/main.ts
- https://github.com/pnpm/pnpm/pull/8213
- https://github.com/pnpm/pnpm/pull/8214
The `pnpm-workspace.yaml` file is currently read whenever `findWorkspacePackages` is called and then discarded.
Following recent discussions in other PRs, let's store `pnpm-workspace.yaml` in `@pnpm/config` for longer-term reuse and pass the `packages` field to `findWorkspacePackages` when possible.
> approach 1 is the right one. Maybe we can read it in @pnpm/config. We already read the root manifest there too. https://github.com/pnpm/pnpm/pull/8020#discussion_r1584486789
> This sounds good to me. I guess you could put patterns to the options. https://github.com/pnpm/pnpm/pull/8120#issuecomment-2146312263
This makes it easier to reuse the contents of `pnpm-workspace.yaml` for pnpm catalogs.
This PR is mostly …
> refactor: store workspace manifest in `@pnpm/config` for reuse

- catalogs/config/CHANGELOG.md
- catalogs/config/README.md
- catalogs/config/jest.config.js
- catalogs/config/package.json
- catalogs/config/src/getCatalogsFromWorkspaceManifest.ts
- catalogs/config/src/index.ts
- catalogs/config/test/getCatalogsFromWorkspaceManifest.test.ts
- catalogs/config/test/tsconfig.json
- catalogs/config/tsconfig.json
- catalogs/config/tsconfig.lint.json
- pnpm-lock.yaml
- workspace/read-manifest/src/catalogs.ts
- workspace/read-manifest/src/index.ts
- workspace/read-manifest/test/index.ts
Adding a new `@pnpm/catalogs.config` package that merges the `catalog` and `catalogs` fields from `pnpm-workspace.yaml`.
This will be used in `@pnpm/config` in a future PR. https://github.com/pnpm/pnpm/pull/8221/commits/fbd0197711bf1499c609f7791ebe259b120f4275
https://github.com/pnpm/pnpm/blob/fbd0197711bf1499c609f7791ebe259b120f4275/config/config/src/index.ts#L587-L592
> feat: create new `@pnpm/catalogs.config` package

- catalogs/resolver/CHANGELOG.md
- catalogs/resolver/README.md
- catalogs/resolver/jest.config.js
- catalogs/resolver/package.json
- catalogs/resolver/src/index.ts
- catalogs/resolver/src/matchCatalogResolveResult.ts
- catalogs/resolver/src/resolveFromCatalog.ts
- catalogs/resolver/test/resolveFromCatalog.test.ts
- catalogs/resolver/test/tsconfig.json
- catalogs/resolver/tsconfig.json
- catalogs/resolver/tsconfig.lint.json
- pnpm-lock.yaml
Creating a new `@pnpm/catalogs.resolver` package.
This is a fairly straightforward local resolver that just takes a catalog protocol specifier (e.g. `catalog:foo`) and resolves it using the `Catalogs` config object from `pnpm-workspace.yaml`.
In future PRs, this will be used in
- `pkg-manager/resolve-dependencies/src/resolveDependencies.ts` to replace `catalog:` protocol specifiers on `pnpm install`.
- `pkg-manifest/exportable-manifest/src/index.ts` to replace `catalog:` protocol specifiers on `publish`.
> feat: create new `@pnpm/catalogs.resolver` package

- .changeset/chilly-eels-study.md
- config/config/package.json
- config/config/src/Config.ts
- config/config/src/index.ts
- config/config/tsconfig.json
- packages/make-dedicated-lockfile/src/index.ts
- pkg-manifest/exportable-manifest/package.json
- pkg-manifest/exportable-manifest/src/index.ts
- pkg-manifest/exportable-manifest/test/index.test.ts
- pkg-manifest/exportable-manifest/tsconfig.json
- pnpm-lock.yaml
- releasing/plugin-commands-publishing/package.json
- releasing/plugin-commands-publishing/src/pack.ts
- releasing/plugin-commands-publishing/src/recursivePublish.ts
- releasing/plugin-commands-publishing/test/publish.ts
- releasing/plugin-commands-publishing/tsconfig.json
Part of https://github.com/pnpm/pnpm/issues/7072
- The `@pnpm/exportable-manifest` now handles `catalog:` protocol dependencies.
- The `pnpm publish` command now replaces `catalog:` protocol dependencies to make `package.json` files portable outside of a pnpm workspace/monorepo.
> feat: implement catalog protocol for publish

- config/config/src/index.ts
I just realized that `warnings` was not optional.
> refactor: remove unnecessary code

- catalogs/config/package.json
- catalogs/protocol-parser/package.json
- catalogs/resolver/package.json
- config/config/package.json
- config/config/src/Config.ts
- config/config/src/index.ts
- config/config/tsconfig.json
- lockfile/lockfile-file/src/lockfileFormatConverters.ts
- lockfile/lockfile-file/src/sortLockfileKeys.ts
- lockfile/lockfile-types/src/index.ts
- pkg-manager/core/package.json
- pkg-manager/core/src/getPeerDependencyIssues.ts
- pkg-manager/core/src/install/allCatalogsAreUpToDate.ts
- pkg-manager/core/src/install/allProjectsAreUpToDate.ts
- pkg-manager/core/src/install/extendInstallOptions.ts
- pkg-manager/core/src/install/index.ts
- pkg-manager/core/test/allProjectsAreUpToDate.test.ts
- pkg-manager/core/test/catalogs.ts
- pkg-manager/core/tsconfig.json
- pkg-manager/resolve-dependencies/package.json
- pkg-manager/resolve-dependencies/src/getCatalogSnapshots.ts
- pkg-manager/resolve-dependencies/src/index.ts
- pkg-manager/resolve-dependencies/src/resolveDependencies.ts
- pkg-manager/resolve-dependencies/src/resolveDependencyTree.ts
- pkg-manager/resolve-dependencies/tsconfig.json
- pnpm-lock.yaml
This implements the following items from the tracking issue https://github.com/pnpm/pnpm/issues/7072.
I've organized this PR into different commits that make sense by themselves. **This PR should be easier to review commit by commit rather than all files changed at once.**
The hardest part of this PR was determining the right place for the `catalog:` → `^1.2.3` translation internally.
- We could model this as a [read package hook](https://github.com/pnpm/pnpm/blob/aa33269f9f9fc0c3505ae1c59264d1706923a971/hooks/read-package-hook/src/createReadPackageHook.ts#L14), which would be similar to how `pnpm.overrides` and `packageExtensions` work. I think this is **too early** of a place for the protocol to be resolved since it means the `pnpm-lock.yaml` file won't have the original `catalog:` …
> feat: implement catalog protocol for install

- pkg-manager/core/package.json
- pkg-manager/core/test/catalogs.ts
- pkg-manager/core/tsconfig.json
- pnpm-lock.yaml
Addressing feedback from:
- https://github.com/pnpm/pnpm/pull/8221#discussion_r1654685354
> refactor: remove filter-packages-from-dir dependency from core tests

- pnpm-lock.yaml
- pnpm-workspace.yaml
Upgrading `@pnpm/registry-mock` to 3.33.0 for the change below.
- https://github.com/pnpm/registry-mock/pull/16
> chore: upgrade `@pnpm/registry-mock` from 3.32.1 to 3.33.0

- catalogs/resolver/src/resolveFromCatalog.ts
- catalogs/resolver/test/resolveFromCatalog.test.ts
Using pnpm catalogs with the `workspace:`, `link:`, and `file:` protocols "_kind of works in the beta release today_". However, I think there's surprising behavior in each.
- For the `workspace:` protocol, it's kind of weird to see the `workspace:*` protocol defined in catalogs in the first place. I can't think of a good reason for this indirection. I think spending time trying to support this isn't a good use of developer time.
- The `link:` and `file:` protocols are often used to refer to relative paths. Since pnpm catalogs are defined in `pnpm-workspace.yaml`, I think most users will expect paths to be relative to that file. Unfortunately they're relative to the project's `package.json`, which doesn't feel right. Let's disable this until we have time to better support it in a future …
> fix: prevent catalogs using the `workspace:`, `link:`, and `file:` protocols

- .changeset/chatty-buses-cheer.md
- cli/default-reporter/src/reportError.ts
- pkg-manager/core/test/catalogs.ts
- pkg-manager/resolve-dependencies/src/resolveDependencies.ts
I'm predicting a common problem with the `catalog:` protocol will be users running `npm publish` instead of `pnpm publish`. I'd like to make errors related to this mistake more clear.
> fix: show better error when encountering external catalog protocol usage

- pkg-manager/core/test/catalogs.ts
- pkg-manager/resolve-dependencies/src/resolveDependencies.ts
In cases where multiple versions of a dependency are present in `pnpm-lock.yaml`, I believe users will expect dependencies using the `catalog:` protocol to all resolve to the same version.
In other words, a lockfile that looks like this would be surprising:
```yaml
importers:
project1:
dependencies:
'is-positive':
specifier: catalog:
version: 3.0.0
project3:
dependencies:
'is-positive':
specifier: catalog:
version: 3.1.0
```
If there's already a catalog resolution in the `pnpm-lock.yaml` file, use the version field.
```yaml
catalogs:
default:
'is-positive':
specifier: ^3.0.0
version: 3.0.0 # 👈 Pick this version when resolving.
```
> fix: reuse existing cataloged resolutions for consistency

- pkg-manager/core/test/catalogs.ts
- pkg-manager/resolve-dependencies/src/resolveDependencies.ts
When running `pnpm update` in this repo, pnpm looks for `execa@0.1.2` and 404s instead of looking for `safe-execa@0.1.2`.
This is because of a bug in my prior PR from a few days ago. 🤦🏻‍♂️
- https://github.com/pnpm/pnpm/pull/8259.
The repo uses the catalog specifier for `execa`. The change above isn't handling npm aliases correctly.
https://github.com/pnpm/pnpm/blob/a3d5f609d01be80582e52b48839aaddf8470562d/pnpm-workspace.yaml#L136
Using `replaceVersionInPref` to fix the bug above. This function handles `npm:` specifiers correctly.
We're currently using this function elsewhere for a very similar short-circuiting purpose.
https://github.com/pnpm/pnpm/blob/89363fa7dfa3e5c51c2cd17e715e8ff7fd7579f0/pkg-manager/resolve-dependencies/src/resolveDependencies.ts#L1200
> fix: reuse catalog resolutions of npm aliases correctly

- pkg-manager/core/test/catalogs.ts
- pkg-manager/resolve-dependencies/src/resolveDependencies.ts
- pkg-manager/resolve-dependencies/src/resolveDependencyTree.ts
- pkg-manager/resolve-dependencies/src/updateProjectManifest.ts
Running `pnpm update` reverts dependencies using the `catalog:` protocol back to their original version ranges. Credit to @KSXGitHub for finding this bug.
Note how `@pnpm/registry-mock` changes from `catalog:` to `^3.34.0` in the video below. (The `path-exists` dependency is actually untouched because it's configured in `pnpm.updateConfig.ignoreDependencies`.)
https://github.com/pnpm/pnpm/assets/906558/62961e3e-914b-4b65-8aa5-da848860a503
The `updateProjectManifest` function is generates a `specsToUpsert` array that determines the values in `package.json` after a `pnpm update`.
Updating this function to understand `catalog:` protocol dependencies.
Now that `updateProjectManifest` understands how to write `catalog:` protocol dependencies, this has the side effect of making `pnpm add …
> fix: preserve catalog protocol when updating project manifest

- pkg-manager/core/test/catalogs.ts
- pkg-manager/resolve-dependencies/src/resolveDependencies.ts
Running `pnpm update --latest` currently causes a consistency bug. Since `pnpm update` doesn't know how to update `pnpm-workspace.yaml` yet,
- The old specifier (ex: `^1.0.0`) of a cataloged dependency would still be present in `pnpm-workspace.yaml`,
- But the latest version (ex: `3.1.0`) would be present in `pnpm-workspace.yaml` and installed on disk.
Let's skip over `catalog:` protocol dependencies until `pnpm update` is refactored to handle `pnpm-workspace.yaml` edits in the future.
> fix: skip cataloged dependencies when running `pnpm update --latest`

- .changeset/wild-mayflies-compete.md
- exec/plugin-commands-script-runners/src/dlx.ts
- exec/plugin-commands-script-runners/test/dlx.createCacheKey.test.ts
- exec/plugin-commands-script-runners/test/dlx.e2e.ts
- pnpm-lock.yaml
- pnpm/test/dlx.ts
- store/plugin-commands-store/package.json
- store/plugin-commands-store/src/cleanExpiredDlxCache.test.ts
- store/plugin-commands-store/test/storePrune.ts
- store/plugin-commands-store/tsconfig.json
Different registries potentially return different packages for the same name, so reusing dlx cache for packages from a different registry would be incorrect.
> fix(dlx/cache): account for customized registries

- .changeset/calm-files-hide.md
- pkg-manager/plugin-commands-installation/src/install.ts
- pnpm-lock.yaml
- releasing/plugin-commands-deploy/package.json
- releasing/plugin-commands-deploy/src/deploy.ts
- releasing/plugin-commands-deploy/src/deployCatalogHook.ts
- releasing/plugin-commands-deploy/test/deploy.test.ts
- releasing/plugin-commands-deploy/test/deployCatalogHook.ts
- releasing/plugin-commands-deploy/tsconfig.json
Using [catalogs](https://pnpm.io/catalogs) breaks `pnpm deploy`. 🤦🏻‍♂️
There's a design problem between pnpm catalogs and `pnpm deploy` that makes this a bit hard to fix correctly.
- The `catalog:` protocol is intentionally only allowed to be used by "_importers_". External dependencies cannot use the `catalog:` protocol by design.
- When using `pnpm deploy`, dependency workspace packages are no longer considered "importers".
Using a `readPackage` hook that only runs within `pnpm deploy`.
This is a bit hacky and has the consequence of allowing the `catalog:` protocol to be usable by external dependencies. See a recent comment on the tradeoffs between this approach and an alternative: https://github.com/pnpm/pnpm/issues/8297#issuecomment-2219484009
> fix: install failure on pnpm deploy when using catalogs

- .changeset/quiet-wasps-melt.md
- exec/plugin-commands-script-runners/src/runRecursive.ts
Fixes #7608
-----
I originally reported the issue a few months ago. Now it's blocking our infrastructure plans so I put the time to fix it myself. This only adds a line that is likely forgotten in the [original implementation](https://github.com/pnpm/pnpm/commit/76aaead321cc10b0dea7ebba3e9a8e123bd82794#diff-c0a21f7925dd7f02d9af2aeb8297f31b6eb5a6bbe684bd7e2344a34f26bbd4e3 ).
The bug was that if you have recursive runs to `pnpm` or if a script in `package.json` calls `pnpm` again (_which probably is the same as recursive run_) then the calls don't respect the `--silent` argument.
I found the commit  by @zkochan from 4 years ago that made `silent` mode work: https://github.com/pnpm/pnpm/commit/76aaead321cc10b0dea7ebba3e9a8e123bd82794#diff-c0a21f7925dd7f02d9af2aeb8297f31b6eb5a6bbe684bd7e2344a3 …
> fix(plugin-commands-script-runners): align `runRecursive` with how `run` assigns silent loglevel

- .changeset/dull-rats-cheer.md
- __fixtures__/has-outdated-deps-using-catalog-protocol/.gitignore
- __fixtures__/has-outdated-deps-using-catalog-protocol/.npmrc
- __fixtures__/has-outdated-deps-using-catalog-protocol/node_modules/.modules.yaml
- __fixtures__/has-outdated-deps-using-catalog-protocol/node_modules/.pnpm/is-negative@1.0.0/node_modules/is-negative/index.js
- __fixtures__/has-outdated-deps-using-catalog-protocol/node_modules/.pnpm/is-negative@1.0.0/node_modules/is-negative/license
- __fixtures__/has-outdated-deps-using-catalog-protocol/node_modules/.pnpm/is-negative@1.0.0/node_modules/is-negative/package.json
- __fixtures__/has-outdated-deps-using-catalog-protocol/node_modules/.pnpm/is-negative@1.0.0/node_modules/is-negative/readme.md
- __fixtures__/has-outdated-deps-using-catalog-protocol/node_modules/.pnpm/is-negative@1.0.1/node_modules/is-negative/index.js
- __fixtures__/has-outdated-deps-using-catalog-protocol/node_modules/.pnpm/is-negative@1.0.1/node_modules/is-negative/license
- __fixtures__/has-outdated-deps-using-catalog-protocol/node_modules/.pnpm/is-negative@1.0.1/node_modules/is-negative/package.json
- __fixtures__/has-outdated-deps-using-catalog-protocol/node_modules/.pnpm/is-negative@1.0.1/node_modules/is-negative/readme.md
- __fixtures__/has-outdated-deps-using-catalog-protocol/node_modules/.pnpm/lock.yaml
- __fixtures__/has-outdated-deps-using-catalog-protocol/node_modules/is-negative
- __fixtures__/has-outdated-deps-using-catalog-protocol/package.json
- __fixtures__/has-outdated-deps-using-catalog-protocol/pnpm-lock.yaml
- __fixtures__/has-outdated-deps-using-catalog-protocol/pnpm-workspace.yaml
- pnpm-lock.yaml
- reviewing/outdated/package.json
- reviewing/outdated/src/outdated.ts
- reviewing/outdated/src/outdatedDepsOfProjects.ts
- reviewing/outdated/tsconfig.json
- reviewing/plugin-commands-outdated/src/outdated.ts
- reviewing/plugin-commands-outdated/test/index.ts
Dependencies using the `catalog:` protocol were accidentally skipped over in `pnpm outdated`.
For example, `cd pkg-manager/core && pnpm outdated` in this repo shows no output:
The `pnpm outdated` and `pnpm outdated --recursive` commands should now work as expected when using catalogs.
> fix: `pnpm outdated` should work with `catalog:` protocol

- .changeset/tall-shirts-scream.md
- cli/cli-utils/src/getConfig.ts
- cli/cli-utils/test/getConfig.test.ts
resolves https://github.com/pnpm/pnpm/issues/5682
Errors and warning should be printed to `stderr`, so that people can use the output in `stdout` in their scripts.
For example, with the changes in this PR `pnpm list --json | jq` will work as expected.
> fix: print warnings to stderr

- fs/find-packages/src/index.ts
I happened to notice this small opportunity for cleanup. This variable is always `undefined`, so there's no reason to include it. Further, I don't see it in the list of available `fast-glob` options: https://www.npmjs.com/package/fast-glob
> chore: remove always undefined variable

- .changeset/smooth-ravens-wave.md
- pkg-manifest/exportable-manifest/src/index.ts
- pkg-manifest/exportable-manifest/test/index.test.ts
fixed: #8355
- If dependencies and `peerDependencies` had the same package version specified, the version in `peerDependencies` would be `depSpec.replace` to change to the incorrect version.
- Fixed so that if peerDependencies specifies a version, it is fixed to that version.
example (before)
```typescript
// pkg-manifest/exportable-manifest/src/index.ts (replaceWorkspaceProtocolPeerDependency)
// depSpec: "workspace:^1.0.0"
// manifest.version: "2.0.0"
return depSpec.replace(
workspaceSemverRegex, // "workspace:^"
`${semverRangeToken}${manifest.version}` // "^2.0.0"
)
// "workspace:^1.0.0" -> "^2.0.01.0.0"
```
> fix(exportable-manifest): replace semver in peerDependency with workspace protocol

- .github/workflows/ci.yml
- .github/workflows/release.yml
- .npmrc
- package.json
It is convenient to automatically switch to the appropriate pnpm version when debugging source code locally.
> chore: add `packageManager` field

- .changeset/happy-dodos-shake.md
- pnpm/src/main.ts
This fixes installation with the standalone script from a directory that has a `package.json` with the `packageManager` field. pnpm was installing the version of pnpm specified in the `packageManager`
field due to  this issue.
close #8422
> fix(setup): never switch to a different CLI version during setup

- .changeset/light-walls-flash.md
- config/package-is-installable/src/checkPlatform.ts
- config/package-is-installable/test/checkPlatform.ts
pnpm currently have an issue when going through certain `package.json` properties when installing the dependency graph.
We, me and my colleague, encountered the issue when our CI pipeline suddenly went haywire during some repo maintenance. We started to see this:
The line where the exception throws is here:
https://github.com/pnpm/pnpm/blob/v9.7.1/config/package-is-installable/src/checkPlatform.ts#L70-L71
A bit of digging revealed that the [oxc-parser](https://github.com/oxc-project/oxc) npm package had a faulty specified `package.json` in one of their distributed platform targets [@oxc-parser/binding-win32-arm64-msvc](https://www.npmjs.com/package/@oxc-parser/binding-win32-arm64-msvc/v/0.24.2?activeTab=code)
It reads:
```json
{
"name": "@oxc-parser/binding-win32-arm64-msvc",
"version": …
```
> fix(package-is-installable): handle null values in wanted platform gracefully

- pnpm/test/run.ts
This should fix the failures like this:
> test: fix failures when retry downloading node

- .changeset/red-mice-compare.md
- __utils__/assert-project/src/index.ts
- __utils__/assert-store/src/index.ts
- exec/plugin-commands-rebuild/src/implementation/index.ts
- exec/plugin-commands-rebuild/test/index.ts
- modules-mounter/daemon/src/createFuseHandlers.ts
- pkg-manager/core/test/brokenLockfileIntegrity.ts
- pkg-manager/core/test/install/patch.ts
- pkg-manager/core/test/install/sideEffects.ts
- pkg-manager/headless/test/index.ts
- pkg-manager/package-requester/src/packageRequester.ts
- pnpm/test/install/misc.ts
- reviewing/license-scanner/src/getPkgInfo.ts
- reviewing/license-scanner/test/getPkgInfo.spec.ts
- store/cafs/src/getFilePathInCafs.ts
- store/package-store/src/storeController/prune.ts
- store/plugin-commands-store-inspecting/src/catIndex.ts
- store/plugin-commands-store-inspecting/src/findHash.ts
- store/plugin-commands-store-inspecting/test/findHash.ts
- store/plugin-commands-store/src/storeStatus/index.ts
- store/plugin-commands-store/test/storeAdd.ts
- store/plugin-commands-store/test/storePrune.ts
close #8204
Some registries allow identical content to be published under different package names or versions. To accommodate this, index files in the store are now stored using both the content hash and package identifier.
This approach ensures that we can:
1. Validate that the integrity in the lockfile corresponds to the correct package,
which might not be the case after a poorly resolved Git conflict.
2. Allow the same content to be referenced by different packages or different versions of the same package.
> feat: adding the package name into the index file name

- .changeset/shaggy-tools-jog.md
- pkg-manager/core/src/install/index.ts
> fix: don't print a warning when printing packages globally

- __utils__/test-fixtures/src/index.ts
- fs/indexed-pkg-importer/src/importIndexedDir.ts
- hooks/read-package-hook/src/createPackageExtender.ts
- lockfile/filtering/src/filterLockfileByImportersAndEngine.ts
- lockfile/pruner/src/index.ts
- lockfile/utils/src/extendProjectsWithTargetDirs.ts
- lockfile/walker/src/index.ts
- network/auth-header/test/removePort.test.ts
- pkg-manager/core/src/install/index.ts
- pkg-manager/core/src/uninstall/removeDeps.ts
- pkg-manager/get-context/src/index.ts
- pkg-manager/headless/src/index.ts
- pkg-manager/modules-cleaner/src/prune.ts
- pkg-manager/plugin-commands-installation/src/import/index.ts
- pkg-manager/resolve-dependencies/src/index.ts
- pkg-manager/resolve-dependencies/src/resolveDependencies.ts
- pkg-manager/resolve-dependencies/src/resolveDependencyTree.ts
- pkg-manager/resolve-dependencies/src/resolvePeers.ts
- pkg-manifest/exportable-manifest/src/overridePublishConfig.ts
- pkg-manifest/exportable-manifest/test/overridePublishConfig.test.ts
- pkg-manifest/manifest-utils/src/updateProjectManifestObject.ts
- releasing/plugin-commands-deploy/test/deploy.test.ts
- reviewing/dependencies-hierarchy/src/buildDependenciesHierarchy.ts
- reviewing/dependencies-hierarchy/src/getTree.ts
- reviewing/license-scanner/src/licenses.ts
- reviewing/plugin-commands-outdated/src/recursive.ts
- store/plugin-commands-store-inspecting/src/findHash.ts
- workspace/filter-workspace-packages/src/index.ts
Changes:
* Most `Object.keys(object).forEach` are replaced by `for in`.
* Most `array.filter(condition).forEach` are replaced by `for of` + `if (!condition) continue`.
* `return` in `forEach` callbacks are replaced by `continue`.
There may be minor improvement to memory footprint as this change would reduce the creations of temporary arrays and temporary functions.
> refactor: replace `forEach` with `for`-loops

- cli/default-reporter/src/reporterForClient/reportUpdateCheck.ts
`echo $PNPM_HOME`
gives output:
/Users/matthew/Library/pnpm
so the check `isExecutedByCorepack(opts.env)`
needs to come first to avoid the issue #8543
> fixes #8543: incorrect self update command provided

- .changeset/eight-comics-peel.md
- packages/render-peer-issues/src/index.ts
Similar issue to https://github.com/pnpm/pnpm/pull/7454
White text on light background for project name.
> Fix white text on light bg for render-peer-issues

- .changeset/silly-teachers-cry.md
- store/package-store/src/storeController/prune.ts
- store/plugin-commands-store/test/storePrune.ts
If you attempt to prune the store but the store doesn't yet exist:
```sh
mkdir store-prune-test
cd store-prune-test
corepack pnpm@9 init
corepack use pnpm@9
echo "store-dir=./store" > .npmrc
pnpm store prune
```
You'll receive the following error:
```sh
Removed all cached metadata files
 ENOENT  ENOENT: no such file or directory, scandir '/<HOME>/tmp/pnpm-no-modules/store/v3/files'
pnpm: ENOENT: no such file or directory, scandir '/<HOME>/tmp/pnpm-no-modules/store/v3/files'
at async Object.readdir (node:internal/fs/promises:950:18)
at async prune (/<HOME>/.cache/node/corepack/v1/pnpm/9.11.0/dist/pnpm.cjs:135292:21)
at async storePrune (/<HOME>/.cache/node/corepack/v1/pnpm/9.11.0/dist/pnpm.cjs:231814:7)
at async /<HOME>/.cache/node/corepack/v1/pnpm/9.11.0/dist/pnpm.cjs:234402:21
at async …
```
> fix(store prune): will not fail if store dir does not exist

- .changeset/grumpy-taxis-own.md
- cspell.json
- store/plugin-commands-store/src/cleanExpiredDlxCache.test.ts
- store/plugin-commands-store/src/cleanExpiredDlxCache.ts
Closes https://github.com/pnpm/pnpm/issues/8579
> fix: prevent `ENOENT` caused by parallel `store prune`

- .changeset/green-bikes-sparkle.md
- exec/plugin-commands-script-runners/src/dlx.ts
The error log from the [last CI failure](https://github.com/pnpm/pnpm/actions/runs/11167032739/job/31049686221?pr=8597):
```log
2024-10-03T21:08:32.6409045Z  EBUSY  EBUSY: resource busy or locked, unlink 'D:\a\pnpm\pnpm_tmp\101_4308\9\project\cache\dlx\v26vuq7etgal3io6jt4obph2cy\pkg'
2024-10-03T21:08:32.6410308Z
2024-10-03T21:08:32.6411283Z pnpm: EBUSY: resource busy or locked, unlink 'D:\a\pnpm\pnpm_tmp\101_4308\9\project\cache\dlx\v26vuq7etgal3io6jt4obph2cy\pkg'
2024-10-03T21:08:32.6412559Z     at async Object.unlink (node:internal/fs/promises:1066:10)
2024-10-03T21:08:32.6413401Z     at async forceSymlink (D:\a\pnpm\pnpm\pnpm\dist\pnpm.cjs:105133:7)
2024-10-03T21:08:32.6414373Z     at async Object.handler [as dlx] (D:\a\pnpm\pnpm\pnpm\dist\pnpm.cjs:224929:9) …
```
> fix: prevent `EBUSY` caused by parallel `dlx`

- .changeset/many-cycles-search.md
- lockfile/filtering/src/filterLockfileByImportersAndEngine.ts
- lockfile/plugin-commands-audit/src/audit.ts
Recently I encountered many Maximum call stack size exceeded errors for the toImporterDepPaths function when trying to add a package, in a repo that uses circular workspace deps.
This is only happening with a recent update, I had to use this patch to continue installing packages but did not manage to create a minimal repro.
> Fix maximum call stack size exceeded error related to circular workspace dependencies

- .changeset/forty-goats-exist.md
- packages/plugin-commands-setup/src/setup.ts
Here, using `$args` causes powershell to join the entire array of arguments into a single string, so we should expand the `args` array using the splat operator (`@`) to keep argument semantics.
Before:
```
PS > pnpx serve ./output
ERR_PNPM_SPEC_NOT_SUPPORTED_BY_ANY_RESOLVER  serve ./output isn't supported by any available resolver.
```
After:
```
PS > pnpx serve ./output
[ output omitted ]
```
> fix(windows): splat arguments for pnpx

- packages/dependency-path/README.md
It seems the `@pnpm/dependency-path` package _was_ previously published under just `dependency-path`, but is now published under `@pnpm/dependency-path`. Ideally the old one should be deprecated and pointed to this one.
> fix: unprefixed package name in readme

- .changeset/honest-fans-sip.md
- config/config/src/index.ts
> feat!: remove prettier and eslint from the default value of public-hoist-pattern

- .changeset/olive-pants-know.md
- store/cafs/src/getFilePathInCafs.ts
> fix: detecting files with executable permissions in side effects cache

- .changeset/smart-flowers-cheat.md
- exec/plugin-commands-rebuild/test/index.ts
- pkg-manager/core/test/install/patch.ts
- pkg-manager/core/test/install/sideEffects.ts
- pkg-manager/headless/test/index.ts
- reviewing/license-scanner/src/getPkgInfo.ts
- store/cafs-types/src/index.ts
- store/cafs/src/addFilesFromDir.ts
- store/cafs/src/checkPkgFilesIntegrity.ts
- store/cafs/src/index.ts
- store/create-cafs-store/src/index.ts
- store/plugin-commands-store-inspecting/src/findHash.ts
- store/server/test/index.ts
- worker/src/worker.ts
The previous structure of the index file:
```
{
"files": {
"<filePath>": {<fileInfo>}
},
"sideEffects": {
"<key>": {
"<filePath>": {<fileInfo>}
}
}
}
```
Side effects listed all the files not just those created by postinstall scripts.
The new format will save a diff instead:
```
{
"files": {
"<filePath>": {<fileInfo>}
},
"sideEffects": {
"<key>": {
"deleted": [<list of deleted files>],
"added": {
"<filePath>": {<fileInfo>} // added or modified files
}
}
}
}
```
> feat!: don't duplicate all file entries in the side effects section of the index file

- CONTRIBUTING.md
Updating the environment setup directions in  `CONTRIBUTING.md` for Git LFS, which is now used for some tests.
- Prior PR: https://github.com/pnpm/pnpm/pull/8509
> Update `CONTRIBUTING.md` for Git LFS

- .changeset/friendly-meals-kick.md
- pkg-manager/get-context/src/index.ts
Return value is `{ question: boolean }` (where `question` is the string given for argument `name`), not `boolean`.
Previously `node_modules` would be purged no matter what answer is given.
Discovered while investigating #8654
> fix: properly check modules purge confirmation answer

- package.json
- pnpm-lock.yaml
- replace `@babel/plugin-proposal-dynamic-import` with `@babel/plugin-transform-dynamic-import`
I noticed the following deprecation warning when running `pnpm install` in the `pnpm` repository:
```
WARN  deprecated @babel/plugin-proposal-dynamic-import@7.18.6: This proposal has been merged to the ECMAScript standard and thus this plugin is no longer maintained. Please use @babel/plugin-transform-dynamic-import instead.
```
On a related note, I don't see any `babel.config.json` or similar usage that would indicate that the babel dependencies are even used? Possibly they could be removed instead?
> chore: replace deprecated babel-plugin-proposal-dynamic-import

- .meta-updater/src/index.ts
- pnpm/package.json
This further specification of npm's ["repository"](https://docs.npmjs.com/cli/v10/configuring-npm/package-json#repository) key allows tools like @renovate-bot to locate the precise package and report on the CHANGELOG.md w/in its auto-generated dependency upgrade reports.
Currently:
Afterwards, that disclosure will include the diff of the changes between the versions being upgraded between
Ex from vitest:
> chore: add "directory" to package.json "repository"

- pnpm/src/main.ts
- pnpm/test/cli.ts
- pnpm/test/install/hooks.ts
- pnpm/test/install/misc.ts
- pnpm/test/monorepo/index.ts
Command-line utilities typically write error messages, including usage/help messages for invalid options, to the standard error (`stderr`).  This ensures that the standard output (`stdout`) remains clean and is especially important if the output is expected to be read by other tools.
For example, if I run `grep --invalid-opt`, all the following gets written to `stderr`, and nothing to `stdout`:
```
grep: unrecognized option '--invalid-opt'
Usage: grep [OPTION]... PATTERNS [FILE]...
Try 'grep --help' for more information.
```
This pattern is followed by most common utilities like `cd`, `ls`, `find`, and `tar` to name a few off the top of my head.
Recently, I ran into some cryptic errors when I launched my terminal:
```
bash:  ERROR : command not found...
bash: For: command not found...
``` …
> fix(pnpm): change `printError` to write to `stderr` instead of `stdout`

- env/path/src/index.ts
While investigating a separate bug (https://github.com/pnpm/pnpm/pull/8679), I noticed we could remove usages of `!` in `prependDirsToPath`.
No changeset in this PR since it should be a no-op.
> refactor: remove `!` usages from `prependDirsToPath`

- .changeset/lemon-sheep-rhyme.md
- .changeset/quiet-carrots-march.md
- crypto/polyfill/README.md
- crypto/polyfill/package.json
- crypto/polyfill/src/index.ts
- crypto/polyfill/tsconfig.json
- crypto/polyfill/tsconfig.lint.json
- packages/crypto.base32-hash/package.json
- packages/crypto.base32-hash/src/index.ts
- pkg-manager/core/package.json
- pkg-manager/core/src/install/index.ts
- pkg-manager/core/tsconfig.json
- pnpm-lock.yaml
- resolving/npm-resolver/package.json
- resolving/npm-resolver/src/pickPackage.ts
- resolving/npm-resolver/tsconfig.json
- reviewing/list/package.json
- reviewing/list/src/pruneTree.ts
- reviewing/list/tsconfig.json
- worker/package.json
- worker/src/worker.ts
- worker/tsconfig.json
`crypto.hash` seems to be faster than `crypto.createHash`.
https://nodejs.org/docs/latest-v20.x/api/crypto.html#cryptohashalgorithm-data-outputencoding
> perf: use `hash` to replace `createHash`

- pnpm/bundle.ts
Fix esbuild external  warning while running `pnpm run compile`, no changeset needed
```
▲ [WARNING] "./get-uid-gid.js" should be marked as external for use with "require.resolve" [require-resolve-not-external]
```
> chore: fix esbuild external warning

- .changeset/great-onions-matter.md
- .changeset/swift-panthers-matter.md
- pnpm/src/switchCliVersion.ts
- pnpm/test/switchingVersions.test.ts
I recently updated my pnpm git clone and ran:
```sh
❯ pnpm install
```
This hung for 10+ minutes and ended up [fork bombing](https://en.wikipedia.org/wiki/Fork_bomb) my laptop. My laptop became unusable and crashed. Note the 13GB+ of swap used and hundreds of `pnpm` processes.
This took me a bit to root cause, but what was happening was the `.tools/9.12.0` directory had a partial download.
Here's the **bad state**:
```
❯ tree -L2 ~/Library/pnpm/.tools/@pnpm+macos-arm64/9.12.0
/Users/gluxon/Library/pnpm/.tools/@pnpm+macos-arm64/9.12.0
├── node_modules
└── package.json
```
Here's what a **good state** is supposed to look like:
```
❯ tree -L2 ~/Library/pnpm/.tools/@pnpm+macos-arm64/9.12.0
/Users/gluxon/Library/pnpm/.tools/@pnpm+macos-arm64/9.12.0
├── bin
│   └── pnpm
├── node_modules
│   └── …
```
> fix: fork bomb when pnpm self-manages its version

- .changeset/soft-kids-build.md
- store/cafs/src/writeBufferToCafs.ts
On running addFilesFromTarball with many workers in the pool there were sometimes race conditions on moving files having same content. It resulted in ERR_PNPM_ENOENT and ERR_PNPM_TARBALL_EXTRACT exceptions during install. The issue was introduced in v8.7.0 and generated many defect reports.
Closes #7676, potentially #7607, #7697 and others
> fix(cafs): avoid race on extracting files from tarballs

- .changeset/shaggy-poems-appear.md
- pkg-manager/plugin-commands-installation/src/link.ts
- pkg-manager/plugin-commands-installation/test/link.ts
`pnpm link --global`  should print ERR_PNPM_NO_GLOBAL_BIN_DIR error when global bin directory is not found. Fow now, it prints nothing.
> fix: print ERR_PNPM_NO_GLOBAL_BIN_DIR error  when global bin directory is not found

- README.md
- __utils__/get-release-text/src/main.ts
- pnpm/README.md
Selecting the logo image enables us to copy the alt text.
---
**What**:
Improving accessibility and usability.
**Why**:
The links to logo images on GitHub are unnecessary.
Additionally, improve semantics.
**How**:
1. Add h1 heading
2. Remove link to image on GitHub (_ref:_ https://stackoverflow.com/a/48744957/9287284)
3. Set alt text
> ♿️ Add alt text to README pnpm logo

- .changeset/tricky-crabs-yell.md
- pkg-manager/plugin-commands-installation/src/add.ts
- pkg-manager/plugin-commands-installation/test/add.ts
- pnpm-lock.yaml
- pnpm/package.json
- pnpm/src/main.ts
- pnpm/test/install/selfUpdate.ts
We have now a dedicated command for installing pnpm (`pnpm self-update`) and we use a special directory to store the different versions of pnpm. Hence it doesn’t make sense to allow installing pnpm globally.
In the future we will probably also rewrite the way global packages are installed. But probably not in scope of pnpm v10.
> fix!: do not allow to install pnpm globally via pnpm add

- .changeset/orange-flies-hammer.md
- .changeset/rotten-olives-visit.md
- pkg-manager/headless/src/index.ts
- pkg-manager/headless/test/fixtures/simple-with-patch/package.json
- pkg-manager/headless/test/fixtures/simple-with-patch/patches/is-positive.patch
- pkg-manager/headless/test/fixtures/simple-with-patch/pnpm-lock.yaml
- pkg-manager/headless/test/index.ts
Resolves #8726 by adding a guard present in non-headless install code path to the headless variant.
> fix: headless install crash when modules dir disabled and patches listed

- .changeset/large-buses-destroy.md
- pnpm-lock.yaml
- releasing/plugin-commands-publishing/package.json
- releasing/plugin-commands-publishing/src/pack.ts
- releasing/plugin-commands-publishing/test/pack.ts
close #8676 
It's useful to display packed files since `pnpm pack` only shows tarball filename now
> feat: display packed files list in `pnpm pack`

- exec/plugin-commands-script-runners/src/dlx.ts
- exec/plugin-commands-script-runners/test/dlx.e2e.ts
- exec/plugin-commands-script-runners/test/utils/index.ts
Prior to this commit, if `symlink` was set to `false` (such as in an RC file), `dlx` would throw `ENOENT` because it expected the `node_modules/the-package` symlink to exist:
```console
$ pnpm config get symlink
false
$ rm -rf ~/.cache/pnpm/
$ pnpm dlx the-package
Packages: +1
+
Progress: resolved 1, reused 1, downloaded 0, added 1, done
 ENOENT  ENOENT: no such file or directory, open '/home/${USER}/.cache/pnpm/dlx/.../
node_modules/the-package/package.json'
```
This commit filters the `symlink` option before installing the package, allowing the symlink to be created, preventing the error.
Fixes #8732.
> fix(dlx): `ENOENT` when `symlink=false` (#8732)

- pnpm/bin/pnpm.cjs
I set up completions using
```sh
source <(pnpm completion zsh)
```
Which causes confusing output
```
zsh: command not found: ERROR:
zsh: command not found: The
zsh: command not found: Visit
```
> fix: output compatibility error to stderr instead of stdout

- pnpm/bin/pnpm.cjs
The enableCompileCache function is a new api in [Nodejs 22 LTS](https://nodejs.org/docs/latest/api/module.html#module-compile-cache) which can speed up the startup time of CLI.
On my laptop, `pnpm -v` costs 650ms and it was 930ms before.
As a reference for a mature project, [TypeScript 5.7 support V8 compile caching in Node.js](https://devblogs.microsoft.com/typescript/announcing-typescript-5-7-rc/#support-for-v8-compile-caching-in-node.js)
> perf: use enableCompileCache in node.js 22

- .changeset/ten-socks-cross.md
- packages/plugin-commands-init/src/init.ts
- packages/plugin-commands-init/test/init.test.ts
It's inconvenient to init project in monorepo via pnpm since `pnpm init` doesn't respect either `--dir` option nor `recursive` option. Both of them will return error if you run init in a monorepo root directory: 
```
ERROR  Unknown option: 'recursive'
```
```
ERR_PNPM_PACKAGE_JSON_EXISTS  package.json already exists
```
This pr allows `pnpm init` to recognize `--dir` option
> fix(init): --dir option should be respected

- .changeset/serious-yaks-dance.md
- pnpm/test/install/misc.ts
- resolving/tarball-resolver/src/index.ts
- resolving/tarball-resolver/test/index.ts
Before determine the URL type, encode the hash if it contains a slash. 
Fix: #7697
> fix: `ERR_PNPM_TARBALL_EXTRACT` when the URL's hash contains a slash

- .changeset/seven-sheep-reflect.md
- config/package-is-installable/src/index.ts
- env/system-node-version/src/index.ts
- env/system-node-version/test/getSystemNodeVersion.test.ts
> fix: don't crash when use-node-version is set and there is no node.js

- pkg-manager/real-hoist/src/index.ts
- pkg-manager/real-hoist/tsconfig.json
- pnpm-lock.yaml
- pnpm-workspace.yaml
Replace `@yarnpkg/nm` import with direct `@yarnpkg/nm/hoist` import and remove a large unused code subtree
Refs: https://github.com/yarnpkg/berry/pull/6611
Two commits so that the first one can be tested individually if needed -- it produces no changes in the `dist`
Before: `9563553` bytes, after: `8920653` bytes for `dist/pnpm.cjs`
More reduction is possible (to ~`7551098` bytes, ~21% total) by fixing other usused yarnpkg imports, but let's start with this one
> fix: ~7% smaller bundle size by not packing unneeded yarnpkg/nm subdeps

- .changeset/weak-peaches-sip.md
- __fixtures__/has-outdated-deps-using-npm-alias/.gitignore
- __fixtures__/has-outdated-deps-using-npm-alias/.npmrc
- __fixtures__/has-outdated-deps-using-npm-alias/node_modules/.modules.yaml
- __fixtures__/has-outdated-deps-using-npm-alias/node_modules/.pnpm/is-negative@1.0.0/node_modules/is-negative/index.js
- __fixtures__/has-outdated-deps-using-npm-alias/node_modules/.pnpm/is-negative@1.0.0/node_modules/is-negative/license
- __fixtures__/has-outdated-deps-using-npm-alias/node_modules/.pnpm/is-negative@1.0.0/node_modules/is-negative/package.json
- __fixtures__/has-outdated-deps-using-npm-alias/node_modules/.pnpm/is-negative@1.0.0/node_modules/is-negative/readme.md
- __fixtures__/has-outdated-deps-using-npm-alias/node_modules/.pnpm/lock.yaml
- __fixtures__/has-outdated-deps-using-npm-alias/node_modules/is-negative-alias
- __fixtures__/has-outdated-deps-using-npm-alias/package.json
- __fixtures__/has-outdated-deps-using-npm-alias/pnpm-lock.yaml
- reviewing/outdated/src/outdated.ts
- reviewing/plugin-commands-outdated/test/index.ts
Fixes https://github.com/pnpm/pnpm/issues/8566.
This bug only manifests when `opts.compatible` is `true`. In this case we were using `allDeps[name]` instead of the catalog-resolved `pref` constant computed earlier in the same function.
https://github.com/pnpm/pnpm/blob/d2e83b0f3ecbb22aafac3269fb9768ed44ce1102/reviewing/outdated/src/outdated.ts#L158
I think `allDeps[name]` was incorrect to use originally. Even before catalogs support was added to the `outdated` command, it should have been `allDeps[alias]`.
The `allDeps[name]` lookup would become `undefined` when using npm aliases. I've added a new test around this.
Although this makes `pnpm update --interactive` no longer crash, updating dependencies using catalogs still isn't possible until https://github.com/pnpm/pnpm/issues/8641 is …
> fix: catalogs exception when running `pnpm outdated` with `--compatible` flag

- .changeset/little-pears-push.md
- pkg-manager/core/src/install/index.ts
- pkg-manager/core/src/parseWantedDependencies.ts
- pkg-manager/core/test/catalogs.ts
`pnpm add` use `catalog:` if the dependency is in the default catalog
Closes #8640
> feat(add): `pnpm add` should use the default catalog

- .changeset/hip-rats-love.md
- pkg-manager/plugin-commands-installation/src/remove.ts
- pkg-manager/plugin-commands-installation/test/remove/workspace.ts
Closes #7674, by ensuring that `linkWorkspacePackagesDepth` is passed to the single project version of the `remove` command.
This started out by writing a test, but then I spotted the relevant part for the single run codepath, and the title has been updated as appropriate.
---
Original description:
This PR adds tests for https://github.com/pnpm/pnpm/issues/7674, and more specifically the reproduction mentioned in https://github.com/pnpm/pnpm/issues/7674#issuecomment-2546429388 and at https://github.com/vluoto/pnpm-remove-link-workspace-packages-false.
This is my first direct contribution to pnpm, and I might have missed a lot of things, regarding the test structure or the expectations. I used `pkg-manager/plugin-commands-installation/test/miscRecursive.ts` as my guide for these tests, and …
> fix(remove): ensure that link-workspace-packages=false is respected in single project runs in a workspace

- .changeset/large-steaks-rhyme.md
- releasing/plugin-commands-publishing/src/pack.ts
- releasing/plugin-commands-publishing/test/pack.ts
This PR allows specifying the desired output path when running the `pnpm pack` command, e.g., `pnpm pack --out my-package.tgz` or `pnpm pack --out ./some-dir/%s.tgz`. Yarn also has a similar feature: https://yarnpkg.com/cli/pack#details
Closes https://github.com/pnpm/pnpm/issues/7834
> feat: add support for specifying a custom output path in the pack command

- .changeset/tiny-pianos-mate.md
- config/config/src/getOptionsFromRootManifest.ts
- exec/plugin-commands-rebuild/test/index.ts
- pnpm/test/install/global.ts
- pnpm/test/install/lifecycleScripts.ts
- pnpm/test/monorepo/index.ts
By default no dependency is allowed to run lifecycle scripts during installation.
> feat!: use an allow list of built dependencies by default

- .changeset/loud-pans-matter.md
- resolving/git-resolver/src/parsePref.ts
- resolving/git-resolver/test/index.ts
- resolving/git-resolver/test/parsePref.test.ts
In the case where:
1. No git auth token was specified by the user
2. The package requested to be fetched via https
3. The user does not have SSH access to the repo but has HTTPS access
4. The package was hosted in a private GitHub repo
pnpm would fallback to using SSH since it was a "likely private repo" and would fail to resolve the package. Now, rather than only checking if there is an auth token specified, it also checks both:
1. Is the repo private
2. Does the user have access to ls-remote it.
And if these conditions are true, it tries to use https anyway.
This matches the behavior of npm and Yarn berry. Yarn classic also has this bug, and there's a code comment that alludes to it.
> fix(git-resolver): handle private git repo resolution

- .changeset/eleven-cameras-invite.md
- releasing/plugin-commands-publishing/src/pack.ts
Regression #3608.
Missing end of line anchors in regex (`$`) will cause every files under package root that has prefixed `package.(json|json5|yaml)` being matched and replaced with `package.json`:
```
/^package\/package\.(json|json5|yaml)/.test("package/package.json.meta")
true
/^package\/package\.(json|json5|yaml)/.test("package/package.yamlol")
true
/^package\/package\.(json|json5|yaml)/.test("package/package.json567")
true
```
> fix(pack): missing end of line anchor in package.json regex filter

- .changeset/friendly-tips-rest.md
- .changeset/serious-swans-wonder.md
- .changeset/shy-hounds-wave.md
- pkg-manager/package-requester/src/packageRequester.ts
- pkg-manager/package-requester/test/index.ts
- pkg-manager/resolve-dependencies/src/resolveDependencies.ts
- pnpm/test/monorepo/dedupePeers.test.ts
- store/store-controller-types/src/index.ts
This PR is a follow-up to https://github.com/pnpm/pnpm/pull/8905.
After merging the PR to fix `pnpm update --filter` changing unrelated projects, I started going through the issue tracker around recursive `update`, to see whether other scenarios would be fixed by those changes. 
There are a handful of issues (https://github.com/pnpm/pnpm/issues/8661, https://github.com/pnpm/pnpm/issues/8329, https://github.com/pnpm/pnpm/issues/8772) that fit the bill, though not all of them with minimal reproductions (especially with regard to listing the `.npmrc` settings). Folks in those issues dicuss the `--interactive` flag, but I was able to reproduce the issue with a non-interactive recursive update and `dedupe-peer-dependents=true`.
The root cause seems similar to #8905: …
> fix: ensure that recursive `pnpm update --latest <pkg>` updates only the specified package

- .changeset/shaggy-news-tickle.md
- exec/build-modules/src/index.ts
- pkg-manager/core/test/install/patch.ts
> fix: don't print patched dependencies in list of non-built deps

- .github/workflows/update-latest.yml
Update to `vedantmgoyal9/winget-releaser@main`, which should hopefully fix the CI errors. Manually created a PR to winget-pkgs for now (and added the `arm64` binary): https://github.com/microsoft/winget-pkgs/pull/213396
> ci: update winget releaser action

- .changeset/happy-bottles-greet.md
- packages/types/src/package.ts
- releasing/plugin-commands-deploy/src/createDeployFiles.ts
Fixes https://github.com/pnpm/pnpm/issues/8962
> fix: deploy should maintain `type` on new manifest

- .changeset/ninety-countries-dance.md
- pnpm-lock.yaml
- resolving/git-resolver/__mocks__/@pnpm/fetch.js
- resolving/git-resolver/package.json
- resolving/git-resolver/src/index.ts
- resolving/git-resolver/src/parsePref.ts
- resolving/git-resolver/test/index.ts
- resolving/git-resolver/test/parsePref.test.ts
Change to respect proxy settings when resolving git dependancies.
To do this, I have exchanged to `fetchWithAgent` instead of `fetch` and pass down pnpm options.
close: #6530
> feat(git-resolver): respect proxy settings when resolving git

- store/cafs/src/parseTarball.ts
ts can infer the type of the constant based on the assignment, without requiring additional type declarations.
> chore: remove unnecessary number type

- .changeset/loud-weeks-camp.md
- pkg-manifest/read-project-manifest/package.json
- pkg-manifest/read-project-manifest/src/index.ts
- pnpm-lock.yaml
- pnpm-workspace.yaml
Replaced `lodash.clonedeep` with the built-in `structuredClone` supported [from Node 17.0.0](https://developer.mozilla.org/en-US/docs/Web/API/Window/structuredClone#browser_compatibility).
I initially created a discussion regarding some dependency cleanup (https://github.com/orgs/pnpm/discussions/9012), but I figured it wouldn't hurt to make a PR for such a tiny change.
> chore: replace `lodash.clonedeep` with the built-in `structuredClone`

- .changeset/proud-crabs-own.md
- pkg-manager/core/src/install/link.ts
> fix: don't read from side-effects cache packages that aren't allowed to be built

- .changeset/gold-cameras-talk.md
- cli/default-reporter/src/reporterForClient/reportUpdateCheck.ts
- cli/default-reporter/test/__snapshots__/reportingUpdateCheck.ts.snap
The previous instructions did not actually update the pnpm version used by corepack in the local project.
See https://github.com/nodejs/corepack/issues/587
> fix: correct corepack self-update instructions

- .changeset/smooth-geckos-jog.md
- pkg-manager/core/src/install/index.ts
- pkg-manager/core/test/catalogs.ts
Fixes a bug originally reported by @sergioflores-j.
- https://github.com/pnpm/pnpm/issues/8638.
When users change the catalog configuration in `pnpm-workspace.yaml`, the catalog resolution process relies on `forgetResolutionsOfPrevWantedDeps()` being called to know which catalog protocol usages have changed. This function is correctly called in the regular non-filtered code path, but was missed in installation code path for `--filter` installs.
This was a mistake I made when implementing catalogs originally.
Let's call `forgetResolutionsOfPrevWantedDeps()` on filtered installs too.
There's likely some refactor to the filtered install code path we could do to make sure these types of bugs are harder to make for others in the future.
I was able to reproduce the issue locally end-to-end. The …
> fix: stale catalog protocol reference on filtered install

- pkg-manager/core/src/install/index.ts
There's a large block of code in `mutateModules()`'s inner `_install()` function that's responsible for performing an installation when the `pnpm-lock.yaml` file is "_up to date_". This PR attempts a few refactors to make that code block easier to understand.
The block of code in question starts with a large if-statement here:
https://github.com/pnpm/pnpm/blob/2d16f7a4a945b3c24936cb5eacf55283aa40d3ab/pkg-manager/core/src/install/index.ts#L410-L434
This PR mostly moves the frozen install code into its own function and adds more comments to it. I'm hoping this makes it easier for others to see the intention of this code in the future.
If I've done this refactor correctly, there should be no differences in pnpm's runtime behavior. Everything should run behave exactly the same.
- Each …
> refactor: make frozen install logic clearer

- .changeset/lemon-schools-jog.md
- cli/default-reporter/src/reportError.ts
Fixing a minor bug I noticed while working on a different issue. We can probably omit the `@undefined` part of the package ID when there's no `version`.
> fix: avoid printing undefined for package version when reporting error

- .changeset/rare-avocados-listen.md
- pkg-manager/core/src/install/index.ts
- pkg-manager/core/test/catalogs.ts
Fixes:
- https://github.com/pnpm/pnpm/issues/8639
This PR looks a bit strange because it's only removing code, but I think it's the right fix. I could use help code reviewing to make sure though. Here's my thought process:
Within the `installInContext` function, there seems to be a second attempt at performing a frozen install. This happens after the `tryFrozenInstall` function bails out.
https://github.com/pnpm/pnpm/blob/43681529cfa70da4f8256512522894683d3453b9/pkg-manager/core/src/install/index.ts#L1436-L1451
I believe we can remove the secondary frozen install here without affecting performance. For a filtered install:
- If the lockfile is up to date, the standard `tryFrozenInstall` function will still be used.
- If the lockfile needs updates, we use the existing code path to compute …
> fix: catalog snapshots removed on filtered install with `--fix-lockfile`

- .changeset/rare-avocados-listen.md
- pkg-manager/core/src/install/index.ts
- pkg-manager/core/test/catalogs.ts
This is a backport of https://github.com/pnpm/pnpm/pull/9126 for the v9 branch.
There were a merge conflict cherry-picking https://github.com/pnpm/pnpm/commit/41dada429bff5be4391516fd82dbd442f6ca38f5 due to some changes to `injectWorkspacePackages` and `ignoredBuilds` in this function.
To fix, I manually performed the same code edits again rather than try to resolve the conflict.
I also ran a quick `git diff` of the `installInContext` function on `v9` and `main` to make sure I resolved the merge conflicts correctly.
> fix: catalog snapshots removed on filtered install with --fix-lockfile (v9)

- .changeset/dirty-rules-exercise.md
- pnpm/src/main.ts
- pnpm/test/link.ts
This adds a special treatment to the link command in main.ts
Fixes https://github.com/pnpm/pnpm/issues/4296
> fix: pnpm link: imply global mode when no arguments are specified

- .changeset/strange-tigers-dress.md
- pkg-manager/core/test/catalogs.ts
- pkg-manager/plugin-commands-installation/src/installDeps.ts
- releasing/plugin-commands-deploy/src/deploy.ts
Fixes:
- https://github.com/pnpm/pnpm/issues/9112
For accurate `pnpm-lock.yaml` updates on a filtered install, catalogs relies on `ctx.projects` here to be all projects in the workspace. This supports a code path to compute the full `pnpm-lock.yaml` file before performing mutating modules on a filtered install.
https://github.com/pnpm/pnpm/blob/41dada429bff5be4391516fd82dbd442f6ca38f5/pkg-manager/core/src/install/index.ts#L1433
It turns out this is only the case if `dedupe-peer-dependents` is enabled. I missed this since `dedupe-peer-dependents` defaults to `true`.
https://github.com/pnpm/pnpm/blob/76973d8c81cde9de5174f219e6ff2486a9dc53b2/pkg-manager/plugin-commands-installation/src/installDeps.ts#L222-L227
For completeness, here's where `allProjectsGraph` becomes `ctx.allProjects` …
> fix: catalog snapshots removed on filtered install with `dedupe-peer-dependents=false`

- .changeset/common-pugs-flash.md
- .changeset/empty-windows-ring.md
- crypto/hash/package.json
- crypto/hash/src/index.ts
- crypto/hash/test/index.ts
- crypto/hash/tsconfig.json
- lockfile/verification/package.json
- lockfile/verification/src/allProjectsAreUpToDate.ts
- lockfile/verification/src/index.ts
- lockfile/verification/src/localTarballDepsAreUpToDate.ts
- lockfile/verification/test/allProjectsAreUpToDate.test.ts
- lockfile/verification/tsconfig.json
- pnpm-lock.yaml
- resolving/local-resolver/package.json
- resolving/local-resolver/src/index.ts
- resolving/local-resolver/tsconfig.json
Today, adding a local tarball dependency to a project makes `pnpm install` significantly slower on every subsequent run.
This is because part of the logic determining whether the `pnpm-lock.yaml` file is up to date returns false if any project in the workspace uses a `file:` dependency on a tarball. The `allProjectsAreUpToDate` function doesn't check if contents of the tarball to see if the tarball has changed since the last installation.
Updating `allProjectsAreUpToDate` to check if the referenced tarball has changed on disk.
If the tarball is unchanged, this results in a significant performance improvement during installation. In a large project I work on, this reduced installation time from 70s to 10s when the lockfile doesn't need to be updated.
> feat: support frozen installs in projects using local tarball dependencies

- .meta-updater/src/index.ts
- env/plugin-commands-env/src/parseNodeSpecifier.ts
- eslint.config.mjs
- exec/pkg-requires-build/src/index.ts
- fetching/tarball-fetcher/src/localTarballFetcher.ts
- lockfile/fs/src/gitBranchLockfile.ts
- lockfile/fs/src/gitMergeFile.ts
- lockfile/fs/src/lockfileFormatConverters.ts
- lockfile/fs/src/lockfileName.ts
- package.json
- packages/dependency-path/src/index.ts
- patching/plugin-commands-patching/src/patchCommit.ts
- patching/plugin-commands-patching/test/patch.test.ts
- pkg-manager/core/src/install/link.ts
- pkg-manager/plugin-commands-installation/src/import/yarnUtil.ts
- pkg-manager/plugin-commands-installation/src/link.ts
- pkg-manager/plugin-commands-installation/test/add.ts
- pkg-manifest/exportable-manifest/src/index.ts
- pnpm-lock.yaml
- pnpm/test/run.ts
- releasing/plugin-commands-publishing/src/pack.ts
- resolving/git-resolver/src/index.ts
- resolving/local-resolver/src/parsePref.ts
- resolving/npm-resolver/src/fetch.ts
- reviewing/license-scanner/src/getPkgInfo.ts
- reviewing/list/src/renderTree.ts
- store/plugin-commands-store-inspecting/src/catFile.ts
- worker/src/worker.ts
- workspace/spec-parser/src/index.ts
1. Reduce unnecessary capture groups.
2. Replace a single character set.
3. Use `i` flag.
4. Use 	`\d` or `\w` to replace range characters.
5. add eslint plugin https://github.com/ota-meshi/eslint-plugin-regexp
> refactor: improve regexp

- .changeset/orange-lights-wish.md
- pkg-manager/plugin-commands-installation/src/update/getUpdateChoices.ts
A deprecation mark is added based on the original logic to prompt the user.
close #9206
> fix: update choice list not show deprecated pkg

- cli/default-reporter/test/filterLogHook.ts
- cli/default-reporter/test/index.ts
- cli/default-reporter/test/reportingContext.ts
- cli/default-reporter/test/reportingDeprecations.ts
- cli/default-reporter/test/reportingErrors.ts
- cli/default-reporter/test/reportingExecutionTime.ts
- cli/default-reporter/test/reportingLifecycleScripts.ts
- cli/default-reporter/test/reportingPeerDependencyIssues.ts
- cli/default-reporter/test/reportingProgress.ts
- cli/default-reporter/test/reportingRequestRetry.ts
- cli/default-reporter/test/reportingScope.ts
- cli/default-reporter/test/reportingUpdateCheck.ts
This PR should be easier to review by looking at each commit individually.
I've isolated each type of refactor into its own commit, making it easier to scroll through the changes to make sure refactors of each type were done correctly.
---
The tests in the `cli/default-reporter` package are silently failing. **They always pass, even if the `expect(...).toBe(...)` statements fail.**
One easy way to reproduce this is by setting `jest.retryTimes(0)` here:
https://github.com/pnpm/pnpm/blob/58d859793f8238a6e78aaae57e0727508ad7a29a/__utils__/jest-config/setupFilesAfterEnv.js#L3
And adding `test.only` here:
https://github.com/pnpm/pnpm/blob/58d859793f8238a6e78aaae57e0727508ad7a29a/cli/default-reporter/test/reportingLifecycleScripts.ts#L29
If you run:
```console
❯ cd cli/default-reporter
❯ pnpm …
```
> test: fix silently failing tests in `default-reporter` package

- __utils__/jest-config/setupFilesAfterEnv.js
- cli/default-reporter/test/filterLogHook.ts
- cli/default-reporter/test/index.ts
- cli/default-reporter/test/reportingContext.ts
- cli/default-reporter/test/reportingDeprecations.ts
- cli/default-reporter/test/reportingErrors.ts
- cli/default-reporter/test/reportingExecutionTime.ts
- cli/default-reporter/test/reportingLifecycleScripts.ts
- cli/default-reporter/test/reportingPeerDependencyIssues.ts
- cli/default-reporter/test/reportingProgress.ts
- cli/default-reporter/test/reportingRequestRetry.ts
- cli/default-reporter/test/reportingScope.ts
- cli/default-reporter/test/reportingUpdateCheck.ts
I strongly believe we should turn off `jest.retryTimes` globally. Retrying every test can hide buggy tests that should be fixed instead.
We can always add `jest.retryTimes(1)` to individual `.ts` test files that are failing in the future, but I do believe it shouldn't be the global default for all tests.
I've fixed a lot of flaking tests in the last year! I think we're now in a good state to turn off retries. 😊
- https://github.com/pnpm/pnpm/pull/9253
- https://github.com/pnpm/pnpm/pull/7472
- https://github.com/pnpm/pnpm/pull/7445
- https://github.com/pnpm/pnpm/pull/7346
> test: turn off test retries since they can hide buggy tests

- .changeset/old-emus-double.md
- .changeset/social-cooks-study.md
- pkg-manager/plugin-commands-installation/src/install.ts
- pkg-manager/plugin-commands-installation/src/installDeps.ts
- pkg-manager/plugin-commands-installation/src/recursive.ts
- releasing/plugin-commands-deploy/src/deploy.ts
Upon updating `allProjectsGraph` to always contain all projects (https://github.com/pnpm/pnpm/pull/9259), only 1 test began failing:
This test caught a real problem. When `project-1` depends on `project-2`, the workspace dependency was no longer getting injected into the `deploy` directory.
This is because when `pnpm deploy` is ran with `node-linker=hoisted`, we add all workspace packages as an argument to the `hoist` function.
https://github.com/pnpm/pnpm/blob/a76da0c53c822943af7c5ba92ff3c53b63668751/pkg-manager/real-hoist/src/index.ts#L51-L66
This hoists all workspace packages into the original root `node_modules` **instead of the injected deploy directory**. As a result, pnpm installs them in their normal location and never in the deploy directory.
Before this change, the …
> refactor: prune lockfile importers when running `pnpm deploy` to prepare for `allProjectsGraph` refactor

- exec/plugin-commands-script-runners/test/dlx.e2e.ts
- pnpm-lock.yaml
- pnpm-workspace.yaml
We recently disabled Jest retries globally (https://github.com/pnpm/pnpm/pull/9255), but we should probably re-add retries for this one test that I'm noticing fail occasionally.
Example from: https://productionresultssa0.blob.core.windows.net/actions-results/c72271d4-7ce6-424d-8764-de766e462bbf/workflow-job-run-92795e1e-d0be-55e6-a5b9-6c5f23a789c1/logs/job/job-logs.txt?rsct=text%2Fplain&se=2025-03-10T03%3A45%3A07Z&sig=VQHdY%2FvSofp0FUwPJmnnZCP6Py6YRmPrSrP%2BifBStrg%3D&ske=2025-03-10T11%3A39%3A45Z&skoid=ca7593d4-ee42-46cd-af88-8b886a2f84eb&sks=b&skt=2025-03-09T23%3A39%3A45Z&sktid=398a6654-997b-47e9-b12b-9515b896b4de&skv=2025-01-05&sp=r&spr=https&sr=b&st=2025-03-10T03%3A35%3A02Z&sv=2025-01-05
```
2025-03-10T03:14:29.8513611Z FAIL test/dlx.e2e.ts (355.572 s)
2025-03-10T03:14:29.8516494Z   ● …
```
> test(dlx): use @pnpm.e2e/for-testing-pnpm-dlx from @pnpm/registry-mock

- .changeset/bumpy-forks-love.md
- patching/plugin-commands-patching/src/patch.ts
The following are the results before and after the modification in an environment that does not support terminalLink :
|before|after|
|---|----|
|![image](https://github.com/user-attachments/assets/10dc1cc9-d055-4ce0-a38f-e79dbb2a62f0)|![image](https://github.com/user-attachments/assets/1612620e-361e-4f1f-b7c4-c44f17887a05)|
> fix: `terminalLink` does not support

- .changeset/shaky-stars-hear.md
- env/plugin-commands-env/src/node.ts
- env/plugin-commands-env/src/parseNodeSpecifier.ts
- env/plugin-commands-env/test/node.test.ts
- env/plugin-commands-env/test/parseNodeSpecifier.ts
close #9276 
It's easily to reproduce it by setting an invalid Node.js version:
```
pnpm config set use-node-version 22.14
```
Then most of pnpm commands break with:
```
 ERR_PNPM_INVALID_NODE_VERSION  "22.14" is not a valid Node.js version
```
And only when you delete the wrong config in `~/.config/pnpm/rc` manually, everything works.
> fix: invalid Node.js version in use-node-version should not break

- .changeset/stale-impalas-marry.md
- lockfile/audit/package.json
- lockfile/audit/src/index.ts
- lockfile/audit/tsconfig.json
- lockfile/plugin-commands-audit/test/__snapshots__/index.ts.snap
- pnpm-lock.yaml
Resolves: https://github.com/pnpm/pnpm/issues/9280
> Prevent 'pnpm audit' from crashing with an OOM error by disabling the finding of dependency paths unless opted into

- .changeset/shaggy-chefs-reply.md
- resolving/npm-resolver/src/index.ts
- resolving/npm-resolver/test/index.ts
- resolving/resolver-base/src/index.ts
Prior discussion: https://github.com/pnpm/pnpm/pull/9266#discussion_r1991515784
Instead of `local-filesystem`, the `@pnpm/npm-resolver` package will now return `workspace` in the `resolvedVia` field for workspace packages.
To ensure only workspace packages can use the `catalog:` protocol, we'll need `@pnpm/npm-resolver` to return more information on whether the resolved result is a workspace package.
This requires a change to `@pnpm/npm-resolver` since it's the package that makes the final determination on whether a requested dependency comes from the workspace. Dependencies on workspace packages usually come from the `workspace:` protocol, but it's also possible to depend on a workspace package using a normal semver range (e.g. `^1.0.0`).
> feat: return `workspace` for `resolvedVia` for workspace packages

- .changeset/moody-beans-like.md
- config/config/src/index.ts
> fix: setting `workspace-concurrency` to negative number

- .changeset/calm-weeks-admire.md
- config/config/src/getOptionsFromRootManifest.ts
- config/config/test/getOptionsFromRootManifest.test.ts
env variables can be used in `.npmrc` files, so we should support the same in `pnpm-workspace.yaml` files.
> feat: using env variables in setting names and values

- .changeset/pretty-pandas-hear.md
- patching/plugin-commands-patching/src/patchRemove.ts
When get configuration information, the stored `patchFile` file path has been spliced, and does not need to be spliced ​​again when removing it.
https://github.com/pnpm/pnpm/blob/01f2bcfa9b38b02db970641466c689a2602a7051/config/config/src/getOptionsFromRootManifest.ts#L81
> fix: `patch-remove` command failed to remove path file

- pkg-manager/core/test/catalogs.ts
I'm writing new tests for `pnpm update` with the `catalog:` protocol and realized it'd be better to use a `@pnpm.e2e/*` package for this since public packages like `is-positive` can release new versions and break our tests.
I chose `@pnpm.e2e/foo` since that's what's used in other `pnpm update` tests, but we could also create a new package in registry-mock dedicated for update tests if desired.
https://github.com/pnpm/pnpm/blob/963fa8a2a019e1c8ceb556014e66d3cf0256d12d/pkg-manager/plugin-commands-installation/test/update/update.ts#L13
> refactor: swap `is-positive` for `@pnpm.e2e/foo` in catalog update tests

- .changeset/sweet-plants-sneeze.md
- pnpm-lock.yaml
- pnpm-workspace.yaml
Hi!
Small PR to bump reflink from 0.1.18 to 0.1.19 as [0.1.18 does not exist for macos (darwin x64)](https://www.npmjs.com/package/@reflink/reflink-darwin-x64?activeTab=versions), preventing programmatic usage.
> fix(deps): bump reflink to support macos

- exec/build-commands/src/approveBuilds.ts
approve-builds If no option is selected, a corresponding message prompt is given.
> feat: `approve-builds` output `ignoredBuiltDependencies` msg

- .changeset/free-chairs-cough.md
- pnpm-lock.yaml
- workspace/manifest-writer/package.json
- workspace/manifest-writer/src/index.ts
- workspace/manifest-writer/tsconfig.json
When writing the configuration into the `pnpm-workspace.yaml` file, the relevant information is not sorted by key. 
Now, many projects have configured relevant eslint rules to sort the field information. I think it is better to sort when writing the settings.
> refactor: workspace setting sorted by key

- .changeset/curly-paths-wash.md
- tools/plugin-commands-self-updater/src/installPnpmToTools.ts
> fix: pnpm version management, when `dangerouslyAllowAllBuilds` is set to `true`

- .changeset/afraid-banks-poke.md
- config/config/src/Config.ts
- config/config/src/index.ts
- config/config/src/types.ts
- packages/plugin-commands-init/package.json
- packages/plugin-commands-init/src/init.ts
- packages/plugin-commands-init/test/init.test.ts
- pnpm-lock.yaml
add functionality to include "type": "module" in package.json when using --module or -m flag with pnpm init. Updated cliOptionsTypes and handler to handle the new flag and ensure proper sorting of fields in package.json
Closes #9416
> feat(plugin-commands-init): add support for --init-type flag in pnpm init

- fs/find-packages/src/index.ts
`tinyglobby` supports the `/package.{json,yaml,json5}` pattern, so we can group them.
> refactor: combine multiple pattern parameters

- cache/commands/test/cacheView.cmd.test.ts
- pkg-manager/core/test/catalogs.ts
- pkg-manager/package-requester/test/index.ts
- workspace/state/test/createWorkspaceState.test.ts
- workspace/state/test/updatePackagesList.test.ts
Related PR: https://github.com/pnpm/pnpm/pull/9431
`toMatchObject` and `objectContaining` have a subtle difference in depth: `objectContaining` would fail if one of the nested object has more properties.
This PR:
* Replaces nested `objectContaining` with a single `toMatchObject` at the top.
* Brings back `objectContaining` where it makes sense (such as when it needs to guarantee empty objects, for example).
* Replaces `expect.objectContaining({})` with `expect.any(Object)`.
> test: use `toMatchObject` and `objectContaining` where appropriate

- .changeset/hot-tires-report.md
- .changeset/new-waves-remain.md
- .changeset/tricky-wolves-trade.md
- config/config/src/concurrency.ts
- config/config/src/index.ts
- config/config/test/concurrency.test.ts
- exec/build-modules/package.json
- exec/build-modules/src/index.ts
- exec/build-modules/tsconfig.json
- exec/plugin-commands-rebuild/src/recursive.ts
- exec/plugin-commands-script-runners/src/exec.ts
- exec/plugin-commands-script-runners/src/run.ts
- exec/plugin-commands-script-runners/src/runRecursive.ts
- pkg-manager/plugin-commands-installation/src/recursive.ts
- pnpm-lock.yaml
- pnpm/src/cmd/recursive.ts
- releasing/plugin-commands-publishing/src/pack.ts
- releasing/plugin-commands-publishing/src/publish.ts
- releasing/plugin-commands-publishing/src/recursivePublish.ts
The main issues solved by this PR are:
1. When the number of host CPUs is less than 4, set the default workspaceConcurrency to the number of CPU cores and ensure that it is not greater than 4 (there may be problems in the container, but this may not be a problem that pnpm needs to solve)
2. Eliminate the magic number 4 related to workspaceConcurrency
3. Export `getWorkspaceConcurrency`, `getDefaultWorkspaceConcurrency` in @pnpm/config
4. Add support for `recursive pack` [#9477](https://github.com/pnpm/pnpm/pull/9477)
5. Add `workspace-concurrency` cli option for pack and publish [#9477](https://github.com/pnpm/pnpm/pull/9477)
> feat: add `workspace-concurrency` cli option for pack and publish command

- pkg-manager/core/test/catalogs.ts
While working on https://github.com/pnpm/pnpm/issues/8641, I noticed our usage of `addDependenciesToPackage` in catalog tests are incorrect. Instead of updating dependencies of a specific importer (e.g. `project1` in most tests), it's getting added to the root project.
This caused a surprise when I wrote a `pnpm update` test and observed the old version of the package stick around in the lockfile.
Updating the catalog tests to pass a `dir` option to `addDependenciesToPackage` so the correct importer is updated.
We should consider making the `dir` option to `addDependenciesToPackage` required. To specify the root project, users would pass `"."`.
> test: fix catalog tests adding dependencies to wrong package

- .changeset/mighty-guests-lay.md
- .changeset/shy-seas-lick.md
- config/config/src/index.ts
- config/config/test/index.ts
closes https://github.com/pnpm/pnpm/issues/4858
> fix: fixed extra-bin-paths not set if using `ignore-script=true` in a monorepo

- .changeset/bright-oranges-like.md
- resolving/tarball-resolver/src/index.ts
- resolving/tarball-resolver/test/index.ts
Fixes https://github.com/pnpm/pnpm/issues/9531 by only locking redirects when the final target is immutable
> fix: don't lock ephemeral tarball urls

- pkg-manager/core/src/install/index.ts
- pkg-manager/plugin-commands-installation/src/installDeps.ts
- pkg-manager/plugin-commands-installation/src/recursive.ts
- pkg-manager/resolve-dependencies/src/index.ts
- pkg-manager/resolve-dependencies/src/resolveDependencyTree.ts
Copying a small change from my `pnpm update` branch. It would be useful to rename the `newCatalogs` field returned during an install to `updatedCatalogs` for a few reasons:
1. This object will also contain changed catalogs as a part of a `pnpm update` soon.
2. I think the "_updated_" naming better matches the `updatedManifest` naming, which serves a very similar purpose.
https://github.com/pnpm/pnpm/blob/e6a194acdd927d5279bec196a6aa9c9d119f4333/pkg-manager/core/src/install/index.ts#L145-L146
> refactor: rename `newCatalogs` to `updatedCatalogs`

- .changeset/wide-ghosts-own.md
- config/config/src/Config.ts
- config/config/src/index.ts
- config/config/src/types.ts
- patching/plugin-commands-patching/test/patch.test.ts
- pkg-manager/core/package.json
- pkg-manager/core/src/install/checkCompatibility/CatalogVersionMismatchError.ts
- pkg-manager/core/src/install/extendInstallOptions.ts
- pkg-manager/core/src/install/index.ts
- pkg-manager/core/test/catalogs.ts
- pkg-manager/core/tsconfig.json
- pkg-manager/plugin-commands-installation/src/installDeps.ts
- pnpm-lock.yaml
Add new `catalogMode` setting for automatically adding new dependencies to the default catalog.
Closes pnpm#8876, Closes pnpm#8308
Related PR: https://github.com/pnpm/pnpm/pull/9484
> feat: add new `catalogMode` setting

- .changeset/fancy-files-wish.md
- pkg-manager/core/test/catalogs.ts
- pkg-manager/resolve-dependencies/src/getCatalogSnapshots.ts
- pkg-manager/resolve-dependencies/src/index.ts
- pkg-manager/resolve-dependencies/src/resolveDependencies.ts
- pkg-manager/resolve-dependencies/src/resolveDependencyTree.ts
Fixes https://github.com/pnpm/pnpm/issues/8641.
This PR mostly removes code that made `pnpm update` intentionally skip over `catalog:` protocol dependencies. It also adds new tests for the changed functionality.
Updating catalog dependencies wasn't safe to do before, but should now be supported with the following prerequisite PRs merging.
- https://github.com/pnpm/pnpm/pull/9419
- https://github.com/pnpm/pnpm/pull/9484 (Thanks @KSXGitHub)
- https://github.com/pnpm/pnpm/pull/9514
- https://github.com/pnpm/pnpm/pull/9561
- https://github.com/pnpm/pnpm/pull/9587
- https://github.com/pnpm/pnpm/pull/9588
- https://github.com/pnpm/pnpm/pull/9589
- https://github.com/pnpm/pnpm/pull/9611
- https://github.com/pnpm/pnpm/pull/9590
When updating `pnpm-workspace.yaml`, pnpm does not yet retain …
> feat: support `catalog:` protocol on `pnpm update`

- .github/workflows/ci.yml
Today, when pushing to a branch in the pnpm repo and opening a pull request, CI runs for both the `pull_request` and the `push` event.
I suspect the duplicate builds aren't intentional and only running once saves on resources.
When the pull request event is skipped, it gets a weird title. It looks like there's [some discussion of this on GitHub](https://github.com/orgs/community/discussions/13261).
Contributors to pnpm opening a PR from a forked repository won't see this since GitHub Actions will run on their PR.
> ci: prevent duplicate builds for pull requests in original repo

- .changeset/bright-clubs-throw.md
- store/plugin-commands-server/src/start.ts
- store/server/example/server.js
- store/server/src/createServer.ts
- store/server/test/index.ts
Noticed while investigating tests in #8810 
Tests were flaking locally
`net.Server#listen` is not ready before it calls the callback, and connections failed randomly
Refs: https://nodejs.org/api/net.html#serverlistenoptions-callback
Alternatively this whole method could be made async
These random flakes/hangs could have been the reason why you had to add 38d7ca869de19b8473b6cc6767ee8b56560c8cb2 (which can now be removed, tests seem stable/fast here)
> fix: wait for server to listen

- __utils__/jest-config/config.js
I am not sure how did this work on CI?
Tests seemed to fail locally for `pnpm run _test` but passed for `../../node_modules/.bin/jest`
Tests are run through pnpm itself, which pollutes env vars, and those `pnpm_*` env variables confused config reads in tests, e.g. added pnpmfile config property which wasn't present when `jest` was executed manually
This affected e.g. running `_test` in `exec/build-commands`
Before (`_test` only, `../../node_modules/.bin/jest` was fine):
```console
FAIL  test/approveBuilds.test.ts (6.806 s)
✕ approve selected build (2028 ms)
✓ approve no builds (262 ms)
✓ works when root project manifest doesn't exist in a workspace (271 ms)
✓ should update onlyBuiltDependencies when package.json exists with ignoredBuiltDependencies defined (290 ms)
✓ should approve builds …
```
> test: cleanup pnpm_ env variables in jest-config

- __typings__/local.d.ts
- pkg-manager/plugin-commands-installation/src/import/index.ts
- pkg-manager/resolve-dependencies/src/resolvePeers.ts
- pnpm-lock.yaml
- pnpm-workspace.yaml
Combined with #8809 (landed), this gives 21% size reduction
Includes `@yarnpkg/core@^4.2.0` bump to get https://github.com/yarnpkg/berry/pull/6614 in
> fix: 15% smaller bundle size

- pnpm/test/install/misc.ts
This test was failing locally on my mac, the files have been `foo.js` and `package.json`, not `Foo.js` and `package.json`
Is this behavior intended? Or is this a bug?
Also see https://github.com/nodejs/node/issues/3232 about readdir order stability
Without this PR:
> test: fix case-insensitive install test

- __utils__/test-ipc-server/src/TestIpcServer.ts
tests using `getLines()` assume no colors
and do things like parseInt on output, or just compare with hardcoded values
some tests get broken if color is forced with FORCE_COLOR, this addresses most of that
If something ever needs colors there, they could be restored e.g. via a flag in arguments to opt out of stripping
Also, `.getBuffer()` intentionally was not changed and returns raw output
> test: strip VT control chars in getLines()

- .changeset/icy-steaks-call.md
- exec/plugin-commands-script-runners/src/create.ts
Fixes #8545
- Adds option parsing to the 'create' command to detect --help and -h flags before package resolution.
- Displays the same help message as 'pnpm help create' and exits when either flag is present.
- Maintains backwards compatibility: all other arguments are treated as package names or parameters.
> fix: support --help and -h flags for 'pnpm create' command

- .changeset/blue-hairs-drum.md
- fetching/pick-fetcher/src/index.ts
- patching/plugin-commands-patching/src/getPatchedDependency.ts
- patching/plugin-commands-patching/src/patchCommit.ts
Dependencies installed via `pkg.pr.new` may not be published to npm, but we should also support patch-related operations.
For example, install the following dependencies and then add patches.
`pnpm i https://pkg.pr.new/@vue/runtime-vapor@13520`
> fix: patch support unpublished pkg

- .changeset/floppy-grapes-kick.md
- .changeset/thin-ghosts-feel.md
- cli/cli-utils/package.json
- cli/cli-utils/src/getConfig.ts
- hooks/pnpmfile/src/requireHooks.ts
- hooks/pnpmfile/test/index.ts
- pnpm-lock.yaml
- pnpm-workspace.yaml
- pnpm/test/hooks.ts
We have a couple of official pnpm config dependencies that work via pnpmfiles: `@pnpm/better-defaults`, `@pnpm/types-fixer`, `@pnpm/node-path-for-esm`. Currently, we have to instruct users to add a reference to the pnpmfiles in these config dependencies. With this change, it will be enough to name the config dependency following a convention, it should start with either `@pnpm/plugin-` or `pnpm-plugin-`. If the config dependency will be named this way, pnpm will automatically load the `pnpmfile.cjs` from it. This is now easier to implement since I added support for multiple pnpmfiles via https://github.com/pnpm/pnpm/pull/9702
I was considering loading esm files from these plugins but looks like they don't work well with all the Node.js versions that we currently support: …
> feat: loading pnpmfiles automatically from plugins

- pkg-manifest/read-project-manifest/src/index.ts
- pkg-manifest/read-project-manifest/test/index.ts
Running `pnpm add -D node@runtime:24` adds a new runtime entry to `devEngines`.
> feat(add): update devEngines.runtime with a Node.js entry

- .changeset/upset-ends-yell.md
- pkg-manager/modules-cleaner/src/prune.ts
This PR introduced a bug where it switched out a reduce for a for loop. I'm not sure where to write tests here but I'm happy to if you could point me to where I could.
Tested this against my bug reproduction.
https://github.com/pnpm/pnpm/pull/8537/files#diff-494d01d2e936696b2af0a7338260c27cbc5fb00345ee2506a086d38f974b8365R242-R247
Resolves: https://github.com/pnpm/pnpm/issues/9782
> fix: address pnpm failing to prune hoisted dev dependencies

- .changeset/twenty-lions-rush.md
- env/node.fetcher/src/index.ts
- fetching/fetcher-base/src/index.ts
- fetching/tarball-fetcher/test/fetch.ts
- pkg-manager/package-requester/src/packageRequester.ts
Reverts a change introduced via #9755
> revert: there's no need to pass the packageId to the fetcher

- .changeset/beige-camels-post.md
- deps/graph-builder/src/lockfileToDepGraph.ts
- pkg-manager/core/test/install/local.ts
- pkg-manager/headless/src/index.ts
When using the file protocol on a local tarball:
```json
{
"bar": "file:../../bar.tgz"
}
}
```
I observed pnpm not re-link `node_modules/bar` when changing `bar.tgz`. This only happened when running a filtered install. (The filter does include the package above.) Example:
```console
pnpm install --filter ./packages/foo
```
Here's a minimal repro of the above: https://github.com/gluxon/pnpm-pull-9805-repro
This is due to a common assumption across the codebase. We assume the path for a virtual store directory uniquely identifies its contents. In this case, pnpm is seeing that `node_modules/.pnpm/bar@file+bar.tgz` already exists and doesn't re-link it.
https://github.com/pnpm/pnpm/blob/10195e4857d29ca2de5023d213478b9a94ec4d3f/deps/graph-builder/src/lockfileToDepGraph.ts#L19 …
> fix: re-link local tarball when contents change (without rename) during filtered install

- __utils__/eslint-config/package.json
- cli/default-reporter/tsconfig.json
- lockfile/plugin-commands-audit/tsconfig.json
- pnpm-lock.yaml
- pnpm-workspace.yaml
- pnpm/tsconfig.json
Seems like we are stuck with typescript 5.8 due to an issue with lru-cache
> chore: update typescript to v5.9

- __utils__/test-fixtures/src/index.ts
- cli/cli-utils/src/getConfig.ts
- completion/plugin-commands-completion/src/getOptionType.ts
- config/matcher/src/index.ts
- exec/plugin-commands-script-runners/src/run.ts
- lockfile/utils/src/pkgSnapshotToResolution.ts
- object/property-path/src/token/StringLiteral.ts
- packages/dependency-path/src/index.ts
- pkg-manager/core/src/install/validateModules.ts
- releasing/plugin-commands-publishing/src/publish.ts
- resolving/jsr-specifier-parser/src/index.ts
- text/comments-parser/src/insertComments.ts
- workspace/filter-workspace-packages/src/parsePackageSelector.ts
When determining the value of the first letter of a string, using strict equality is more efficient than startsWith. refer to [link](https://perf.link/#eyJpZCI6InpyZjd5OHg5Mm13IiwidGl0bGUiOiJGaW5kaW5nIG51bWJlcnMgaW4gYW4gYXJyYXkgb2YgMTAwMCIsImJlZm9yZSI6ImNvbnN0IGRhdGEgPSBbLi4uQXJyYXkoMTAwMCkua2V5cygpXS5tYXAoKCkgPT4gTWF0aC5yYW5kb20oKS50b1N0cmluZygxNikpIiwidGVzdHMiOlt7Im5hbWUiOiJGaW5kIGl0ZW0gMTAwIiwiY29kZSI6ImRhdGEuZmluZCh4ID0%2BIHguc3RhcnRzV2l0aCgnLicpKSIsInJ1bnMiOls2MDAwMCw1NTAwMCw1NzAwMCw3MjAwMCwyNzAwMCw5MzAwMCw5NjAwMCw4MTAwMCwxMTEwMDAsMzAwMCwyODAwMCwxMzAwMDAsMTUwMDAsMjEwMDAsMTU0MDAwLDEwMDAsNTYwMDAsODkwMDAsMzkwMDAsMzMwMDAsMTIwMDAsMzAwMCwyNDAwMCw0MDAwMCwxMjAwMCwxMjAwMCwzNjAwMCwxNTYwMDAsMTA3MDAwLDIwMDAwLDE3MjAwMCwzMzAwMCwyNTAwMCw3MDAwLDEzMDAwLDEyNTAwMCwxNTYwMDAsMTMwMDAsNTgwMDAsMTY5MDAwLDEyMD …
> perf: replace startsWith with strict equality

- deps/graph-builder/src/lockfileToDepGraph.ts
- packages/dependency-path/src/index.ts
- store/store-path/src/index.ts
Using startswith is more efficient than using indexOf to determine whether the subscript is 0. [link](https://perf.link/#eyJpZCI6Imd2dGtvM3AwaWoyIiwidGl0bGUiOiJGaW5kaW5nIG51bWJlcnMgaW4gYW4gYXJyYXkgb2YgMTAwMCIsImJlZm9yZSI6ImNvbnN0IGRhdGEgPSBbLi4uQXJyYXkoMTAwMCkua2V5cygpXS5tYXAoKCkgPT4gTWF0aC5yYW5kb20oKS50b1N0cmluZygxNikpIiwidGVzdHMiOlt7Im5hbWUiOiJGaW5kIGl0ZW0gMTAwIiwiY29kZSI6ImRhdGEuZmluZCh4ID0%2BIHguc3RhcnRzV2l0aCgnZmlsZTonKSkiLCJydW5zIjpbMTAwMCwwLDExMDAwLDEwMDAsOTAwMCwxMTAwMCwxMjAwMCw3MDAwLDMyMDAwLDMwMDAsODAwMCwyMDAwLDEyMDAwLDIwMDAsMTYwMDAsMTAwMCwzMDAwLDIwMDAsMTkwMDAsNTAwMCw5MDAwLDUwMDAsODAwMCwxMDAwMCwyMDAwLDEwMDAsODAwMCwxNzAwMCwxMDAwLDIwMDAsMTIwMDAsMTAwMCwxMzAwMCw0MDAwLDEwMDAsMjAwMCwyMTAwMCwxMTAwMCw3MDAwLDEwMDAsNzAwMCwxNjAwMCwxMDAwLDQwMDAsMTEwMDAsMTAwMCwxMTAwMCwxMjAwMCwxMDAwLDcwMDAsODAwM …
> perf: replace indexOf with startsWith

- .changeset/good-llamas-dream.md
- lockfile/lockfile-to-pnp/src/index.ts
- lockfile/lockfile-to-pnp/test/index.ts
I compared PNPM's `.pnp.cjs` with the one generated by Yarn Berry, and it turned out that Yarn normalises `packageLocation` to always end in a trailing slash:
Here's where they ensure this when writing `.pnp.cjs`: https://github.com/yarnpkg/berry/blob/f6a58c2803d6572af28e118eecd10c795e1228b1/packages/plugin-pnp/sources/PnpLinker.ts#L492
And here's where they normalise at read-time: https://github.com/yarnpkg/berry/blob/f6a58c2803d6572af28e118eecd10c795e1228b1/packages/yarnpkg-pnp/sources/loader/makeApi.ts#L511-L512
This PR makes PNPM adhere to this behaviour.
I verified that it resolves https://github.com/pnpm/pnpm/issues/9904 by manually updating the paths in `.pnp.cjs`.
> fix(lockfile-to-pnp): ensure packageLocation ends in trailing slash

- releasing/plugin-commands-deploy/src/deploy.ts
This makes the experience better for those who have a script named "deploy", and may potentially get confused why "pnpm deploy" doesn't work.
Related to #9475 but doesn't actually fix it.
PS: Not sure if `docs(deploy)` is correct. Feel free to change the title.
> fix(deploy): hint "pnpm run deploy" for "pnpm deploy" outside a workspace

- .changeset/every-walls-search.md
- pkg-manager/plugin-commands-installation/src/remove.ts
When removing a dependency, we should also execute `cleanupUnusedCatalogs` configuration related logic.
> fix: remove pkg apply cleanupUnusedCatalogs

- .changeset/three-islands-juggle.md
- pkg-manager/resolve-dependencies/src/resolveDependencyTree.ts
Fixes https://github.com/pnpm/pnpm/issues/9662.
This warning was originally added in:
- https://github.com/pnpm/pnpm/pull/9484
Looking through the original PR, I think the intention of this warning was to only print when running `pnpm add --save-catalog`.
Let's gate this warning around `saveCatalogName != null`. I suspect this was the original intention in https://github.com/pnpm/pnpm/pull/9484. CC @KSXGitHub to confirm.
This warning prints whenever:
https://github.com/pnpm/pnpm/blob/904ae1a87589e755a7a4c13f3b083ac244bb406e/pkg-manager/resolve-dependencies/src/resolveDependencyTree.ts#L255
I noticed a few cases when `normalizedBareSpecifier` will be different than the specifier defined in `pnpm-workspace.yaml`.
- When there's no `pnpm-lock.yaml` file, `normalizedBareSpecifier` will be the …
> fix: only show save catalog skip warning when using `pnpm add --save-catalog`
