README.md, bin/pnpm-install, lib/err.js, lib/install.js, lib/install/post_install.js, package.json, test/index.js
Supports chokidar, node-sass, fsevents... you name it. Nuff said ;)
=> Compiled packages

lib/fs/require_json.js, lib/install.js
Work in progress.
The fetch and build steps need to be separate to eventually support tarball and github packages and such.
=> Separate build and fetch steps

HISTORY.md, lib/install.js, lib/logger.js, lib/resolve.js, lib/resolve/tarball.js, test/index.js
```
pnpm i http://registry.npmjs.org/is-array/-/is-array-1.0.1.tgz
```
=> Installing from tarballs

HISTORY.md, lib/config.js, lib/fetch.js, lib/got.js, lib/logger.js, lib/promise.js, package.json
#24 - pnpm now only fetches up to 16 things at the same time. This improves reliability considerably.
=> Limit download concurrency (#24)

README.md
Added npm badge to README.md. Can't wait till 1.0.0 :)
Thanks! :+1:
=> Added npm badge to README.md

.travis.yml
I disabled this before since travis caches were problematic at one point, let's see if it's not a problem now.
=> Reenable travis caching

docs/roadmap.md, docs/vs-npm.md, lib/rel_symlink.js
=> Windows support

lib/cmd/install.js, test/index.js, test/support/simple-package.json
=> Add support for --production flag

HISTORY.md, README.md, lib/got.js, lib/install.js, package.json
:sparkles: :confetti_ball: \o/ :confetti_ball: :sparkles:
huge thanks to @crcn for donating the name and @davej for the initiative to reach out to Craig.
=> Rename to pnpm

lib/got.js
Avoid `getaddrinfo ENOTFOUND` error.
=> Enable http(s) keepalive

lib/cmd/install.js
This makes it possible to configure to have a common store for all packages
=> resolve store_path

lib/install.js, lib/install/link_bins.js
Link package bins to node_modules/.bin even if the packages were cached
close #242
=> Always link package bins

lib/install.js, lib/install/link_bins.js
Related issue https://github.com/rstacruz/pnpm/issues/244
combined with https://github.com/rstacruz/pnpm/issues/242
=> Preserve symlinks on Node.js >=v6.3.0

lib/cmd/install.js, lib/install.js, lib/install_multiple.js, test/index.js
=> Support optional dependencies

docs/roadmap.md, lib/fetch.js, lib/install.js, lib/resolve.js, lib/resolve/github.js, lib/resolve/local.js, test/index.js, test/local-pkg/index.js, test/local-pkg/package.json
=> Support installing from files

README.md, appveyor.yml, bin/pnpm-install, lib/cmd/install.js, lib/got.js, lib/install/link_bins.js, lib/install/post_install.js, lib/logger.js, lib/resolve/local.js, package.json, test/index.js, test/support/prepare.js
close #258 
Fixed a few issues that were on Windows and configured AppVeyor to pass the tests https://ci.appveyor.com/project/zkochan/pnpm
I suggest to add appveyor status check for the master branch after this will be merged. Windows users will be very happy :smile:
=> Add Windows CI via AppVeyor, use npmrc settings, run script via npm cli

HISTORY.md, bin/pnpm.js, docs/README.md, docs/global-install.md, docs/roadmap.md, lib/cmd/init_cmd.js, lib/defaults.js, lib/fs/expand_tilde.js, lib/get_save_type.js, test/index.js
=> Support global install

HISTORY.md, bin/pnpm.js, docs/api.md, docs/roadmap.md, index.js, lib/api/init_cmd.js, lib/api/install_pkg_deps.js, lib/api/link.js, lib/cmd/link.js, lib/defaults.js, lib/install/link_bins.js, lib/install/link_peers.js, lib/resolve_global_pkg_path.js, package.json, test/index.js
=> Implement pnpm link

.github/ISSUE_TEMPLATE.md
This should help to get all the necessary information from the issue creator,
=> docs(CONTRIBUTING): create issue template

lib/install.js
This was broken by commit 0c247a1f4cc1959fe370109f488bb552c50ade20
The fix is just reverting the unnecessary changes that have broken the tmp dir locking.
Issue introduced in [v0.25.0](https://github.com/rstacruz/pnpm/releases/tag/v0.25.0)
=> fix: temp dir locking

lib/resolve/tarball.js, test/index.js
=> fix: failing to install some tarball dependencies

src/resolve/git.ts, src/resolve/index.ts, test/index.ts, tsconfig.json
=> Support SSH GIT dependencies

src/api/install.ts, src/defaults.ts, src/network/got.ts
=> feat(network): support all the npm's proxy/ssl configs

src/install/isAvailable.ts, src/install/linkPeers.ts, src/resolve/npm.ts
=> fix(install): interpret versions and ranges loosely

package.json, src/api/extendOptions.ts, src/api/getContext.ts, src/api/initCmd.ts, src/api/install.ts, src/api/link.ts, src/api/lock.ts, src/api/prune.ts, src/api/uninstall.ts, src/fs/storeJsonController.ts, src/install/index.ts, src/resolveGlobalPkgPath.ts, tsconfig.json
I wasn't able to remove the context object completely yet, but it is now a lat smaller.
Related to #379
=> Getting rid of the cmd object

bin/node-gyp-bin/node-gyp, package.json, src/install/postInstall.ts, src/runScript.ts, test/install.ts, typings/local.d.ts
I have good and bad news
Bad - building of native addons were broken at least since 0.39.0
Good - now they are covered with integration tests
=> fix(scripts): build native addons

src/fs/relSymlink.ts, src/install/index.ts, src/install/linkPeers.ts
=> fix(install): don't escape path to scoped packages in subdeps

.gitignore, package.json, sinopia/config.yaml, test/support/prepare.ts
=> test: use a local sinopia server for e2e testing

package.json, src/api/extendOptions.ts, src/api/install.ts, src/install/index.ts, src/resolve/index.ts, src/resolve/npm.ts, src/types.ts, test/install.ts, test/packages/dep-of-pkg-with-1-dep/index.js, test/packages/dep-of-pkg-with-1-dep/package.json, test/packages/pkg-with-1-dep/index.js, test/packages/pkg-with-1-dep/package.json, typings/local.d.ts
This is the 1st step to implement `pnpm update`
Also implemented the tag option
=> feat: add --depth option

src/bin/pnpm.ts, src/cmd/update.ts, src/install/installMultiple.ts, test/cli.ts, test/support/run-cli.ts, tsconfig.json
=> feat(update): implement

src/api/install.ts, src/install/fetch.ts, src/install/installMultiple.ts, src/resolve/index.ts, src/resolve/npm.ts, src/types.ts
Approximately 3.5% faster. I thought it would be more significant, but better than nothing
=> Fetching sub-dependencies sooner 

src/install/fetch.ts, src/install/installMultiple.ts, test/install.ts
=> fix: reinstall broken packages in the store

src/resolve/git.ts
=> fix(install): dirs in stores can't contain colons

src/api/install.ts, src/install/fetch.ts
=> fix(fetch): limit simultaneous fetches

src/api/install.ts
=> fix(bin): bins should be linked in all dependencies

src/api/extendOptions.ts, src/api/install.ts, src/api/lock.ts, src/api/prune.ts, src/api/uninstall.ts, src/types.ts
=> feat: add lockStaleDuration config

src/api/install.ts, src/install/fetch.ts, src/install/installMultiple.ts, src/memoize.ts
A small refactoring of concurrency
=> refactor: concurrency

src/api/link.ts, src/install/installMultiple.ts, test/link.ts, test/packages/hello-world-js-bin/package.json
=> fix(link): don't reinstall linked packages

package.json, src/resolve/git.ts, typings/local.d.ts
=> fix(git+ssh): git clone with correct ssh URL

package.json, src/api/uninstall.ts, src/binify.ts, src/install/linkBins.ts, src/types.ts, test/install.ts
=> feat(bin): symlink executables when directories.bin specified

package.json
Closes #654
https://greenkeeper.io/
=> fix(package): update fs-write-stream-atomic to version 1.0.10

package.json, src/api/getContext.ts, src/api/install.ts, src/api/removeOrphanPkgs.ts, src/api/verify.ts, src/fs/shrinkwrap.ts, src/install/fetch.ts, src/install/installMultiple.ts, src/resolve/index.ts, src/resolve/npm/getRegistryName.ts, src/resolve/npm/index.ts, src/resolve/npm/loadPackageMeta.ts, src/types.ts, test/install.ts, test/shrinkwrap.ts, test/uninstall.ts
Ref #664 
~20% smaller files and more readable.
More improvements are coming
~26% smaller with 6f19f3fd4a8f684933121d78d18ef82c422465df
~52% smaller with 118238ab3e3317ef75dcfe2eef136b54da64e3b5
~57% smaller with 32dcacb4c442bb11ad57797bb36f17c38fd57c44
=> feat: make shrinkwrap.yaml smaller

package.json
Closes #670
https://greenkeeper.io/
=> fix(package): update npm-registry-client to version 8.0.2

src/install/installMultiple.ts, test/install.ts
=> fix: optional dependencies are always resolved

package.json, shrinkwrap.yaml, test/uninstall.ts
Closes #703
https://greenkeeper.io/
=> fix(package): update write-pkg to version 3.0.1

docs/api.md, package.json, shrinkwrap.yaml, src/api/extendOptions.ts, src/api/getContext.ts, src/api/install.ts, src/api/link.ts, src/bin/pnpm.ts, src/cmd/link.ts, src/link/index.ts, src/types.ts, test/cli.ts, test/install/misc.ts, test/link.ts, test/utils/prepare.ts, test/utils/testDefaults.ts, typings/local.d.ts
=> fix: global installation always works now

src/resolve/git.ts, src/resolve/index.ts, test/install/fromRepo.ts
=> fix: installation of packages from non-github repos

src/safeIsInnerLink.ts
=> fix: pnpm does not delete stuff from node_modules

src/api/extendOptions.ts, src/api/install.ts, src/network/got.ts, src/types.ts
=> fix: always-auth config value is not ignored anymore

src/bin/pnpm.ts, test/cli.ts
=> fix(CLI): options are passed through to npm

src/link/resolvePeers.ts
=> perf: substitute immutable code to make tree creation faster

README.md, src/api/extendOptions.ts, src/api/install.ts, src/api/prune.ts, src/api/uninstall.ts, src/bin/pnpm.ts, src/types.ts
=> feat: add a --no-lock option

src/api/install.ts
=> fix: delay during post-install stage

src/fs/readPkg.ts, src/removeDeps.ts, src/save.ts, test/shrinkwrap.ts
=> fix: package.json has to be normalized before usage

src/api/install.ts, src/depsToSpecs.ts, src/install/installMultiple.ts, src/resolve/index.ts, test/install/lifecycleScripts.ts, test/shrinkwrap.ts
Even dev packages when installing with the --production flag
=> feat: always add all packages to shrinkwrap.yaml

package.json
=> fix(package): update @types/node to version 8.0.7

package.json
=> fix(package): update @types/ramda to version 0.24.1

src/bin/pnpm.ts, src/cmd/help.ts, src/cmd/server.ts, test/server.ts
=> feat(server): choosing the communication protocol

package.json, shrinkwrap.yaml, src/bin/pnpm.ts, src/cmd/help.ts, src/cmd/server/index.ts, src/cmd/server/start.ts, src/cmd/server/stop.ts, test/recursive.ts, test/server.ts
=> feat(server): add stop command

src/cmd/help.ts, src/cmd/recursive.ts, test/recursive.ts
=> pnpm recursive link|dislink

README.md
Closes #1022 
Its a big FAQ though 😂
=> docs(readme): doesn't work with x

package.json, shrinkwrap.yaml, src/cmd/install.ts, src/cmd/recursive.ts, src/cmd/update.ts, src/requireHooks.ts, src/requirePnpmfile.ts, src/types.ts, test/install/hooks.ts
close #910 
setting `npm set pnpmfile ~/pnpmfile.js` will allow to use a global pnpmfile
cc @jsumners, @vjpr
=> feat: custom location of pnpmfile

packages/supi/src/api/rebuild.ts, packages/supi/test/rebuild.ts
=> fix(rebuild): rebuild should not fail on linked packages

packages/pnpm/src/createStore.ts, packages/supi/src/link/index.ts, packages/supi/src/link/resolvePeers.ts, packages/supi/src/link/updateShrinkwrap.ts, packages/supi/src/resolveDependencies.ts, packages/supi/test/install/shrinkwrapOnly.ts, packages/supi/test/utils/testDefaults.ts
=> perf: request corgi (stripped) metadata from npm registry

packages/headless/shrinkwrap.yaml, packages/pnpm/package.json, packages/pnpm/shrinkwrap.yaml, packages/pnpm/src/cmd/help.ts, packages/pnpm/src/cmd/list.ts, packages/pnpm/src/cmd/recursive.ts, packages/pnpm/test/recursive.ts, packages/supi/shrinkwrap.yaml
=> feat: pnpm recursive list

packages/pnpm/src/cmd/help.ts, packages/pnpm/src/cmd/recursive/index.ts, packages/pnpm/src/cmd/recursive/outdated.ts, packages/pnpm/test/recursive.ts
=> feat: pnpm recursive outdated

packages/config/src/index.ts, packages/pnpm/src/cmd/help.ts, packages/pnpm/src/createStoreController.ts, packages/pnpm/test/server.ts
=> feat: --no-allow-start-store-server

packages/supi/package.json, packages/supi/shrinkwrap.yaml, packages/supi/src/link/resolvePeers.ts, packages/supi/test/install/peerDependencies.ts
=> fix: avoid property 'requiresBuild' of undefined error

packages/pnpm/src/requirePnpmfile.ts, packages/pnpm/test/install/hooks.ts
=> fix: throw meaningful error on bad readPackage hook

packages/config/shrinkwrap.yaml, packages/default-reporter/shrinkwrap.yaml, packages/headless/package.json, packages/headless/shrinkwrap.yaml, packages/headless/src/index.ts, packages/pnpm/shrinkwrap.yaml, packages/supi/package.json, packages/supi/shrinkwrap.yaml, packages/supi/src/api/link.ts, packages/supi/src/link/index.ts, packages/utils/shrinkwrap.yaml, tools/shrinkwrap.yaml
=> fix: prefer bins of packages that have the same bin as package name

packages/headless/package.json, packages/headless/shrinkwrap.yaml, packages/headless/src/index.ts, packages/headless/test/fixtures/deps-have-lifecycle-scripts/shrinkwrap.yaml, packages/headless/test/fixtures/has-glob-and-rimraf/shrinkwrap.yaml, packages/headless/test/fixtures/has-glob/shrinkwrap.yaml, packages/headless/test/fixtures/has-local-dep/shrinkwrap.yaml, packages/headless/test/fixtures/has-local-dir-dep/shrinkwrap.yaml, packages/headless/test/fixtures/prod-dep-is-dev-subdep/shrinkwrap.yaml, packages/headless/test/fixtures/resolved-peer-deps-in-subdeps/shrinkwrap.yaml, packages/headless/test/fixtures/simple-with-more-deps/shrinkwrap.yaml, packages/headless/test/fixtures/simple/shrinkwrap.yaml, packages/supi/package.json, packages/supi/shrinkwrap.yaml, packages/supi/src/constants.ts, packages/supi/src/link/index.ts, packages/supi/src/link/resolvePeers.ts, packages/supi/src/link/updateShrinkwrap.ts, packages/supi/src/resolveDependencies.ts, packages/supi/test/install/aliases.ts, packages/supi/test/install/local.ts, packages/supi/test/install/misc.ts, packages/supi/test/shrinkwrap.ts, packages/utils/package.json, packages/utils/shrinkwrap.yaml
=> perf: add hasBin to package snapshots in shrinkwrap.yaml

packages/config/src/index.ts
=> fix: install global packages to APPDATA

packages/supi/package.json, packages/supi/shrinkwrap.yaml, packages/supi/src/link/resolvePeers.ts, packages/supi/test/install/peerDependencies.ts, packages/supi/typings/local.d.ts
=> fix: peer deps are missing only if they cannot be required

packages/config/src/index.ts, packages/headless/shrinkwrap.yaml, packages/pnpm/shrinkwrap.yaml, packages/pnpm/src/cmd/help.ts, packages/pnpm/src/cmd/recursive/index.ts, packages/pnpm/src/types.ts, packages/pnpm/test/recursive/misc.ts
=> feat(recursive): --filter

packages/config/src/PnpmConfigs.ts, packages/config/src/index.ts
Follow‑up to #1244.
Resolves #1264.
=> fix(config): Allow turning off forced installation in %APPDATA%

packages/supi/src/api/extendInstallOptions.ts
=> fix(reporting): log shamefully-flatten message as an info message

packages/supi/src/link.ts, packages/supi/test/link.ts, packages/supi/test/packages/symlink-workspace/app1/packages/public/bar/package.json, packages/supi/test/packages/symlink-workspace/app1/packages/public/foo/package.json, packages/supi/test/packages/symlink-workspace/app1/packages/public/foo/shrinkwrap.yaml, packages/supi/test/packages/symlink-workspace/app2/packages/public
https://github.com/pnpm/pnpm/issues/1208
=> fix: use realpaths for symlink source and target

packages/supi/test/link.ts, packages/supi/test/packages/symlink-workspace/app2/packages/public
=> use realpaths for workspace package linking

packages/pnpm/src/cmd/recursive/index.ts, packages/pnpm/test/monorepo/index.ts
Cycles of length 1 in the dependency graph ie., packages that depend on
themselves, confuse the 'graph-sequencer' function that is used to order the
packages topologically.
Sometimes, it makes sense to make packages depend on themselves eg., to install
their exposed scripts in `node_modules/.bin`, so we should either fix the
`graph-sequencer` or apply this patch.
An example for this behavior is:
- Package 'a' depends on 'b' and 'c'
- Package 'b' depends on 'b'
- Package 'c' depends on 'b' and 'c'
Now run:
pnpm recursive --filter=a... [some command]
**Expected behavior**:
- Packages are visited in order [['b'], ['c'], ['a']], where no parallel
execution is possible.
**Actual behavior**:
- Packages are visited in order [['b'], ['a'], ['c']].
This patch fixes that behavior.
=> fix: ignore cycles of length 1 in dependency graph when sorting

packages/pnpm/src/main.ts, packages/pnpm/test/monorepo/index.ts, packages/shrinkwrap/src/write.ts, packages/supi/src/install/extendInstallOptions.ts, packages/supi/src/install/index.ts, packages/supi/src/link/index.ts, packages/supi/src/link/options.ts, packages/supi/src/uninstall/extendUninstallOptions.ts, packages/supi/src/uninstall/index.ts
=> fix: use correct shrinkwrap format when installing in repo root package

packages/supi/src/getContext/readShrinkwrapFiles.ts, packages/supi/test/shrinkwrap.ts
=> fix: recreate deleted wanted shrinkwrap from current one

packages/supi/src/install/link.ts
=> fix: `ERROR Cannot set property 'requiresBuild' of undefined`

packages/headless/src/index.ts, packages/headless/test/fixtures/side-effects/package.json, packages/headless/test/fixtures/side-effects/shrinkwrap.yaml, packages/headless/test/index.ts, packages/package-requester/src/packageRequester.ts, packages/package-store/src/storeController/index.ts, packages/server/src/connectStoreController.ts, packages/server/src/createServer.ts, packages/store-controller-types/src/index.ts
This fixes headless mode in Glitch
=> use server to retrieve the side effects cache

packages/list/src/index.ts, packages/list/src/renderParseable.ts, packages/list/src/renderTree.ts, packages/list/test/index.ts, packages/pnpm/src/cmd/help.ts, packages/pnpm/src/cmd/list.ts, packages/pnpm/src/cmd/recursive/list.ts, packages/pnpm/test/list.ts, packages/pnpm/test/recursive/list.ts
=> feat: pnpm ls --depth -1 prints projects

packages/default-reporter/src/index.ts, packages/default-reporter/src/reporterForClient/index.ts, packages/default-reporter/src/reporterForClient/reportScope.ts, packages/default-reporter/test/index.ts, packages/default-reporter/test/reportingScope.ts, packages/pnpm/src/cmd/recursive/index.ts, packages/pnpm/src/loggers/index.ts, packages/pnpm/src/main.ts
=> feat: notify user about scope of the command

packages/pnpm/src/cmd/recursive/exec.ts, packages/pnpm/src/cmd/recursive/index.ts, packages/pnpm/test/recursive/exec.ts
Current package name should be in env var called $PNPM_PACKAGE_NAME
when running `pnpm m exec -- echo $PNPM_PACKAGE_NAME
close #1553
=> feat(exec): $PNPM_PACKAGE_NAME

packages/config/src/index.ts, packages/config/test/index.ts, packages/headless/src/index.ts, packages/headless/src/runDependenciesScripts.ts, packages/headless/test/fixtures/side-effects-of-subdep/package.json, packages/headless/test/fixtures/side-effects-of-subdep/shrinkwrap.yaml, packages/headless/test/fixtures/with-1-dep/package.json, packages/headless/test/fixtures/with-1-dep/shrinkwrap.yaml, packages/headless/test/index.ts, packages/package-store/package.json, packages/package-store/src/storeController/index.ts, packages/server/src/connectStoreController.ts, packages/server/src/createServer.ts, packages/server/test/index.ts, packages/shamefully-flatten/src/index.ts, packages/store-controller-types/src/index.ts, packages/supi/src/constants.ts, packages/supi/src/install/extendInstallOptions.ts, packages/supi/src/install/index.ts, packages/supi/src/install/link.ts, packages/supi/src/install/resolvePeers.ts, packages/supi/src/uninstall/extendUninstallOptions.ts, packages/supi/src/uninstall/index.ts, packages/supi/test/install/independentLeaves.ts, packages/supi/test/install/sideEffects.ts, shrinkwrap.yaml
=> fix: shamefully-flatten should work with independent-leaves

packages/core-loggers/src/lifecycleLogger.ts, packages/default-reporter/package.json, packages/default-reporter/src/reporterForClient/reportLifecycleScripts.ts, packages/default-reporter/src/reporterForClient/utils/formatPrefix.ts, packages/default-reporter/test/index.ts, packages/default-reporter/test/reportingLifecycleScripts.ts, packages/default-reporter/typings/local.d.ts, packages/headless/src/index.ts, packages/headless/src/runDependenciesScripts.ts, packages/lifecycle/src/index.ts, packages/lifecycle/test/index.ts, packages/supi/src/install/index.ts, packages/supi/src/rebuild/index.ts, shrinkwrap.yaml
=> feat(reporting): collapse build output of deps inside node_modules

packages/default-fetcher/package.json, packages/default-reporter/src/reportError.ts, packages/default-reporter/test/reportingErrors.ts, packages/package-requester/package.json, packages/package-store/package.json, packages/package-store/src/errorTypes/PnpmError.ts, packages/pnpm/src/errorTypes.ts, packages/server/package.json, packages/supi/src/errorTypes.ts, packages/supi/test/offline.ts, shrinkwrap.yaml
=>  fix: when a network connection fails, report correct error message

packages/default-fetcher/package.json, packages/default-resolver/package.json, packages/headless/src/index.ts, packages/package-requester/package.json, packages/package-requester/src/packageRequester.ts, packages/package-requester/test/index.ts, packages/package-store/package.json, packages/resolve-dependencies/package.json, packages/resolve-dependencies/src/resolveDependencies.ts, packages/server/test/index.ts, packages/shamefully-flatten/src/index.ts, packages/shrinkwrap-utils/package.json, packages/store-controller-types/package.json, packages/store-controller-types/src/index.ts, packages/supi/package.json, packages/supi/src/install/link.ts, packages/supi/src/install/resolvePeers.ts, packages/supi/src/rebuild/index.ts, packages/supi/src/storeAdd.ts, packages/supi/src/uninstall/index.ts, packages/supi/test/install/shrinkwrapDirectory.ts, shrinkwrap.yaml
This is an issue that may only happen in monorepos that use a
shared shrinkwrap.yaml
=> fix: path to local tarball should be relative to shrinkwrap dir

packages/default-fetcher/src/index.ts, packages/package-store/src/fs/linkIndexedDir.ts, packages/pnpm/package.json, packages/pnpm/src/createStore.ts, packages/pnpm/test/install/misc.ts, packages/supi/package.json, packages/supi/test/install/misc.ts, packages/tarball-fetcher/package.json, packages/tarball-fetcher/src/createDownloader.ts, packages/tarball-fetcher/src/index.ts, pnpm-lock.yaml
=> fix: ignore file duplicates on case insensitive filesystems

packages/config/src/index.ts, packages/config/test/index.ts, packages/pnpm/src/cmd/link.ts, packages/pnpm/src/getConfigs.ts, packages/pnpm/src/main.ts
=> fix: depth should be 0 by default for list command

packages/headless/src/index.ts, packages/supi/src/install/link.ts, packages/supi/test/install/misc.ts
=> fix: reinstall missing packages to node_modules

packages/config/src/PnpmConfigs.ts, packages/config/src/index.ts, packages/config/test/index.ts, packages/default-reporter/src/reporterForClient/pkgsDiff.ts, packages/default-reporter/src/reporterForClient/reportSummary.ts, packages/default-reporter/test/index.ts, packages/pnpm/src/cmd/help.ts, packages/pnpm/src/cmd/install.ts, packages/pnpm/src/cmd/recursive/index.ts, packages/pnpm/src/types.ts, packages/pnpm/test/install/misc.ts, packages/supi/src/install/index.ts, packages/supi/src/save.ts, packages/supi/src/uninstall/removeDeps.ts, packages/supi/test/install/peerDependencies.ts
=> feat: --save-peer

packages/headless/package.json, packages/lockfile-types/index.d.ts, packages/outdated/package.json, packages/pnpm/package.json, packages/resolve-dependencies/src/resolveDependencies.ts, packages/supi/package.json, packages/supi/src/install/resolvePeers.ts, packages/supi/src/install/updateLockfile.ts, packages/supi/test/install/peerDependencies.ts, packages/types/src/package.ts, pnpm-lock.yaml
=> feat: optional peer dependencies

packages/fetch-from-npm-registry/package.json, packages/fetch-from-npm-registry/src/index.ts, packages/fetch-from-npm-registry/test/index.ts, pnpm-lock.yaml
Authorization headers should be removed on redirects.
close #1815
TODO:
cc @aquark, @schummar, @christiango
=> fix: fails to install from private registry (Azure Devops)

packages/lockfile-utils/test/pkgSnapshotToResolution.ts, packages/supi/src/install/updateLockfile.ts, packages/supi/test/lockfile.ts
=> fix(lockfile): relative tarballs should not start with slash

packages/pnpm/src/cmd/publish.ts, packages/pnpm/test/publish.ts, packages/types/src/package.ts
=> feat: allow typings, types, main and module in publishConfig

packages/build-modules/src/index.ts, packages/config/src/PnpmConfigs.ts, packages/config/src/index.ts, packages/config/test/index.ts, packages/headless/package.json, packages/headless/src/index.ts, packages/lifecycle/package.json, packages/lifecycle/src/index.ts, packages/lifecycle/src/runLifecycleHook.ts, packages/lifecycle/src/runLifecycleHooksConcurrently.ts, packages/outdated/package.json, packages/pnpm/package.json, packages/pnpm/src/bin/pnpx.ts, packages/pnpm/src/cmd/recursive/run.ts, packages/pnpm/src/types.ts, packages/pnpm/test/monorepo/index.ts, packages/pnpm/test/recursive/run.ts, packages/pnpm/test/utils/execPnpm.ts, packages/pnpm/test/utils/index.ts, packages/supi/package.json, packages/supi/src/install/extendInstallOptions.ts, packages/supi/src/install/index.ts, packages/supi/src/rebuild/extendRebuildOptions.ts, packages/supi/src/rebuild/index.ts, pnpm-lock.yaml
=> feat: prepend workspace bins to PATH for lifecycle scripts

packages/supi/src/install/index.ts, packages/supi/test/install/local.ts, packages/supi/test/install/misc.ts
=> fix: pnpm install should not update existing lockfile

packages/resolve-dependencies/src/index.ts, packages/resolve-dependencies/src/resolveDependencies.ts, packages/supi/src/install/index.ts, packages/supi/test/lockfile.ts
=> fix: preserve existing versions when updating lockfile format

packages/config/src/PnpmConfigs.ts, packages/config/src/index.ts, packages/headless/package.json, packages/outdated/package.json, packages/pnpm/package.json, packages/pnpm/src/cmd/run.ts, packages/pnpm/src/types.ts, packages/pnpm/test/install/global.ts, packages/supi/package.json, pnpm-lock.yaml
=> fix: use the right cwd when building deps of global packages

packages/dependencies-hierarchy/package.json, packages/dependencies-hierarchy/src/index.ts, packages/dependencies-hierarchy/test/index.ts, packages/pnpm/src/cmd/help.ts, pnpm-lock.yaml
=> feat(list): search by globs

packages/outdated/package.json, packages/outdated/src/index.ts, packages/outdated/test/index.ts, packages/pnpm/src/cmd/help.ts, pnpm-lock.yaml
=> feat(outdated): pnpm outdated supports selection by pattern

packages/headless/package.json, packages/outdated/package.json, packages/pnpm/package.json, packages/pnpm/src/cmd/install.ts, packages/pnpm/test/rebuild.ts, packages/supi/package.json, pnpm-lock.yaml
=> fix: partial install in monorepo with --independent-leaves

packages/pnpm/package.json, packages/pnpm/src/cmd/outdated.ts, packages/pnpm/src/cmd/recursive/outdated.ts, packages/pnpm/src/main.ts, packages/pnpm/test/outdated.ts, packages/pnpm/test/recursive/outdated.ts, pnpm-lock.yaml
=> Better "pnpm outdated"

packages/pnpm/src/cmd/help.ts, packages/pnpm/src/cmd/index.ts, packages/pnpm/src/cmd/install.ts, packages/pnpm/src/cmd/recursive/index.ts, packages/pnpm/src/getCommandFullName.ts, packages/pnpm/src/main.ts, packages/pnpm/test/install/misc.ts
=> feat(pnpm): Make `pnpm add` require the <pkg> parameter

packages/outdated/src/index.ts, packages/outdated/test/index.ts, packages/pnpm/src/cmd/outdated.ts, packages/pnpm/src/cmd/recursive/outdated.ts, packages/pnpm/test/outdated.ts, packages/pnpm/test/packages/has-outdated-deps/node_modules/.pnpm-lock.yaml, packages/pnpm/test/packages/has-outdated-deps/package.json, packages/pnpm/test/packages/has-outdated-deps/pnpm-lock.yaml, packages/pnpm/test/recursive/outdated.ts
=> feat(cli): outdated should print deprecated pkgs

packages/config/src/index.ts, packages/config/test/index.ts, packages/pnpm/src/cmd/help.ts, packages/pnpm/src/cmd/recursive/index.ts, packages/pnpm/test/install/global.ts, packages/pnpm/test/list.ts, packages/pnpm/test/recursive/misc.ts, packages/pnpm/test/root.ts, packages/supi/src/getContext/index.ts
Also, --no-hoist flag supported
=> feat: hoist by default

packages/pnpm/package.json, packages/pnpm/src/cmd/help.ts, pnpm-lock.yaml
=> Nicer alignments in the help command output

packages/pnpm/test/install/selfUpdate.ts, packages/pnpm/test/monorepo/index.ts, packages/pnpm/test/recursive/misc.ts, packages/pnpm/test/server.ts, packages/pnpm/test/utils/execPnpm.ts, packages/pnpm/test/utils/index.ts
This fixes the names and implementations of functions in `execPnpm.ts`.
=> test(pnpm/utils): Fix `execPnpm.ts`

packages/config/src/Config.ts, packages/config/src/index.ts, packages/config/test/index.ts, packages/pnpm/src/cmd/help.ts, packages/pnpm/src/main.ts
=> feat: --color

packages/find-packages/package.json, packages/find-packages/src/index.ts, packages/pnpm/src/findWorkspacePackages.ts, packages/pnpm/src/packageIsInstallable.ts, pnpm-lock.yaml
This adds a return type to `find‑packages`.
=> feat(find‑packages): Add return type

packages/supi/test/install/aliases.ts, packages/supi/test/install/auth.ts, packages/supi/test/install/fromRepo.ts, packages/supi/test/install/fromTarball.ts, packages/supi/test/install/hoist.ts, packages/supi/test/install/independentLeaves.ts, packages/supi/test/install/lifecycleScripts.ts, packages/supi/test/install/local.ts, packages/supi/test/install/misc.ts, packages/supi/test/install/only.ts, packages/supi/test/install/optionalDependencies.ts, packages/supi/test/install/peerDependencies.ts, packages/supi/test/install/reporting.ts, packages/supi/test/install/sideEffects.ts, packages/supi/test/install/store.ts, packages/supi/test/install/updatingPkgJson.ts, packages/supi/test/link.ts, packages/supi/test/lockfile.ts, packages/supi/test/offline.ts, packages/supi/test/packageImportMethods.ts, packages/supi/test/rebuild.ts, packages/supi/test/storeStatus.ts, packages/supi/test/uninstall.ts, packages/supi/test/unlink.ts, packages/supi/test/utils/testDefaults.ts
Don't unpack all files when installing deps in tests
=> test: speed up tests execution

packages/pnpm/src/cmd/recursive/run.ts, packages/pnpm/src/cmd/run.ts, packages/pnpm/test/run.ts
=> fix: don't forward tail args to pre/post scripts

packages/modules-cleaner/src/prune.ts, packages/supi/src/install/index.ts, packages/supi/test/install/misc.ts
=> fix: always save the store metadata. Even on crash

packages/config/src/Config.ts, packages/config/src/index.ts, packages/pnpm/src/cmd/help.ts, packages/pnpm/src/cmd/link.ts, packages/pnpm/src/main.ts, packages/pnpm/test/install/global.ts, packages/supi/README.md, packages/supi/src/link/index.ts, packages/supi/test/link.ts
=> feat: rename pnpm-prefix to global-dir

packages/pnpm/src/cmd/install.ts, packages/pnpm/src/cmd/recursive/index.ts, packages/pnpm/src/main.ts, packages/pnpm/test/monorepo/index.ts, packages/pnpm/test/update.ts, packages/resolve-dependencies/src/getNonDevWantedDependencies.ts, packages/resolve-dependencies/src/index.ts, packages/resolve-dependencies/src/resolveDependencies.ts, packages/resolve-dependencies/src/wantedDepIsLocallyAvailable.ts, packages/supi/src/install/getWantedDependencies.ts, packages/supi/src/install/index.ts, packages/supi/src/link/index.ts, packages/supi/src/parseWantedDependencies.ts, packages/supi/src/save.ts, packages/supi/src/utils/getPref.ts, packages/supi/test/install/updatingPkgJson.ts, packages/utils/src/getWantedDependencies.ts, packages/utils/src/index.ts
close #2130
close #1657
- @pnpm/utils
=> feat(update): version ranges are updated in package.json

packages/supi/package.json, packages/supi/src/guessPinnedVersionFromExistingSpec.ts, packages/supi/src/install/getWantedDependencies.ts, packages/supi/src/install/index.ts, packages/supi/src/parseWantedDependencies.ts, packages/supi/src/utils/getPref.ts, packages/supi/test/install/multipleImporters.ts, pnpm-lock.yaml, typings/typed.d.ts
=> feat: update workpace dependencies

packages/pkgs-graph/src/index.ts
Use `Array.includes()` to check for existence.
=> chore: minor code refactor

packages/outdated/package.json, packages/outdated/src/index.ts, packages/outdated/test/index.ts, pnpm-lock.yaml
=> fix(outdated): a dep is not outdated if it's newer than current

package.json, packages/resolve-dependencies/src/resolveDependencies.ts, packages/supi/test/install/peerDependencies.ts, pnpm-lock.yaml
=> feat: peerDependenciesMeta implies peerDependencies

packages/filter-lockfile/package.json, packages/filter-lockfile/src/filterLockfileByImporters.ts, packages/hoist/package.json, packages/hoist/src/index.ts, packages/lockfile-walker/README.md, packages/lockfile-walker/package.json, packages/lockfile-walker/src/index.ts, packages/lockfile-walker/tsconfig.json, packages/lockfile-walker/tslint.json, packages/supi/package.json, packages/supi/src/rebuild/index.ts, pnpm-lock.yaml
This will make it easier to do #1153
=> refactor: create a lockfile walker

packages/pnpm/src/bin/pnpm.ts, packages/pnpm/src/cmd/add.ts, packages/pnpm/src/cmd/audit.ts, packages/pnpm/src/cmd/help.ts, packages/pnpm/src/cmd/import.ts, packages/pnpm/src/cmd/index.ts, packages/pnpm/src/cmd/install.ts, packages/pnpm/src/cmd/installTest.ts, packages/pnpm/src/cmd/link.ts, packages/pnpm/src/cmd/list.ts, packages/pnpm/src/cmd/outdated.ts, packages/pnpm/src/cmd/pack.ts, packages/pnpm/src/cmd/prune.ts, packages/pnpm/src/cmd/publish.ts, packages/pnpm/src/cmd/rebuild.ts, packages/pnpm/src/cmd/recursive/index.ts, packages/pnpm/src/cmd/remove.ts, packages/pnpm/src/cmd/restart.ts, packages/pnpm/src/cmd/root.ts, packages/pnpm/src/cmd/run.ts, packages/pnpm/src/cmd/server/index.ts, packages/pnpm/src/cmd/start.ts, packages/pnpm/src/cmd/stop.ts, packages/pnpm/src/cmd/store.ts, packages/pnpm/src/cmd/test.ts, packages/pnpm/src/cmd/unlink.ts, packages/pnpm/src/cmd/update.ts, packages/pnpm/src/cmd/why.ts, packages/pnpm/src/main.ts, packages/pnpm/test/outdated.ts
=> refactor: move help and aliases to command files

packages/common-cli-options-help/src/index.ts, packages/plugin-commands-recursive/src/filter.ts, packages/plugin-commands-recursive/src/parsePackageSelectors.ts, packages/plugin-commands-recursive/test/misc.ts
`package^..` is like `package...` but excludes `package` itself. `..^package` is like `...package` but excludes `package` itself.
=> feat: add `^..' and `..^' filters

packages/supi/src/install/getPreferredVersions.ts, packages/supi/src/install/index.ts, packages/supi/test/install/update.ts
=> fix: prefer reusing already existing pkg versions when installing

packages/plugin-commands-script-runners/src/restart.ts, packages/plugin-commands-script-runners/src/run.ts, packages/plugin-commands-script-runners/src/start.ts, packages/plugin-commands-script-runners/src/stop.ts, packages/plugin-commands-script-runners/src/test.ts, packages/plugin-commands-script-runners/test/index.ts
=> feat(run): --if-present

packages/supi/src/install/index.ts, packages/supi/src/utils/getPref.ts, packages/supi/test/install/misc.ts
=> fix: updating package version w/o being told to do so

packages/common-cli-options-help/src/index.ts, packages/filter-workspace-packages/package.json, packages/filter-workspace-packages/src/getChangedPackages.ts, packages/filter-workspace-packages/src/index.ts, packages/filter-workspace-packages/src/parsePackageSelector.ts, packages/filter-workspace-packages/test/index.ts, packages/filter-workspace-packages/test/parsePackageSelector.ts, packages/plugin-commands-recursive/src/recursive.ts, pnpm-lock.yaml
=> feat: filtering by changed packages

packages/pnpmfile/package.json, packages/pnpmfile/src/requirePnpmfile.ts, packages/pnpmfile/test/index.ts, packages/pnpmfile/test/pnpmfiles/undefined.js
=> fix: print warning when pnpmfile exports undefined

packages/plugin-commands-installation/src/remove.ts, packages/supi/src/uninstall/removeDeps.ts
=> fix(rm): --save-dev|--save-optional|--save-prod

packages/npm-resolver/example.js, packages/npm-resolver/src/pickPackage.ts, packages/npm-resolver/test/index.ts
additionally, fix usage in example
=> feat: check package name for scope and report better error #1306

packages/cli-utils/package.json, packages/cli-utils/src/pnpmPkgJson.ts, packages/store-connection-manager/package.json, packages/store-connection-manager/src/runServerInBackground.ts, pnpm-lock.yaml
=> fix: finding pnpm's main manifest location

packages/npm-resolver/src/fetch.ts, packages/npm-resolver/test/index.ts
=> feat: add info when not-found package name has valid semver

packages/modules-cleaner/package.json, packages/modules-cleaner/src/removeDirectDependency.ts, packages/supi/test/uninstall.ts, pnpm-lock.yaml
=> fix: remove all .cmd/.ps1 binstubs on Windows

packages/cli-utils/src/pnpmPkgJson.ts, packages/pnpm/src/bin/pnpx.ts, packages/pnpm/test/cli.ts
Fix a regression of pnpx caused by #2303
close #2331
close #2324
=> fix: pnpx regression introduced by 4.9.0

fixtures/has-no-lockfile/.gitignore, fixtures/has-no-lockfile/.npmrc, fixtures/has-no-lockfile/package.json, packages/outdated/src/outdated.ts, packages/outdated/src/outdatedDepsOfProjects.ts, packages/outdated/test/outdated.spec.ts, packages/plugin-commands-outdated/test/index.ts
=> feat(outdated): don't fail when no lockfile & no deps

packages/plugin-commands-installation/test/miscRecursive.ts, packages/pnpm/test/recursive/update.ts, packages/pnpm/test/update.ts, packages/supi/src/parseWantedDependencies.ts, packages/supi/test/install/misc.ts
=> fix: preserve version prefix on update

packages/plugin-commands-installation/src/installDeps.ts, packages/plugin-commands-installation/src/recursive.ts, packages/plugin-commands-installation/test/update/interactive.ts, packages/plugin-commands-installation/test/update/recursive.ts, packages/plugin-commands-installation/test/update/update.ts, packages/pnpm/test/update.ts
=> fix: update -r --prod should not update dev deps

packages/plugin-commands-installation/src/prune.ts, packages/plugin-commands-installation/test/prune.ts
=> fix: prune --prod

packages/default-reporter/src/reportError.ts, packages/default-reporter/test/reportingErrors.ts, packages/default-resolver/package.json, packages/default-resolver/src/index.ts, packages/error/src/index.ts, packages/resolve-dependencies/src/resolveDependencies.ts, packages/supi/test/install/misc.ts, pnpm-lock.yaml
=> fix: print a better error message on bad spec

packages/parse-cli-args/src/index.ts, packages/parse-cli-args/test/index.ts, packages/pnpm/src/main.ts
=> fix(CLI): correct error on unknown recursive cmds

packages/link-bins/src/index.ts, packages/supi/src/install/extendInstallOptions.ts, packages/supi/src/install/index.ts, packages/supi/test/install/misc.ts
Close #2309.
Is this the right direction? also thinking of testing solution.
=> feat: print a warning if a globally installed package has no bins

packages/plugin-commands-installation/src/recursive.ts, packages/plugin-commands-installation/test/miscRecursive.ts
=> fix: rm -r in workspace with non-shared lockfile

packages/pnpm/package.json, packages/pnpm/src/main.ts, pnpm-lock.yaml
This will hopefully fix #990 and fix #1591
=> fix: global update of pnpm

packages/default-reporter/src/reportError.ts, packages/default-reporter/test/reportingErrors.ts, packages/error/src/index.ts, packages/plugin-commands-installation/src/index.ts, packages/plugin-commands-installation/src/remove.ts, packages/plugin-commands-installation/test/remove/remove.ts, packages/pnpm/test/install/misc.ts
=> feat: rm should fail if dep is not available

packages/filter-lockfile/src/LockfileMissingDependencyError.ts, packages/filter-lockfile/src/filterLockfileByImporters.ts, packages/filter-lockfile/src/filterLockfileByImportersAndEngine.ts, packages/filter-lockfile/test/filterByImporters.ts, packages/supi/src/install/index.ts, packages/supi/test/lockfile.ts
Unless frozenLockfile is true, a broken lockfile should
be fixed and installation should succeed.
=> fix: a broken lockfile should be fixed

packages/audit/package.json, packages/audit/src/index.ts, packages/audit/test/index.ts, packages/audit/test/lockfileToAuditTree.ts, pnpm-lock.yaml
=> fix(audit): fail in case of a server error

.changeset/mighty-keys-type.md, package.json, packages/lifecycle/src/runLifecycleHook.ts
=> feat: skip scripts that use "npx only-allow pnpm"

.changeset/breezy-maps-double.md, packages/cafs/src/checkFilesIntegrity.ts, packages/cafs/src/getFilePathInCafs.ts, packages/cafs/src/index.ts, packages/package-requester/src/packageRequester.ts, packages/package-requester/test/index.ts, packages/package-store/src/storeController/index.ts, packages/plugin-commands-store/package.json, packages/plugin-commands-store/src/storeStatus/index.ts, packages/plugin-commands-store/test/storeAdd.ts, packages/plugin-commands-store/test/storePrune.ts, packages/plugin-commands-store/test/storeStatus.ts, packages/plugin-commands-store/test/storeUsages.ts, packages/pnpm/test/install/misc.ts, packages/supi/test/install/lockfileOnly.ts, packages/tarball-fetcher/test/download.ts, pnpm-lock.yaml, privatePackages/assert-project/src/index.ts, privatePackages/assert-store/package.json, privatePackages/assert-store/src/index.ts
Store the package index files in the CAFS.
ref #2521
=> perf: reduce directory nesting in the store

.changeset/long-masks-burn.md, packages/package-store/package.json, packages/package-store/src/storeController/index.ts, packages/package-store/src/storeController/prune.ts, packages/plugin-commands-store/test/storePrune.ts, pnpm-lock.yaml
=> feat: pruning of the content-addressable store

packages/pnpm/src/cmd/help.ts, packages/pnpm/test/help.spec.ts
=> WIP chore: add descriptions to cli commands

packages/pnpm/README.md
pnpm is still unknown for many developers. As a result, when they
first find it, their first assumption is that it is "a new package
manager".
So we should mention in the README that pnpm has years of development
invested into it, and it is used by some big companies.
=> Improvements to the README file

.changeset/eleven-hounds-exercise.md, packages/pnpm/src/main.ts, packages/pnpm/test/cli.ts
=> fix: don't error on deprecated options

.changeset/rich-experts-whisper.md, packages/package-requester/package.json, packages/package-requester/src/packageRequester.ts, pnpm-lock.yaml
=> fix: too long file names when writing to store

.changeset/great-chairs-look.md, .changeset/lucky-oranges-wonder.md, .changeset/nasty-wasps-rest.md, .changeset/swift-glasses-impress.md, packages/dependency-path/src/index.ts, packages/dependency-path/test/index.ts, packages/supi/src/install/lockfile.ts, packages/supi/test/lockfile.ts, packages/tarball-resolver/src/index.ts, packages/tarball-resolver/test/index.ts
=> fix: installing tarballs from registry origin via non-standard URLs

.changeset/cyan-dingos-switch.md, .changeset/fluffy-kiwis-add.md, packages/outdated/src/createManifestGetter.ts, packages/plugin-commands-publishing/src/recursivePublish.ts
=> perf: don't request the full metadata

.changeset/good-rings-carry.md, packages/supi/src/install/link.ts, packages/supi/test/install/optionalDependencies.ts
=> fix: broken current lockfile on partial install

.changeset/orange-phones-press.md, packages/package-store/src/storeController/prune.ts, packages/plugin-commands-store/test/storePrune.ts
=> fix: do not scan non-directories in store directory when pruning store

.changeset/long-otters-sell.md, .changeset/seven-rocks-arrive.md, .changeset/weak-feet-taste.md, packages/config/package.json, packages/config/src/Config.ts, packages/config/src/index.ts, packages/config/tsconfig.json, packages/global-bin-dir/README.md, packages/global-bin-dir/package.json, packages/global-bin-dir/src/index.ts, packages/global-bin-dir/test/index.ts, packages/global-bin-dir/tsconfig.json, packages/plugin-commands-installation/package.json, packages/plugin-commands-installation/src/link.ts, packages/plugin-commands-installation/src/unlink.ts, packages/plugin-commands-installation/tsconfig.json, packages/pnpm/test/link.ts, packages/pnpm/test/uninstall.ts, pnpm-lock.yaml
ref #1360
can be tried out through: `npm i -g pnpm@dev`
=> Fixing issues with global install

.changeset/itchy-grapes-battle.md, .changeset/strong-plants-shake.md, packages/config/src/Config.ts, packages/config/src/index.ts, packages/global-bin-dir/src/index.ts, packages/global-bin-dir/test/index.ts, packages/plugin-commands-installation/src/link.ts, packages/plugin-commands-installation/test/prune.ts
=> fix: finding a suitable global executables directory

.changeset/brave-teachers-fail.md, .changeset/mean-spies-rhyme.md, .changeset/wet-planes-do.md, packages/headless/src/index.ts, packages/lifecycle/src/runLifecycleHook.ts, packages/plugin-commands-rebuild/src/implementation/index.ts, packages/plugin-commands-script-runners/src/run.ts, packages/plugin-commands-store/src/storeAdd.ts, packages/plugin-commands-store/src/storePrune.ts, packages/plugin-commands-store/src/storeStatus/index.ts, packages/pnpm/src/err.ts, packages/pnpm/src/main.ts, packages/pnpm/test/run.ts, packages/supi/src/install/index.ts, packages/supi/src/link/index.ts
=> fix: run --silent

.changeset/honest-steaks-cheat.md, .changeset/serious-plants-fix.md, packages/prune-lockfile/src/index.ts, packages/resolve-dependencies/src/resolveDependencies.ts, packages/supi/test/install/optionalDependencies.ts
...that has an optional dependency
close #2663
=> fix: installing a new optional dependency

.changeset/nasty-walls-destroy.md, packages/parse-cli-args/src/index.ts, packages/parse-cli-args/test/index.ts, packages/pnpm/src/parseCliArgs.ts, packages/pnpm/test/cli.ts
=> feat: any unknown command is assumed to be a script

.changeset/lemon-otters-talk.md, .changeset/nasty-walls-destroy.md, packages/parse-cli-args/src/index.ts, packages/parse-cli-args/test/index.ts, packages/pnpm/src/cmd/index.ts, packages/pnpm/src/parseCliArgs.ts
=> refactor(parse-cli-args): add opts.fallbackCommand

.changeset/early-pumpkins-smoke.md, packages/supi/test/install/fromRepo.ts, packages/tarball-resolver/src/index.ts, packages/tarball-resolver/test/index.ts
=> feat: install git-hosted dep through the repo URL

.changeset/healthy-cups-cross.md, packages/find-workspace-packages/package.json, packages/find-workspace-packages/src/index.ts, packages/find-workspace-packages/test/index.ts
=> feat: treat a pkg with no version as if it had v0.0.0

.changeset/nasty-teachers-matter.md, packages/config/src/index.ts
=> feat: hoist all ESLint plugins to the root node_modules

packages/git-resolver/package.json, packages/git-resolver/src/index.ts, packages/git-resolver/src/parsePref.ts, packages/git-resolver/test/index.ts, pnpm-lock.yaml
=> feat: installation of private git-hosted repos using auth tokens

.changeset/afraid-parrots-accept.md, packages/pnpm/src/main.ts, packages/pnpm/test/recursive/misc.ts
=> feat: `pnpm install` worked like `pnpm install --filter {.}...` when recursiveInstall is false

.changeset/tame-spoons-provide.md, packages/list/src/renderTree.ts, packages/list/test/index.ts
=> fix(list): don't use inverse to highight

.changeset/eighty-tables-train.md, packages/pnpm/package.json, packages/pnpm/src/main.ts, pnpm-lock.yaml
=> fix: --no-color should work with all commands

.changeset/proud-beds-clean.md, packages/plugin-commands-publishing/src/recursivePublish.ts, packages/plugin-commands-publishing/test/recursivePublish.ts
=> fix: pnpm publish -r --dry-run

.changeset/slimy-sheep-prove.md, .changeset/strong-dogs-greet.md, packages/headless/src/index.ts, packages/prune-lockfile/src/index.ts, packages/supi/test/install/peerDependencies.ts
=> fix: pnpm i --prod --frozen-lockfile with peer deps

.changeset/dirty-comics-doubt.md, packages/get-context/src/index.ts
=> fix: don't remove the modules directory, just the contents of it

.changeset/fifty-avocados-sneeze.md, packages/plugin-commands-audit/src/audit.ts, packages/plugin-commands-audit/test/index.ts
=> fix(audit): don't error when the found vulnerabilities are allowed

.changeset/wise-deers-provide.md, packages/plugin-commands-publishing/src/publish.ts, packages/plugin-commands-publishing/test/publish.ts
=> Added workspace peer dependencies substitution

.changeset/moody-humans-jam.md, packages/lockfile-utils/src/pkgSnapshotToResolution.ts, packages/lockfile-utils/test/pkgSnapshotToResolution.ts
=> fix: registry set in lockfile resolution should not be ignored

.changeset/blue-zoos-leave.md, packages/npm-resolver/src/pickPackageFromMeta.ts, packages/npm-resolver/test/index.ts, packages/npm-resolver/test/meta/is-positive-broken.json
=> fix: get the right pkg name of a pkg resolved from GitHub registry

.changeset/hot-berries-invent.md, packages/read-modules-dir/src/index.ts, packages/supi/test/install/misc.ts
=> fix: ignore files in node_modules

.changeset/cuddly-moons-hug.md, .changeset/pretty-hounds-jump.md, packages/read-project-manifest/src/index.ts, packages/read-project-manifest/test/index.ts, packages/write-project-manifest/package.json, packages/write-project-manifest/src/index.ts, pnpm-lock.yaml
=> fix: don't alway add a trailing new line to package.json

.changeset/giant-lions-march.md, packages/parse-cli-args/src/index.ts, packages/parse-cli-args/test/index.ts, packages/pnpm/src/formatError.ts, packages/pnpm/test/formatError.test.ts
=> feat: allow unknown options if they are prefixed with "config."

.changeset/bright-flowers-exist.md, fixtures/pkg-with-external-lockfile/pkg/.npmrc, fixtures/pkg-with-external-lockfile/pkg/package.json, fixtures/pkg-with-external-lockfile/pnpm-lock.yaml, packages/headless/package.json, packages/headless/src/index.ts, packages/headless/test/index.ts, pnpm-lock.yaml, privatePackages/test-fixtures/package.json, privatePackages/test-fixtures/src/index.ts
=> fix: hoisting in a workspace with no root package

.changeset/gorgeous-laws-rush.md, packages/headless/tsconfig.json, packages/supi/src/install/link.ts, packages/supi/test/install/local.ts
=> fix: reunpack the contents of a modified tarball dep

.changeset/funny-goats-march.md, packages/plugin-commands-publishing/src/recursivePublish.ts
=> fix(publish): don't use pnpm-temp dist tag

.changeset/fuzzy-pots-march.md, .changeset/real-ducks-cross.md, .changeset/weak-seas-complain.md, packages/default-reporter/src/index.ts, packages/default-reporter/src/reportError.ts, packages/default-reporter/src/reporterForClient/index.ts, packages/default-reporter/src/reporterForClient/reportMisc.ts, packages/default-reporter/src/reporterForServer.ts, packages/default-reporter/test/reportingErrors.ts, packages/error/src/index.ts, packages/npm-resolver/src/fetch.ts, packages/npm-resolver/test/index.ts, packages/plugin-commands-installation/test/miscRecursive.ts, packages/server/test/index.ts, packages/tarball-fetcher/src/createDownloader.ts, packages/tarball-fetcher/test/download.ts
=> feat: print more info on forbid errors

.changeset/hot-timers-count.md, packages/config/src/index.ts
=> fix: publicly hoist any dependency that is related to ESLint

.changeset/metal-flowers-prove.md, packages/plugin-commands-installation/src/installDeps.ts, packages/plugin-commands-installation/src/recursive.ts, packages/plugin-commands-installation/test/update/update.ts
=> fix: adding new dependency in a workspace project

.changeset/brown-poems-prove.md, packages/config/src/index.ts, packages/config/test/index.ts
=> fix: global install with save set to false

.changeset/shiny-years-brush.md, packages/npm-resolver/src/index.ts, packages/npm-resolver/test/index.ts
=> fix: print the actual version in no matching version error

.changeset/smooth-drinks-do.md, packages/plugin-commands-script-runners/src/run.ts, packages/plugin-commands-script-runners/test/index.ts
=> feat(run): print info about root workspace scripts

.changeset/honest-walls-train.md, packages/package-store/src/storeController/createImportPackage.ts, packages/package-store/test/createImportPackage.spec.ts
=> fix: import method selection on unknown errors

jest.config.js, packages/client/jest.config.js, packages/client/package.json, packages/client/test/index.ts
client package
https://github.com/pnpm/pnpm/issues/2858
=> refactor: client pkg to jest

packages/fetch/jest.config.js, packages/fetch/package.json, packages/fetch/test/fetchFromRegistry.ts
https://github.com/pnpm/pnpm/issues/2858
=> refactor: fetch pkg to jest

packages/filter-lockfile/jest.config.js, packages/filter-lockfile/package.json, packages/filter-lockfile/test/filterByImporters.ts, packages/filter-lockfile/test/filterByImportersAndEngine.ts, packages/filter-workspace-packages/jest.config.js, packages/filter-workspace-packages/package.json, packages/filter-workspace-packages/test/index.ts, packages/filter-workspace-packages/test/parsePackageSelector.ts, packages/find-packages/jest.config.js, packages/find-packages/package.json, packages/find-packages/test/index.ts, packages/find-workspace-packages/jest.config.js, packages/find-workspace-packages/package.json, packages/find-workspace-packages/test/index.ts
https://github.com/pnpm/pnpm/issues/2858
=> Jest migration chapter 3

.changeset/smooth-zoos-rush.md, packages/global-bin-dir/src/index.ts, packages/global-bin-dir/test/index.ts
When searching for a global bin directory, also look for symlinked
commands.
close #2888
=> fix: finding global bin directory

.changeset/twenty-drinks-juggle.md, packages/get-context/src/index.ts
Fixes <https://github.com/pnpm/pnpm/issues/2506>
=> fix: don’t remove non‑pnpm `.dot_files` from `node_modules`

.changeset/lovely-kiwis-care.md, packages/supi/src/install/link.ts, packages/supi/test/install/only.ts
=> fix: installing prod deps only

packages/config/jest.config.js, packages/config/package.json, packages/config/test/findBestGlobalPrefixOnWindows.ts, packages/config/test/index.ts, packages/default-resolver/jest.config.js, packages/default-resolver/package.json, packages/default-resolver/test/index.ts, packages/dependency-path/jest.config.js, packages/dependency-path/package.json, packages/dependency-path/test/index.ts
/pnpm/packages/default-resolver @juanpicado
/pnpm/packages/dependency-path @juanpicado
/pnpm/packages/config @juanpicado
=> test: refactor packages to jest

packages/local-resolver/jest.config.js, packages/local-resolver/package.json, packages/local-resolver/test/index.ts, packages/lockfile-file/jest.config.js, packages/lockfile-file/package.json, packages/lockfile-file/test/read.ts, packages/lockfile-utils/jest.config.js, packages/lockfile-utils/package.json, packages/lockfile-utils/test/nameVerFromPkgSnapshot.ts, packages/lockfile-utils/test/pkgSnapshotToResolution.ts, packages/lockfile-utils/test/satisfiesPackageManifest.ts
Migrated 3 more packages over to Jest
* `local-resolver`
* `lockfile-file`
* `lockfile-utils`
=> Migrate more tests to Jest

packages/filter-lockfile/jest.config.js, packages/find-packages/jest.config.js, packages/find-workspace-packages/jest.config.js, packages/git-fetcher/jest.config.js, packages/git-fetcher/package.json, packages/git-fetcher/test/index.ts, packages/global-bin-dir/jest.config.js, packages/global-bin-dir/package.json, packages/global-bin-dir/test/index.ts, pnpm-lock.yaml
- /pnpm/packages/git-fetcher
- /pnpm/packages/global-bin-dir
=> test: jest migration 

.changeset/metal-cycles-cheat.md, packages/constants/src/index.ts, packages/resolve-dependencies/src/resolveDependencies.ts, packages/resolve-dependencies/src/resolvePeers.ts, packages/resolve-dependencies/test/resolvePeers.ts, packages/supi/test/install/peerDependencies.ts
=> fix: recursive peer dependency

.changeset/late-items-fail.md, packages/resolve-dependencies/src/resolvePeers.ts, packages/resolve-dependencies/test/resolvePeers.ts
=> fix: caching during peer resolution

.changeset/red-tools-thank.md, packages/link-bins/src/index.ts
=> fix: linking bins inside a workspace

.changeset/large-avocados-run.md, package.json, packages/build-modules/src/index.ts, packages/config/src/Config.ts, packages/config/src/index.ts, packages/headless/src/index.ts, packages/lifecycle/src/runLifecycleHook.ts, packages/plugin-commands-installation/src/installDeps.ts, packages/plugin-commands-rebuild/src/implementation/extendRebuildOptions.ts, packages/plugin-commands-rebuild/src/implementation/index.ts, packages/plugin-commands-rebuild/src/rebuild.ts, packages/plugin-commands-script-runners/src/run.ts, packages/plugin-commands-script-runners/src/runRecursive.ts, packages/plugin-commands-script-runners/test/index.ts, packages/supi/src/install/extendInstallOptions.ts, packages/supi/src/install/index.ts, pnpm-lock.yaml
=> feat: script-shell

packages/outdated/jest.config.js, packages/outdated/package.json, packages/outdated/test/getManifest.spec.ts, packages/outdated/test/index.ts, packages/outdated/test/outdated.spec.ts, packages/package-bins/jest.config.js, packages/package-bins/package.json, packages/package-bins/test/index.ts, packages/pnpmfile/jest.config.js, packages/pnpmfile/package.json, packages/pnpmfile/src/index.ts, packages/pnpmfile/src/requirePnpmfile.ts, packages/pnpmfile/test/index.ts, utils/updater/src/index.ts
On going jest migration https://github.com/pnpm/pnpm/issues/2858
=> test: migrate packages to jest

.changeset/fifty-seals-approve.md, .changeset/moody-toys-develop.md, .changeset/shy-cheetahs-judge.md, packages/get-context/src/index.ts, packages/get-context/src/readLockfiles.ts, packages/lockfile-file/package.json, packages/lockfile-file/src/autofixMergeConflicts.ts, packages/lockfile-file/src/gitMergeFile.ts, packages/lockfile-file/src/read.ts, packages/merge-lockfiles/README.md, packages/merge-lockfiles/jest.config.js, packages/merge-lockfiles/package.json, packages/merge-lockfiles/src/index.ts, packages/merge-lockfiles/test/index.ts, packages/merge-lockfiles/tsconfig.json, packages/merge-lockfiles/tsconfig.lint.json, packages/supi/src/install/index.ts, packages/supi/test/lockfile.ts, pnpm-lock.yaml
=> feat: autofix merge conflicts in pnpm-lock.yaml

.changeset/chilly-scissors-compare.md, packages/npm-resolver/package.json, packages/npm-resolver/src/fetch.ts, packages/npm-resolver/test/index.ts, pnpm-lock.yaml
=> fix: retry metadata download if the received JSON is broken

.changeset/sixty-oranges-jam.md, packages/exportable-manifest/src/index.ts, packages/npm-resolver/src/index.ts, packages/npm-resolver/test/index.ts, packages/plugin-commands-publishing/test/publish.ts
=> feat: aliases for workspace packages

.changeset/flat-socks-dance.md, .changeset/mighty-kangaroos-brake.md, .changeset/quiet-papayas-tie.md, packages/exportable-manifest/src/index.ts, packages/local-resolver/src/parsePref.ts, packages/local-resolver/test/index.ts, packages/npm-resolver/src/index.ts, packages/npm-resolver/test/index.ts, packages/plugin-commands-publishing/test/publish.ts
=> feat: specifying a path to workspace packages in version specs

.changeset/five-baboons-switch.md, packages/config/src/Config.ts, packages/config/src/index.ts, packages/npm-resolver/src/index.ts, packages/npm-resolver/test/index.ts, packages/package-requester/src/packageRequester.ts, packages/plugin-commands-installation/src/install.ts, packages/plugin-commands-installation/test/miscRecursive.ts, packages/resolve-dependencies/src/resolveDependencies.ts, packages/resolve-dependencies/src/resolveDependencyTree.ts, packages/resolver-base/src/index.ts, packages/store-controller-types/src/index.ts, packages/supi/src/install/extendInstallOptions.ts, packages/supi/src/install/index.ts
=> feat: prefer-workspace-packages

.changeset/thin-houses-confess.md, .gitignore, package.json, packages/pnpm/bin/pnpm.js, packages/pnpm/bin/pnpx.js, packages/pnpm/node-gyp-bin/node-gyp, packages/pnpm/node-gyp-bin/node-gyp.cmd, packages/pnpm/package.json, pnpm-lock.yaml, utils/updater/src/index.ts
=> fix: broken Homebrew package

packages/filter-workspace-packages/src/index.ts, packages/filter-workspace-packages/test/index.ts
Closes #2917 
Questions:
- Failed to run `pnpm changeset`, got `Error: Failed to find where HEAD diverged from master. Does master exist?`. Is that OK?
- ~~Can you point me to the e2e tests, so I'll add one there too?~~
=> feat: include dependents dependencies in combined filter

.changeset/hip-clocks-share.md, packages/npm-resolver/src/pickPackageFromMeta.ts, packages/npm-resolver/test/index.ts, packages/npm-resolver/test/meta/malformed.json
=> fix(npm-resolver): throw a meaningful error on malformed meta

.changeset/forty-badgers-add.md, packages/pnpm/package.json, utils/updater/src/index.ts
=> fix: install-completion

.changeset/hungry-dolls-rush.md, packages/headless/src/index.ts, packages/supi/test/install/hoist.ts
=> fix(headless): don't create broken symlinks

.changeset/eighty-hotels-draw.md, packages/plugin-commands-script-runners/src/run.ts, packages/plugin-commands-script-runners/test/index.ts
=> fix: --no-bail

.changeset/silly-moles-sing.md, packages/plugin-commands-installation/src/link.ts, packages/plugin-commands-installation/test/link.ts
=> fix: linking deps by absolute path

.changeset/long-seahorses-arrive.md, packages/pnpm/package.json, packages/pnpm/src/pnpm.ts, pnpm-lock.yaml
=> feat: specify the target shell for completion

.changeset/light-eagles-tan.md, packages/config/src/Config.ts, packages/config/src/index.ts, packages/headless/src/index.ts, packages/headless/test/index.ts, packages/plugin-commands-installation/tsconfig.json, packages/supi/src/install/extendInstallOptions.ts, packages/supi/src/install/index.ts, packages/supi/test/install/misc.ts
Continuation of #3047
Is it a good name for the option?
=> feat: enable-modules-dir=false

.changeset/poor-points-poke.md, packages/supi/src/install/link.ts, packages/supi/test/install/hoist.ts
=> fix: don't create broken symlinks during hoisting

.changeset/friendly-taxis-shave.md, packages/resolve-dependencies/src/resolveDependencies.ts, packages/resolve-dependencies/src/resolveDependencyTree.ts, packages/supi/test/install/multipleImporters.ts
=> fix: overrides using the workspace protocol

.changeset/silent-islands-happen.md, packages/list/src/renderTree.ts, packages/list/test/index.ts
close #3024
side by side comparison
=> fix: format package name in ls comand

.changeset/empty-snails-grin.md, packages/headless/src/index.ts, packages/headless/test/fixtures/has-nonexistent-optional-dep/package.json, packages/headless/test/fixtures/has-nonexistent-optional-dep/pnpm-lock.yaml, packages/headless/test/index.ts
=> fix(headless): skip optional dep that cannot be installed

.changeset/silver-lions-repair.md, packages/global-bin-dir/src/index.ts, packages/global-bin-dir/test/index.ts
=> fix: npx pnpm install --global pnpm

.changeset/dirty-owls-prove.md, .changeset/olive-pianos-eat.md, .changeset/shaggy-experts-worry.md, packages/lockfile-file/src/write.ts, packages/lockfile-file/test/normalizeLockfile.test.ts, packages/lockfile-types/src/index.ts, packages/resolve-dependencies/src/resolveDependencies.ts, packages/resolve-dependencies/src/resolveDependencyTree.ts, packages/supi/src/install/index.ts, packages/supi/test/install/lifecycleScripts.ts, packages/types/src/package.ts
=> feat: ignoring the build of specific dependencies

.changeset/clever-penguins-train.md, .changeset/lucky-mugs-divide.md, .changeset/six-humans-sin.md, .changeset/thick-badgers-perform.md, packages/cli-utils/package.json, packages/cli-utils/src/getConfig.ts, packages/cli-utils/tsconfig.json, packages/config/src/index.ts, packages/config/test/index.ts, packages/default-reporter/src/index.ts, packages/pnpm/src/cmd/index.ts, packages/pnpm/src/main.ts, pnpm-lock.yaml
=> feat: print warnings if unknown settings are found in .npmrc

.changeset/afraid-dryers-sin.md, packages/plugin-commands-publishing/package.json, packages/plugin-commands-publishing/src/recursivePublish.ts, packages/plugin-commands-publishing/test/recursivePublish.ts, pnpm-lock.yaml
=> feat: print an info message when there is no new packages to publish recursively

.changeset/proud-lies-shout.md, packages/config/src/index.ts, packages/config/test/index.ts
=> fix: remove empty keys from config key check

.changeset/proud-snakes-destroy.md, packages/plugin-commands-publishing/src/publish.ts, packages/plugin-commands-publishing/test/publish.ts
=> fix: remove --publish-branch with branch name to npm publish args

.changeset/green-ravens-flow.md, packages/config/src/Config.ts, packages/config/src/index.ts, packages/plugin-commands-script-runners/src/exec.ts, packages/plugin-commands-script-runners/src/runRecursive.ts, packages/plugin-commands-script-runners/test/index.ts, packages/plugin-commands-script-runners/test/runRecursive.ts, packages/pnpm/src/cmd/recursive.ts
=> add --reverse flag

.changeset/funny-goats-drum.md, .changeset/gold-fishes-grow.md, .changeset/swift-jobs-accept.md, packages/outdated/src/createManifestGetter.ts, packages/pick-registry-for-package/jest.config.js, packages/pick-registry-for-package/package.json, packages/pick-registry-for-package/src/index.ts, packages/pick-registry-for-package/test/index.spec.ts, packages/plugin-commands-publishing/src/recursivePublish.ts, packages/plugin-commands-store/src/storeAdd.ts, packages/resolve-dependencies/src/resolveDependencies.ts
=> fix: return correct scoped registry for alias dependency

.changeset/olive-starfishes-reflect.md, .gitignore, packages/headless/src/index.ts, packages/headless/test/index.ts, packages/lockfile-to-pnp/src/index.ts, packages/mount-modules/src/createFuseHandlers.ts, packages/plugin-commands-script-runners/src/exec.ts, packages/plugin-commands-script-runners/src/run.ts, packages/plugin-commands-script-runners/src/runRecursive.ts, packages/supi/src/install/index.ts, packages/supi/test/install/misc.ts
=> fix: rename .pnp.js to .pnp.cjs

.changeset/nervous-fishes-repair.md, packages/pnpm/src/main.ts
=> fix: don't print warnings about unknown settings

.changeset/giant-tigers-smoke.md, packages/plugin-commands-listing/src/why.ts
=> feat(why): implement shorthands for "--dev" & "--prod" options

.changeset/long-dancers-allow.md, packages/default-reporter/test/index.ts, packages/plugin-commands-installation/src/install.ts, packages/plugin-commands-installation/test/add.ts, packages/plugin-commands-installation/test/peerDependencies.ts, packages/plugin-commands-installation/test/prune.ts, packages/plugin-commands-installation/test/update/interactive.ts, packages/plugin-commands-installation/test/utils.ts, packages/plugin-commands-listing/test/utils.ts, packages/plugin-commands-outdated/test/utils.ts, packages/plugin-commands-publishing/test/utils.ts, packages/plugin-commands-rebuild/test/utils.ts, packages/plugin-commands-script-runners/test/utils.ts, packages/pnpm/test/hooks.ts, packages/pnpm/test/install/hooks.ts, packages/pnpm/test/monorepo/index.ts, packages/pnpm/test/recursive/misc.ts, packages/pnpmfile/README.md, packages/pnpmfile/package.json, packages/pnpmfile/src/requireHooks.ts, packages/pnpmfile/src/requirePnpmfile.ts
=> feat: rename pnpmfile.js to .pnpmfile.cjs

.changeset/famous-tigers-rhyme.md, packages/lockfile-file/package.json, packages/lockfile-file/src/write.ts, packages/lockfile-file/test/__snapshots__/write.ts.snap, packages/lockfile-file/test/write.ts, packages/read-project-manifest/package.json, pnpm-lock.yaml
=> feat(lockfile): resolution should be the first key

.changeset/rich-worms-obey.md, package.json, packages/lockfile-file/package.json, packages/lockfile-file/src/write.ts, packages/lockfile-file/test/__snapshots__/write.ts.snap, packages/supi/test/install/misc.ts, packages/supi/test/install/multipleImporters.ts, packages/supi/test/lockfile.ts, pnpm-lock.yaml
=> feat: improved formatting of the pnpm-lock.yaml

.changeset/neat-cats-search.md, .changeset/selfish-spies-whisper.md, .changeset/small-flowers-trade.md, packages/config/package.json, packages/config/src/Config.ts, packages/config/src/findBestGlobalPrefix.ts, packages/config/src/index.ts, packages/config/test/findBestGlobalPrefix.test.ts, packages/config/test/index.ts, packages/global-bin-dir/package.json, packages/plugin-commands-installation/package.json, packages/plugin-commands-installation/src/link.ts, packages/plugin-commands-installation/test/add.ts, packages/plugin-commands-installation/test/link.ts, packages/plugin-commands-installation/test/peerDependencies.ts, packages/plugin-commands-installation/test/prune.ts, packages/plugin-commands-installation/test/update/interactive.ts, packages/plugin-commands-installation/test/utils.ts, packages/plugin-commands-installation/tsconfig.json, packages/plugin-commands-listing/test/utils.ts, packages/plugin-commands-outdated/test/utils.ts, packages/plugin-commands-publishing/test/utils.ts, packages/pnpm/test/install/global.ts, packages/pnpm/test/install/selfUpdate.ts, packages/pnpm/test/root.ts, pnpm-lock.yaml
=> fix: cli has no write access to the selected global dir

.changeset/three-balloons-build.md, packages/plugin-commands-audit/src/audit.ts, packages/plugin-commands-audit/test/index.ts
=> fix(audit): auditing only a given type of dependencies

packages/config/src/index.ts
A global directory candidate should not be skipped only because the target directory was not yet created.
=> fix: searching for suitable global directory

.changeset/wise-lemons-rule.md, packages/plugin-commands-store/src/storeStatus/index.ts, packages/plugin-commands-store/test/storeStatus.ts
=> fix: emfile error on `pnpm store status`

.changeset/gorgeous-colts-perform.md, .changeset/polite-fishes-kneel.md, packages/get-context/src/index.ts, packages/get-context/src/readLockfiles.ts, packages/lockfile-file/src/read.ts, packages/supi/src/install/index.ts, packages/supi/test/lockfile.ts
=> fix: ignore broken lockfiles, unless --frozen-lockfile is set

.changeset/large-poets-smell.md, .changeset/old-birds-rhyme.md, packages/cafs/src/checkFilesIntegrity.ts, packages/headless/src/index.ts, packages/package-requester/package.json, packages/package-requester/src/packageRequester.ts, packages/package-requester/test/index.ts, packages/package-requester/tsconfig.json, packages/package-store/test/index.ts, packages/resolve-dependencies/src/resolveDependencies.ts, packages/server/src/createServer.ts, packages/server/test/index.ts, packages/store-controller-types/src/index.ts, packages/supi/src/install/index.ts, packages/supi/test/brokenLockfileIntegrity.ts, pnpm-lock.yaml
=> fix: verify the name and version of the package in the store

.changeset/pretty-knives-kick.md, packages/package-store/package.json, packages/package-store/src/fs/importIndexedDir.ts, packages/package-store/test/importingPkgWithInvalidFiles.ts, packages/package-store/tsconfig.json, pnpm-lock.yaml
=> fix: linking packages with invalid file names

.changeset/many-oranges-rhyme.md, packages/link-bins/src/index.ts
=> fix(bin): don't add non-directory to NODE_PATH in command shim

.changeset/ten-lions-complain.md, packages/config/src/index.ts, packages/config/test/index.ts
=> fix: noproxy

.changeset/four-wombats-clap.md, .changeset/khaki-humans-jump.md, .changeset/kind-cats-love.md, .changeset/tricky-carrots-sip.md, packages/lifecycle/src/index.ts, packages/link-bins/test/.gitignore, packages/link-bins/test/fixtures/bin-dir/pkg/bin/subdir/index.js, packages/link-bins/test/fixtures/bin-dir/pkg/package.json, packages/link-bins/test/index.ts, packages/package-bins/jest.config.js, packages/package-bins/package.json, packages/package-bins/src/index.ts, packages/package-bins/test/fixtures/bin-dir/rootBin.js, packages/package-bins/test/fixtures/bin-dir/subdir/subBin.js, packages/package-bins/test/index.ts, packages/read-package-json/package.json, packages/read-package-json/src/index.ts, pnpm-lock.yaml
=> fix: installing packages that have bin dirs with subdirs

.changeset/stale-colts-speak.md, packages/plugin-commands-store/src/storeStatus/index.ts, packages/plugin-commands-store/test/storeStatus.ts
=> fix: use correct path fix for integrity.json with git dependency

.changeset/chilly-goats-smoke.md, packages/pnpm/package.json, packages/pnpm/test/cli.ts, pnpm-lock.yaml
close #3249
Related changes:
https://github.com/zkochan/npx/commit/028c4251c91f2b037dab3d59c3e2f068e22e08a6
https://github.com/zkochan/npx/commit/baea8626aaaab75ad915fa2583699da240f511b3
=> feat!: pnpx asks if a package should be installed

.changeset/large-pears-melt.md, packages/plugin-commands-script-runners/src/run.ts, packages/plugin-commands-script-runners/test/index.ts, packages/pnpm/test/run.ts
=> feat!: don't execute pre/post scripts automatically

.changeset/fair-carpets-mix.md, .github/workflows/ci.yml, packages/exportable-manifest/src/index.ts, packages/exportable-manifest/test/index.test.ts, packages/plugin-commands-publishing/src/publish.ts, packages/plugin-commands-publishing/test/recursivePublish.ts, packages/pnpm/test/cli.ts, packages/pnpm/test/install/misc.ts
=> fix: npm should not run lifecycle events on `pnpm publish`

.changeset/brave-nails-destroy.md, .changeset/violet-cups-swim.md, packages/list/src/index.ts, packages/list/src/renderTree.ts, packages/list/test/index.ts, packages/plugin-commands-listing/src/list.ts
=> fix(list): don't list unsaved dependencies

.changeset/brave-trees-hammer.md, packages/config/src/Config.ts, packages/config/src/index.ts, packages/plugin-commands-script-runners/src/run.ts, packages/plugin-commands-script-runners/test/index.ts
=> feat: enable-pre-post-scripts

.changeset/real-moose-brush.md, packages/cafs/package.json, packages/get-context/package.json, packages/git-fetcher/package.json, packages/headless/package.json, packages/lockfile-file/package.json, packages/modules-cleaner/package.json, packages/package-store/package.json, packages/plugin-commands-import/package.json, packages/plugin-commands-publishing/package.json, packages/plugin-commands-script-runners/package.json, packages/plugin-commands-store/package.json, packages/pnpm/package.json, packages/remove-bins/package.json, packages/server/package.json, packages/supi/package.json, pnpm-lock.yaml
=> fix: Node.js 16 warning

.changeset/friendly-pumas-prove.md, packages/read-project-manifest/package.json, packages/read-project-manifest/src/readFile.ts, pnpm-lock.yaml
=> fix(read-project-manifest): avoid EMFILE errors

.changeset/wild-tools-taste.md, packages/audit/src/lockfileToAuditTree.ts
=> fix(audit): public registry responds with 502 error

.changeset/loud-kangaroos-smell.md, .changeset/serious-crews-serve.md, packages/git-fetcher/src/index.ts, packages/package-store/src/storeController/index.ts, packages/package-store/src/storeController/prune.ts, packages/tarball-fetcher/package.json, packages/tarball-fetcher/src/createDownloader.ts, pnpm-lock.yaml
=> fix: installing Git-hosted packages

.changeset/six-crews-work.md, packages/cafs/package.json, packages/cafs/src/checkFilesIntegrity.ts, pnpm-lock.yaml
=> fix(cafs): use graceful-fs for reading files

.changeset/green-ties-invite.md, packages/supi/test/install/misc.ts, pnpm-lock.yaml
=> fix: installing two dependencies with same name

.changeset/tiny-foxes-roll.md, packages/hoist/src/index.ts
=> fix(hoist): don't print a warning on skipped optional deps

.changeset/eighty-spiders-grab.md, packages/pnpm/test/hooks.ts, packages/pnpmfile/package.json, packages/pnpmfile/src/requireHooks.ts, packages/supi/src/install/index.ts, pnpm-lock.yaml
=> fix: always pass the right args to readPackage hook

.changeset/hot-kangaroos-matter.md, packages/pnpm/src/checkForUpdates.ts, packages/pnpm/src/main.ts
=> fix: update notifier should fail early

.changeset/dirty-gifts-share.md, packages/plugin-commands-setup/README.md, packages/plugin-commands-setup/jest.config.js, packages/plugin-commands-setup/package.json, packages/plugin-commands-setup/src/index.ts, packages/plugin-commands-setup/src/setup.ts, packages/plugin-commands-setup/test/setup.test.ts, packages/plugin-commands-setup/tsconfig.json, packages/plugin-commands-setup/tsconfig.lint.json, packages/pnpm/package.json, packages/pnpm/src/cmd/index.ts, packages/pnpm/tsconfig.json, pnpm-lock.yaml
This command is needed to setup pnpm after standalone installation (related https://github.com/pnpm/pnpm/discussions/3434)
=> feat: a new command for setting up pnpm

.changeset/early-rockets-beg.md, .changeset/great-ants-punch.md, .changeset/stale-emus-chew.md, packages/plugin-commands-nvm/package.json, packages/plugin-commands-nvm/src/node.ts, packages/plugin-commands-nvm/test/node.test.ts, packages/plugin-commands-script-runners/package.json, packages/plugin-commands-script-runners/src/exec.ts, packages/plugin-commands-script-runners/test/exec.ts, packages/plugin-commands-script-runners/test/utils.ts, packages/pnpm/CHANGELOG.md, packages/pnpm/src/cmd/index.ts, pnpm-lock.yaml
ref https://github.com/pnpm/pnpm/discussions/3434
=> fix: `pnpm exec` should use the right Node.js version

.changeset/metal-forks-grow.md, .changeset/ninety-dolphins-begin.md, packages/parse-cli-args/src/index.ts, packages/parse-cli-args/test/index.ts, packages/plugin-commands-script-runners/src/run.ts, packages/pnpm/src/main.ts, packages/pnpm/test/cli.ts
=> feat: run arbitrary commands via pnpm CLI

.changeset/early-boxes-applaud.md, packages/fetch/src/fetchFromRegistry.ts, packages/npm-registry-agent/src/index.ts, packages/npm-registry-agent/test/index.ts, packages/store-connection-manager/src/createNewStoreController.ts
=> fix: rename strictSSL to strictSsl in all places

.changeset/tricky-yaks-fly.md, packages/plugin-commands-publishing/src/publish.ts, packages/plugin-commands-publishing/src/recursivePublish.ts, packages/plugin-commands-publishing/test/recursivePublish.ts
the implementation in #3490 had a mistake that the test didn't catch 😞, now I tested it locally and now it for sure works as expected
=> fix publishConfig.directory script

.changeset/neat-rabbits-serve.md, package.json, packages/lockfile-file/package.json, packages/lockfile-file/test/__snapshots__/write.test.ts.snap, packages/lockfile-file/test/write.test.ts, pnpm-lock.yaml
=> fix: broken lockfile when values in engines have new lines

packages/git-resolver/src/index.ts, packages/git-resolver/test/index.ts
=> feat(git-resolver): installing by partial commit

.changeset/rare-pianos-buy.md, packages/plugin-commands-publishing/src/publish.ts, packages/plugin-commands-publishing/test/recursivePublish.ts
=> fix(publish): copy .npmrc from the root of repository

.changeset/thirty-adults-invite.md, packages/plugin-commands-installation/src/installDeps.ts, packages/plugin-commands-installation/test/warnCyclicDependencies.ts
Improve the message that warns about cyclic dependencies
=> fix: use a more detailed cyclic depedencies warning (#3569)

.changeset/little-eagles-give.md, packages/plugin-commands-installation/src/link.ts, packages/plugin-commands-installation/test/link.ts
=> fix(link): throw an error if "pnpm link" has no options and params

.changeset/rich-books-relate.md, .changeset/sixty-yaks-buy.md, .changeset/ten-dogs-call.md, packages/plugin-commands-installation/src/link.ts, packages/supi/src/link/index.ts
=> fix(link): don't run install in the global pkg when linking global pkgs

.changeset/clever-seals-shake.md, packages/lifecycle/package.json, packages/lifecycle/src/runLifecycleHook.ts, pnpm-lock.yaml
=> fix: print a warning when a lifecycle script is skipped

.changeset/long-dryers-run.md, packages/plugin-commands-publishing/src/pack.ts, packages/plugin-commands-publishing/src/publish.ts, packages/plugin-commands-publishing/test/publish.ts
=> fix(publish): run scripts when publishConfig.directory is used

.changeset/tall-carpets-count.md, packages/read-modules-dir/package.json, packages/read-modules-dir/src/index.ts, pnpm-lock.yaml
=> fix: avoid too many open files error

.changeset/friendly-toes-relax.md, packages/resolve-dependencies/src/resolvePeers.ts, packages/supi/test/install/peerDependencies.ts
=> fix: improve error message on peer dependency issues

.changeset/forty-horses-push.md, packages/npm-resolver/src/index.ts, packages/npm-resolver/test/index.ts, packages/npm-resolver/test/meta/broken-integrity.json
=> fix(npm-resolver): ignore broken shasum in metadata

.changeset/gentle-pandas-live.md, .changeset/selfish-clocks-bow.md, .changeset/sweet-pianos-sniff.md, .meta-updater/src/index.ts, packages/package-requester/package.json, packages/package-requester/src/packageRequester.ts, packages/package-requester/test/index.ts, packages/package-requester/tsconfig.json, packages/package-store/src/storeController/index.ts, packages/plugin-commands-import/package.json, packages/plugin-commands-installation/package.json, packages/plugin-commands-listing/package.json, packages/plugin-commands-outdated/package.json, packages/plugin-commands-publishing/package.json, packages/plugin-commands-rebuild/package.json, packages/plugin-commands-script-runners/package.json, packages/plugin-commands-store/package.json, packages/pnpm/package.json, packages/resolve-dependencies/package.json, packages/resolve-dependencies/src/index.ts, packages/resolve-dependencies/src/resolveDependencies.ts, packages/resolve-dependencies/tsconfig.json, packages/store-connection-manager/src/createNewStoreController.ts, packages/store-controller-types/src/index.ts, packages/supi/test/install/installationChecks.ts, packages/supi/test/install/optionalDependencies.ts, pnpm-lock.yaml
=> fix: do not download optional dependencies that are not needed

.changeset/fifty-avocados-know.md, packages/plugin-commands-setup/package.json, packages/plugin-commands-setup/src/setup.ts, pnpm-lock.yaml
=> feat: pnpm setup should move the CLI to the pnpm home dir

.changeset/cyan-clouds-care.md, packages/config/src/dirs.ts, packages/config/test/dirs.test.ts
=> fix(config): default home directory on macOS

.changeset/tough-pillows-switch.md, package.json, packages/resolve-dependencies/src/resolveDependencies.ts, packages/resolve-dependencies/src/resolveDependencyTree.ts, packages/supi/test/install/optionalDependencies.ts, pnpm-lock.yaml
=> fix: unsupported platform error

.changeset/fluffy-olives-check.md, packages/local-resolver/src/index.ts, packages/local-resolver/test/index.ts, packages/supi/test/install/local.ts
=> feat: allow to link a directory with no manifest

.changeset/blue-cougars-visit.md, packages/plugin-commands-env/src/env.ts, packages/plugin-commands-env/src/node.ts, packages/plugin-commands-env/test/env.test.ts, packages/pnpm/src/main.ts
ref https://github.com/pnpm/pnpm/discussions/3434#discussioncomment-1197842
=> feat(env): link npm and npx as well, when installing Node.js

.changeset/yellow-mugs-peel.md, packages/pnpm/src/err.ts
=> fix: a broken package.json should not make the CLI silently exit

.changeset/serious-pets-brush.md, packages/global-bin-dir/src/index.ts, packages/global-bin-dir/test/index.ts
=> fix: always prefer the pnpm home directory when search for global bin dir

.changeset/spicy-tigers-smoke.md, packages/plugin-commands-env/src/env.ts
=> fix: the env command on Windows

.changeset/empty-queens-run.md, packages/supi/src/install/createVersionsOverrider.ts, packages/supi/test/install/createVersionOverrider.test.ts
=> fix: overrides that contain parent with range

.changeset/loud-peas-yawn.md, .changeset/strong-coats-occur.md, packages/fetch/src/fetchFromRegistry.ts, packages/fetching-types/src/index.ts, packages/npm-resolver/src/fetch.ts
=> perf: accept gzip, deflate encoding from the registry

package.json, packages/git-resolver/package.json, packages/git-resolver/test/index.ts, pnpm-lock.yaml
close #3643
Using a fork until https://github.com/npm/hosted-git-info/pull/109 gets merged
=> fix: use correct GitLab tarball archive URL

.changeset/mean-trainers-burn.md, packages/package-bins/src/index.ts, packages/package-bins/test/index.ts
=> fix: allow the $ sign to be a command name

.changeset/smooth-brooms-smash.md, packages/fetch/package.json, packages/fetch/src/fetch.ts, packages/fetch/test/fetchFromRegistry.test.ts, packages/fetching-types/package.json, packages/npm-resolver/test/index.ts, packages/plugin-commands-env/src/node.ts, packages/server/package.json, packages/server/src/connectStoreController.ts, packages/server/test/index.ts, packages/tarball-fetcher/src/createDownloader.ts, packages/tarball-fetcher/test/download.ts, pnpm-lock.yaml
=> fix: do not silently exit on bad HTTPS requests

packages/supi/src/install/index.ts
=> typo in comment: hear -> here

.changeset/gold-ties-hear.md, .changeset/serious-foxes-fold.md, .changeset/strange-camels-wave.md, packages/link-bins/package.json, packages/link-bins/src/index.ts, packages/link-bins/tsconfig.json, packages/manifest-utils/src/updateProjectManifestObject.ts, packages/plugin-commands-env/package.json, packages/plugin-commands-installation/src/installDeps.ts, packages/plugin-commands-installation/test/global.ts, packages/resolve-dependencies/src/index.ts, packages/resolve-dependencies/src/updateProjectManifest.ts, packages/supi/src/install/extendInstallOptions.ts, packages/supi/src/install/getWantedDependencies.ts, packages/supi/src/install/index.ts, packages/supi/src/uninstall/removeDeps.ts, packages/types/src/package.ts, pnpm-lock.yaml
References:
* https://github.com/pnpm/pnpm/discussions/3434
* https://github.com/pnpm/pnpm/issues/3595
* https://github.com/pnpm/cmd-shim/pull/38
=> feat: pin Node.js to global package

.changeset/honest-rats-try.md, packages/link-bins/package.json, packages/plugin-commands-env/package.json, packages/remove-bins/package.json, packages/remove-bins/src/removeBins.ts, pnpm-lock.yaml
=> fix: installed commands cannot be found on case sensitive Windows

.changeset/empty-pots-crash.md, packages/exe/scripts/build-artifacts.ts, packages/pnpm/package-linux-arm64.json, packages/pnpm/package-macos-arm64.json
=> fix: artifacts

.changeset/bright-kiwis-press.md, packages/plugin-commands-script-runners/src/runRecursive.ts, packages/plugin-commands-script-runners/test/runRecursive.ts, packages/pnpm/test/run.ts
=> fix(run): don't run pre/post script on recursive run

.changeset/spicy-ads-brush.md, packages/plugin-commands-env/src/env.ts, packages/plugin-commands-env/src/node.ts, packages/plugin-commands-env/src/resolveNodeVersion.ts, packages/plugin-commands-env/test/resolveNodeVersion.test.ts
=> fix(env): use network/proxy settings

.changeset/clean-dolphins-lay.md, packages/git-resolver/src/parsePref.ts, packages/git-resolver/test/index.ts, packages/git-resolver/test/parsePref.test.ts
fixes https://github.com/pnpm/pnpm/issues/3944
update regex
new unit tests are added to cover ssh port in git ssh protocol.
=> fix(git-resolver): supports ssh port

.changeset/sweet-geese-ring.md, packages/plugin-commands-script-runners/src/dlx.ts, packages/plugin-commands-script-runners/test/dlx.e2e.ts, packages/plugin-commands-script-runners/test/dlx.ts
=> fix(dlx): should work with scoped packages

.changeset/curly-boats-grin.md, .changeset/plenty-llamas-grin.md, packages/plugin-commands-publishing/src/publish.ts, packages/plugin-commands-script-runners/src/exec.ts, packages/pnpm/src/err.ts, packages/pnpm/src/main.ts
=> fix: aviod error log cut

.changeset/honest-cougars-marry.md, packages/lifecycle/src/runLifecycleHooksConcurrently.ts
=> fix: don't always index the project directory

.changeset/pink-chefs-attack.md, packages/core/src/install/index.ts, packages/core/test/install/lifecycleScripts.ts
=> feat: `pnpm:devPreinstall` script

.changeset/cuddly-coins-lick.md, .changeset/strong-clocks-knock.md, packages/directory-fetcher/src/index.ts, packages/directory-fetcher/test/index.ts, packages/local-resolver/src/parsePref.ts, packages/local-resolver/test/index.ts, packages/npm-resolver/src/index.ts, packages/npm-resolver/test/index.ts, packages/resolve-dependencies/src/updateLockfile.ts
=> fix: recursive install from subdir when injected deps are present

.github/workflows/ci.yml
Preserve ANSI codes in the source code. (https://github.com/PowerShell/PowerShell/releases/tag/v7.2.0-preview.9)
=> ci: set $PSStyle.OutputRendering in Windows

.changeset/early-toys-think.md, packages/store-connection-manager/src/index.ts
=> fix: use workspace for store use it is enabled

.changeset/empty-dancers-stare.md, package.json, packages/core/test/install/misc.ts, packages/link-bins/src/index.ts, pnpm-lock.yaml
=> fix: don't crash if a bin file cannot be created

.changeset/dirty-trains-perform.md, .changeset/tiny-rules-wait.md, packages/core/test/install/only.ts, packages/local-resolver/src/index.ts, packages/local-resolver/test/index.ts, packages/symlink-dependency/src/symlinkDirectRootDependency.ts
=> fix: don't fail if a linked directory is not found

.changeset/big-llamas-tie.md, packages/resolve-dependencies/src/resolvePeers.ts
=> fix: peer dependency ranges should be checked loosely

.changeset/fresh-moles-switch.md, packages/config/package.json, packages/parse-cli-args/package.json, packages/plugin-commands-script-runners/package.json, packages/plugin-commands-script-runners/src/exec.ts, packages/plugin-commands-script-runners/src/run.ts, packages/plugin-commands-script-runners/test/exec.ts, packages/pnpm/bin/pnpm.cjs
closes: https://github.com/pnpm/pnpm/issues/3972
=> fix: recursive cmd add reverse option

.changeset/gorgeous-suns-add.md, packages/plugin-commands-script-runners/src/exec.ts, packages/plugin-commands-script-runners/src/run.ts, packages/plugin-commands-script-runners/test/exec.ts
=> fix(exec): pnpm exec should return the correct exit code

.changeset/odd-garlics-laugh.md, packages/plugin-commands-env/src/node.ts, packages/plugin-commands-env/src/normalizeArch.ts, packages/plugin-commands-env/test/normalizeArch.test.ts
=> fix(env): installing Node.js on Raspberry Pi 4

.changeset/real-badgers-mate.md, package.json, packages/core/test/install/lifecycleScripts.ts, packages/headless/src/index.ts, pnpm-lock.yaml
=> fix(headless): postinstall script should run after root deps are linked

package.json
As the doc of https://nodejs.org/api/packages.html#packages_packagemanager
=> chore: add corepack fileds in package.json

.changeset/late-crews-speak.md, packages/plugin-commands-setup/src/setup.ts, packages/plugin-commands-setup/test/setup.test.ts
=> fix(setup): shell rc files should be created

.changeset/brown-spies-stare.md, .changeset/giant-toes-notice.md, .changeset/hungry-dragons-wait.md, packages/audit/src/index.ts, packages/fetch/src/fetchFromRegistry.ts, packages/fetch/src/index.ts, packages/plugin-commands-audit/src/audit.ts
=> fix(audit): audit should work with a proxy

.changeset/red-toys-obey.md, packages/config/package.json, packages/config/src/getScopeRegistries.ts, packages/config/src/index.ts, packages/config/test/index.ts, packages/config/test/scoped-registries.ini, packages/lockfile-utils/package.json, packages/normalize-registries/package.json, packages/resolve-dependencies/package.json, pnpm-lock.yaml
This reverts commit a7ff2d5ceb9be0f2430fa4cf1183ce22554055aa.
this reverts #4032 (maybe temporarily)
this is to fix #4052
=> revert: "fix: don't add trailing slash to registry URLs (#4032)"

.changeset/blue-crabs-sparkle.md, packages/git-fetcher/src/index.ts, packages/git-fetcher/test/index.ts, packages/tarball-fetcher/package.json, packages/tarball-fetcher/src/createDownloader.ts, packages/tarball-fetcher/test/download.ts, pnpm-lock.yaml
=> fix: installing big git-hosted packages

.changeset/kind-toys-relate.md, packages/plugin-commands-env/package.json, packages/plugin-commands-env/src/env.ts, packages/plugin-commands-env/src/getNodeMirror.ts, packages/plugin-commands-env/src/node.ts, packages/plugin-commands-env/src/resolveNodeVersion.ts, packages/plugin-commands-env/test/env.test.ts, packages/plugin-commands-env/test/getNodeMirror.test.ts, packages/plugin-commands-env/test/node.test.ts, packages/plugin-commands-env/test/resolveNodeVersion.test.ts, pnpm-lock.yaml
=> feat: add node-mirror:<releaseDir> options

.changeset/dirty-cups-live.md, .changeset/mean-lamps-march.md, packages/pkgs-graph/src/index.ts, packages/pkgs-graph/test/index.ts
=> fix: pkg deps don't ignore the workspace project without set version

.changeset/eight-ads-mate.md, packages/plugin-commands-installation/src/installDeps.ts, packages/plugin-commands-installation/src/recursive.ts, packages/plugin-commands-installation/test/update/recursive.ts, packages/plugin-commands-installation/test/update/update.ts, packages/pnpm/test/update.ts
=> fix(update): allow to update subdependencies

.changeset/cold-humans-end.md, .changeset/polite-readers-heal.md, .changeset/spotty-cows-destroy.md, packages/lockfile-file/src/read.ts, packages/lockfile-file/src/sortLockfileKeys.ts, packages/lockfile-file/test/fixtures/2/node_modules/.pnpm/lock.yaml, packages/lockfile-file/test/fixtures/2/pnpm-lock.yaml, packages/lockfile-file/test/read.test.ts
=> fix: lockfile up-to-date check when it has dependenciesMeta field

.changeset/fair-hotels-suffer.md, .changeset/many-colts-think.md, packages/core/src/install/index.ts, packages/headless/src/index.ts, packages/plugin-commands-installation/src/install.ts
=> feat: add more documentation about --no-frozen-lockfile

.changeset/fresh-balloons-brake.md, .changeset/lemon-clocks-brake.md, packages/config/src/Config.ts, packages/config/src/index.ts, packages/core/src/install/extendInstallOptions.ts, packages/core/src/install/index.ts, packages/headless/package.json, packages/headless/src/index.ts, packages/headless/src/lockfileToDepGraph.ts, packages/headless/src/lockfileToHoistedDepGraph.ts, packages/headless/test/fixtures/has-several-versions-of-same-pkg/package.json, packages/headless/test/fixtures/has-several-versions-of-same-pkg/pnpm-lock.yaml, packages/headless/test/fixtures/pnpm-workspace.yaml, packages/headless/test/fixtures/workspace2/bar/package.json, packages/headless/test/fixtures/workspace2/foo/package.json, packages/headless/test/fixtures/workspace2/pnpm-lock.yaml, packages/headless/test/index.ts, packages/headless/tsconfig.json, packages/real-hoist/README.md, packages/real-hoist/jest.config.js, packages/real-hoist/package.json, packages/real-hoist/src/index.ts, packages/real-hoist/test/index.ts, packages/real-hoist/tsconfig.json, packages/real-hoist/tsconfig.lint.json, pnpm-lock.yaml
=> feat: Create a node modules directory without using symlinks

packages/core/src/install/index.ts, packages/core/test/install/nodeLinkerNodeModules.ts, packages/headless/test/index.ts
It should be possible to create a symlinkless node_modules
in a project that don't yet have a lockfile
ref #4073
=> feat: symlinkless node_modules implementation part 2

.changeset/nice-flowers-kneel.md, packages/core/test/hoistedNodeLinker/install.ts, packages/real-hoist/src/index.ts
=> fix: hoisting aliased packages

.changeset/lucky-garlics-deliver.md, .changeset/thick-scissors-confess.md, packages/headless/src/lockfileToDepGraph.ts, packages/headless/src/lockfileToHoistedDepGraph.ts, packages/package-requester/src/packageRequester.ts, packages/resolve-dependencies/src/resolveDependencies.ts
=> fix: progress reporting with node-linker=hoisted

.changeset/fresh-countries-smell.md, packages/core/test/hoistedNodeLinker/install.ts, packages/headless/src/index.ts
=> fix: run the install scripts of deps in a workspace with no root project

packages/config/package.json, packages/core-loggers/package.json, packages/core/package.json, packages/default-reporter/package.json, packages/fetcher-base/package.json, packages/headless/package.json, packages/hoist/package.json, packages/modules-cleaner/package.json, packages/package-is-installable/package.json, packages/package-requester/package.json, packages/package-store/package.json, packages/parse-cli-args/package.json, packages/plugin-commands-installation/package.json, packages/plugin-commands-publishing/package.json, packages/plugin-commands-script-runners/package.json, packages/pnpm/package.json, packages/read-modules-dir/package.json, packages/read-projects-context/package.json, packages/real-hoist/package.json, packages/remove-bins/package.json, packages/resolve-dependencies/package.json, packages/resolve-workspace-range/package.json, packages/resolver-base/package.json, packages/symlink-dependency/package.json
`pnpm run tsc -- --watch` was wrong, everytimes i adjust a package will get error, so i replace all here...
=> chore: adjust start cmd

.changeset/light-schools-buy.md, .changeset/short-spoons-sit.md, packages/config/src/Config.ts, packages/core/src/install/index.ts, packages/plugin-commands-installation/src/install.ts, packages/plugin-commands-installation/src/installDeps.ts, packages/plugin-commands-installation/test/add.ts
=> feat: `pnpm add <pkg>` autoinstalls any missing peer dependencies

.changeset/eight-eagles-bathe.md, packages/directory-fetcher/package.json, packages/directory-fetcher/src/index.ts, packages/directory-fetcher/test/fixtures/simple-pkg/package.json, packages/directory-fetcher/test/index.ts, packages/directory-fetcher/tsconfig.json, pnpm-lock.yaml
This change was need to support injection in Bit workspace:
https://github.com/teambit/bit/pull/5251
=> fix(directory-fetcher): don't fail if the linked package has no `package.json`

.changeset/young-walls-care.md, packages/plugin-commands-publishing/src/pack.ts
ref https://github.com/pnpm/pnpm/discussions/3536
=> feat(pack)!: limit what files are packed as executables

.changeset/thick-buses-sparkle.md, packages/pnpm/src/shorthands.ts
=> feat: -F is a short alias of --filter

.changeset/dry-flowers-grab.md, .changeset/large-games-hug.md, .changeset/serious-frogs-yell.md, packages/core/src/install/extendInstallOptions.ts, packages/core/src/install/index.ts, packages/core/test/install/lifecycleScripts.ts, packages/lockfile-file/src/sortLockfileKeys.ts, packages/lockfile-file/src/write.ts, packages/lockfile-file/test/normalizeLockfile.test.ts, packages/lockfile-types/src/index.ts, packages/plugin-commands-installation/src/getOptionsFromRootManifest.ts, packages/resolve-dependencies/src/index.ts, packages/resolve-dependencies/src/resolveDependencies.ts, packages/resolve-dependencies/src/resolveDependencyTree.ts, packages/types/src/package.ts
=> feat: onlyBuiltDependencies

.changeset/spicy-eggs-play.md, packages/default-reporter/src/index.ts, packages/default-reporter/src/reporterForClient/index.ts, packages/default-reporter/src/reporterForClient/reportSummary.ts, packages/default-reporter/test/index.ts, packages/plugin-commands-installation/src/installDeps.ts
=> fix: print an info message when NODE_ENV is set to production

.github/config.yml
bot app: https://github.com/apps/welcome
=> chore(github): add welcome bot app

packages/plugin-commands-init/fixtures/init-module/.pnpm-init.js, packages/plugin-commands-init/package.json, packages/plugin-commands-init/src/init.ts, packages/plugin-commands-init/src/utils.ts, packages/plugin-commands-init/test/init.test.ts, packages/plugin-commands-init/test/utils.test.ts, packages/plugin-commands-init/tsconfig.json, pnpm-lock.yaml
Related to https://github.com/pnpm/pnpm/pull/4422
=> feat: respect the npmrc

.changeset/large-dragons-guess.md, packages/plugin-commands-installation/src/fetch.ts
=> fix: fetch should allow the same options as install

.changeset/wet-rabbits-talk.md, packages/manifest-utils/src/getPref.ts, packages/manifest-utils/test/getPref.test.ts
=> fix: handle undefined version spec

.changeset/small-snakes-think.md, packages/core/test/install/injectLocalPackages.ts, packages/resolve-dependencies/src/resolvePeers.ts
=> fix: peer dependency has workspace protocol

.changeset/slow-laws-cheat.md, packages/core/src/install/index.ts, packages/core/test/install/peerDependencies.ts
=> fix: only `pnpm install` should fail on peer dep issues

.changeset/tiny-nails-allow.md, packages/config/src/Config.ts, packages/config/src/index.ts, packages/pnpm/CHANGELOG.md, packages/pnpm/src/main.ts, packages/pnpm/test/monorepo/index.ts
=> feat: add legacy-dir-filtering

.changeset/short-coats-accept.md, packages/plugin-commands-init/src/init.ts, packages/plugin-commands-init/test/init.test.ts
=> fix(init): don't fail if a parent dir has a package.json

.changeset/many-fireants-design.md, .changeset/red-deers-deny.md, packages/plugin-commands-installation/src/add.ts, packages/plugin-commands-script-runners/src/dlx.ts
=> fix: dlx should work without a configured global directory

.changeset/hungry-toes-cheat.md, packages/plugin-commands-installation/src/installDeps.ts, packages/plugin-commands-installation/test/install.ts
=> fix(install): exit with an error when no package.json is found

.changeset/chatty-rivers-roll.md, .changeset/nasty-baboons-return.md, packages/plugin-commands-publishing/package.json, packages/plugin-commands-publishing/src/pack.ts, packages/plugin-commands-publishing/src/publish.ts, packages/run-npm/src/index.ts, pnpm-lock.yaml
=> fix: publish in workspace

.changeset/sour-balloons-rhyme.md, packages/plugin-commands-publishing/src/pack.ts, packages/plugin-commands-publishing/test/pack.ts
display more informative error for packing when package name or version is missing
=> refactor: display more informative error for packing (close #4653)

.changeset/six-llamas-design.md, packages/pnpm/src/main.ts, packages/pnpm/test/cli.ts
=> fix(dlx): print install output to stderr

.changeset/calm-ravens-rest.md, packages/plugin-commands-setup/src/setup.ts
=> fix(setup): update the current shell, not the preferred one

.changeset/fifty-taxis-exist.md, packages/plugin-commands-script-runners/src/dlx.ts, packages/plugin-commands-script-runners/test/dlx.e2e.ts, packages/plugin-commands-script-runners/test/dlx.ts
=> fix(dlx): pnpm dlx should work with git-hosted pkgs

.changeset/hot-hairs-thank.md, packages/dependency-path/src/index.ts, packages/dependency-path/test/index.ts
=> fix: sanitize dir names in the store

.changeset/dull-spies-eat.md, packages/plugin-commands-setup/src/setupOnWindows.ts, packages/plugin-commands-setup/test/setupOnWindows.test.ts
=> fix(setup): don't fail if PNPM_HOME is not yet in the system registry

.changeset/green-geckos-scream.md, packages/config/src/index.ts, packages/pnpm/test/install/only.ts
=> fix: only devDependencies are installed regardless of the node env

.changeset/seven-roses-cover.md, packages/core/test/install/autoInstallPeers.ts, packages/resolve-dependencies/src/resolveDependencies.ts
=> fix(auto-install-peers): don't fail on projects with linked deps

.changeset/few-horses-happen.md, packages/default-reporter/src/reporterForClient/index.ts, packages/default-reporter/src/reporterForClient/reportUpdateCheck.ts, packages/default-reporter/test/__snapshots__/reportingUpdateCheck.ts.snap, packages/default-reporter/test/reportingUpdateCheck.ts
When pnpm was installed with Corepack, suggest to update it with Corepack as well
=> fix(cli): suggest to update with Corepack

.changeset/young-cougars-obey.md, packages/default-reporter/src/reportError.ts
ref https://stackoverflow.com/q/72468635/537682
=> fix: add better peer dep error hints

.changeset/nasty-shoes-attack.md, packages/build-modules/src/buildSequence.ts, packages/build-modules/src/index.ts, packages/calc-dep-state/src/index.ts, packages/calc-dep-state/test/index.ts, packages/core/src/install/link.ts, packages/core/test/install/patch.ts, packages/headless/src/index.ts, packages/headless/src/linkHoistedModules.ts, packages/lockfile-types/src/index.ts, packages/resolve-dependencies/src/index.ts, packages/resolve-dependencies/src/updateLockfile.ts
=> fix: patch package even if it is not in the onlyBuiltDependencies list

.changeset/cyan-eels-own.md, packages/config/src/Config.ts, packages/config/src/index.ts, packages/pnpm/src/cmd/index.ts, packages/pnpm/src/main.ts, packages/pnpm/test/monorepo/index.ts
=> fix: respect include-workspace-root npmrc option

.changeset/metal-wasps-impress.md, packages/core/src/install/index.ts
=> fix: install --lockfile-only should exit early

.changeset/cold-toes-push.md, packages/resolve-dependencies/src/index.ts
=> fix: partial install in workspace with patches should not fail

.changeset/soft-seals-shop.md, packages/crypto.base32-hash/package.json, packages/crypto.base32-hash/src/index.ts, packages/crypto.base32-hash/test/index.ts, packages/crypto.base32-hash/tsconfig.json, pnpm-lock.yaml
=> fix(patch): the hash of the patch file should be the same on both Windows and POSIX

.changeset/perfect-peaches-explain.md, packages/plugin-commands-publishing/package.json, packages/plugin-commands-publishing/src/publish.ts, packages/plugin-commands-publishing/tsconfig.json, packages/pnpm/src/cmd/help.ts, pnpm-lock.yaml
=> fix: document the -r option

.changeset/green-drinks-teach.md, .changeset/neat-apes-lay.md, .changeset/thin-trees-mate.md, packages/core/src/install/allProjectsAreUpToDate.ts, packages/core/src/install/index.ts, packages/core/test/allProjectsAreUpToDate.test.ts, packages/core/test/install/autoInstallPeers.ts, packages/headless/src/index.ts, packages/lockfile-utils/src/satisfiesPackageManifest.ts, packages/lockfile-utils/test/satisfiesPackageManifest.ts, packages/manifest-utils/src/getSpecFromPackageManifest.ts, packages/resolve-dependencies/src/getWantedDependencies.ts, packages/resolve-dependencies/src/index.ts
=> fix: auto install root peer deps when auto-install-peers=true

.changeset/breezy-geese-end.md, packages/lockfile-utils/src/satisfiesPackageManifest.ts, packages/lockfile-utils/test/satisfiesPackageManifest.ts
=> fix: frozen install in a project with peer deps and `auto-install-peers=true`

.changeset/weak-sheep-carry.md, packages/render-peer-issues/src/index.ts, packages/render-peer-issues/test/__snapshots__/index.ts.snap
=> feat: print package versions in peer dependency issues

.changeset/nervous-poets-hunt.md, .changeset/red-readers-knock.md, packages/core/src/index.ts, packages/core/src/install/extendInstallOptions.ts, packages/core/src/install/hooks.ts, packages/core/src/install/index.ts, packages/lockfile-to-pnp/package.json, packages/lockfile-to-pnp/src/index.ts, packages/lockfile-to-pnp/tsconfig.json, packages/pnpm/test/hooks.ts, packages/pnpm/test/install/hooks.ts, packages/pnpmfile/package.json, packages/pnpmfile/src/requireHooks.ts, packages/pnpmfile/tsconfig.json, pnpm-lock.yaml
This PR adds a new `preResolve` hook that can be used to run some code before resolution kicks in.
=> feat: add new hook that runs pre resolution

.changeset/tidy-rivers-marry.md, packages/core/src/install/index.ts, packages/core/test/install/gitBranchLockfile.test.ts
Fixes https://github.com/pnpm/pnpm/issues/5212
=> fix: mergeGitBranchLockfiles when merged lockfile is up-to-date

.changeset/thirty-squids-study.md, packages/core/test/install/autoInstallPeers.ts, packages/resolve-dependencies/package.json, packages/resolve-dependencies/src/nodeIdUtils.ts, packages/resolve-dependencies/src/resolveDependencies.ts, packages/resolve-dependencies/src/resolveDependencyTree.ts, pnpm-lock.yaml
=> fix: auto-install-peers in a workspace

.changeset/famous-rocks-yawn.md, packages/plugin-commands-installation/src/link.ts
Close https://github.com/pnpm/pnpm/issues/5445
=> fix: add global option in pnpm link --help

.changeset/great-dolls-collect.md, .changeset/kind-bottles-knock.md, packages/hooks.read-package-hook/src/createReadPackageHook.ts, packages/hooks.read-package-hook/test/createReadPackageHook.ts
=> fix: path the project directory to the readPackage hook

packages/config/test/index.ts
Fix test cases error in @pnpm/config
=> test: update tests in @pnpm/config

.changeset/quick-mayflies-rush.md, .changeset/shiny-icons-hunt.md, packages/outdated/package.json, packages/outdated/src/outdated.ts, packages/outdated/src/outdatedDepsOfProjects.ts, packages/outdated/test/outdated.spec.ts, packages/outdated/tsconfig.json, pnpm-lock.yaml
=> fix(outdated): should work when the tarballs are hosted on a different domain

.changeset/twelve-bikes-serve.md, packages/config/package.json, packages/config/src/index.ts, packages/config/test/fixtures/pkg-using-workspaces/package.json, packages/config/test/index.ts, packages/config/tsconfig.json, pnpm-lock.yaml
=> fix: print a warning if a package.json uses workspaces field

.changeset/dirty-donuts-talk.md, packages/plugin-commands-publishing/src/publish.ts, packages/plugin-commands-publishing/test/gitChecks.ts
Close https://github.com/pnpm/pnpm/issues/5563
=> fix: remove double negative error code name in ERR_PNPM_GIT_NOT_UNCLEAN

.changeset/fluffy-insects-jump.md, releasing/plugin-commands-publishing/src/publish.ts, releasing/plugin-commands-publishing/test/publish.ts
=> fix(publish): exit with non-zero code when publish tgz failed

.changeset/breezy-tables-mate.md, pnpm/src/pnpm.ts
Related discussion: https://github.com/pnpm/pnpm/discussions/5683
=> fix: add pnpm set-script and pkg passed through to npm

.changeset/pink-socks-learn.md, lockfile/plugin-commands-audit/src/audit.ts, lockfile/plugin-commands-audit/test/__snapshots__/index.ts.snap, lockfile/plugin-commands-audit/test/index.ts
=> fix(audit): ignore vulnerabilities listed in ignoreCves

.changeset/rotten-mayflies-enjoy.md, reviewing/plugin-commands-licenses/src/licenses.ts
=> fix(licenses): print help when no subcommand is specified

.changeset/olive-readers-drop.md, exec/plugin-commands-script-runners/src/dlx.ts, exec/plugin-commands-script-runners/test/dlx.e2e.ts
=> feat(plugin-commands-script-runners): add --shell-mode option for pnpm dlx

.changeset/odd-ligers-fold.md, .changeset/seven-seahorses-hug.md, .changeset/stupid-lizards-stare.md, exec/plugin-commands-rebuild/test/index.ts, exec/prepare-package/src/index.ts, fetching/git-fetcher/package.json, fetching/git-fetcher/src/index.ts, fetching/git-fetcher/test/index.ts, fetching/tarball-fetcher/src/gitHostedTarballFetcher.ts, fetching/tarball-fetcher/src/index.ts, fetching/tarball-fetcher/test/fetch.ts, pkg-manager/client/src/index.ts, pkg-manager/core/src/install/index.ts, pkg-manager/core/test/install/fromRepo.ts, pkg-manager/headless/src/lockfileToDepGraph.ts, pkg-manager/headless/src/lockfileToHoistedDepGraph.ts, pkg-manager/package-requester/src/packageRequester.ts, pkg-manager/resolve-dependencies/src/resolveDependencies.ts, pkg-manager/resolve-dependencies/src/resolveDependencyTree.ts, pnpm-lock.yaml, store/store-connection-manager/src/createNewStoreController.ts, store/store-controller-types/src/index.ts
=> fix: don't build git-hosted dependencies when scripts are ignored

.changeset/fast-chefs-sip.md, config/plugin-commands-config/src/config.ts, config/plugin-commands-config/test/configSet.test.ts
=> fix(config): config set key=value should work

.changeset/light-dots-buy.md, pkg-manager/link-bins/src/index.ts, pkg-manager/link-bins/test/fixtures/simple-fixture/node_modules/simple/index.js, pkg-manager/link-bins/test/index.ts
- fixed https://github.com/pnpm/pnpm/issues/5822 
- fixed https://github.com/pnpm/pnpm/issues/5890
=> fix(link-bins): ensure permission of bin file when symlinked

.changeset/clean-swans-listen.md, .changeset/eleven-fireants-warn.md, .changeset/flat-eagles-tease.md, .changeset/fuzzy-birds-joke.md, exec/build-modules/package.json, exec/build-modules/src/index.ts, exec/build-modules/tsconfig.json, packages/parse-wanted-dependency/src/index.ts, packages/plugin-commands-patching/package.json, packages/plugin-commands-patching/src/patch.ts, packages/plugin-commands-patching/src/patchCommit.ts, packages/plugin-commands-patching/src/writePackage.ts, packages/plugin-commands-patching/test/patch.test.ts, packages/plugin-commands-patching/tsconfig.json, patching/apply-patch/README.md, patching/apply-patch/package.json, patching/apply-patch/src/index.ts, patching/apply-patch/tsconfig.json, patching/apply-patch/tsconfig.lint.json, pnpm-lock.yaml, pnpm-workspace.yaml
fix #5632 
* reuse existed patch file by default.
* add `--ignore-patches` option to ignore current patch files
=> feat(plugin-commands-patching): apply existed patch file when re-patch

.changeset/sour-lizards-kiss.md, pkg-manager/core/test/install/fixLockfile.ts, pkg-manager/get-context/package.json, pkg-manager/resolve-dependencies/src/resolveDependencies.ts
=> fix: install --fix-lockfile error when package has no dependencies(#5878)

.changeset/chatty-pens-end.md, .changeset/fluffy-pianos-complain.md, pkg-manager/core/test/install/sideEffects.ts, pkg-manager/package-requester/src/packageRequester.ts, store/cafs/src/checkFilesIntegrity.ts, store/cafs/src/checkPkgFilesIntegrity.ts, store/cafs/src/index.ts, store/cafs/src/readManifestFromStore.ts, store/cafs/test/index.ts
=> fix: corrupted side effects cache should be ignored

.changeset/thin-keys-march.md, releasing/plugin-commands-publishing/src/pack.ts, releasing/plugin-commands-publishing/src/publish.ts, releasing/plugin-commands-publishing/test/publish.ts
=> fix: don't run prepublishOnly and prepublish on pack

.changeset/neat-suns-smoke.md, pkg-manager/resolve-dependencies/src/resolveDependencies.ts, pkg-manager/resolve-dependencies/src/resolveDependencyTree.ts
=> fix: lockfile v6 on projects with patched deps

.changeset/cuddly-hounds-unite.md, pkg-manager/headless/src/linkHoistedModules.ts
=> fix: out of memory exception with node-linker=hoisted

.changeset/selfish-bears-matter.md, .changeset/wicked-owls-brush.md, fs/hard-link-dir/README.md, fs/hard-link-dir/package.json, fs/hard-link-dir/src/index.ts, fs/indexed-pkg-importer/package.json, fs/indexed-pkg-importer/src/importIndexedDir.ts, fs/indexed-pkg-importer/test/createImportPackage.test.ts, pnpm-lock.yaml
=> fix: cross-device link not permitted when node-linker=hoisted

.github/workflows/release.yml
Resolves https://github.com/pnpm/pnpm/pull/5989#issuecomment-1407656193.
=> ci: add release environment to publish job

config/plugin-commands-config/package.json, env/plugin-commands-env/package.json, exec/plugin-commands-rebuild/package.json, exec/plugin-commands-script-runners/package.json, lockfile/plugin-commands-audit/package.json, packages/plugin-commands-doctor/package.json, packages/plugin-commands-init/package.json, packages/plugin-commands-setup/package.json, patching/plugin-commands-patching/package.json, pkg-manager/plugin-commands-installation/package.json, pnpm-lock.yaml, pnpm/package.json, releasing/plugin-commands-deploy/package.json, releasing/plugin-commands-publishing/package.json, reviewing/plugin-commands-licenses/package.json, reviewing/plugin-commands-listing/package.json, reviewing/plugin-commands-outdated/package.json, store/plugin-commands-server/package.json, store/plugin-commands-store/package.json
=>  fix: help string for filter options 

.changeset/strong-poets-juggle.md, packages/dependency-path/src/index.ts, packages/dependency-path/test/index.ts
=> fix: issues with storybook and the new lockfile format

.changeset/pretty-adults-breathe.md, __utils__/assert-project/package.json, __utils__/assert-store/package.json, config/config/src/Config.ts, config/config/src/index.ts, exec/plugin-commands-rebuild/package.json, exec/plugin-commands-script-runners/package.json, package.json, patching/plugin-commands-patching/package.json, pkg-manager/core/package.json, pkg-manager/core/src/install/extendInstallOptions.ts, pkg-manager/core/test/install/resolutionMode.ts, pkg-manager/core/test/lockfile.ts, pkg-manager/headless/package.json, pkg-manager/package-requester/package.json, pkg-manager/plugin-commands-installation/package.json, pkg-manager/resolve-dependencies/src/resolveDependencies.ts, pkg-manager/resolve-dependencies/src/resolveDependencyTree.ts, pnpm-lock.yaml, pnpm/package.json, pnpm/test/monorepo/index.ts, releasing/plugin-commands-deploy/package.json, releasing/plugin-commands-publishing/package.json, reviewing/plugin-commands-licenses/package.json, reviewing/plugin-commands-listing/package.json, reviewing/plugin-commands-outdated/package.json, store/plugin-commands-store/package.json
This is going to be the default resolution mode in v8.
=> feat: lowest-direct resolution mode

.changeset/tidy-peas-grin.md, lockfile/plugin-commands-audit/src/audit.ts
=> fix(plugin-commands-audit): fix AUDIT_TABLE_OPTIONS not to overwrite TABLE_OPTIONS

.changeset/nasty-gorillas-punch.md, hooks/read-package-hook/src/createPackageExtender.ts, hooks/read-package-hook/test/createPackageExtender.test.ts
fixed https://github.com/pnpm/pnpm/issues/6010
=> fix: use Map to prevent odd manifest name

.changeset/strong-papayas-learn.md, config/config/src/index.ts, pkg-manager/core/src/install/extendInstallOptions.ts, pkg-manager/plugin-commands-installation/src/update/index.ts, pkg-manager/plugin-commands-installation/test/update/interactive.ts
=> feat!: resolution-mode is lowest-direct by default

.github/workflows/update-latest.yml
This should fix the CI errors now.
=> ci: bump Winget Releaser version to v2

.changeset/weak-books-fail.md, network/fetch/package.json, pnpm-lock.yaml
=> fix: https proxy servers configuration

exec/plugin-commands-rebuild/src/implementation/index.ts
https://github.com/pnpm/pnpm/issues/6092
=> fix: don't throw MISSING_HOISTED_LOCATIONS error for skipped packages

.changeset/gold-chicken-sit.md, cli/cli-utils/src/recursiveSummary.ts, exec/plugin-commands-rebuild/src/recursive.ts, exec/plugin-commands-script-runners/package.json, exec/plugin-commands-script-runners/src/exec.ts, exec/plugin-commands-script-runners/src/run.ts, exec/plugin-commands-script-runners/src/runRecursive.ts, exec/plugin-commands-script-runners/test/exec.e2e.ts, exec/plugin-commands-script-runners/test/runRecursive.ts, pkg-manager/plugin-commands-installation/src/recursive.ts, pnpm-lock.yaml
=> feat: add --report-summary option for pnpm exec and pnpm run

.changeset/little-donuts-suffer.md, reviewing/list/src/getPkgInfo.ts, reviewing/list/src/renderJson.ts, reviewing/list/src/renderTree.ts, reviewing/list/test/index.ts
=> feat: show path info for pnpm why --json or --long 

.changeset/serious-rice-boil.md, config/plugin-commands-config/src/ConfigCommandOptions.ts, config/plugin-commands-config/src/config.ts, config/plugin-commands-config/test/configDelete.test.ts, config/plugin-commands-config/test/configGet.test.ts, config/plugin-commands-config/test/configList.test.ts, config/plugin-commands-config/test/configSet.test.ts
=> fix: config set should write to the global config file

.changeset/shy-drinks-beam.md, env/plugin-commands-env/src/env.ts, env/plugin-commands-env/test/env.test.ts
=> fix(env): fail with a meaningful error when no pnpm home dir is found

.changeset/seven-crews-roll.md, pkg-manager/plugin-commands-installation/src/installDeps.ts, pkg-manager/plugin-commands-installation/src/recursive.ts, pnpm/test/monorepo/dedupePeers.test.ts
=> fix: dedupe-peer-dependents on a subset of projects

pkg-manager/plugin-commands-installation/package.json, pkg-manager/plugin-commands-installation/src/installDeps.ts, pkg-manager/plugin-commands-installation/tsconfig.json, pnpm-lock.yaml
=> fix: dedupe-peer-dependents when running a command inside a workspace project

.changeset/nervous-dots-sleep.md, config/plugin-commands-config/package.json, config/plugin-commands-config/src/ConfigCommandOptions.ts, config/plugin-commands-config/src/configSet.ts, config/plugin-commands-config/test/managingAuthSettings.test.ts, config/plugin-commands-config/tsconfig.json, pnpm-lock.yaml
=> fix: settings related to authorization should be set by npm CLI

.changeset/gentle-lies-type.md, .changeset/young-insects-smoke.md, fs/graceful-fs/src/index.ts, fs/indexed-pkg-importer/package.json, fs/indexed-pkg-importer/src/index.ts, fs/indexed-pkg-importer/test/createImportPackage.test.ts, fs/indexed-pkg-importer/tsconfig.json, pnpm-lock.yaml
=> fix: retry copying from store on EBUSY error

env/plugin-commands-env/src/env.ts, env/plugin-commands-env/test/env.test.ts
Correct a spelling mistake on the standalone word
=> fix: typo standalone

.changeset/quick-worms-rush.md, releasing/plugin-commands-publishing/src/publish.ts, releasing/plugin-commands-publishing/src/recursivePublish.ts, releasing/plugin-commands-publishing/test/recursivePublish.ts
=> fix:  when publish some package throws an error, exit code should be non-zero

.changeset/lucky-chairs-begin.md, pkg-manager/core/test/install/dedupeInWorkspace.ts, resolving/npm-resolver/src/pickPackageFromMeta.ts
=> fix: direct deduplication with resolution-mode=lowest-direct

.changeset/real-eels-approve.md, pkg-manager/resolve-dependencies/src/index.ts, pkg-manager/resolve-dependencies/src/resolvePeers.ts, pnpm/test/monorepo/peerDependencies.ts
=> fix: peer dependency is not unlinked when adding a new dependency

.changeset/slow-meals-worry.md, pkg-manager/resolve-dependencies/src/index.ts
=> fix: peer dependency is not unlinked

.changeset/new-kids-push.md, pnpm/bin/pnpm.cjs
=> fix: lowest supported node.js version in the error message

.changeset/tough-ears-remain.md, exec/lifecycle/package.json, pnpm-lock.yaml
=> fix(deps): update `@yarnpkg/shell`

.changeset/angry-frogs-deny.md, .github/workflows/ci.yml, env/node.fetcher/package.json, env/plugin-commands-env/package.json, network/fetch/package.json, network/fetching-types/package.json, pnpm-lock.yaml, store/server/package.json
=> ci: run tests on Node.js 20

.changeset/smart-waves-lie.md, pkg-manager/core/test/install/excludeLinksFromLockfile.ts, pkg-manager/resolve-dependencies/src/index.ts
ref https://github.com/teambit/bit/pull/7176
=> fix: don't include external links in lockfile, when they resolve peers

.changeset/heavy-dolls-itch.md, .changeset/neat-zoos-glow.md, pkg-manager/core/src/install/extendInstallOptions.ts, pkg-manager/core/test/breakingChanges.ts, pkg-manager/core/test/install/only.ts, pkg-manager/core/test/lockfile.ts, pkg-manager/get-context/src/index.ts, pkg-manager/plugin-commands-installation/src/install.ts, releasing/plugin-commands-deploy/src/deploy.ts
=> fix(deploy): always purge modules directory

.changeset/sour-zebras-confess.md, pkg-manager/plugin-commands-installation/src/update/index.ts, reviewing/outdated/src/outdated.ts, reviewing/outdated/src/outdatedDepsOfProjects.ts, reviewing/outdated/test/outdated.spec.ts, reviewing/plugin-commands-outdated/src/outdated.ts, reviewing/plugin-commands-outdated/src/recursive.ts
=> fix: should respect ignore patterns in updateConfig.ignoreDependencies

.changeset/dirty-spoons-report.md, pkg-manager/core/test/install/multipleImporters.ts, resolving/npm-resolver/src/index.ts, resolving/npm-resolver/test/index.ts
=> fix: error message when package is not found in workspace

pnpm/dev/pd.js
=> fix: rename find-workspace-packages in pd

resolving/npm-resolver/src/pickPackageFromMeta.ts
=> fix: parameter typo

.changeset/silent-onions-design.md, pkg-manager/plugin-commands-installation/src/installDeps.ts, pkg-manager/plugin-commands-installation/src/update/index.ts, pnpm/test/install/global.ts
=> fix: pnpm update --global --latest

.changeset/nasty-seals-attack.md, config/config/package.json, pnpm-lock.yaml
=> fix: don't crash when APPDATA is undefined on Windows

.changeset/rich-knives-swim.md, __typings__/local.d.ts, patching/apply-patch/__fixtures__/invalid.patch, patching/apply-patch/jest.config.js, patching/apply-patch/package.json, patching/apply-patch/src/index.ts, patching/apply-patch/test/applyPatchToDir.ts, patching/apply-patch/tsconfig.json, pnpm-lock.yaml
close #6683
ref #5268
ref #5278
=> fix: throw a meaningful error message when applying patch fails

.changeset/quiet-oranges-end.md, network/auth-header/src/index.ts, network/auth-header/test/getAuthHeaderByURI.ts
=> fix: searching for auth token for URL with port

.changeset/chilled-dancers-thank.md, pkg-manager/core/test/install/peerDependencies.ts, pkg-manager/resolve-dependencies/src/resolvePeers.ts
=> fix: resolving peer deps when there are aliased deps

.changeset/lemon-maps-clap.md, exec/plugin-commands-script-runners/src/run.ts, pnpm/test/run.ts
=> fix(run): output of scripts running concurrently in one project

.changeset/swift-onions-count.md, pnpm/src/main.ts, pnpm/test/run.ts
=> fix: --parallel should not fail on single project

.changeset/three-seas-lick.md, pkg-manager/core/src/install/allProjectsAreUpToDate.ts, pkg-manager/core/test/allProjectsAreUpToDate.test.ts
fix https://github.com/pnpm/pnpm/issues/6592
=> fix: treat the linked dependency which version type is tag as update-to-date

pnpm/src/main.ts
=> refactor: reduce repeated error message

.changeset/angry-goats-divide.md, packages/types/src/package.ts, releasing/plugin-commands-publishing/src/recursivePublish.ts
fixes https://github.com/pnpm/pnpm/issues/6775
=> feat: publishConfig.registry

.changeset/tough-houses-admire.md, fs/indexed-pkg-importer/package.json, fs/indexed-pkg-importer/src/importIndexedDir.ts, fs/indexed-pkg-importer/test/createImportPackage.test.ts, pkg-manager/package-requester/package.json, pkg-manager/package-requester/src/packageRequester.ts, pnpm-lock.yaml, resolving/npm-resolver/package.json, resolving/npm-resolver/src/pickPackage.ts, store/cafs/package.json, store/cafs/src/index.ts, store/create-cafs-store/package.json, store/store-path/package.json
Related changes: https://github.com/zkochan/packages/commit/f730084cd3d487cbcbe29dd1a05c41b8bc435356
This is one of the improvements suggested by @dmichon-msft in [this comment](https://github.com/orgs/pnpm/discussions/6376#discussioncomment-6420573)
=> perf: don't random ID to temp file names

.changeset/tame-crabs-clean.md, store/cafs/src/index.ts, store/create-cafs-store/src/index.ts, store/package-store/src/index.ts, store/package-store/src/storeController/index.ts, store/store-connection-manager/src/createNewStoreController.ts
=> fix(cafs): create the locker once per process

.changeset/quiet-brooms-serve.md, pkg-manager/core/package.json, pkg-manager/core/src/install/index.test.ts, pkg-manager/core/src/install/index.ts, pkg-manager/core/test/install/packageExtensions.ts, pnpm-lock.yaml
fixes https://github.com/pnpm/pnpm/issues/6824
=> feat: sort keys before calculating checksum

.changeset/green-donuts-pull.md, pnpm-lock.yaml, store/cafs/package.json, store/cafs/src/index.ts, store/cafs/src/writeBufferToCafs.ts, store/cafs/test/writeBufferToCafs.test.ts
=> fix: make shorter temp file names in the store

.changeset/empty-pugs-design.md, cli/default-reporter/src/reporterForClient/reportProgress.ts
Related: https://github.com/teambit/bit/pull/7703
=> fix: throttle progress

network/auth-header/src/helpers/removePort.ts, network/auth-header/src/index.ts, network/auth-header/test/getAuthHeaderByURI.ts, network/auth-header/test/removePort.test.ts
* chore(test): move removePort to it's own helper function
* add support for more url types, http,https,ws,wss
=> chore(tests): add tests specifically for removePort function includes http|https|wss|ws

.changeset/hungry-queens-invite.md, exec/lifecycle/src/runLifecycleHook.ts, exec/lifecycle/test/fixtures/inspect-frozen-lockfile/package.json, exec/lifecycle/test/fixtures/inspect-frozen-lockfile/postinstall.js, exec/lifecycle/test/index.ts
fixes https://github.com/pnpm/pnpm/issues/6865
=> feat: override `frozen-lockfile` before lifecycle

.changeset/few-icons-rule.md, exec/plugin-commands-script-runners/src/dlx.ts, exec/plugin-commands-script-runners/test/dlx.e2e.ts
=> fix(dlx): should not print an error stack when dlx fails

.changeset/orange-llamas-thank.md, fetching/tarball-fetcher/package.json, fetching/tarball-fetcher/src/remoteTarballFetcher.ts, pnpm-lock.yaml
ref https://github.com/pnpm/pnpm/pull/6819#discussion_r1265774839
=> perf: report download progress less often

.changeset/sour-spiders-rest.md, hooks/read-package-hook/src/createVersionsOverrider.ts, hooks/read-package-hook/src/isIntersectingRange.ts, hooks/read-package-hook/test/createVersionOverrider.test.ts
=> fix(overrides): filter overrides by intersection instead of subset

reviewing/dependencies-hierarchy/src/getPkgInfo.ts, reviewing/plugin-commands-listing/test/index.ts
=> fix(list): don't fail on local directory dependencies

.changeset/perfect-forks-beg.md, pkg-manager/core/src/install/index.ts, pkg-manager/core/test/install/lockfileOnly.ts
=> fix: install --frozen-lockfile --lockfile-only should work

.changeset/kind-rivers-happen.md, pnpm-lock.yaml, resolving/npm-resolver/src/index.ts, workspace/pkgs-graph/package.json, workspace/pkgs-graph/src/index.ts, workspace/pkgs-graph/test/index.ts, workspace/pkgs-graph/tsconfig.json
=> fix: respect workspace alias syntax in pkg graph

.changeset/hungry-sheep-approve.md, hooks/read-package-hook/src/createVersionsOverrider.ts, hooks/read-package-hook/test/createVersionOverrider.test.ts
=> fix: override peerDependencies in `pnpm.overrides`

.changeset/empty-teachers-fry.md, pkg-manager/plugin-commands-installation/src/link.ts, pkg-manager/plugin-commands-installation/test/link.ts
=> fix: warn when linking a package with peerDeps

.changeset/short-beds-run.md, pkg-manager/core/test/install/fromRepo.ts, pkg-manager/resolve-dependencies/src/resolveDependencyTree.ts
=>  fix(resolve-dependencies): dedupe deps with the same alias in direct dependencies

.changeset/little-actors-judge.md, config/config/src/index.ts
=> feat: resolution-mode is highest by default

.changeset/eighty-squids-mate.md, pkg-manager/plugin-commands-installation/src/installDeps.ts, pkg-manager/plugin-commands-installation/src/recursive.ts
fixes https://github.com/pnpm/pnpm/issues/6890
closes https://github.com/pnpm/pnpm/pull/6996
=> feat(install): use side effect cache when rebuild

.changeset/soft-ears-mate.md, releasing/plugin-commands-publishing/src/recursivePublish.ts
=> fix(publish): reduce concurrency in the publish command

pnpm/test/server.ts
We're seeing a few CI failures of the following form. In this case, all tests have passed, but there's some resource that's causing the test to continue hanging. Example link: https://github.com/pnpm/pnpm/actions/runs/6006623069/job/16350590766.
```
Test Suites: 2 skipped, 31 passed, 31 of 33 total
Tests:       6 skipped, 223 passed, 229 total
Snapshots:   0 total
Time:        793.365 s
Ran all test suites.
Jest did not exit one second after the test run has completed.
This usually means that there are asynchronous operations that weren't stopped in your tests. Consider running Jest with `--detectOpenHandles` to troubleshoot this issue.
```
I'm seeing this happen on my branches, as well as a recent PR from another contributor: https://github.com/pnpm/pnpm/pull/6978
I believe what's …
=> test: ensure server stops after test failure to fix hanging

.changeset/plenty-feet-return.md, exec/plugin-commands-script-runners/src/create.ts, exec/plugin-commands-script-runners/test/create.ts
=> fix(plugin-commands-script-runner): allow create scoped package with preferred version

.changeset/quick-pots-promise.md, fetching/directory-fetcher/package.json, fetching/directory-fetcher/src/index.ts, fetching/directory-fetcher/test/fixtures/exportable-manifest/package.json, fetching/directory-fetcher/test/index.ts, fetching/directory-fetcher/tsconfig.json, pnpm-lock.yaml, releasing/plugin-commands-deploy/package.json, releasing/plugin-commands-deploy/test/deploy.test.ts
This reverts commit d57e4de6dcc4bb59a88301fdc054d8e256902cdc.
This reverts #6943
This will solve:
- https://github.com/pnpm/pnpm/issues/7040
- https://github.com/pnpm/pnpm/issues/6994
=> revert: "feat(deploy): apply publishConfig to all packages during deploy (#6943)"

.changeset/great-shirts-hug.md, fs/indexed-pkg-importer/src/index.ts
=> fix: installation with disableRelinkFromStore set to true

.changeset/unlucky-starfishes-exercise.md, cli/default-reporter/src/reporterForClient/index.ts, cli/default-reporter/src/reporterForClient/reportDeprecations.ts, cli/default-reporter/test/reportingDeprecations.ts
=> feat: print a summary about deprecated subdeps

.changeset/wild-jeans-carry.md, pkg-manager/headless/src/linkHoistedModules.ts
=> fix: directories are not being removed from node_modules while linking commands

.meta-updater/src/index.ts, pnpm-lock.yaml, pnpm/bin/pnpm.cjs, pnpm/package.json
ref #6447
ref https://github.com/pnpm/pnpm/issues/6447#issuecomment-1722445619
ref https://github.com/pnpm/pnpm/issues/6447#issuecomment-1722447634
ref https://github.com/pnpm/pnpm/issues/6447#issuecomment-1722696226
=> perf: use `v8-compile-cache` to speed up cold boot

.changeset/clever-cameras-cover.md, pkg-manager/plugin-commands-installation/src/update/getUpdateChoices.ts, pkg-manager/plugin-commands-installation/src/update/index.ts, pkg-manager/plugin-commands-installation/test/update/getUpdateChoices.test.ts, pkg-manager/plugin-commands-installation/test/update/interactive.ts
=> refactor(plugin-commands-installation): optimize cli output after select dependencies when update

.changeset/gentle-geese-wink.md, fs/indexed-pkg-importer/src/index.ts
=> fix: don't use reflinks on Windows

.github/CODEOWNERS
As discussed, I am adding myself as a code owner for the hooks package.
=> chore: add d3lm as code owner for hooks

.changeset/rotten-seals-teach.md, packages/plugin-commands-setup/package.json, pnpm-lock.yaml
=> fix(setup): add newline to the end of shell configs

.changeset/brave-donkeys-grow.md, pkg-manager/package-bins/src/index.ts, pkg-manager/package-bins/test/index.ts
=> feat: allow scoped name as bin name

__typings__/local.d.ts, __typings__/typed.d.ts, config/config/src/Config.ts, config/config/src/index.ts, cspell.json, pkg-manager/core/test/breakingChanges.ts
This adds type safety to the kebab-case .npmrc format, generated dynamically from the config types
=> refactor: add type safety for config

.changeset/slimy-eyes-type.md, exec/build-modules/src/index.ts
close #7268
Fixes a regression introduced in https://github.com/pnpm/pnpm/pull/7214
I want to ship the fix fast, so I'll cover it with a test in a separate PR.
=> fix: don't rebuild unmodified deps on repeat install

.changeset/rude-laws-sparkle.md, __typings__/typed.d.ts, fs/packlist/README.md, fs/packlist/package.json, fs/packlist/src/index.ts, package.json, pnpm-lock.yaml
=> fix: downgrade npm-packlist to improve performance

exec/plugin-commands-script-runners/test/exec.e2e.ts, exec/plugin-commands-script-runners/test/runRecursive.ts
Seeing these tests flake very frequently on Windows. I reran a CI workflow a few times today and see it consistently fail. [Example link](https://pipelinesghubeus21.actions.githubusercontent.com/q8if4qHz65q1fIE6liKA2L7nEhE5ZrHnRF6uXsjEYMNGzHT5Dq/_apis/pipelines/1/runs/19140/signedlogcontent/5?urlExpires=2023-11-26T21%3A29%3A58.4007354Z&urlSigningMethod=HMACV1&urlSignature=5WC4wGKqUQ7lY4JmLX927DvGwViSU93SUy7Uq3J6ITc%3D).
```
2023-11-26T20:52:37.0903303Z   ● `pnpm -r --resume-from run` should executed from given package
2023-11-26T20:52:37.0904139Z 
2023-11-26T20:52:37.0904465Z     expect(received).toContain(expected) // indexOf
2023-11-26T20:52:37.0904995Z 
2023-11-26T20:52:37.0905361Z     Expected value: "project-3"
2023-11-26T20:52:37.0906145Z     Received array: ["project-2"] …
```
=> test: fix flaking `--resume-from` tests on windows

.changeset/chatty-insects-push.md, network/auth-header/src/helpers/removePort.ts, network/auth-header/src/index.ts, network/auth-header/test/getAuthHeaderByURI.ts, network/auth-header/test/removePort.test.ts
Resolves https://github.com/pnpm/pnpm/issues/7371
=> feat(network): basic auth header

.changeset/mean-elephants-wink.md, patching/plugin-commands-patching/test/patch.test.ts, patching/plugin-commands-patching/test/utils/index.ts, pkg-manager/core/test/install/autoInstallPeers.ts, pkg-manager/resolve-dependencies/src/index.ts, pkg-manager/resolve-dependencies/src/resolvePeers.ts
fixes regression introduced via #7359
=> fix: dependency deduplication

.changeset/grumpy-meals-admire.md, exec/plugin-commands-script-runners/src/run.ts, exec/plugin-commands-script-runners/test/exec.e2e.ts
Fixes https://github.com/pnpm/pnpm/issues/7244
=> fix(run): stop passing flags as fallback command

.changeset/stupid-spoons-attend.md, pkg-manager/headless/src/index.ts
=> fix: reporting of added dependencies

.changeset/hungry-days-kiss.md, cspell.json, lockfile/lockfile-utils/src/pkgSnapshotToResolution.ts, lockfile/lockfile-utils/test/pkgSnapshotToResolution.ts, pkg-manager/resolve-dependencies/src/resolveDependencies.ts
Fixes https://github.com/pnpm/pnpm/issues/7368
=> fix(fix-lockfile): crash on tarballs

.changeset/wild-suns-beg.md, pkg-manager/modules-cleaner/src/prune.ts, pkg-manager/modules-cleaner/src/removeDirectDependency.ts
=> fix: no permission to delete empty directories

__utils__/assert-project/package.json, __utils__/prepare/package.json, exec/plugin-commands-rebuild/src/implementation/extendRebuildOptions.ts, package.json, pkg-manager/core/src/install/extendInstallOptions.ts, pkg-manager/link-bins/package.json, pkg-manager/package-bins/package.json, pkg-manager/package-requester/src/packageRequester.ts, pnpm-lock.yaml, store/cafs/package.json, store/store-path/package.json, worker/src/index.ts
=> chore(dep): update @types/node

.changeset/nasty-games-grab.md, pkg-manager/plugin-commands-installation/test/update/issue-7415.ts, pnpm-lock.yaml, reviewing/outdated/package.json, reviewing/outdated/src/outdated.ts, reviewing/outdated/tsconfig.json
Fixes https://github.com/pnpm/pnpm/issues/7415
=> fix(outdated): git specificers

.changeset/khaki-wombats-hug.md, .changeset/lemon-mails-doubt.md, cspell.json, env/node.fetcher/package.json, fs/indexed-pkg-importer/package.json, packages/make-dedicated-lockfile/package.json, pkg-manager/resolve-dependencies/package.json, pnpm-lock.yaml, resolving/npm-resolver/package.json, store/cafs/package.json
close #7213
Related change: https://github.com/zkochan/packages/commit/0397b5df8b4233a644ea45639ddb1c06f93b24c1
=> fix: EPERM error in the store

.changeset/lazy-pans-perform.md, cli/common-cli-options-help/src/index.ts, config/config/src/Config.ts, config/config/src/index.ts, pnpm/src/cmd/index.ts, pnpm/src/main.ts, pnpm/test/monorepo/index.ts
=> feat(pnpm): add parameter --fail-if-no-match to get exit code as 1

.changeset/blue-scissors-perform.md, pnpm-lock.yaml, store/plugin-commands-store-inspecting/package.json, store/plugin-commands-store-inspecting/src/catIndex.ts
=> feat: sort the message of the `cat-index` command output

.changeset/quiet-ladybugs-whisper.md, fs/indexed-pkg-importer/package.json, pnpm-lock.yaml
=> fix: fatal error when using CoW in Windows

.changeset/silly-moles-rhyme.md, config/config/src/dirs.ts, config/config/test/dirs.test.ts
=> feat!: use the same directories on macOS as on Linux

.changeset/fair-grapes-roll.md, cli/cli-utils/jest.config.js, cli/cli-utils/package.json, cli/cli-utils/src/getConfig.ts, cli/cli-utils/test/getConfig.test.ts, cli/cli-utils/tsconfig.json, config/config/src/index.ts, pnpm-lock.yaml
=> fix: the warning should not be printed when --json is specified

.changeset/wild-shrimps-tie.md, packages/plugin-commands-doctor/src/doctor.ts
=> fix: fixed doctor command warning message error

.changeset/tough-hounds-laugh.md, fs/indexed-pkg-importer/src/index.ts
=> fix: don't fail if the file already exists (Windows Reflinks)

.changeset/tall-bears-tan.md, pkg-manager/resolve-dependencies/src/updateLockfile.ts
=> fix: don't add bundleDependencies=false to the lockfile

.changeset/curly-plums-change.md, __utils__/assert-project/package.json, __utils__/assert-store/package.json, exec/plugin-commands-rebuild/package.json, exec/plugin-commands-script-runners/package.json, package.json, patching/plugin-commands-patching/package.json, pkg-manager/core/package.json, pkg-manager/core/test/install/peerDependencies.ts, pkg-manager/headless/package.json, pkg-manager/package-requester/package.json, pkg-manager/plugin-commands-installation/package.json, pkg-manager/resolve-dependencies/src/resolveDependencies.ts, pkg-manager/resolve-dependencies/src/resolvePeers.ts, pkg-manager/resolve-dependencies/src/updateLockfile.ts, pkg-manager/resolve-dependencies/test/dedupeDepPaths.test.ts, pkg-manager/resolve-dependencies/test/resolvePeers.ts, pnpm-lock.yaml, pnpm/package.json, releasing/plugin-commands-deploy/package.json, releasing/plugin-commands-publishing/package.json, reviewing/plugin-commands-licenses/package.json, reviewing/plugin-commands-listing/package.json, reviewing/plugin-commands-outdated/package.json, store/plugin-commands-store/package.json
=> fix: resolve peer having peer correctly

.changeset/hip-fishes-roll.md, package.json, pnpm-lock.yaml, resolving/git-resolver/package.json
fix https://github.com/pnpm/pnpm/issues/7603
=> fix: Gitlab resolver

packages/dependency-path/src/index.ts, packages/dependency-path/test/index.ts
=> fix: converting dep path to file name

.changeset/smart-frogs-sniff.md, config/config/src/index.ts, pnpm/test/run.ts
per the poll results: https://twitter.com/pnpmjs/status/1755902257751605717
=> feat!: enabe-pre-post-scripts is true by default

.changeset/great-parents-explode.md, .changeset/late-frogs-sit.md, fetching/git-fetcher/package.json, fetching/git-fetcher/src/index.ts, fetching/git-fetcher/test/index.ts, fetching/tarball-fetcher/package.json, fetching/tarball-fetcher/src/gitHostedTarballFetcher.ts, fetching/tarball-fetcher/test/fetch.ts, pnpm-lock.yaml, store/cafs/src/addFilesFromDir.ts, worker/src/index.ts, worker/src/types.ts, worker/src/worker.ts
=> fix!: only fetch the included files of a git-hosted dependency

.changeset/dull-trainers-relate.md, fetching/tarball-fetcher/src/remoteTarballFetcher.ts, fetching/tarball-fetcher/test/fetch.ts, packages/error/src/index.ts, worker/src/index.ts, worker/src/worker.ts
=> fix: error code when cannot add tarball to store

.changeset/heavy-cars-press.md, worker/src/worker.ts
=> fix: always add name and version to the index file

fetching/git-fetcher/test/index.ts, fetching/tarball-fetcher/test/fetch.ts, pnpm-lock.yaml, store/cafs/package.json, store/cafs/src/addFilesFromDir.ts, store/cafs/test/index.ts
close https://github.com/pnpm/pnpm/issues/7691
close https://github.com/pnpm/pnpm/issues/7253
=> fix: resolve symlink dirs when uploading side-effects

.changeset/thick-countries-deny.md, exec/run-npm/src/index.ts
Fixes: https://github.com/nodejs/corepack/issues/419
=> fix: set `COREPACK_ENABLE_STRICT=0` in `runNpm`

__fixtures__/has-2-outdated-deps/node_modules/.pnpm/lock.yaml, __fixtures__/with-git-protocol-dep/pnpm-lock.yaml, __fixtures__/with-non-package-dep/pnpm-lock.yaml, exec/plugin-commands-rebuild/test/index.ts, lockfile/lockfile-file/src/lockfileFormatConverters.ts, lockfile/lockfile-file/test/lockfileV6Converters.test.ts, lockfile/lockfile-types/src/index.ts, packages/dependency-path/src/index.ts, pkg-manager/core/test/install/fromRepo.ts, pkg-manager/core/test/lockfile.ts, pkg-manager/package-requester/test/index.ts, resolving/git-resolver/src/index.ts, resolving/git-resolver/test/index.ts, resolving/local-resolver/src/index.ts, resolving/tarball-resolver/src/index.ts, resolving/tarball-resolver/test/index.ts, reviewing/dependencies-hierarchy/test/index.ts
=> feat!: package ID should be an exact version spec

.changeset/long-horses-raise.md, pnpm/dev/pd.js, pnpm/src/errorHandler.ts, pnpm/test/cli.ts, pnpm/test/install/lifecycleScripts.ts, pnpm/test/run.ts
=> fix(run): preserve the exit code of the child process

.changeset/friendly-tips-search.md, exec/prepare-package/src/index.ts
=> fix: use the right pkg manager for building git-hosted deps

packages/error/src/index.ts, packages/git-utils/src/index.ts, packages/make-dedicated-lockfile/src/bin.ts, packages/make-dedicated-lockfile/src/index.ts, packages/plugin-commands-doctor/src/doctor.ts, packages/plugin-commands-init/src/init.ts, packages/plugin-commands-init/src/utils.ts, packages/plugin-commands-setup/src/setup.ts, packages/render-peer-issues/src/index.ts, packages/which-version-is-pinned/src/index.ts
Closes https://github.com/pnpm/pnpm/pull/7868
Closes https://github.com/pnpm/pnpm/pull/7869
Closes https://github.com/pnpm/pnpm/pull/7870
=> refactor: return type annotations small packages in the `packages` directory

workspace/filter-workspace-packages/src/index.ts, workspace/filter-workspace-packages/test/index.ts, workspace/pkgs-graph/src/index.ts
This change may require bumping major versions of the affected packages
=> refactor: replace intersection with extends

.changeset/gold-cars-protect.md, pkg-manager/core/test/install/optionalDependencies.ts, pkg-manager/resolve-dependencies/src/resolveDependencyTree.ts
=> fix: linking optional dependencies

.changeset/yellow-dolphins-battle.md, cli/cli-utils/src/packageIsInstallable.ts
=> fix: print a hint about the `package-manager-strict` setting

.changeset/two-points-peel.md, pkg-manager/resolve-dependencies/src/resolveDependencies.ts
=> fix: resolution of aliased dependencies

.changeset/moody-geckos-bathe.md, deps/graph-builder/src/lockfileToDepGraph.ts, lockfile/filter-lockfile/src/filterLockfileByImportersAndEngine.ts, pkg-manager/core/test/install/optionalDependencies.ts, pkg-manager/headless/src/lockfileToHoistedDepGraph.ts, pkg-manager/package-requester/src/packageRequester.ts
=> fix: ignore the engines.pnpm field of dependencies

.changeset/spotty-houses-repeat.md, hooks/read-package-hook/src/createVersionsOverrider.ts, hooks/read-package-hook/test/createVersionOverrider.test.ts
Fixes https://github.com/pnpm/pnpm/issues/7858
=> fix(overrides): relative `file:`

.changeset/four-adults-burn.md, pkg-manager/resolve-dependencies/src/hoistPeers.ts, pkg-manager/resolve-dependencies/src/resolveDependencies.ts, pkg-manager/resolve-dependencies/test/hoistPeers.test.ts
=> fix: resolving peer deps with prerelease versions

.changeset/cold-pears-relax.md, lockfile/lockfile-file/src/lockfileFormatConverters.ts, lockfile/lockfile-file/test/lockfileFormatConverters.test.ts, lockfile/lockfile-file/test/lockfileV6Converters.test.ts
=> fix: converting lockfile with directory dependencies

.changeset/new-jeans-sparkle.md, lockfile/lockfile-file/package.json, lockfile/lockfile-file/src/lockfileFormatConverters.ts, lockfile/lockfile-file/test/lockfileFormatConverters.test.ts, lockfile/lockfile-file/tsconfig.json, pnpm-lock.yaml, resolving/git-resolver/src/createGitHostedPkgId.ts, resolving/git-resolver/src/index.ts, resolving/git-resolver/test/createGitHostedPkgId.test.ts
=> fix: git-hosted dependencies

.changeset/mighty-rats-suffer.md, lockfile/lockfile-utils/src/nameVerFromPkgSnapshot.ts, lockfile/lockfile-utils/test/index.ts, lockfile/lockfile-utils/test/nameVerFromPkgSnapshot.ts, pkg-manager/package-requester/src/packageRequester.ts, pkg-manager/resolve-dependencies/src/resolveDependencies.ts
=> fix: cannot read properties of undefined (reading missingPeersOfChildren)

.changeset/stupid-buckets-think.md, lockfile/prune-lockfile/src/index.ts, pkg-manager/core/test/install/optionalDependencies.ts, pkg-manager/resolve-dependencies/src/updateLockfile.ts
=> fix: dependencies that are not only optional should be installed when optionals are skipped

.changeset/moody-cows-invite.md, pkg-manager/link-bins/package.json, pkg-manager/link-bins/src/index.ts, pkg-manager/link-bins/test/fixtures/bin-name-conflicts-no-own-name/.gitignore, pkg-manager/link-bins/test/fixtures/bin-name-conflicts-no-own-name/node_modules/bar/index.js, pkg-manager/link-bins/test/fixtures/bin-name-conflicts-no-own-name/node_modules/bar/package.json, pkg-manager/link-bins/test/fixtures/bin-name-conflicts-no-own-name/node_modules/foo/index.js, pkg-manager/link-bins/test/fixtures/bin-name-conflicts-no-own-name/node_modules/foo/package.json, pkg-manager/link-bins/test/fixtures/different-versions/.gitignore, pkg-manager/link-bins/test/fixtures/different-versions/node_modules/my-command-greater/index.js, pkg-manager/link-bins/test/fixtures/different-versions/node_modules/my-command-greater/package.json, pkg-manager/link-bins/test/fixtures/different-versions/node_modules/my-command-lesser/index.js, pkg-manager/link-bins/test/fixtures/different-versions/node_modules/my-command-lesser/package.json, pkg-manager/link-bins/test/fixtures/different-versions/node_modules/my-command-middle/index.js, pkg-manager/link-bins/test/fixtures/different-versions/node_modules/my-command-middle/package.json, pkg-manager/link-bins/test/fixtures/matching-alias-vs-matching-name/.gitignore, pkg-manager/link-bins/test/fixtures/matching-alias-vs-matching-name/node_modules/my-command/index.js, pkg-manager/link-bins/test/fixtures/matching-alias-vs-matching-name/node_modules/my-command/package.json, pkg-manager/link-bins/test/fixtures/matching-alias-vs-matching-name/node_modules/original-my-command/index.js, pkg-manager/link-bins/test/fixtures/matching-alias-vs-matching-name/node_modules/original-my-command/package.json, pkg-manager/link-bins/test/index.ts, pnpm-lock.yaml
Fixes https://github.com/pnpm/pnpm/issues/7833
=> fix: race condition that creates corrupted scripts

pnpm/src/pnpm.ts
=> feat: support home command

README.md, cli/default-reporter/src/reporterForClient/reportUpdateCheck.ts, cli/default-reporter/test/__snapshots__/reportingUpdateCheck.ts.snap, config/config/CHANGELOG.md, pnpm/CHANGELOG.md, pnpm/README.md
https://en.wikipedia.org/wiki/Twitter#Rebrand_to_X
=> fix: update `twitter.com` to `x.com`

.changeset/violet-islands-wink.md, exec/plugin-commands-script-runners/package.json, exec/plugin-commands-script-runners/src/exec.ts, exec/plugin-commands-script-runners/test/exec.e2e.ts, exec/plugin-commands-script-runners/test/exec.logs.ts, exec/plugin-commands-script-runners/tsconfig.json, pnpm-lock.yaml
Fixes https://github.com/pnpm/pnpm/issues/8065
=> feat(exec): log prefix

.changeset/good-pumas-eat.md, lockfile/lockfile-to-pnp/package.json, lockfile/lockfile-to-pnp/src/index.ts, pnpm-lock.yaml
Fixes https://github.com/pnpm/pnpm/issues/8161
=> chore(deps): update `@yarnpkg/pnp` to latest

.changeset/nice-apes-protect.md, exec/plugin-commands-script-runners/src/exec.ts, exec/plugin-commands-script-runners/test/exec.logs.ts
Fixes https://github.com/pnpm/pnpm/issues/8174
=> feat(exec): default `reporterHidePrefix` to `true`

.changeset/fluffy-birds-carry.md, config/config/src/Config.ts, config/config/src/index.ts, exec/plugin-commands-rebuild/src/implementation/extendRebuildOptions.ts, lockfile/lockfile-file/src/lockfileFormatConverters.ts, lockfile/lockfile-file/src/read.ts, lockfile/lockfile-types/src/index.ts, lockfile/plugin-commands-audit/test/index.ts, packages/dependency-path/src/index.ts, patching/plugin-commands-patching/test/utils/index.ts, pkg-manager/core/src/getPeerDependencyIssues.ts, pkg-manager/core/src/install/extendInstallOptions.ts, pkg-manager/core/src/install/index.ts, pkg-manager/core/src/link/options.ts, pkg-manager/core/test/lockfile.ts, pkg-manager/get-context/src/index.ts, pkg-manager/get-context/src/readLockfiles.ts, pkg-manager/get-context/test/index.ts, pkg-manager/resolve-dependencies/src/index.ts, pkg-manager/resolve-dependencies/src/resolveDependencyTree.ts, pkg-manager/resolve-dependencies/src/resolvePeers.ts, pkg-manager/resolve-dependencies/test/dedupeDepPaths.test.ts, pkg-manager/resolve-dependencies/test/resolvePeers.ts, store/plugin-commands-store/src/storeStatus/extendStoreStatusOptions.ts
=> fix: make the peers suffix shorter

.changeset/cyan-windows-grab.md, config/config/src/index.ts
Fixes https://github.com/pnpm/pnpm/issues/8195
=> fix(config): missing config field

.changeset/tall-bees-call.md, packages/plugin-commands-setup/src/setup.ts
Resolves https://github.com/pnpm/pnpm/issues/8230
=> feat: create pnpx for bundled pnpm

.changeset/three-dingos-roll.md, pkg-manager/core/src/install/index.ts, pkg-manager/plugin-commands-installation/src/recursive.ts
=> fix: installation with filtering and dedupe-peer-dependents=true

.changeset/lemon-forks-leave.md, patching/plugin-commands-patching/src/getPatchedDependency.ts
Fixes https://github.com/pnpm/pnpm/issues/8257
=> fix(patch): error message for missing .modules.yaml

.changeset/tasty-tips-know.md, pkg-manager/core/test/install/autoInstallPeers.ts, pkg-manager/resolve-dependencies/src/resolveDependencies.ts, pnpm-lock.yaml, pnpm-workspace.yaml
=> fix: install peer of optional peer

.changeset/bright-mirrors-relate.md, pnpm-lock.yaml, pnpm-workspace.yaml
=> fix(config): passing public-hoist-pattern and hoist-pattern via env

.changeset/sixty-horses-act.md, exec/plugin-commands-script-runners/src/exec.ts, pnpm/test/exec.ts
Fixes https://github.com/pnpm/pnpm/issues/8356
=> feat(exec): add missing support for executionEnv

.changeset/smart-planes-tease.md, workspace/find-packages/src/index.ts, workspace/find-packages/test/__fixtures__/warning-for-non-root-project/packages/bar/package.json, workspace/find-packages/test/__fixtures__/warning-for-non-root-project/packages/foo/package.json, workspace/find-packages/test/index.ts
Fixes https://github.com/pnpm/pnpm/issues/8413
=> fix: replace pnpm warnings with subfield warnings

.changeset/purple-days-punch.md, exec/plugin-commands-script-runners/src/dlx.ts
Closes https://github.com/pnpm/pnpm/pull/8420
=> fix(dlx): failures on concurrent runs of dlx

.changeset/cuddly-comics-fix.md, pnpm-lock.yaml, pnpm/src/main.ts, tools/plugin-commands-self-updater/package.json, tools/plugin-commands-self-updater/src/selfUpdate.ts, tools/plugin-commands-self-updater/test/selfUpdate.test.ts, tools/plugin-commands-self-updater/tsconfig.json
Continuation of https://github.com/pnpm/pnpm/pull/8424
`pnpm self-update` should update the `packageManager` field in `package.json`.
=> feat: self-update should update pnpm in the packageManager field

.changeset/pretty-yaks-remember.md, .changeset/three-games-remember.md, packages/types/src/project.ts, pkg-manager/plugin-commands-installation/src/recursive.ts, releasing/plugin-commands-deploy/src/deploy.ts, releasing/plugin-commands-deploy/test/deploy.test.ts
=> fix(deploy): write `node_modules/.modules.yaml` to the deploy directory

pnpm/test/exec.ts, pnpm/test/install/lifecycleScripts.ts, pnpm/test/run.ts, releasing/plugin-commands-publishing/test/recursivePublish.ts
Concerning https://github.com/pnpm/pnpm/pull/8477#issuecomment-2317625282
=> refactor: replace `undefined` to prevent confusion

pkg-manager/plugin-commands-installation/test/update/interactive.ts
Related: https://github.com/pnpm/pnpm/commit/0f5d841fc6748988783c506f6ae048352f2e8d12#commitcomment-146043552
=> test: pin micromatch latest tag

.changeset/short-ravens-clap.md, pnpm/src/parseCliArgs.ts, pnpm/test/filterProd.test.ts, pnpm/test/monorepo/index.ts, pnpm/test/run.ts
Fixes https://github.com/pnpm/pnpm/issues/4821
=> fix(cli): `pnpm test` requiring `--`

.changeset/twenty-news-fetch.md, pkg-manager/plugin-commands-installation/src/recursive.ts, releasing/plugin-commands-deploy/test/deploy.test.ts
close #8475
close https://github.com/pnpm/pnpm/pull/8504
=> fix: deploy with shared-workspace-lockfile=false

.changeset/famous-tigers-protect.md, reviewing/list/src/index.ts, reviewing/plugin-commands-listing/src/list.ts, reviewing/plugin-commands-listing/test/json.ts
Fixes https://github.com/pnpm/pnpm/issues/8519
=> fix(listing): `--json` shows wrong `private`

exec/plugin-commands-script-runners/src/exec.ts
Closes https://github.com/pnpm/pnpm/issues/8520
=> docs(exec): add more options to exec's help

.changeset/good-points-double.md, .changeset/pink-pans-bake.md, exec/plugin-commands-rebuild/src/implementation/extendRebuildOptions.ts, packages/constants/src/index.ts, pkg-manager/plugin-commands-installation/src/install.ts, pkg-manager/plugin-commands-installation/src/installDeps.ts, pkg-manager/plugin-commands-installation/test/install.ts, pnpm-lock.yaml, pnpm-workspace.yaml, resolving/npm-resolver/src/pickPackage.ts, resolving/npm-resolver/test/publishedBy.test.ts, store/package-store/src/storeController/prune.ts, store/plugin-commands-store/test/storePrune.ts, store/store-connection-manager/src/createNewStoreController.ts
Fixes https://github.com/pnpm/pnpm/issues/7362
=> fix: install packages with incompatible libc

.changeset/tough-jars-study.md, hooks/read-package-hook/src/createVersionsOverrider.ts, hooks/read-package-hook/test/createVersionOverrider.test.ts, pkg-manager/core/test/install/overrides.ts
Resolves https://github.com/pnpm/pnpm/issues/8572
=> feat(overrides): remove dependencies

.changeset/young-insects-grab.md, pkg-manager/core/test/install/misc.ts, pkg-manager/core/test/install/peerDependencies.ts, pkg-manager/resolve-dependencies/src/resolvePeers.ts
This fixes an issue that appeared after merging #8457
close #8570
=> fix: installation hanging due to parent peers resolution dead lock

.changeset/real-monkeys-divide.md, pnpm/src/pnpm.ts
https://docs.npmjs.com/cli/v10/commands/npm-bugs
=> feat: add issues alias to `pnpm bugs`

.changeset/afraid-wolves-obey.md, pkg-manager/plugin-commands-installation/test/update/update.ts, pkg-manager/resolve-dependencies/src/resolveDependencies.ts, pnpm-lock.yaml, pnpm-workspace.yaml
=> fix(update): update latest should not update peer dependencies

.changeset/bright-pots-carry.md, releasing/plugin-commands-publishing/src/publish.ts, releasing/plugin-commands-publishing/test/publish.ts, releasing/plugin-commands-publishing/test/recursivePublish.ts, releasing/plugin-commands-publishing/test/utils/index.ts
Fixes regression introduced in #7862
close #7950
=> fix(publish): it should be possible to publish from a local tgz file

.changeset/sour-experts-cough.md, cli/parse-cli-args/src/index.ts
=> fix: every command should read settings from the root workspace project

cli/default-reporter/src/reportError.ts, pkg-manager/plugin-commands-installation/src/link.ts
=> fix: lint errors, resolves: #8698

config/config/src/index.ts
=> fix: handles `"packageManager": "pnpm"` in package.json, resolves: #8696

.changeset/chatty-garlics-change.md, .changeset/many-peas-switch.md, packages/render-peer-issues/src/index.ts, packages/render-peer-issues/test/index.ts, pkg-manager/resolve-dependencies/src/resolvePeers.ts, pnpm/test/install/misc.ts
=> fix: rendering of missing peer dependencies output

.changeset/soft-hotels-run.md, pkg-manager/core/test/install/peerDependencies.ts, pkg-manager/resolve-dependencies/src/resolvePeers.ts
=> fix: crash during peers resolution

.changeset/spicy-needles-peel.md, releasing/plugin-commands-publishing/src/pack.ts, releasing/plugin-commands-publishing/test/pack.ts
=> feat: support json format output in pnpm pack

.changeset/brown-weeks-roll.md, exec/plugin-commands-script-runners/src/exec.ts, exec/plugin-commands-script-runners/test/exec.ts
=> fix: `pnpm exec` should specify command

.changeset/short-knives-raise.md, __typings__/local.d.ts, config/config/src/readLocalConfig.ts, config/config/test/fixtures/has-number-setting/.npmrc, config/config/test/readLocalConfig.test.ts
=> fix: proper types of settings in local .npmrc files

.changeset/tall-rocks-judge.md, pnpm/src/main.ts, pnpm/test/install/misc.ts
=> fix: the CLI should fail if a different package manager is required by the project

.changeset/friendly-ravens-collect.md, packages/plugin-commands-setup/package.json, packages/plugin-commands-setup/src/setup.ts, pnpm-lock.yaml
=> fix: ETXTBSY error on running setup

cli/default-reporter/src/reporterForClient/reportUpdateCheck.ts, cli/default-reporter/test/__snapshots__/reportingUpdateCheck.ts.snap
=> chore: remove link to X from update notifier

package.json, pnpm-lock.yaml, pnpm-workspace.yaml
https://github.com/advisories/GHSA-3xgq-45jj-v275
=> fix: upgrade cross-sapwn

pnpm-lock.yaml, pnpm-workspace.yaml
The old version has a log command that I forgot to remove
=> chore(deps): update @reflink/reflink to 0.1.18

.changeset/proud-zoos-grow.md, exec/plugin-commands-script-runners/package.json, exec/plugin-commands-script-runners/src/dlx.ts, exec/plugin-commands-script-runners/test/dlx.e2e.ts, exec/plugin-commands-script-runners/tsconfig.json, pnpm-lock.yaml, pnpm/test/dlx.ts
=> feat!: dlx should use exact versions of packages in the cache key

lockfile/audit/src/types.ts, lockfile/plugin-commands-audit/src/audit.ts, lockfile/plugin-commands-audit/test/__snapshots__/index.ts.snap
=> feat: audit displaying ignored count

.changeset/old-kings-wait.md, pkg-manager/plugin-commands-installation/src/update/index.ts, pnpm/test/install/global.ts
=> fix: global update should not fail if no packages are found

package.json, pnpm-lock.yaml
https://github.com/advisories/GHSA-rhx6-c78j-4q9w
=> fix: audit

.changeset/poor-fans-attack.md, pnpm-lock.yaml, pnpm-workspace.yaml
=> fix!: reduce the amount of `npm_package_` env variables

.changeset/chilled-birds-hope.md, cli/default-reporter/src/reporterForClient/reportSummary.ts, cli/default-reporter/test/index.ts, config/config/src/index.ts, pkg-manager/plugin-commands-installation/src/install.ts, pnpm/test/install/only.ts, releasing/plugin-commands-deploy/src/deploy.ts
=> feat!: ignore the NODE_ENV env variable

.changeset/fast-papayas-heal.md, config/config/src/index.ts, cspell.json, packages/plugin-commands-doctor/package.json, packages/plugin-commands-doctor/src/doctor.ts, packages/plugin-commands-doctor/test/index.ts, pnpm-lock.yaml
=> fix: installation dependency error in exFAT drive

.changeset/hot-balloons-reflect.md, pkg-manager/core/test/hoistedNodeLinker/install.ts, pkg-manager/resolve-dependencies/src/resolveDependencies.ts, pnpm-lock.yaml, pnpm-workspace.yaml
=> fix: hoisted install with dependency that is a peer of itself

.changeset/dull-zoos-knock.md, pkg-manifest/exportable-manifest/src/index.ts, pkg-manifest/exportable-manifest/test/index.test.ts
Closes #8904 
Fix regression introduced in https://github.com/pnpm/pnpm/commit/398472c
=> fix: correctly resolve workspace dependencies with relative paths

.changeset/metal-suits-add.md, config/config/src/getOptionsFromRootManifest.ts, config/config/test/getOptionsFromRootManifest.test.ts
=> fix: onlyBuiltDependencies

pnpm/dev/pd.js
=> chore: pd should not switch to another version of pnpm

.changeset/popular-mice-watch.md, pnpm-lock.yaml, pnpm-workspace.yaml
=> fix: update @pnpm/npm-conf to v3

.changeset/lucky-foxes-compare.md, patching/plugin-commands-patching/src/patchCommit.ts, patching/plugin-commands-patching/test/patch.test.ts
=> fix(plugin-commands-patching): exclude .DS_Store file at patch-commit

.changeset/popular-hats-confess.md, patching/plugin-commands-patching/src/patch.ts, patching/plugin-commands-patching/test/patch.test.ts
Fixes https://github.com/pnpm/pnpm/issues/8919
=> fix(patching): reuse patch without version

.changeset/empty-chairs-push.md, pkg-manager/resolve-dependencies/src/getWantedDependencies.ts, pkg-manager/resolve-dependencies/src/toResolveImporter.ts, pkg-manager/resolve-dependencies/src/validatePeerDependencies.ts, pkg-manager/resolve-dependencies/test/validatePeerDependencies.test.ts
Closes https://github.com/pnpm/pnpm/issues/8934
=> feat!: prevent nonsense `peerDependencies`

.changeset/lucky-scissors-guess.md, deps/status/src/checkDepsStatus.ts, pnpm/test/install/issue-8959.ts, pnpm/test/verifyDepsBeforeRun/multiProjectWorkspace.ts
Fixes https://github.com/pnpm/pnpm/issues/8959
=> fix: check for delete modules dir in sub-project

.changeset/eighty-lemons-rule.md, cspell.json, pkg-manager/core/src/install/index.ts, pkg-manager/core/test/install/lifecycleScripts.ts, pkg-manager/headless/src/index.ts
=> fix: install dependencies execute preprepare and postprepare scripts

.changeset/red-pens-cheer.md, deps/status/src/checkDepsStatus.ts, deps/status/src/index.ts, exec/plugin-commands-script-runners/src/installCommand.ts, exec/plugin-commands-script-runners/src/runDepsStatusCheck.ts, exec/plugin-commands-script-runners/test/installCommand.test.ts, pnpm/test/verifyDepsBeforeRun/install.ts
Fixes https://github.com/pnpm/pnpm/issues/9019
=> fix: `verify-deps-before-run` after `install --prod|--no-optional`

.changeset/poor-goats-march.md, pnpm/src/switchCliVersion.ts, pnpm/test/switchingVersions.test.ts
=> fix: `packageManager` specified version should not start with `v`

.changeset/sweet-tomatoes-own.md, packages/plugin-commands-init/package.json, packages/plugin-commands-init/src/init.ts, packages/plugin-commands-init/tsconfig.json, pnpm-lock.yaml
=> feat: `init` command create file add `packageManager` field

.changeset/two-adults-rhyme.md, cli/default-reporter/src/reporterForClient/reportSummary.ts
https://github.com/pnpm/pnpm/pull/9071#issuecomment-2649695421
=> fix: do not output ignored scripts warnings and error messages at the same time

.changeset/few-ducks-agree.md, exec/build-modules/src/index.ts, pkg-manager/headless/src/index.ts, pnpm/test/install/lifecycleScripts.ts
=> fix: don't remove ignored builds list on repeat install

config/config/src/concurrency.ts
=> refactor: use `availableParallelism` get the amount of paralllelism available

.changeset/spicy-toys-check.md, exec/build-modules/src/index.ts, pnpm/test/install/lifecycleScripts.ts
=> fix: print warning about ignored builds on repeat install

cli/default-reporter/package.json, cli/default-reporter/src/reporterForClient/reportSummary.ts, package.json, pnpm-lock.yaml
I also had to fix an eslint warning to get past the pre-push check
=> chore: upgrade cspell

.changeset/fifty-trainers-unite.md, pnpm-lock.yaml, workspace/manifest-writer/package.json, workspace/manifest-writer/src/index.ts, workspace/manifest-writer/test/tsconfig.json, workspace/manifest-writer/test/updateWorkspaceManifest.test.ts, workspace/manifest-writer/tsconfig.json
=> fix: updateWorkspaceManifest not writing to manifest file

.changeset/few-islands-wink.md, workspace/find-workspace-dir/src/index.ts
=> feat: support check more invalid workspace file

.changeset/tall-eagles-sleep.md, exec/plugin-commands-script-runners/src/dlx.ts, pkg-manager/plugin-commands-installation/src/add.ts
close #9178
close #9174
TODO: add test in separate PR.
=> fix: dlx should ignore settings from package.json

config/config/test/getOptionsFromRootManifest.test.ts
=> chore: Fix typo

.changeset/nine-readers-compete.md, pnpm/src/main.ts
close https://github.com/pnpm/pnpm/issues/9177
=> fix: config set should be global by default

.changeset/beige-comics-taste.md, pnpm-lock.yaml, tools/plugin-commands-self-updater/package.json, tools/plugin-commands-self-updater/src/selfUpdate.ts
ref https://github.com/pnpm/pnpm/issues/9192
=> fix: self-update should never install a brokne pnpm CLI

.changeset/metal-olives-relax.md, packages/types/src/package.ts, releasing/plugin-commands-deploy/src/createDeployFiles.ts
=> fix(deploy): missing `imports` and `license` fields

.changeset/public-hounds-live.md, config/config/src/getOptionsFromRootManifest.ts, config/config/src/index.ts, patching/plugin-commands-patching/src/patchCommit.ts, pkg-manager/plugin-commands-installation/src/install.ts, pkg-manager/plugin-commands-installation/test/installConfigDeps.ts, pkg-manager/plugin-commands-installation/test/patchedDependencies.ts, pnpm/test/config.ts, releasing/plugin-commands-deploy/test/shared-lockfile.test.ts, reviewing/plugin-commands-licenses/test/index.ts
Related discussion: https://github.com/orgs/pnpm/discussions/9037
=> feat: setting config settings via pnpm-workspace.yaml

.changeset/heavy-otters-know.md, releasing/plugin-commands-deploy/src/createDeployFiles.ts, releasing/plugin-commands-deploy/test/shared-lockfile.test.ts
=> fix(deploy): don't remove fields from the deployed package's package.json

.changeset/legal-taxis-heal.md, config/config/src/getOptionsFromRootManifest.ts, config/config/test/getOptionsFromRootManifest.test.ts
=> fix: don't ignore pnpm.patchedDependencies from package.json

.changeset/free-carpets-send.md, pnpm/src/errorHandler.ts, pnpm/src/main.ts
=> fix: process exit when --silent is used

.changeset/tender-hoops-obey.md, pnpm/src/reporter/index.ts
=> fix: `pnpm-workspace.yaml` config `peerDependencyRules` does not work

.changeset/polite-plants-jump.md, exec/plugin-commands-script-runners/src/run.ts, exec/plugin-commands-script-runners/src/runRecursive.ts, exec/plugin-commands-script-runners/test/runRecursive.ts
Fixes https://github.com/pnpm/pnpm/issues/9180
=> fix(exec): add missing `node-options` to `recursive run`

releasing/plugin-commands-deploy/test/deploy.test.ts
See motivation at:
- https://github.com/pnpm/pnpm/pull/9259
When a future commit updates `allProjectsGraph` to always contains the full project graph, I'd like to make sure we don't accidentally inject all workspace packages on a `pnpm deploy`. Only the selected workspace package should be injected into the deployed dir, not the `allProjectsGraph`.
Adding 2 new tests to make sure this doesn't accidentally break in the future.
=> test: ensure only selected workspace packages are linked on deploy

.changeset/fresh-rooms-relate.md, config/config/src/index.ts
close #9233
More code might need to be moved to the end of the function but for now moving just enough to fix the open issue.
=> fix: install --prod=false

cli/default-reporter/src/reporterForClient/reportUpdateCheck.ts, cli/default-reporter/test/__snapshots__/reportingUpdateCheck.ts.snap
=> fix: make improvements to the update box

.changeset/great-groups-fry.md, exec/plugin-commands-script-runners/src/dlx.ts, exec/plugin-commands-script-runners/test/utils/index.ts, pkg-manager/plugin-commands-installation/src/add.ts
=> fix: dlx with --allow-build flag

.changeset/tame-hoops-sink.md, pnpm-lock.yaml, worker/package.json, worker/src/index.ts
=> perf: optimize the amount of workers

__utils__/eslint-config/index.js, __utils__/eslint-config/no-dupe-conditions.js
Regarding the problem solved by #9223, to avoid similar problems, it might be better for us to add a related rule, but the official does not seem to have any relevant rules, so we can implement it ourselves.
=> chore: add `no-dupe-conditions` rule

.changeset/fruity-corners-dance.md, pkg-manager/core/src/install/index.ts
=> fix: keep the `ignoredBuilds` field when installing different pkg

.changeset/breezy-bananas-lay.md, .changeset/nine-cooks-open.md, exec/build-commands/src/approveBuilds.ts, exec/build-commands/src/getAutomaticallyIgnoredBuilds.ts, exec/build-commands/src/ignoredBuilds.ts, exec/build-commands/test/approveBuilds.test.ts, pkg-manager/modules-yaml/src/index.ts
Fixes https://github.com/pnpm/pnpm/issues/9296
=> fix: remove warnings after approve no builds

.changeset/odd-moments-tell.md, config/plugin-commands-config/src/configSet.ts, config/plugin-commands-config/test/configSet.test.ts, pnpm-lock.yaml, workspace/manifest-writer/package.json, workspace/manifest-writer/src/index.ts
=> feat: config delete local should delete setting in pnpm-workspace.yaml

.changeset/green-eagles-clean.md, exec/plugin-commands-rebuild/package.json, exec/plugin-commands-rebuild/src/implementation/index.ts, exec/plugin-commands-rebuild/tsconfig.json, pnpm-lock.yaml
=> fix: pnpm rebuild causes approve build list error

.changeset/nasty-paws-cut.md, config/config/src/Config.ts, config/config/src/index.ts, config/config/src/transformPath.ts, config/config/test/transformPath.test.ts
Resolves https://github.com/pnpm/pnpm/issues/9217
=> feat: replace tilde with homedir

.changeset/quiet-bikes-ask.md, config/plugin-commands-config/src/config.ts, config/plugin-commands-config/src/configGet.ts, config/plugin-commands-config/src/configSet.ts, config/plugin-commands-config/src/get.ts, config/plugin-commands-config/src/set.ts, config/plugin-commands-config/test/configGet.test.ts, config/plugin-commands-config/test/configList.test.ts
=> fix(config): config get returns auth related settings properly

.changeset/breezy-clouds-kick.md, config/plugin-commands-config/src/configSet.ts, config/plugin-commands-config/test/configSet.test.ts
=> fix: config set should save the settings in the right format

.changeset/lucky-parents-post.md, fs/find-packages/src/index.ts
=> fix: tinyglobby regression

.changeset/little-lights-lie.md, config/config/src/index.ts
=> fix: `pnpm-workspace.yaml` config `sharedWorkspaceLockfile` does not work

config/config/test/fixtures/settings-in-workspace-yaml/pnpm-workspace.yaml, config/config/test/index.ts
=> test: setting `sharedWorkspaceLockfile` in `pnpm-workspace.yaml`

config/plugin-commands-config/src/config.ts
close #9396
sync https://github.com/pnpm/pnpm.io/pull/659
=> fix: update `location` option desc

.changeset/tidy-memes-dig.md, pkg-manager/plugin-commands-installation/src/add.ts, pnpm-lock.yaml, pnpm/package.json, pnpm/test/install/lifecycleScripts.ts, pnpm/tsconfig.json
=> fix: write `allow-build` value to `pnpm-workspace.yaml`

.changeset/fine-pears-win.md, .changeset/silly-crabs-pull.md, deps/status/src/checkDepsStatus.ts, pnpm/test/verifyDepsBeforeRun/issue-9424.ts
Fixes https://github.com/pnpm/pnpm/issues/9424
=> fix(verifyDepsBeforeRun): hoisted/pnp node linker

.changeset/long-windows-lay.md, config/config/src/Config.ts, config/config/src/index.ts, config/config/src/types.ts, config/config/test/fixtures/never-built-dependencies/pnpm-workspace.yaml, config/config/test/index.ts, pkg-manager/plugin-commands-installation/src/add.ts, pkg-manager/plugin-commands-installation/src/install.ts, pkg-manager/plugin-commands-installation/src/update/index.ts
=> feat: dangerouslyAllowAllBuilds allows to enable the build of all dependencies

.changeset/eager-pigs-flow.md, cspell.json, pnpm-lock.yaml, pnpm-workspace.yaml
=> fix(deps): update @zkochan/cmd-shim to v7

.changeset/mighty-cameras-kiss.md, config/config/src/getOptionsFromRootManifest.ts, exec/plugin-commands-script-runners/src/run.ts, exec/plugin-commands-script-runners/test/index.ts, pkg-manager/plugin-commands-installation/src/install.ts, pkg-manager/plugin-commands-installation/src/installDeps.ts, pkg-manager/plugin-commands-installation/src/update/index.ts, pkg-manager/plugin-commands-installation/test/update/interactive.ts, pkg-manager/plugin-commands-installation/test/update/update.ts, reviewing/plugin-commands-outdated/src/outdated.ts, reviewing/plugin-commands-outdated/src/recursive.ts, reviewing/plugin-commands-outdated/test/index.ts
=> fix: updateConfig in pnpm-workspace.yaml should not be ignored

.changeset/thirty-clubs-dig.md, pkg-manager/package-requester/src/packageRequester.ts, store/store-controller-types/src/index.ts
=> fix: don't remove cpu field on subsequent install

.changeset/gentle-turtles-ring.md, config/config/src/index.ts, pnpm/test/link.ts
=> fix: linking package globally from workspace should work

.changeset/tangy-taxes-turn.md, resolving/git-resolver/src/parseBareSpecifier.ts, resolving/git-resolver/test/parsePref.test.ts
=> fix: correct url loss pathname

.changeset/old-symbols-invite.md, releasing/plugin-commands-deploy/src/createDeployFiles.ts, releasing/plugin-commands-deploy/test/shared-lockfile.test.ts
Fixes #9283 
An alternative to #9483
=> fix: let deploy inherit overrides

.changeset/thin-badgers-punch.md, exec/plugin-commands-script-runners/src/runRecursive.ts
Optimistically this should resolve https://github.com/pnpm/pnpm/issues/9563
=> ci: respect silent reporter when deciding whether to output CI group stdout markers

.changeset/kind-trees-pay.md, config/config/src/index.ts, pnpm/test/verifyDepsBeforeRun/exec.ts, pnpm/test/verifyDepsBeforeRun/multiProjectWorkspace.ts, pnpm/test/verifyDepsBeforeRun/singleProjectWorkspace.ts
=> fix: use pnpm_config_ instead of npm_config_

.changeset/brave-cobras-pay.md, pnpm/test/deploy.ts, releasing/plugin-commands-deploy/src/deploy.ts
Fixes https://github.com/pnpm/pnpm/issues/9550
=> fix(deploy/legacy): unexpected directory creations

pkg-manager/core/test/catalogs.ts
Adding a new test to better cover the existing `catalog resolutions should be consistent` case.
One of my earlier approaches in https://github.com/pnpm/pnpm/pull/9517 caused a bug here that this test caught
=> test: ensure catalog resolutions are consistent for new dep with different peers

package.json
=> ci(test-branch): git fetch only fetch origin main branch

.changeset/lazy-apples-stick.md, reviewing/license-scanner/src/getPkgInfo.ts, reviewing/plugin-commands-licenses/src/licensesList.ts, reviewing/plugin-commands-licenses/test/index.ts
=> fix: licenses list print path error

.changeset/silver-clubs-eat.md, pkg-manager/core/src/install/link.ts
=> fix: hoisting of dependencies after resolution stage

.changeset/cold-crews-lay.md, pnpm/src/main.ts, pnpm/test/list.ts
Fixes https://github.com/pnpm/pnpm/issues/9672
=> fix(listing/json): empty filter should print empty array

.changeset/tired-points-brake.md, cspell.json, exec/lifecycle/package.json, exec/lifecycle/src/runLifecycleHook.ts, exec/lifecycle/test/index.ts, pnpm-lock.yaml, pnpm-workspace.yaml, pnpm/test/run.ts, worker/package.json, worker/src/index.ts
=> fix(lifecycle): replace shell-quote with shlex

.changeset/gold-eggs-check.md, workspace/manifest-writer/src/index.ts
ref https://github.com/pnpm/pnpm/pull/9453#issuecomment-3016137576
=> refactor: workspace setting sorted by key

cli/cli-utils/src/getConfig.ts, config/config/src/Config.ts, hooks/pnpmfile/src/requireHooks.ts, hooks/pnpmfile/test/__fixtures__/default/.pnpmfile.cjs, hooks/pnpmfile/test/index.ts, pnpm-workspace.yaml
Fixes an issue introduced via https://github.com/pnpm/pnpm/pull/9702
=> fix: the default pnpmfile should only be loaded if the pnpmfile settings is not set

.changeset/legal-drinks-smile.md, lockfile/utils/src/pkgSnapshotToResolution.ts
=> refactor: pkgSnapshotToResolution

.changeset/good-cycles-fix.md, config/config-writer/src/index.ts, config/plugin-commands-config/src/configSet.ts, pkg-manager/plugin-commands-installation/src/installDeps.ts, pkg-manager/plugin-commands-installation/src/recursive.ts, workspace/manifest-writer/src/index.ts, workspace/manifest-writer/test/addCatalogs.test.ts, workspace/manifest-writer/test/updateWorkspaceManifest.test.ts
=> refactor: combine addCatalogs to updateWorkspaceManifest

.changeset/petite-badgers-rest.md, pkg-manager/core/test/install/peerDependencies.ts, pkg-manager/resolve-dependencies/package.json, pkg-manager/resolve-dependencies/src/dedupeInjectedDeps.ts, pkg-manager/resolve-dependencies/src/hoistPeers.ts, pkg-manager/resolve-dependencies/src/resolveDependencies.ts, pnpm-lock.yaml
close #9913
This fixes a regression introduced in #9835
=> fix: pick package by real name to resolve a peer dependency

.changeset/major-cobras-clap.md, config/package-is-installable/src/checkEngine.ts, config/package-is-installable/test/checkEngine.ts
=> fix: throw an error if nodeVersion is not a semver version

.changeset/thin-berries-report.md, pnpm-lock.yaml, pnpm-workspace.yaml
=> fix: canceling a running process with Ctrl-C should make `pnpm run` return a non-zero exit code

.changeset/tiny-shoes-brush.md, packages/constants/src/index.ts
=> fix: location of full metadata cache

.changeset/vast-yaks-cut.md, pkg-manager/core/test/install/minimumReleaseAge.ts, pkg-manager/resolve-dependencies/package.json, pkg-manager/resolve-dependencies/src/resolveDependencies.ts, pkg-manager/resolve-dependencies/src/resolveDependencyTree.ts, pkg-manager/resolve-dependencies/tsconfig.json, pnpm-lock.yaml
=> feat: `minimumReleaseAgeExclude` support patterns

.changeset/lazy-doodles-lie.md, pkg-manager/plugin-commands-installation/src/remove.ts, workspace/manifest-writer/src/index.ts, workspace/manifest-writer/test/removeCatalogs.test.ts
=> fix: correctly apply cleanupUnusedCatalogs when remove pkg

.changeset/lucky-sheep-love.md, exec/lifecycle/src/runLifecycleHook.ts
=> fix: don't fail with scriptShell set to false

.changeset/proud-llamas-clap.md, exec/plugin-commands-script-runners/src/dlx.ts
=> fix: dlx should work with minimumeReleaseAge set
